### ISSUE TITLE
Cloudflare detection

### ISSUE THREAD

**Issue by matg19** [ultrafunkamsterdam/undetected-chromedriver#100]
It doesn't seem to be working pass Cloudflare anymore, the driver stays at the wait 5 seconds page and it keeps reloading (new ray ID every 5 secs) but the site does not load.

**Comment by ultrafunkamsterdam** [comment]
Then  most likely your ip is flagged. The driver does not automagically unflags ip. I also just updated the package for some other issues, and changed the mechanism of reconnecting. It 'might' fix your issue as well. Please update to the latest version 2.1.1 and try again.
