### ISSUE TITLE
Detected by https://hermes.com

### ISSUE THREAD

**Issue by buddyeorl** [ultrafunkamsterdam/undetected-chromedriver#1007]
Chrome Version 108.0.5359.124 (Official Build) (arm64)
UC 3.2.0
Running on a MacOs Aventura 13.0
![www hermes com_](https://user-images.githubusercontent.com/31565793/214249328-6459642b-c41c-4752-af54-eac347abe945.png)

**Comment by mdmintz** [comment]
It's working for me with [SeleniumBase](https://github.com/seleniumbase/SeleniumBase)'s ``uc``-mode (undetected-chromedriver mode):

``pip install seleniumbase``, then run the following with ``python``:

```python
from seleniumbase import SB

with SB(uc=True) as sb:
    sb.open("https://www.hermes.com/us/en/")
    sb.sleep(3)
    hermes_img = "hermes_img.png"
    sb.driver.save_screenshot(hermes_img)
    print("\nScreenshot saved to: %s" % hermes_img)
```

Output:

```
Screenshot saved to: hermes_img.png
```

<img width="600" alt="hermes" src="https://user-images.githubusercontent.com/6788579/214321162-046451c3-2409-4ebf-b92d-bb122cfc1be8.png">

[SeleniumBase](https://github.com/seleniumbase/SeleniumBase) has its own methods, but you can always access the ``driver`` with ``sb.driver`` in this particular format.

**Comment by buddyeorl** [comment]
Is also working for me the first time I run my script, but as soon as you run your script it a second time you'll be blocked,

**Comment by mdmintz** [comment]
I ran my script multiple times, and it's still working for me:

```bash
(venv) MM-MacBook-Air:tests michael$ python hermes.py 

Screenshot saved to: hermes_img.png
(venv) MM-MacBook-Air:tests michael$ python hermes.py 

Screenshot saved to: hermes_img.png
(venv) MM-MacBook-Air:tests michael$ python hermes.py 

Screenshot saved to: hermes_img.png
```

**Comment by buddyeorl** [comment]
maybe I need a clean Ip as and try again, but as of now I've been blocked on each refresh or second script run, I was just blocked on this route [link](https://www.hermes.com/us/en/category/women/bags-and-small-leather-goods/bags-and-clutches/#|)

**Comment by Ronaldomata34** [comment]
Hi, It was working days ago using undetected-chromedriver and protonvpn-cli, and now it is not working, I'm trying to scrape a website protected by Imperva/Incapsula, I will try with SeleniumBase :D

**Comment by buddyeorl** [comment]
will there be any fix available? currently with uc, most routes in some sites like hermes are being blocked on a second try,

**Comment by Ronaldomata34** [comment]
> will there be any fix available? currently with uc, most routes in some sites like hermes are being blocked on a second try,

Hey @buddyeorl, I think that we must to wait until undetected-chromedriver be patched, meanwhile I tested with SeleniumBase and it is working for me.

**Comment by ManiMozaffar** [comment]
#1031 
You may use this for fix.

**Comment by WZQ1993** [comment]
@ManiMozaffar

**Comment by WZQ1993** [comment]
hey @ManiMozaffar,i use https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/1031 but it not work for me.

this is my code and env

env
undetected-chromedriver  3.4         d:\mydata\wangzq\desktop\undetected-chromedriver-beta\undetected-chromedriver-beta
selenium                 4.8.0
chrome 109

````
def get_cookie(proxyStr):
    options = uc.ChromeOptions()
    if proxyStr:
        options.add_argument('--proxy-server=%s' % proxyStr)
    options.add_argument('--incognito')
    driver = uc.Chrome(options=options)

    driver.get('https://www.hermes.cn/cn/zh/')
    time.sleep(5)
    driver.save_screenshot('index.png')
    print("\nScreenshot saved to: %s" % 'index.png')
    driver.get('https://www.hermes.cn/cn/zh/category/女士/#|')
    time.sleep(5)
    driver.save_screenshot('category.png')
    print("\nScreenshot saved to: %s" % 'category.png')
````

I got the following two screenshots. and i also tried another ip 
index.png
![index](https://user-images.githubusercontent.com/11957047/217269569-a0f663be-f7ee-4f72-81fa-5372e1d6642e.png)
category.png
![category](https://user-images.githubusercontent.com/11957047/217269626-78c2a1c9-73ed-4a81-9822-e7cd092060c1.png)
Thanks a lot
