### ISSUE TITLE
Detected by https://www.coolbet.com

### ISSUE THREAD

**Issue by JohnPortella** [ultrafunkamsterdam/undetected-chromedriver#1009]
Chromium Version 109.0.5414.87
UC 3.2.1
Running on a Manjaro 22.0.1

![error 15](https://user-images.githubusercontent.com/4221947/214963540-bea2cff2-0773-4da8-b271-b960092d1e5d.JPG)

It worked until 2 days ago (01/26)

**Comment by lukect** [comment]
Try this: https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/986

**Comment by JohnPortella** [comment]
Great. It works !!!
