### ISSUE TITLE
Trainline website not scraping

### ISSUE THREAD

**Issue by goldenking0412** [ultrafunkamsterdam/undetected-chromedriver#102]
my scraper is being detected by thetrainline.com

In this link
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/46

I've found chrome debug could be potential solution.
So I've implemented like this

```
options.add_argument('--remote-debugging-port=7102')
```

Is this wrong?

And I've added so many features but it get success only 10% or 20%

Thanks

**Comment by goldenking0412** [comment]
I gave you git access and can you check new_driver method in app/controllers/application_controller.rb?

There we have all things to make scraper undeteced

Thanks

**Comment by goldenking0412** [comment]
@czoins, Can you check this thread and help me?
Thanks

**Comment by ultrafunkamsterdam** [comment]
Hodl on, hodl on...
Whats wrong with using just: 
```python
import undetected_chromedriver.v2 as uc
driver = uc.Chrome()
with driver:
    driver.get('https://yourhighlysecuredsite.xyz')
``` 

?

**Comment by goldenking0412** [comment]
We're writing it in ruby not python
So I've checked your code and implemented your logic in our scraper

**Comment by ultrafunkamsterdam** [comment]
You'd better check v2.py in that case .  Oh, and not raising an issue here just to discuss this.

**Comment by quangpham** [comment]
@goldenking0412 have you got your issue solved? I'm writing a similiar crawler in ruby and I'm hitting the same problem :) Would you mind sharing me some experience making it works in Ruby? Cheers!
