### ISSUE TITLE
Google profile logs out automatically 

### ISSUE THREAD

**Issue by Zeal5** [ultrafunkamsterdam/undetected-chromedriver#1021]
I tried logging into google account and created a profile for it but google keeps logging me out after a day or so my best guess is cookies are not being stored for some reason is this a bug or a feature? And how do i solve this.
Thanks

**Comment by ManiMozaffar** [comment]
Hello, you need to store cookies yourself or use user directory when launching selenium.


Saving user directory

```py
options = uc.ChromeOptions()
user_dir_path = 'path/to/somewhere'
options.add_argument(f"--user-data-dir={user_dir_path }")
```

Loading/Saving cookies
```py
## getting cookies
cookies = driver.get_cookies()

## loading cookies using CDP (safely)
for cookie in cookies:
      try:
          current_cookie = {
              "name":cookie["name"],
              "value":cookie["value"],
              "domain":cookie["domain"],
              "httpOnly":cookie["httpOnly"],
              "secure":cookie["secure"],
          }
          
          if "expiry" in cookie.keys():
              current_cookie["expires"] = cookie["expiry"]
          
          driver.execute_cdp_cmd("Network.setCookie", current_cookie)
          
      except Exception as e:
          logger.error(f"This cookie does not upload --> {cookie['name']}, Reason:{e}")
```

**Comment by Zeal5** [comment]
Thanks for the reply.
didn't know it didn't send cookies automatically

**Comment by Zeal5** [comment]
wait i have another question now did you mean if i use a dir i shouldn't have to load cookies manually? bcz i am using a dir

```
opts.add_argument(fr"--user-data-dir={chrome_profile}")
opts.add_argument("--profile-directory=Profile 2")
```
where chrome_profile is the path to a dir
also some cookies have expiration dates so how can i manage that should i continuously save and use recent cookies?
or saving cookies once and using old cookies will work fine

**Comment by sdfgsdfgd** [comment]
`Hello, you need to store cookies yourself or use user directory when launching selenium.` 

this is wrong ! 


I'm using a newly created `user-data-dir` and mine is also force logging me out around 24 hour mark. 

Should we be storing the cookies manually, on top of using custom user data directory  ? I'll try this and report back..
