### ISSUE TITLE
Imperva dedecction

### ISSUE THREAD

**Issue by melleryb** [ultrafunkamsterdam/undetected-chromedriver#1023]
Hi. I try all things like stealh-selenium,window.cdc_*,fake user-agent but everytime imperva dedect me.

https://fingerprint.com/products/bot-detection and other bot dedect result is clear.Do you guys any idea about this ?.It's not about my ip because i try at different ip's.Sorry for my bad eng btw.

**Comment by lukect** [comment]
Fixed: #1010

**Comment by melleryb** [comment]
> Fixed: #1010

Still same :/
![image](https://user-images.githubusercontent.com/68063945/216575828-57b85198-c531-4280-9011-fe799efc12be.png)

i am using your fork.I am passing captcha and few steps after imperva got me.

**Comment by lukect** [comment]
> Still same :/ ![image](https://user-images.githubusercontent.com/68063945/216575828-57b85198-c531-4280-9011-fe799efc12be.png)
> 
> i am using your fork.I am passing captcha and few steps after imperva got me.

Send a video. I have a full feature bot for this site and it still works perfectly. You are probably being detected due to IP address or unnatural behaviour.

**Comment by melleryb** [comment]
https://user-images.githubusercontent.com/68063945/216637941-85f60f64-1063-4b5e-9fd0-e628bd2d7048.mp4
Hi.There is a a little video about this.Generally it's catch me this or next step.My ip is clear because it's first time i join in at this ip.

**Comment by lukect** [comment]
> https://user-images.githubusercontent.com/68063945/216637941-85f60f64-1063-4b5e-9fd0-e628bd2d7048.mp4 Hi.There is a a little video about this.Generally it's catch me this or next step.My ip is clear because it's first time i join in at this ip.I will be very happy if you send it to me the browser settings for this site

The IP address in your original video is listed in databases as Turkish residential. In my experience, these gov.uk firewalled websites are restricted to UK residential IPs.

**Comment by melleryb** [comment]
> 

Oh okey.1 more question are you using another settings at your uc driver and any uc options ? I need to complete automation for join a job.Its important for me

**Comment by lukect** [comment]
Start ChromeDriver like this:

```python
@contextmanager
def start_chromedriver() -> uc.Chrome:
    options = ChromeOptions()

    options.add_argument("--disable-renderer-backgrounding")
    options.add_argument("--disable-backgrounding-occluded-windows")
    if settings.MINIMIZE_WINDOW:
        options.add_argument('--window-size=1920,1080')
    else:
        options.add_argument('--start-maximized')
    if settings.INCOGNITO_BROWSER:
        options.add_argument('--incognito')

    # Disable password store.
    options.add_argument("--password-store=basic")
    options.add_experimental_option(
        "prefs",
        {
            "credentials_enable_service": False,
            "profile.password_manager_enabled": False,
        },
    )

    options.page_load_strategy = 'normal'

    _driver = uc.Chrome(options)
    if settings.MINIMIZE_WINDOW:
        _driver.minimize_window()
    _driver.implicitly_wait(settings.DRIVER_IMPLICIT_WAIT)
    _driver.set_script_timeout(10)
    _driver.set_page_load_timeout(10)

    try:
        yield _driver
    finally:
        _driver.quit()
        logger.info("Stopping ChromeDriver!")
```

```python
with start_chromedriver() as driver:
    # logic 
```

**Comment by melleryb** [comment]
Thank you.I will try at uk ip.I hope it works.

**Comment by melleryb** [comment]
> ```python
> ```python
> contextmanager
> def start_chromedriver() -> uc.Chrome:
>     options = ChromeOptions()
> 
>     options.add_argument("--disable-renderer-backgrounding")
>     options.add_argument("--disable-backgrounding-occluded-windows")
>     if settings.MINIMIZE_WINDOW:
>         options.add_argument('--window-size=1920,1080')
>     else:
>         options.add_argument('--start-maximized')
>     if settings.INCOGNITO_BROWSER:
>         options.add_argument('--incognito')
> 
>     # Disable password store.
>     options.add_argument("--password-store=basic")
>     options.add_experimental_option(
>         "prefs",
>         {
>             "credentials_enable_service": False,
>             "profile.password_manager_enabled": False,
>         },
>     )
> 
>     options.page_load_strategy = 'normal'
> 
>     _driver = uc.Chrome(options)
>     if settings.MINIMIZE_WINDOW:
>         _driver.minimize_window()
>     _driver.implicitly_wait(settings.DRIVER_IMPLICIT_WAIT)
>     _driver.set_script_timeout(10)
>     _driver.set_page_load_timeout(10)
> 
>     try:
>         yield _driver
>     finally:
>         _driver.quit()
>         logger.info("Stopping ChromeDriver!")
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```python
> with start_chromedriver() as driver:
>     # logic 
> ```
> ```



> Start ChromeDriver like this:
> 
> ```python
> @contextmanager
> def start_chromedriver() -> uc.Chrome:
>     options = ChromeOptions()
> 
>     options.add_argument("--disable-renderer-backgrounding")
>     options.add_argument("--disable-backgrounding-occluded-windows")
>     if settings.MINIMIZE_WINDOW:
>         options.add_argument('--window-size=1920,1080')
>     else:
>         options.add_argument('--start-maximized')
>     if settings.INCOGNITO_BROWSER:
>         options.add_argument('--incognito')
> 
>     # Disable password store.
>     options.add_argument("--password-store=basic")
>     options.add_experimental_option(
>         "prefs",
>         {
>             "credentials_enable_service": False,
>             "profile.password_manager_enabled": False,
>         },
>     )
> 
>     options.page_load_strategy = 'normal'
> 
>     _driver = uc.Chrome(options)
>     if settings.MINIMIZE_WINDOW:
>         _driver.minimize_window()
>     _driver.implicitly_wait(settings.DRIVER_IMPLICIT_WAIT)
>     _driver.set_script_timeout(10)
>     _driver.set_page_load_timeout(10)
> 
>     try:
>         yield _driver
>     finally:
>         _driver.quit()
>         logger.info("Stopping ChromeDriver!")
> ```
> 
> ```python
> with start_chromedriver() as driver:
>     # logic 
> ```

Ty.I will try this at uk ip.I hope it works.

**Comment by MPanek6** [comment]
> Start ChromeDriver like this:
> 
> ```python
> @contextmanager
> def start_chromedriver() -> uc.Chrome:
>     options = ChromeOptions()
> 
>     options.add_argument("--disable-renderer-backgrounding")
>     options.add_argument("--disable-backgrounding-occluded-windows")
>     if settings.MINIMIZE_WINDOW:
>         options.add_argument('--window-size=1920,1080')
>     else:
>         options.add_argument('--start-maximized')
>     if settings.INCOGNITO_BROWSER:
>         options.add_argument('--incognito')
> 
>     # Disable password store.
>     options.add_argument("--password-store=basic")
>     options.add_experimental_option(
>         "prefs",
>         {
>             "credentials_enable_service": False,
>             "profile.password_manager_enabled": False,
>         },
>     )
> 
>     options.page_load_strategy = 'normal'
> 
>     _driver = uc.Chrome(options)
>     if settings.MINIMIZE_WINDOW:
>         _driver.minimize_window()
>     _driver.implicitly_wait(settings.DRIVER_IMPLICIT_WAIT)
>     _driver.set_script_timeout(10)
>     _driver.set_page_load_timeout(10)
> 
>     try:
>         yield _driver
>     finally:
>         _driver.quit()
>         logger.info("Stopping ChromeDriver!")
> ```
> 
> ```python
> with start_chromedriver() as driver:
>     # logic 
> ```

Hi @lukect, have you ever been detected using this? Trying to access the DVSA website from the UK but i'm still getting detected even when using fake useragent. Oddly the code works on an alternative pc so must be something to do with my browser setup. Do you know of any solutions?

**Comment by lukect** [comment]
> > Start ChromeDriver like this:
> > ```python
> > @contextmanager
> > def start_chromedriver() -> uc.Chrome:
> >     options = ChromeOptions()
> > 
> >     options.add_argument("--disable-renderer-backgrounding")
> >     options.add_argument("--disable-backgrounding-occluded-windows")
> >     if settings.MINIMIZE_WINDOW:
> >         options.add_argument('--window-size=1920,1080')
> >     else:
> >         options.add_argument('--start-maximized')
> >     if settings.INCOGNITO_BROWSER:
> >         options.add_argument('--incognito')
> > 
> >     # Disable password store.
> >     options.add_argument("--password-store=basic")
> >     options.add_experimental_option(
> >         "prefs",
> >         {
> >             "credentials_enable_service": False,
> >             "profile.password_manager_enabled": False,
> >         },
> >     )
> > 
> >     options.page_load_strategy = 'normal'
> > 
> >     _driver = uc.Chrome(options)
> >     if settings.MINIMIZE_WINDOW:
> >         _driver.minimize_window()
> >     _driver.implicitly_wait(settings.DRIVER_IMPLICIT_WAIT)
> >     _driver.set_script_timeout(10)
> >     _driver.set_page_load_timeout(10)
> > 
> >     try:
> >         yield _driver
> >     finally:
> >         _driver.quit()
> >         logger.info("Stopping ChromeDriver!")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```python
> > with start_chromedriver() as driver:
> >     # logic 
> > ```
> 
> Hi @lukect, have you ever been detected using this? Trying to access the DVSA website from the UK but i'm still getting detected even when using fake useragent. Oddly the code works on an alternative pc so must be something to do with my browser setup. Do you know of any solutions?

Try adding [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en) or other common extensions to the profile.
