### ISSUE TITLE
Avoid redownloading driver every time?

### ISSUE THREAD

**Issue by alexreg** [ultrafunkamsterdam/undetected-chromedriver#1027]
I see that if I avoid redownloading the undetected-chromedriver every time I run my program, then the site in question (familysearch.org) detects me. Could someone please explain how it fingerprints the driver? Why does redownloading the same driver fix the issue? I'm wondering if there's a less costly fix here.

**Comment by ManiMozaffar** [comment]
Hello @alexreg, 
I don't think that's relevant.  How do they detect you? I did a quick lookup, and I couldn't find anything related to fingeprint. 
Please specify how do you get blocked, under what condition.

A good reference to check your browser fingerprint
https://amiunique.org/fp

And also you may read this paper to get more information regarding how fingerprinting works in general:
Laperdrix.P(2019). Browser Fingerprinting: A survey. doi 10.1145

however, some fingerprint such WebGLData are gpu based, and they are driverless. 
You may spoof them using an extension, but spoofing a webgl is not really recommended, high chances the system detects it.

```py
import undetected_chromedriver as uc
options= uc.ChromeOptions()
extension_path = 'path/to/extension' 
options.add_argument(f"--load-extension={extension_path}")
uc.Chrome (options=options)
```

**Comment by alexreg** [comment]
@ManiMozaffar Thanks for your reply. I believe the reason that some sites block you if you use the same patched version of the driver more than once is because of the CDC call function. If you grep for `gen_call_function_js_cache_name`, you will see that every time this library patches the driver (which it downloads anew every time), it uses a random function name to avoid detection. So, I think a more efficient solution might be to download the chrome driver just once, but patch it every time it is launched.

**Comment by alexreg** [comment]
@lukect Hey, since your fork seems to be the most actively maintained at this moment, I was wondering what you thought of this. Maybe we can integrate this into your fork at least?

**Comment by ManiMozaffar** [comment]
> @ManiMozaffar Thanks for your reply. I believe the reason that some sites block you if you use the same patched version of the driver more than once is because of the CDC call function. If you grep for `gen_call_function_js_cache_name`, you will see that every time this library patches the driver (which it downloads anew every time), it uses a random function name to avoid detection. So, I think a more efficient solution might be to download the chrome driver just once, but patch it every time it is launched.

If you can mention some examples I'll try. The detection process isn't always related to driver or browser, sometimes you gotta think out of box, by using solutions such as multiacc. I can guide you better if you can share your code and the amount of time you ran your code until got detected. 

I've written a script and visited website 500 times, using same driver, and it didn't detect me as bot.
Right now, once your chrome is patched once, the is_binary_patched method will return True and avoid it to be changed in future.

**Comment by alexreg** [comment]
@ManiMozaffar I think it must depend on the particular website or at least the anti-bot system. In my case this happens with Incapsula on familysearch.org, when I use the same patched driver across multiple runs/sessions. As soon as I revert to default behaviour (download and patch driver anew each run), it doesn't get detected.

There's also some discussion of this issue [here](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/614).

**Comment by ultrafunkamsterdam** [comment]
set uc.Chrome(executable_path="path/to/your/existing/driver")

**Comment by alexreg** [comment]
@ultrafunkamsterdam Sure, but I'm saying, why not download the driver once and just copy and patch it each time undetected-chromedriver runs, so you get the random ID that comes with it? Isn't that just as good, or am I missing something?

**Comment by lukect** [comment]
> @ManiMozaffar Thanks for your reply. I believe the reason that some sites block you if you use the same patched version of the driver more than once is because of the CDC call function. If you grep for `gen_call_function_js_cache_name`, you will see that every time this library patches the driver (which it downloads anew every time), it uses a random function name to avoid detection. So, I think a more efficient solution might be to download the chrome driver just once, but patch it every time it is launched.

It doesn't really matter whether it is the same every time, only that it is different for each individual user of undetected-chromedriver, so that the antibots cannot hard-code a check. I guess maybe they could do some type of check to see if they've seen the same random prop name twice, but seems ineffective and unlikely at this point.

**Comment by alexreg** [comment]
@lukect Oh I see. So in that case case, why is undetected-chromedriver bothering to unlink the driver when it exits?
