### ISSUE TITLE
Cloudflare detects undetected-chromedriver

### ISSUE THREAD

**Issue by BluelyTASer** [ultrafunkamsterdam/undetected-chromedriver#103]
Uh oh, this is a very very very big problem......
https://user-images.githubusercontent.com/59511669/107132825-17ab2100-68c1-11eb-8029-b71b8061af10.mp4

**Comment by ultrafunkamsterdam** [comment]
Uh oh, it's a very arguable use case.

Original undetected-chromedriver does not work for sites which are using the tightest cloudflare protection ( = under attack mode). You need to use undected_chromedriver.v2 for this. See the main github entry page for an example
