### ISSUE TITLE
Add these ChromeOptions by automatically to prevent issues?

### ISSUE THREAD

**Issue by lukect** [ultrafunkamsterdam/undetected-chromedriver#1033]
I think these options (all previously shared in the past by @sebdelsol) should all automatically be added by UC, because automation is impossible without them:
```python
options = ChromeOptions()

options.add_argument("--disable-renderer-backgrounding")
options.add_argument("--disable-backgrounding-occluded-windows")

options.add_argument("--password-store=basic")
options.add_experimental_option(
    "prefs",
    {
        "credentials_enable_service": False,
        "profile.password_manager_enabled": False,
    },
)
```
The first two options prevent the Chrome renderer from stopping if a window isn't visible.
The next two options disable the Chrome password store prompts.

**Comment by ManiMozaffar** [comment]
I don't think the next two stops you from the automation. 
I've been using --disable-backgrounding-occluded-windows for almost a year, and it was enough in my case, never prompted an error to me. 
I've added it in my own PR request, as mentioned here, as a variable called is_focused which is set to True by default.

#1031
