### ISSUE TITLE
Bug with finding elements in the latest version.

### ISSUE THREAD

**Issue by abdulzain6** [ultrafunkamsterdam/undetected-chromedriver#1036]
Hi, I admire all the contributors for this wonderful project wanted to point out a bug i encountered with the latest version.
Here is the code:
```import undetected_chromedriver as uc
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
import time
driver = uc.Chrome()
driver.get("https://www.google.com")
image_xpath = '//img[@alt= "Google"]'

img = WebDriverWait(driver, 8).until(EC.element_to_be_clickable((By.XPATH, image_xpath)))
ActionChains(driver).move_to_element(img).perform()
print("Hovered")
time.sleep(10000)```
```
It raises the following exception:
```
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.evaluate threw exception: SyntaxError: missing ) after argument list
  (Session info: chrome=109.0.5414.74)
Stacktrace:
#0 0x55f675e1a303 <unknown>
#1 0x55f675beed37 <unknown>
#2 0x55f675bfa8df <unknown>
#3 0x55f675bf1df1 <unknown>
#4 0x55f675bf1931 <unknown>
#5 0x55f675bf2351 <unknown>
#6 0x55f675bf26dc <unknown>
#7 0x55f675c2b188 <unknown>
#8 0x55f675c2b6c1 <unknown>
#9 0x55f675c65b34 <unknown>
#10 0x55f675c4b9ad <unknown>
#11 0x55f675c6388c <unknown>
#12 0x55f675c4b753 <unknown>
#13 0x55f675c1ea14 <unknown>
#14 0x55f675c1fb7e <unknown>
#15 0x55f675e6932e <unknown>
#16 0x55f675e6cc0e <unknown>
#17 0x55f675e4f610 <unknown>
#18 0x55f675e6dc23 <unknown>
#19 0x55f675e41545 <unknown>
#20 0x55f675e8e6a8 <unknown>
#21 0x55f675e8e836 <unknown>
#22 0x55f675ea9d13 <unknown>
#23 0x7f3597290402 <unknown>
```
I tested it by reinstalling the old version and it worked fine. So possibly a bug with the latest one.
 Thanks and keep up the good work

**Comment by ultrafunkamsterdam** [comment]
Thanks for your reaction.

Cannot reproduce on windows , but i can reproduce on linux. unfortunately i have to fiddle through this and takes some time.

![image](https://user-images.githubusercontent.com/21027969/216833748-67fba986-5006-4cf8-870f-ff3bf1d7ab84.png)

**Comment by ultrafunkamsterdam** [comment]
Thanks for your reaction.
i could not reproduce this on windows, but i i could reproduce on linux. that's unfortunate :(.  i will have to fiddle trough the code to find out and solve. This could take some time. If previous version works for you, i recommend to use that.
![image](https://user-images.githubusercontent.com/21027969/216834168-1f815dec-a69b-4bec-b6f0-755638a4ea02.png)

![image](https://user-images.githubusercontent.com/21027969/216834071-2ee0d32e-a1a5-49c4-ae4a-e68b65f659cf.png)

**Comment by ultrafunkamsterdam** [comment]
i might have fixed this by using even another method which i had in my backup plan.
For me it works.


Could you try  installing this branch:
```
pip install git+https://github.com/ultrafunkamsterdam/undetected-chromedriver#fix-linux-find-elements
```

**Comment by abdulzain6** [comment]
I installed using the command above, still same issue

**Comment by ultrafunkamsterdam** [comment]
that's strange
![image](https://user-images.githubusercontent.com/21027969/216836457-2a2e41a5-b10e-4782-a54d-5cf7b5ed8a3f.png)

**Comment by abdulzain6** [comment]
Also no worries, i have switched to version 3.2.. will take a look at the issue myself too

**Comment by ultrafunkamsterdam** [comment]
run ```pip uninstall undetected-chromedriver``` select y
run ```pip install git+https://github.com/ultrafunkamsterdam/undetected-chromedriver@fix-linux-find-elements```   not a hash but @ for branch

**Comment by abdulzain6** [comment]
So i discovered where the issue is i think
```
       finalize(self, self._ensure_close, self)
        self.debug = debug
        self.patcher = Patcher(
            executable_path=driver_executable_path,
            force=patcher_force_close,
            version_main=version_main,
        )
       # self.patcher.auto()
        # self.patcher = patcher
```
Probably with the patcher, not patching the driver fixes it

**Comment by abdulzain6** [comment]
Tried the branch, that works

**Comment by ultrafunkamsterdam** [comment]
you probably have another instance running in the background and so you're using the 'wrong' driver exe. you need to make sure you delete that too when installing .  great to hear it works

**Comment by abdulzain6** [comment]
Well, i discovered this on a docker container running on a remote machine used for work... then i tried running it on the machine hosting the container.. and now on my on personal pc had the same issue...

**Comment by abdulzain6** [comment]
here is the fix             
```
match_injected_codeblock = re.search(rb"\{window\.cdc.*?;\}", content)
```
Just as i thought, the old regex removed some other suff too 
```
```
b'{window.cdc_adoQpoasnfa76pfcZLmcfl_Array = window.Array;window.cdc_adoQpoasnfa76pfcZLmcfl_Promise = window.Promise;window.cdc_adoQpoasnfa76pfcZLmcfl_Symbol = window.Symbol;}) ();\x00UPDATE %Q.sqlite_master SET tbl_name = %Q, name = CASE WHEN type=\'table\' THEN %Q WHEN name LIKE \'sqliteX_autoindex%%\' ESCAPE \'X\'      AND type=\'index\' THEN \'sqlite_autoindex_\' || %Q || substr(name,%d+18) ELSE name END WHERE tbl_name=%Q COLLATE nocase AND (type=\'table\' OR type=\'index\' OR type=\'trigger\');\x00".",">");Y(191,"/","?");Y(192,"`","~");Y(219,"[","{");\x00+a.m+" expects at least"+a.la+" arguments, "+b.length+" given");\x00ow Error("Invalid type name: "+e);Hb(a,"(");N(a,"Bad nodetype");\x00ow Error("Invalid type name: "+e);Mb(a,"(");M(a,"Bad nodetype");\x00;Y({c:103,b:103},"7");Y({c:104,b:104},"8");Y({c:105,b:105},"9");\x00n"==typeof a)b=3;else throw Error("Unexpected evaluation result.");\x00ction(){throw new N(9,"Browser does not support MSGesture events.");\x00]/.test(d)))return new N;d=new N;S(a,"Missing next location step.");\x00Z(120);Z(121);Z(122);Z(123);Z({c:107,b:187},"=","+");Z(108,",");\x00;Y({c:104,b:104},"8");Y({c:105,b:105},"9");Y({c:106,b:106},"*");\x002029]/g,"\\u00a0"):a.replace(/[ \\f\\t\\v\\u2028\\u2029]+/g," ");\x00")}var wc="A AREA BUTTON INPUT LABEL SELECT TEXTAREA".split(" ");\x00DROP TABLE IF EXISTS %Q.\'%q_segments\';DROP TABLE IF EXISTS %Q.\'%q_segdir\';DROP TABLE IF EXISTS %Q.\'%q_docsize\';DROP TABLE IF EXISTS %Q.\'%q_stat\';%s DROP TABLE IF EXISTS %Q.\'%q_content\';\x00ALTER TABLE %Q.\'%q_content\'  RENAME TO \'%q_content\';\x00ALTER TABLE %Q.\'%q_stat\'  RENAME TO \'%q_stat\';\x00ALTER TABLE %Q.\'%q_segments\' RENAME TO \'%q_segments\';\x00ALTER TABLE %Q.\'%q_segdir\'   RENAME TO \'%q_segdir\';\x00ALTER TABLE %Q.\'%q_docsize\'  RENAME TO \'%q_docsize\';\x00;J.prototype.toString=function(){var a="Binary Expression: "+this.$;\x00[29]="invalid element coordinates";P[12]="invalid element state";\x0027]="no such alert";T[7]="no such element";T[8]="no such frame";\x00out";U[33]="session not created";U[10]="stale element reference";\x00","{");Y(220,"\\\\","|");Y(221,"]","}");Y({c:59,b:186},";\x00,";"))});b=b.join("");return b=";"==b.charAt(b.length-1)?b:b+";\x00)return"";d=d?D(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";\x00n(a,b,c,d){c=J(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";\x00 priority:\x00, granularity:\x00:memory:\x00 [internally:\x00lue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:\x00Sockets ready:\x009",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:\x00",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:\x00e",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:\x00Failed to send path MTU target_mtu:\x00idle_timeout:\x00 handshake_timeout:\x00unknown type of timeout:\x00. Timeout:\x00host:transport:\x00javascript:\x00w)||window).document,a="CSS1Compat"==a.compatMode?a.documentElement:\x00;case "boolean":h=!!z(h);break;case "string":h=z(h);break;default:\x00State=!1;break;case 8:case 9:this.singleNodeValue=Za(a);break;default:\x00rState=!1;break;case 8:case 9:this.singleNodeValue=A(a);break;default:\x00ngClientRect){a:{try{var d=a.getBoundingClientRect()}catch(e){a={left:\x00 != receive_window_offset:\x00, offset:\x00Attempt to write packet:\x00;localabstract:\x00f(this.J.length){var b=u(this.J,function(c,d){return c+K(d)},"Steps:\x00, coalesced.packet_lengths:\x00Cannot compute the length of a null ack frame. free_bytes:\x00is.f.C()){var b=qa(this.f.f,function(c,d){return c+F(d)},"Predicates:\x00is.b.m()){var b=p(this.b.b,function(c,d){return c+D(d)},"Predicates:\x00ents);}).apply({navigator:typeof window!=\'undefined\'?window.navigator:\x00nt with the xpath expression "+b+" because of the following error:\x00is_server:\x00 after:\x00, but failed to kill browser:\x00 frame_header:\x00, prev_packet_number:\x00, packet_number:\x00LaunchProcess: failed to execvp:\x00, prev_receive_timestamp:\x00, receive_timestamp:\x00killforward:tcp:\x00mailto:\x00#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:\x00:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:\x00nchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:\x00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:\x00 version:\x00e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:\x00SerializeCoalescedPacket failed. buffer_len:\x00a);}'
```

Th above mentioned code should do it :)

**Comment by abdulzain6** [comment]
it contains xpath related stuff so maybe it messed it up
```
dow.navigator:\x00nt with the xpath expression "+b+" because of the following erro
```

**Comment by ultrafunkamsterdam** [comment]
Strange it does only on Linux I'll try and test yours on both platforms. Thanks so far

**Comment by abdulzain6** [comment]
Okay no probs, Looking forward to contibuting to this. Have some code and ideas that can build on this project... on frontiers like fingerprinting.. Thanks

**Comment by ultrafunkamsterdam** [comment]
@abdulzain6 . You did know i'm busy rewriting this completely and have chromedriver removed entirely?

**Comment by abdulzain6** [comment]
Nah didn't know about that:)

**Comment by abdulzain6** [comment]
Using cdp?

**Comment by Boby4458** [comment]
I'm having the same problem on my Mac. Finding by XPATH simply doesn't work at all.

**Comment by Remington-awl** [comment]
I met that challenge and worked out a feasible solution



https://pythondev.space/questions/what-could-be-causing-selenium-to-not-recognize-an-element-when-using-this-xpath-expression
