### ISSUE TITLE
Profiling still works somehow

### ISSUE THREAD

**Issue by udiudiudiudi** [ultrafunkamsterdam/undetected-chromedriver#104]
I installed the latest driver, and it appears to be working,
but then after 50-80 (its not always the same) runs, suddenly thetrainline.com starts to block the bot.

my thinking is that they somehow profile me, and its not IP, since i have storm proxies European rotating residential

**Comment by ultrafunkamsterdam** [comment]
That's your problem. Also residential ips get flagged when these residents lend their ip for malicious activities.
