### ISSUE TITLE
 After update to 3.4: unknown error: Runtime.evaluate threw exception: SyntaxError:  missing ) after argument list

### ISSUE THREAD

**Issue by stevenhubhub** [ultrafunkamsterdam/undetected-chromedriver#1040]
Thanks to the author for writing such a powerful, elegant open source product, I'm happy to update to 3.4 now, but I'm having problems after updating to the new version, as the author says it's a major update that may have an impact on the code, and unfortunately I'm having a problem right now after updating to the new version.

**### Basic environmental information:**
python 3.9.2
debian 11 bullseye
google-chrome 109.*stable/110.*beta
selenium: The latest
docker: No docker
**### Error message:**
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.evaluate threw exception: SyntaxError: missing ) after argument list
  (Session info: headless chrome=109.0.5414.119)
Stacktrace:
#0 0x55e3dc84d303 <unknown>
#1 0x55e3dc621d37 <unknown>
#2 0x55e3dc62d8df <unknown>
#3 0x55e3dc624df1 <unknown>
#4 0x55e3dc624931 <unknown>
#5 0x55e3dc625351 <unknown>
#6 0x55e3dc6256dc <unknown>
#7 0x55e3dc65e188 <unknown>
#8 0x55e3dc65e6c1 <unknown>
#9 0x55e3dc698b34 <unknown>
#10 0x55e3dc67e9ad <unknown>
#11 0x55e3dc69688c <unknown>
#12 0x55e3dc67e753 <unknown>
#13 0x55e3dc651a14 <unknown>
#14 0x55e3dc652b7e <unknown>
#15 0x55e3dc89c32e <unknown>
#16 0x55e3dc89fc0e <unknown>
#17 0x55e3dc882610 <unknown>
#18 0x55e3dc8a0c23 <unknown>
#19 0x55e3dc874545 <unknown>
#20 0x55e3dc8c16a8 <unknown>
#21 0x55e3dc8c1836 <unknown>
#22 0x55e3dc8dcd13 <unknown>
#23 0x7fa85aafeea7 start_thread

**Here's another mistake that sometimes occurs:**
FileNotFoundError: [Errno 2] No such file or directory:  '/root/.local/share/undetected_chromedriver/undetected_chromedriver'```

**Sometimes it also appears:**
* Cannot connect to 127.0.0*...

**_I confirm that this issue is related to multithreading/multiprocessing, but I don't know the exact reason because I'm not a professional, if I don't use multithreading/processing using the latest UC 3.4 test, it doesn't show any error.

After many tests, the error message mentioned above only appears when the version is upgraded to 3.4, for example, 3.2.1 does not appear._**

Thanks!

**Comment by stevenhubhub** [comment]
Add:
The problems mentioned above do not occur under windows operating systems and are perfectly normal, they only occur in linux.

**Comment by stevenhubhub** [comment]
Add:
The above question has been tested personally and I think it has nothing to do with headless.

**Comment by stevenhubhub** [comment]
Add:
UC 3.4.2 will also have the above problems. I have tested both 3.4.0 and 3.4.2, and both will appear.

**Comment by stevenhubhub** [comment]
Add:
I've tested this problem on multiple linux machines, including ubuntu, and in total I've tested about 10 different new linux VMS.

**Comment by stevenhubhub** [comment]
Add:
I always used a brand new linux vm in my tests, so the problem still occurs, if I remove the latest version of UC and replace it with 3.2.1 everything is fine.

**Comment by ultrafunkamsterdam** [comment]
if you had just read the previous 4 issues, which are the same, you would know

**Comment by stevenhubhub** [comment]
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\LENOVO\anaconda3\envs\localrayactor\lib\site-packages\undetected_chromedriver\__init__.py", line 694, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:1924
from session not created: This version of ChromeDriver only supports Chrome version 110
Current browser version is 109.0.5414.120
Stacktrace:
Backtrace:
	(No symbol) [0x008337D3]
	(No symbol) [0x007C8B81]
	(No symbol) [0x006CB36D]
	(No symbol) [0x006EED6D]
	(No symbol) [0x006E70F0]
	(No symbol) [0x006E6EE1]
	(No symbol) [0x00721ED5]
	(No symbol) [0x00721B2C]
	(No symbol) [0x0071B216]
	(No symbol) [0x006F0D97]
	(No symbol) [0x006F253D]
	GetHandleVerifier [0x00AAABF2+2510930]
	GetHandleVerifier [0x00AD8EC1+2700065]
	GetHandleVerifier [0x00ADC86C+2714828]
	GetHandleVerifier [0x008E3480+645344]
	(No symbol) [0x007D0FD2]
	(No symbol) [0x007D6C68]
	(No symbol) [0x007D6D4B]
	(No symbol) [0x007E0D6B]
	BaseThreadInitThunk [0x76D76BD9+25]
	RtlGetFullPathName_UEx [0x77DB8FD2+1218]
	RtlGetFullPathName_UEx [0x77DB8F9D+1165]
python-BaseException

**Comment by quyunet** [comment]
This version of ChromeDriver only supports Chrome version 110, please update your Browser.

**Comment by ultrafunkamsterdam** [comment]
also in the readme

```python
driver  =  uc.Chrome(version_main=109)

```

or, well , just update :)
