### ISSUE TITLE
Specific contents of a page cause UC to mangle DOM and crash renderer

### ISSUE THREAD

**Issue by slowengine** [ultrafunkamsterdam/undetected-chromedriver#1048]
While working with UC, I stumbled on some pages that would cause UC and only UC to mangle the contents of DOM to a degree where the whole thing would break down after the timeout was reached.
All content after `<head>`, `<body>` and a few other will be wiped clean. No tag is closed. The strange this is, the page is partly loaded, 
DOM is partly loaded as you can see the page being rendered to a point and then BOOM, broken.

The thing is, when I am logged in, everything works until that post is loaded in via API.
But it also causes the page/UC to break when loading that post logged in or logged out. Without API.
I could not track it down to why this happens, but I tested it with pure selenium and there it works without problems.
So it has to be something specific to UC. This has been happening for a few versions now. I tested it just now on 3.4.4 and it still happens.

To reproduce, just do the following. It is recommended to load ublock.
```
import undetected_chromedriver as uc
options = uc.ChromeOptions()
options.add_experimental_option('prefs', {'intl.accept_languages': 'en'})
options.add_argument("--load-extension=extensions/ublock") #up to you
driver = uc.Chrome(options=options)
driver.get('https://patreon.com')
driver.add_cookie({'domain': '.patreon.com', 'name': 'randomcookie', 'value': 'somebullshit'}) #do it like this or suffer
#Open Dev Tools
driver.get('https://www.patreon.com/posts/updated-in-2022-66910536')
#Go to element view
```

After that the chromedriver will wait for a timeout and exit with "timed out renderer" error message. Which... yeah, kinda makes sense when DOM is borked in such a way.

**Comment by ultrafunkamsterdam** [comment]
You are loading extension. unsupported.
