### ISSUE TITLE
import other module from selenium in undetected-chromedriver.v2

### ISSUE THREAD

**Issue by g2asell2019** [ultrafunkamsterdam/undetected-chromedriver#105]
Try this one to import expected_conditions but its doesn't work
`import undetected_chromedriver as uc

b = uc.selenium.webdriver.support.expected_conditions`

We can use this but it's not in v2
`import undetected_chromedriver as uc
uc.install()

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC`

**Comment by g2asell2019** [comment]
but I can import WebDriverWait 

`import undetected_chromedriver.v2 as uc
driver = uc.Chrome()
b = uc.selenium.webdriver.support.ui.WebDriverWait`

**Comment by ultrafunkamsterdam** [comment]
I dont know what jou expect here but just import/use the Chrome/ChromeOptions  classes, and for other selenium stuff just import it from selenium

**Comment by g2asell2019** [comment]
I can import `WebDriverWait` from selenium but "expected_conditions" is not possible
it returns "expected_conditions" is not existed in selenium

**Comment by ultrafunkamsterdam** [comment]
The fact that you "can" import something, does not say you "should", you can also format your harddrive using imports from the package.... 
for expected conditions:
```python
from selenium.webdriver.support import expected_conditions
```
