### ISSUE TITLE
UnboundLocalError: local variable 'target_bytes' referenced before assignment

### ISSUE THREAD

**Issue by alexreg** [ultrafunkamsterdam/undetected-chromedriver#1055]
I sometimes get this error upon creation of a new `Chrome` instance, presumably as a consequence of using a custom `driver_executable_path` that just gets patched once.

```
  ...
  File "/opt/homebrew/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 246, in __init__
    self.patcher.auto()
  File "/opt/homebrew/lib/python3.10/site-packages/undetected_chromedriver/patcher.py", line 99, in auto
    return self.patch_exe()
  File "/opt/homebrew/lib/python3.10/site-packages/undetected_chromedriver/patcher.py", line 228, in patch_exe
    new_content = content.replace(target_bytes, new_target_bytes)
UnboundLocalError: local variable 'target_bytes' referenced before assignment
```

The solution should be very straightforward: just indent [these lines](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/bb65b33f4afb4d7b4b3c1e4c789dfeb2127f2a73/undetected_chromedriver/patcher.py#L228-L239) one level.

**Comment by donggoing** [comment]
It happens to me. Pls review this and merge~ @ultrafunkamsterdam

**Comment by ultrafunkamsterdam** [comment]
this was an indentation issue.

fixed in https://github.com/ultrafunkamsterdam/undetected-chromedriver/commit/ca5fe635b9894cd8f657c0c6023a24900b0d4d71
