### ISSUE TITLE
install chromedriver and patch once

### ISSUE THREAD

**Issue by g2asell2019** [ultrafunkamsterdam/undetected-chromedriver#106]
I wonder why you have to download new chromedriver and patch it on every run
it makes multi-thread harder

**Comment by ultrafunkamsterdam** [comment]
Because you get a unique executable. And it wont download if file is in use. If this is an issue for your app i would reconsider multithreadinf 😉

**Comment by g2asell2019** [comment]
> And it wont download if file is in use
Nope, it will throw Exceptions if there are chromedriver executable and zipped one
Each time I run script, it will delete old chromedriver, download new one then unzip it
I tried multi-thread but current behavior couldn’t make it so far
Then I put it into each folder has its chromedriver, perhaps 80% I got Permission denied or something else

**Comment by g2asell2019** [comment]
Won’t you consider change to this one
`[1] Download chromedriver once
[2] unzip and patch chromedriver
[3] end of session delete the current chromedriver`

**Comment by ultrafunkamsterdam** [comment]
That is current behaviour. Maybe you need to delete the Chromedriver by hand, update the package to the latest and/or run your script from a folder you have write access to.On Feb 8, 2021 18:48, g2asell2019 <notifications@github.com> wrote:

Won’t you consider change to this one

[1] Download chromedriver once [2] unzip and patch chromedriver [3] end of session delete the current chromedriver

**Comment by g2asell2019** [comment]
> That is current behaviour
Nope, it downloads each time not once
> update the package to the latest and/or run your script from a folder you have write access to
It happens sometimes not all the time which makes me wonder
