### ISSUE TITLE
3.4.5 version is detected, but 3.2.1 - not

### ISSUE THREAD

**Issue by AndrewArtamonov** [ultrafunkamsterdam/undetected-chromedriver#1061]
Unfortunately, I can't say exactly what website I'm scraping, but it uses an Akamai bot-protection (can see it in the requests headers)...

Recently, I updated undetected-chromedriver version to 3.4.5 and was immediately detected as bot... Then I downgraded to 3.2.1 and passed all web-site checks.

(chrome version - 110, **non** headless)

**Comment by mdmintz** [comment]
Shortly after Chrome 110 was released, several companies pushed updates to bot-detection algorithms. I'm sure the maintainer is already aware. Part of https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/1010 by @lukect seems to cover the new anti-detection cases, but that PR is currently a few days out-of-date and missing updates for headless mode.

I've been working on a few updates to address these changes in my own framework, https://github.com/seleniumbase/SeleniumBase, which combines parts of @lukect's PR with the latest ``undetected-chromedriver`` as part of the complete framework.

``pip install seleniumbase``, then run the code below with ``python``:

```python
from seleniumbase import SB

with SB(uc=True) as sb:
    sb.open("https://nowsecure.nl/#relax")
    import pdb; pdb.set_trace()
```

That script opens a browser to https://nowsecure.nl/#relax and then drops in a breakpoint. (Type ``c`` and press Enter to continue.) If that works on your site, then we might have the information we need for the maintainer to patch the current algorithm. SeleniumBase has its own APIs, but you can always access the driver with ``sb.driver``.

It's also possible (and likely) that the undetected-chromedriver maintainer already has a fix in the works.

**Comment by ultrafunkamsterdam** [comment]
no code, no example site. closing
