### ISSUE TITLE
detected by cloudfare using V2

### ISSUE THREAD

**Issue by Powablocks** [ultrafunkamsterdam/undetected-chromedriver#107]
Hello,
I'm trying to navigate to the website adbtc.top but the cloudfare protection is always showing the 5s wait message in loop.

import undetected_chromedriver.v2 as uc
options = uc.ChromeOptions()
options.headless=False
chrome = uc.Chrome(options=options)
with chrome:  
    chrome.get('https://adbtc.top/index/enter')

**Comment by ultrafunkamsterdam** [comment]
Probably bad ip or bad behaviour.
Cannot reproduce

```
In [1]: import undetected_chromedriver.v2 as uc

In [2]: driver = uc.Chrome()

In [3]: with driver:
   ...:     driver.get('https://adbtc.top/index/enter')

In [4]: import time; driver.save_screenshot('adbtc.top.%.3f.png' % time.time())
Out[4]: True
```
![adbtc top 1612803525 074](https://user-images.githubusercontent.com/21027969/107254311-785c6a00-6a37-11eb-9205-5ba6c074a931.png)

**Comment by sagistrauss** [comment]
I just tested it and I can confirm that it doesn't pass Cloudfare (clean IP, visiting using regular browser with no issues)
