### ISSUE TITLE
Error status code 64 when using undetected_chromedriver on aarch64 machine (ubuntu server 20.04 + raspberry pi 4). 

### ISSUE THREAD

**Issue by truffledonal** [ultrafunkamsterdam/undetected-chromedriver#1072]
> > @PureSci , could you please paste the output of the following command?
> > This will display the architecture of the patched ChromeDriver:
> > ```
> > file /home/opc/.local/share/undetected_chromedriver/chromedriver_copy
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The output should be **similar** to this:
> > > chromedriver: ELF 64-bit LSB pie executable, **ARM aarch64**, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=bd3a0f6b97e22bd686e6ee6fb13c9fba7467e46b, stripped
> > 
> > 
> > In case you ask, I installed the ChromeDriver using the package from the official Debian repositories:
> > ```
> > aptitude install chromium-driver
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In Ubuntu the package has a different name:
> > ```
> > apt-get install chromium-chromedriver
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And I think in order to use it you also need to run `snap install chromium`. I don't use Ubuntu, so I cannot test further. But one thing I noticed is that the file `/usr/bin/chromedriver` (in Ubuntu) is not the real ChromeDriver but a shell script instead. Are you sure you copied the right thing? The real ChromeDriver (in Ubuntu) I think it lives in `/snap/bin/chromium.chromedriver`.
> 
> Thank you very much! This worked, just a little bit. Now im having the error
> 
> ```
> selenium.common.exceptions.WebDriverException: Message: Service /home/opc/.local/share/undetected_chromedriver/chromedriver_copy unexpectedly exited. Status code was: 64
> ```
> 
> Also here's the output after copying from snap's folder. The driver was at `/var/lib/snapd/snap/bin/chromium.chromedriver`
> 
> ```
> chromedriver_copy: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=c5df2062111d5a7d28e04c59b4728e691e606e3b, stripped
> ```
> 
> Also i am using Oracle Linux 8, which is I think fedora based.

I am receiving the same error after copying the driver at `/snap/bin/chromium.chromedriver`: 

`Message: Service /home/myusr/.local/share/undetected_chromedriver/chromedriver_copy unexpectedly exited. Status code was: 64`

Does anyone have any solution for how to solve this? I can call `chromedriver` and it starts successfully, so I believe there is a functioning chromedriver on my machine. For some reason though, when running with `undetected_chromedriver`, it exits. 

I am running Ubuntu server 20.04 on a Raspberry pi 4. When I call `file` on the `chromedriver_copy` I get the following output:
`/home/myusr/.local/share/undetected_chromedriver/chromedriver_copy: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, Go BuildID=8mNqx8E9JpT0uHPw93Yi/XPcPvDcx_5MYgf4aQ5XK/pwFWkyWEgIi-84C-5Ewm/_l1FN2KO1rgdmbHvg2XE, stripped`

_Originally posted by @truffledonal in https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/727#issuecomment-1435302831_

**Comment by tsipizic** [comment]
This is the file that you need to copy /snap/chromium/current/usr/lib/chromium-browser/chromedriver

**Comment by truffledonal** [comment]
> This is the file that you need to copy /snap/chromium/current/usr/lib/chromium-browser/chromedriver

This worked! Thank you very much.

**Comment by truffledonal** [comment]
> This is the file that you need to copy /snap/chromium/current/usr/lib/chromium-browser/chromedriver

This worked! Thank you so much.
