### ISSUE TITLE
Detected by Datadome

### ISSUE THREAD

**Issue by donggoing** [ultrafunkamsterdam/undetected-chromedriver#1076]
I can open the page(fnac.com with Datadome) for the first time. But when i refresh it, it will come to the captcha page. And then no matter whether manual or automated verification, it will be detected and shows i have been blocked.

As video examples seen in https://github.com/seleniumbase/SeleniumBase/issues/1760#issuecomment-1436217467
Here is an example with seleniumbase(with uc), it also happens to original undetected-chromedriver:

```
from seleniumbase import SB
with SB(undetectable=True, uc_cdp_events=True) as sb:
    sb.open("https://www.fnac.com/mp46660382")
    input('Press Enter to continue...')
```

**Comment by bologer** [comment]
@donggoing could please write how did you resolve it?
