### ISSUE TITLE
Safe to click and type?

### ISSUE THREAD

**Issue by gerarg** [ultrafunkamsterdam/undetected-chromedriver#110]
I'm sorry if this question sounds stupid, I read the important note that states we should never use the GUI to navigate and using keybord or mouse for navigation might cause detection.
This obviously means using something like `pyautogui` is a strict NO, but is it safe to click and/or type using the driver? Something like: 
```python 
# button doesn't redirect but generates a request 
driver.find_element_by_id('buttonId').click()
```
or:
```python 
driver.find_element_by_id('text-field').send_keys('some text')
```

**Comment by ultrafunkamsterdam** [comment]
@gerarg  

What you want to do is perfectly possible. The warning is about manually (with  your hands/fingers using the browser like you normally would). These driver functions are working, otherwise it wouldn't make much sense to create this module :)
