### ISSUE TITLE
Cannot connect to chrome in docker container

### ISSUE THREAD

**Issue by dofmind** [ultrafunkamsterdam/undetected-chromedriver#111]
I used undetected-chromedriver v2 in docker container but it causes follow errors.

```
Traceback (most recent call last):
  File "/app/test.py", line 49, in <module>
    main()
  File "/app/test.py", line 46, in main
    bot.run()
  File "/app/test.py", line 20, in run
    driver = uc.Chrome(options=options)
  File "/usr/local/lib/python3.7/site-packages/undetected_chromedriver/v2.py", line 202, in __init__
    keep_alive=keep_alive,
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/undetected_chromedriver/v2.py", line 256, in start_session
    super().start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:34311
from chrome not reachable
```

If options.debugger_address is not used like below, it works well in docker container.

```
diff --git a/undetected_chromedriver/v2.py b/undetected_chromedriver/v2.py
index 4e8db17..85fd376 100644
--- a/undetected_chromedriver/v2.py
+++ b/undetected_chromedriver/v2.py
@@ -156,8 +156,8 @@ class Chrome(selenium.webdriver.chrome.webdriver.WebDriver):
         if not options:
             options = selenium.webdriver.chrome.webdriver.Options()
 
-        if not options.debugger_address:
-            options.debugger_address = debug_addr
+        #if not options.debugger_address:
+        #    options.debugger_address = debug_addr
 
         if not options.binary_location:
             options.binary_location = find_chrome_executable()
```

**Comment by ultrafunkamsterdam** [comment]
Afaik docker is not supported. The reason being in v2 the browser window is started in a separate process instead of being a child of chromedriver. So to put you in the right direction: install chrome in your container, or do some volume mounting magic so chrome can be started on the host, or use docker network config + code customization to point driver to the chrome instance

**Comment by KacperKubara** [comment]
@ultrafunkamsterdam , I encounter the same error when I try to run this package in a docker container. So, if I understand correctly, all I need to is to download chrome and webdriver manually and then point the Chrome() to this webdriver?

Why even the error above occurs with this debugging address?

**Comment by HMaker** [comment]
> @ultrafunkamsterdam , I encounter the same error when I try to run this package in a docker container. So, if I understand correctly, all I need to is to download chrome and webdriver manually and then point the Chrome() to this webdriver?
> 
> Why even the error above occurs with this debugging address?

You fixed it?

**Comment by HMaker** [comment]
if `options.debugger_address = debug_addr` line be commented out selenium itself will start another instance of chrome which goes against the goal of UC v2.

**Comment by KacperKubara** [comment]
> > @ultrafunkamsterdam , I encounter the same error when I try to run this package in a docker container. So, if I understand correctly, all I need to is to download chrome and webdriver manually and then point the Chrome() to this webdriver?
> > Why even the error above occurs with this debugging address?
> 
> You fixed it?

I didn't, issue is more complex than it seemed to be. See https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/262 and https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/217

**Comment by HMaker** [comment]
@KacperKubara check #268
