### ISSUE TITLE
Doesn't work with chrome option 'user-data-dir'

### ISSUE THREAD

**Issue by fuyarchuk-kg** [ultrafunkamsterdam/undetected-chromedriver#1150]
When trying to use chrome option 'user-data-dir' it opens chrome and picture looks like this and just doing nothing

<img width="1432" alt="Screenshot 2023-03-23 at 01 00 16" src="https://user-images.githubusercontent.com/66023330/227048446-e7252086-e366-4b86-9fad-de77e5a490c0.png">

OS: MacOS Ventura 13.2.1 
undetected-chromedriver version: 3.4.6
chrome version: Version 111.0.5563.110 (Official Build) (arm64)

**Comment by pranavpa8788** [comment]
But why are you visiting the site called "user-data-dir", not sure if this was intended or not. Please provide reproducible code whenever submitting an issue on github

**Comment by fuyarchuk-kg** [comment]
`
     from selenium import webdriver
     import undetected_chromedriver as uc
 
    op = webdriver.ChromeOptions()
    op.add_argument('--disable-blink-features=AutomationControlled')
    op.add_argument('--allow-profiles-outside-user-dir')
    op.add_argument('--enable-profile-shortcut-manager')
    op.add_argument(r'user-data-dir=.\User')
    op.add_argument('--profile-directory=Profile 1')

    driver = uc.Chrome(options=op)

    driver.get(page)`

**Comment by pranavpa8788** [comment]
I think you're supposed to add it as 
op.add_argument(r'--user-data-dir=\User')
try it without the dot as well, and try
op.add_argument('--profile-directory="Profile 1"')
since Profile 1 has an empty space, not sure if that is a factor but give that a shot as well

**Comment by fuyarchuk-kg** [comment]
> I think you're supposed to add it as op.add_argument(r'--user-data-dir=\User') try it without the dot as well, and try op.add_argument('--profile-directory="Profile 1"') since Profile 1 has an empty space, not sure if that is a factor but give that a shot as well

Didn't help(((

**Comment by pranavpa8788** [comment]
Btw this User directory is in the same folder as your script right? You could try one more thing, which is what I do for providing user data dir
```
from pathlib import Path
user_data_dir = Path("\\User").resolve()     # You can also check if the path exists within the program using .exists()
user_data_path = str(user_data_dir)
op.add_argument(f"user-data-dir={user_data_path}")
```
Also, if you don't mind can you specify the url you're trying to visit?

**Comment by fuyarchuk-kg** [comment]
I am visiting stockx.com site, but it isn't the thing!

It also seems like this thing helps - op.add_argument(r'--user-data-dir=\User') 
'\User' instead of '.\User' helps with adding '--' at the beginning. I just missed the '--' at the beginning first time you answered me!

Thanks a lot!!!

**Comment by ultrafunkamsterdam** [comment]
You should have just use uc.ChromeOptions() instead of selenium.webdriver's

**Comment by pranavpa8788** [comment]
@ultrafunkamsterdam omg you're right how did I not notice that

**Comment by 0xUndetectable** [comment]
why crash all time with "options.add_argument('--user-data-dir=C:/Users/'+os.getlogin()+'/AppData/Local/Google/Chrome/User Data/Default/')"

**Comment by VishruthBharadwaj** [comment]
I am trying in this way chrome in Profile3 is opening but its not loading url i gave
Its not printing

**After driver initialization**

Code is below 


options = uc.ChromeOptions()

options.add_argument(r'--user-data-dir=/Users/vishruth/Library/Application Support/Google/Chrome/')
options.add_argument(r'--profile-directory=Profile 3')

print('Before driver initialization')
driver = uc.Chrome(
    options = options 
    )
print('After driver initialization')

# Navigate to a website
driver.get('https://nowsecure.nl/p')

**Comment by fdsanti** [comment]
Were you able to solve this? I'm having the same issue

**Comment by fuyarchuk-kg** [comment]
> Were you able to solve this? I'm having the same issue

https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1150#issuecomment-1483854217 this is how i solved it

**Comment by waldydesing** [comment]
the profiles thing does work, but it doesn't direct to the webpage.
