### ISSUE TITLE
UC(3.4.6) No such file or directory: '/root/.local/share/undetected_chromedriver/undetected/chromedriver'

### ISSUE THREAD

**Issue by soft-top-notch** [ultrafunkamsterdam/undetected-chromedriver#1156]
Hi, 

Thanks in advance for supporting a great library. I just installed this library (latest version) in the linux server. But, I'm getting this error when I try to run `UC.Chrome`:
![image](https://user-images.githubusercontent.com/48213961/227704707-660db726-046f-4b6c-8684-1ab7c02d8067.png)

```
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/undetected_chromedriver/undetected/chromedriver' -> '/root/.local/share/undetected_chromedriver/undetected_chromedriver
```

I installed the latest version of the `Chrome` using Docker.
The code that runs UC chrome driver is like so:
```
display = Display(visible=False, size=[1680, 860])
display.start()

chrome_options = uc.ChromeOptions()
chrome_options.add_argument("--no-sandbox")
local_webdriver = uc.Chrome(options=chrome_options)
```
Could you please let me know why it raises up this issue?

**Comment by rosered90** [comment]
Which architecture is your Linux system AMD or ARM? 
I have encountered this problem on arm, which includes Chrome and undetected_chromedriver may not be very compatible.
The problem with AMD will be solved.

**Comment by NidhoogJX** [comment]
This doesn't seem to be a problem,

1. If Google Browser is not installed in the docker container

"Xfvb analog desktop display is not installed,",

3. xfvb not started

4 DISPLAY variable not specified

import os

os.environ['DISPLAY'] = ':99'

Will report this error

No such file or directory: '/root/.local/share/undetected_ chromedriver/undetected/chromedriver'

Simply put, the required service is not ready or started

**Comment by NidhoogJX** [comment]
对于我来说,我重启了python docker 容器 ,xfvb 服务挂掉了,重启xfvb 服务就正常工作了

**Comment by NidhoogJX** [comment]
For me, I restarted the python docker container, and the xfvb service crashed. Restarting the xfvb service will work properly

**Comment by soft-top-notch** [comment]
Please read what I posted here properly, @NidhoogJX . 
I assume you installed `pyvirtualdisplay` latest version properly in your docker image. 
If the bellow code works fine, then, that means there is no problem in xfvb display side. 

```
display = Display(visible=False, size=[1680, 860])
display.start()
```
And this is relevant to `Chromedriver`, not `Google Chrome Browser`. The `Chrome` browser is already installed in this case,
The problem is in the `chromedriver` side ( either not installed or version mismatch corresponding to `Google Chrome` version )
If uc doesn't connect to the `chromedriver` properly, it raises this kind of error. 
Thanks.

I think we can close this issue.
