### ISSUE TITLE
Renderer issue with chrome version 89.0.4389.82 while running headless

### ISSUE THREAD

**Issue by lui4** [ultrafunkamsterdam/undetected-chromedriver#116]
Hello there,
I'm currently working on a project using the undetectable-chromedriver and I have encountered a major issue with the latest chrome version (89.0.4389.82):

My setup for the chromedriver:
```
def _setup_driver(email):
    options = uc.ChromeOptions()
    options.add_experimental_option("excludeSwitches", ["enable-automation"])
    options.add_experimental_option('excludeSwitches', ['enable-logging'])
    options.add_experimental_option('useAutomationExtension', False)
    options.add_argument(f"user-data-dir=./chrome_profiles/{email}")
    options.add_argument("--ignore-certificate-errors")
    options.add_argument("--allow-running-insecure-content")
    options.add_argument("--disable-extensions")
    options.add_argument('--remote-debugging-port=9222')
    options.add_argument("--headless")
    return uc.Chrome(options=options)
```

I get the following error:

```selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from disconnected: unable to connect to renderer
  (Session info: headless chrome=89.0.4389.82)
```

It looks like it has some problems rendering the driver, but the weirdest part about this issue is that it works once I run it headfull. And I'm not using the v2 version of the the undetected-chromedriver.

Platform: ```x64 Windows 10```
Python version: ```Python 3.9```

**Comment by ultrafunkamsterdam** [comment]
headless/headfull are totally different workings and v2 does not yet support headless (Well it works, but you are getting detected and some other issues may arise). 

I would suggest following the readme, and not add custom options. Stuff like debugging-port is all taken care off and there is no need to specify it, unless you like problems.

without adding all custom options:

```python
import undetected_chromedriver as uc
options = uc.ChromeOptions()
options.headless = True
driver = uc.Chrome(options=options)
```
