### ISSUE TITLE
Can't import cookies

### ISSUE THREAD

**Issue by 0ut0flin3** [ultrafunkamsterdam/undetected-chromedriver#1165]
When I try to import cookies always receive this error:
`selenium.common.exceptions.UnableToSetCookieException: Message: unable to set cookie`

I'm using `undetected_chromedriver==3.4.6` and Google Chrome 111.0.5563.146

**Comment by yatouxingren** [comment]
> 

how to solve this problem？
I get this error now：
self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x16c12ddf0>
response = {'status': 500, 'value': '{"value":{"error":"unable to set cookie","message":"unable to set cookie\\n  (Session info: ...fff203168fc _pthread_start + 224\\n19  libsystem_pthread.dylib             0x00007fff20312443 thread_start + 15\\n"}}'}
