### ISSUE TITLE
cant use add_argument on .v2

### ISSUE THREAD

**Issue by ScottFal** [ultrafunkamsterdam/undetected-chromedriver#117]
is there a way we can use add_argument to .v2? it just seems to ignore them

im trying to use a proxy with .v2

**Comment by ultrafunkamsterdam** [comment]
proxy use is tricky to setup even in the normal chrome/chromedriver. please first get it working in a normal situation before trying it on UC.

**Comment by vesper8** [comment]
@ultrafunkamsterdam Any chance you could share a simple example of v2 working with a provided user agent, proxy and referer ?

Just to see how to set up the options with v2. I'm also having trouble.

**Comment by ultrafunkamsterdam** [comment]
Well referer is not doable, unless you use a proxy which changes your referer structurally, but it wil cause lots of site not to work properly.

```python
# you can use your own proxy, but i use this to test
import aiotor
proxy = aiotor.Proxy()
Initializing Tor background process..


# relevant part
import undetected_chromedriver.v2 as uc
o = uc.ChromeOptions()
o.add_argument(f'--proxy-server=socks5://127.0.0.1:10000')
driver = uc.Chrome(options=o)
driver.execute_cdp_cmd(
            "Network.setUserAgentOverride", {"userAgent": "MySuperPornScraper"}
            )

driver.get('http://whatsmyuseragent.org')


import requests
requests.get('https://httpbin.org/ip').json()
# {'origin': '185.247.144.179'}
```

![image](https://user-images.githubusercontent.com/21027969/112401831-a528c000-8d0b-11eb-8a2a-b784d90f81c1.png)

**Comment by ultrafunkamsterdam** [comment]
Arguments issue fixed in latest version

**Comment by vesper8** [comment]
@ultrafunkamsterdam Thank you for the example.

I can confirm that I am now able to use a proxy and it works with either headless mode or not.

However when trying to scrape a page that is protected by CF, it is not going past the "checking your browser / Please allow up to 5 seconds" page.

I tried it with headless mode but also with normal mode (no headless).

It appears to show the above page for ~5 seconds but it never gets past it and the browser just closes without ever getting to the actual page I want to scrape.

When trying it without headless mode then I am faced with the other issue on macos of having to manually deselect the two checkboxes and press the 'start chrome browse' button manually so I wonder if this is somehow eating up into the time `undetected_chromedriver` would normally wait on the first CF check page.
