### ISSUE TITLE
Error after Chrome upgrade to 112 even with version_main=111

### ISSUE THREAD

**Issue by ggnetoo** [ultrafunkamsterdam/undetected-chromedriver#1181]
I'm getting this error even with version_main=111 after Chrome upgrade to 112:

```
    username.send_keys(p_login)
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 225, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 396, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=112.0.5615.50)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00C35E23+53059]
	(No symbol) [0x00BC4AF1]
	(No symbol) [0x00ABB250]
	(No symbol) [0x00AE7E56]
	(No symbol) [0x00AE700B]
	(No symbol) [0x00B0A7CC]
	(No symbol) [0x00AE2746]
	(No symbol) [0x00B0AB24]
	(No symbol) [0x00B2066F]
	(No symbol) [0x00B0A5C6]
	(No symbol) [0x00AE0A2C]
	(No symbol) [0x00AE20ED]
	GetHandleVerifier [0x00E9D3CE+2573550]
	GetHandleVerifier [0x00ED3340+2794592]
	GetHandleVerifier [0x00ECCF1C+2768956]
	GetHandleVerifier [0x00CCFA60+682880]
	(No symbol) [0x00BCEE22]
	(No symbol) [0x00BCA8B8]
	(No symbol) [0x00BCA99B]
	(No symbol) [0x00BBDB57]
	BaseThreadInitThunk [0x773800F9+25]
	RtlGetAppContainerNamedObjectPath [0x77B87BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77B87B8E+238]
```

**Comment by ggnetoo** [comment]
BTW, I'm getting this error even in a linux machine where the google chrome has not been updated yet:

Error:
    username.send_keys(p_login)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webelement.py", line 231, in send_keys
    Command.SEND_KEYS_TO_ELEMENT, {"text": "".join(keys_to_typing(value)), "value": keys_to_typing(value)}
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webelement.py", line 403, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=111.0.5563.146)
Stacktrace:
#0 0x55896b9a2243 <unknown>
#1 0x55896b766631 <unknown>
#2 0x55896b79d0cc <unknown>
#3 0x55896b79c8e6 <unknown>
#4 0x55896b7c4082 <unknown>
#5 0x55896b7982e3 <unknown>
#6 0x55896b7c424e <unknown>
#7 0x55896b7dc932 <unknown>
#8 0x55896b7c3e53 <unknown>
#9 0x55896b7969ea <unknown>
#10 0x55896b797b2e <unknown>
#11 0x55896b9f6d5e <unknown>
#12 0x55896b9faa80 <unknown>
#13 0x55896b9dc8b0 <unknown>
#14 0x55896b9fbb63 <unknown>
#15 0x55896b9cdf75 <unknown>
#16 0x55896ba1e998 <unknown>
#17 0x55896ba1eb27 <unknown>
#18 0x55896ba39c23 <unknown>
#19 0x7f6a4f294b43 <unknown>

Google-Chrome version:
$ google-chrome --version
Google Chrome 111.0.5563.146

**Comment by jba-tm** [comment]
yeah something update require chrome 112, even last 30 minute

**Comment by wdeasy** [comment]
I got this error today as well but the version_main = 111 worked for me.

driver = uc.Chrome(options = options, version_main = 111)

**Comment by scriptpro92** [comment]
It leaves me but does not click and does not write email password.
solution?

**Comment by gafito7762** [comment]
Please download right chromedriver for your chrome version here.

https://chromedriver.chromium.org/downloads

**Comment by andresarre** [comment]
the creator of UC posted a video teaching how to solve

https://www.youtube.com/watch?v=7eJ3BGKEfm8&ab_channel=PyAjudeMe
