### ISSUE TITLE
Failed when running web crawling script with undetected-chromedriver in headless mode.

### ISSUE THREAD

**Issue by Chen-Ying-Chen** [ultrafunkamsterdam/undetected-chromedriver#1184]
Hi all,

Hope this message finds you well.

I'm writing to ask for help. 
I ran the following code for web crawling with undetected-chromedriver in headless mode, but failed with this error message: 

> **raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:xxxxx
> from chrome not reachable**

**Part of my codes:**
```
options = uc.ChromeOptions()
options.add_argument('--disable-extensions')
options.add_argument('--disable-gpu')
options.add_argument('--no-sandbox') # Bypass OS security model
options.add_argument('start-maximized')
options.add_argument('disable-infobars')
options.add_argument('--headless=new')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--remote-debugging-port=9222')
options.add_argument('--disable-browser-side-navigation')
options.add_argument('--disable-features=VizDisplayCompositor')
options.add_argument('--disable-blink-features=AutomationControlled')
driver = uc.Chrome(options=options)

driver.get('https://dune.com/browse/dashboards')
time.sleep(4)
driver.implicitly_wait(30)

```

If you know anything that may fix this problem , please share with me.
Thank you!!

**Comment by ultrafunkamsterdam** [comment]
Apparently you're missing Chrome browser

**Comment by Chen-Ying-Chen** [comment]
@ultrafunkamsterdam 

Thank you for your reply. 
I was able to successfully run the code without using `options.add_argument('--headless=new')`, so I believe this may be the cause of the error message I mentioned earlier. 
Would you be able to provide a more detailed explanation? 
Thank you so much.
