### ISSUE TITLE
It seems that the options.add_argument() functions are not working in the following

### ISSUE THREAD

**Issue by y0un9kane** [ultrafunkamsterdam/undetected-chromedriver#1190]
inoperative
options.add_argument('--window-size=800,600')
options.add_argument('--lang=en-US')
options.add_argument('--disable-tracking')
options.add_argument("--timezone=America/New_York")

These are certain to work
options.add_argument('--proxy-server=
options.add_argument( '--user-agent=
options.add_argument("--incognito")

**Comment by ultrafunkamsterdam** [comment]
Rtfm
