### ISSUE TITLE
Webdriver version issue

### ISSUE THREAD

**Issue by charizardmatok** [ultrafunkamsterdam/undetected-chromedriver#1192]
Hello everyone, I need help, please.

The following setup results in a:

selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:59290
from session not created: This version of ChromeDriver only supports Chrome version 112

I tried downloading a chromedriver executable, and setting that as the 'driver_executable_path', but that results in recaptcha noticing that a bot is trying to solve it. Any help?

Setup:
```
ua = 'Mozilla/5.0 (Windows NT 4.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36'

options = webdriver.ChromeOptions()

options.add_argument("--window-size=1920,1080")

options.add_argument(f'--user-agent={ua}')
options.add_argument('--incognito')

options.add_argument('--no-sandbox')
options.add_argument("--disable-extensions")

driver = webdriver.Chrome(options=options)

**Comment by juanfradb** [comment]
how could you solve it?
