### ISSUE TITLE
v2 driver entering Welcome to Google Chrome first run dialog every time

### ISSUE THREAD

**Issue by starbolin-git** [ultrafunkamsterdam/undetected-chromedriver#120]
Mac OS Big Sur
Chrome 89.0.4389.90

Every attempt to launch the browser with v2 driver triggers the first run dialog box:
"Welcome to Google Chrome", Google Chrome is ready to complete your installation.
(x) Set Google Chrome as your default browser
(x) Help make Google Chrome better by automatically sending usage statistics and crash reports to Google.
\>>Start Google Chrome<<

Legacy driver does not have this issue.

Examples:
```
import undetected_chromedriver.v2 as uc
driver = uc.Chrome()
```

Tried adding combination of various options to avoid e.g.:
```
options = uc.ChromeOptions()
options.add_argument("--no-first-run")
options.add_argument("--disable-fre")
options.add_argument("--no-default-browser-check")
driver = uc.Chrome(options=options)
```

also tried using selenium ChromeOptions as not sure this is implemented yet in v2 e.g.
```
import undetected_chromedriver.v2 as uc
from selenium import webdriver
options = webdriver.ChromeOptions()
options.add_argument("--no-first-run")
driver = uc.Chrome(options=options)
```
Nothing worked.  Why is this only happening in v2?  Is there a workaround?

**Comment by ultrafunkamsterdam** [comment]
YEp, the problem here is MacOS and their annoyingly urge for putting popup screens for even the most unneeded "consents". I had this issue as well when tested it on MacOS. This certainly is something worth investigating, maybe by fixing the other issue : being able to reuse the profile. Then still  doubt whether they'll find another popup to throw at you. Lets keep this open for investigation.

**Comment by vesper8** [comment]
Having the same problem.

It does work if you run it in headless mode however. But @ultrafunkamsterdam mentioned that this might break other things and get you detected. I'm running it from my own local IP where the website already recognizes me as a human.

This does circumvent the two prompts and return the html

```
import undetected_chromedriver.v2 as uc
from bs4 import BeautifulSoup

options = uc.ChromeOptions()
options.headless = True
driver = uc.Chrome(options=options)

with driver:
    driver.get('https://steamdb.info/patchnotes/6420358/')
    page = BeautifulSoup(driver.page_source, 'html.parser')
    print(page)
```

**Comment by ultrafunkamsterdam** [comment]
well... get-detected. It really depends.. if you are a normal scraper, scraping a normal website (or your own perhaps)  works perfectly fine in headless, just as the regular chrome driver so to say :)
But usually the sites protected with Web Application Firewalls or other means of bot detection usually have their reasons to do so, and so those scrapers usually don't have a very legit reason to do so. 9/10 sites are perfectly scrapable with even the normal regular chromedriver.

**Comment by vesper8** [comment]
> YEp, the problem here is MacOS and their annoyingly urge for putting popup screens for even the most unneeded "consents". I had this issue as well when tested it on MacOS. This certainly is something worth investigating, maybe by fixing the other issue : being able to reuse the profile. Then still doubt whether they'll find another popup to throw at you. Lets keep this open for investigation.

Any chance you could re-open this issue @ultrafunkamsterdam as the issue is ongoing (With the required consents on every attempt). This issue combined with the fact that you can't get a pass in headless mode means that there isn't currently any way of getting around the Cloudflare check on MacOS

**Comment by jglorioso** [comment]
I was able to avoid the prompt in MacOS by creating a directory with a file named `First Run` (empty) then listing that directory as a custom profile.

Ex:
```
import undetected_chromedriver.v2 as uc
import os
from pathlib import Path

# Create empty profile
os.mkdir('./chrome_profile')
Path('./chrome_profile/First Run').touch()

options = uc.ChromeOptions()
options.add_argument('--user-data-dir=./chrome_profile/')
uc.Chrome(options=options)
```

**Comment by thiagobenine** [comment]
Thanks @jglorioso. This solved for me!

**Comment by didthon** [comment]
> I was able to avoid the prompt in MacOS by creating a directory with a file named `First Run` (empty) then listing that directory as a custom profile.
> 
> Ex:
> 
> ```
> import undetected_chromedriver.v2 as uc
> import os
> from pathlib import Path
> 
> # Create empty profile
> os.mkdir('./chrome_profile')
> Path('./chrome_profile/First Run').touch()
> 
> options = uc.ChromeOptions()
> options.add_argument('--user-data-dir=./chrome_profile/')
> uc.Chrome(options=options)
> ```

Great thanks, this works

**Comment by frederikme** [comment]
@jglorioso This is a genius fix. Many thanks! :-)
Sometimes it definitely is worth the time scrolling through past issues instead of trial and error.

**Comment by Dhruv97Sharma** [comment]
> Mac OS Big Sur Chrome 89.0.4389.90
> 
> Every attempt to launch the browser with v2 driver triggers the first run dialog box: "Welcome to Google Chrome", Google Chrome is ready to complete your installation. (x) Set Google Chrome as your default browser (x) Help make Google Chrome better by automatically sending usage statistics and crash reports to Google. >>Start Google Chrome<<
> 
> Legacy driver does not have this issue.
> 
> Examples:
> 
> ```
> import undetected_chromedriver.v2 as uc
> driver = uc.Chrome()
> ```
> 
> Tried adding combination of various options to avoid e.g.:
> 
> ```
> options = uc.ChromeOptions()
> options.add_argument("--no-first-run")
> options.add_argument("--disable-fre")
> options.add_argument("--no-default-browser-check")
> driver = uc.Chrome(options=options)
> ```
> 
> also tried using selenium ChromeOptions as not sure this is implemented yet in v2 e.g.
> 
> ```
> import undetected_chromedriver.v2 as uc
> from selenium import webdriver
> options = webdriver.ChromeOptions()
> options.add_argument("--no-first-run")
> driver = uc.Chrome(options=options)
> ```
> 
> Nothing worked. Why is this only happening in v2? Is there a workaround?

I tried to resolve the same problem but the option parameters that you have added worked for me now, I guess they added fixes in the library.

The following solution worked for me, I hope it helps and works for someone else as well:

```
import undetected_chromedriver.v2 as uc

options = uc.ChromeOptions()
options.add_argument('--disable-notifications')
options.add_argument("--disable-popup-blocking")
options.add_argument("--no-first-run")
options.add_argument("--disable-fre")
options.add_argument("--no-default-browser-check")
self.driver = uc.Chrome(options = options, version_main=110)
```
