### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 87

### ISSUE THREAD

**Issue by rrfaria** [ultrafunkamsterdam/undetected-chromedriver#121]
Chrome 89 doesn't works 

when starts it complains 
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 87

Current browser version is 89.0.4389.90 with binary path /app/.apt/usr/bin/google-chrome

**Comment by ultrafunkamsterdam** [comment]
delete ./chromedriver from your working directory.
