### ISSUE TITLE
How can I allow pop-ups?

### ISSUE THREAD

**Issue by juanfrilla** [ultrafunkamsterdam/undetected-chromedriver#1213]
I'm trying to download a pdf file through opening it in a new tab:

`self.driver.execute_script("window.open('" + pdf_url + "', '_blank');")`

But when the script reaches to the line I put above and Its executed without headless mode,  It opens the browser go to the url and I'm getting that popups are blocked

I'm trying to enable pop-ups like that:

using ```options = uc.ChromeOptions()
        options.add_argument("--disable-popup-blocking")```

But does not work (keeps appearing that pop-ups are blocked when open the browser), any solution?

**Comment by nullANzero** [comment]
> I'm trying to download a pdf file through opening it in a new tab:
> 
> `self.driver.execute_script("window.open('" + pdf_url + "', '_blank');")`
> 
> But when the script reaches to the line I put above and Its executed without headless mode, It opens the browser go to the url and I'm getting that popups are blocked
> 
> I'm trying to enable pop-ups like that:
> 
> using `options = uc.ChromeOptions() options.add_argument("--disable-popup-blocking")`
> 
> But does not work (keeps appearing that pop-ups are blocked when open the browser), any solution?

Do you fix it?
