### ISSUE TITLE
Multi-threaded use of UC is impossible

### ISSUE THREAD

**Issue by RealKien** [ultrafunkamsterdam/undetected-chromedriver#1238]
I'm meeting the error: `Text file busy: '/home/webapp/.local/share/undetected_chromedriver/undetected_chromedriver'` , when I try to call 2 undetected chromedrivers at the same time with the command 
`driver = uc.Chrome(options=opts, version_main=111)` (so the command is inside a function, and I would call the function twice at the same time concurrently)

Is there anyway to fix this? I followed the solution in the below discussion but to no avail...

Full error trace:
```
May  5 22:36:36 ip-172-31-74-2 web: [2023-05-05 22:36:36,238] ERROR in app: Exception on /search/search/collect_data [POST]
May  5 22:36:36 ip-172-31-74-2 web: Traceback (most recent call last):
May  5 22:36:36 ip-172-31-74-2 web: File "/var/app/venv/staging-LQM1lest/lib64/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
May  5 22:36:36 ip-172-31-74-2 web: response = self.full_dispatch_request()
May  5 22:36:36 ip-172-31-74-2 web: File "/var/app/venv/staging-LQM1lest/lib64/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
May  5 22:36:36 ip-172-31-74-2 web: rv = self.handle_user_exception(e)
May  5 22:36:36 ip-172-31-74-2 web: File "/var/app/venv/staging-LQM1lest/lib64/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
May  5 22:36:36 ip-172-31-74-2 web: rv = self.dispatch_request()
May  5 22:36:36 ip-172-31-74-2 web: File "/var/app/venv/staging-LQM1lest/lib64/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
May  5 22:36:36 ip-172-31-74-2 web: return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
May  5 22:36:36 ip-172-31-74-2 web: File "/var/app/current/Web_Development/Search/views.py", line 165, in collect_data
May  5 22:36:36 ip-172-31-74-2 web: driver = future.result()
May  5 22:36:36 ip-172-31-74-2 web: File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 444, in result
May  5 22:36:36 ip-172-31-74-2 web: return self.__get_result()
May  5 22:36:36 ip-172-31-74-2 web: File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 389, in __get_result
May  5 22:36:36 ip-172-31-74-2 web: raise self._exception
May  5 22:36:36 ip-172-31-74-2 web: File "/usr/lib64/python3.8/concurrent/futures/thread.py", line 57, in run
May  5 22:36:36 ip-172-31-74-2 web: result = self.fn(*self.args, **self.kwargs)
May  5 22:36:36 ip-172-31-74-2 web: File "/var/app/current/Web_Development/Search/views.py", line 150, in initialize_driver
May  5 22:36:36 ip-172-31-74-2 web: driver = uc.Chrome(options=opts, version_main=111)
May  5 22:36:36 ip-172-31-74-2 web: File "/var/app/venv/staging-LQM1lest/lib64/python3.8/site-packages/undetected_chromedriver/__init__.py", line 441, in __init__
May  5 22:36:36 ip-172-31-74-2 web: super(Chrome, self).__init__(
May  5 22:36:36 ip-172-31-74-2 web: File "/var/app/venv/staging-LQM1lest/lib64/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 84, in __init__
May  5 22:36:36 ip-172-31-74-2 web: super().__init__(
May  5 22:36:36 ip-172-31-74-2 web: File "/var/app/venv/staging-LQM1lest/lib64/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in __init__
May  5 22:36:36 ip-172-31-74-2 web: self.service.start()
May  5 22:36:36 ip-172-31-74-2 web: File "/var/app/venv/staging-LQM1lest/lib64/python3.8/site-packages/selenium/webdriver/common/service.py", line 96, in start
May  5 22:36:36 ip-172-31-74-2 web: self._start_process(self._path)
May  5 22:36:36 ip-172-31-74-2 web: File "/var/app/venv/staging-LQM1lest/lib64/python3.8/site-packages/selenium/webdriver/common/service.py", line 197, in _start_process
May  5 22:36:36 ip-172-31-74-2 web: self.process = subprocess.Popen(
May  5 22:36:36 ip-172-31-74-2 web: File "/usr/lib64/python3.8/subprocess.py", line 858, in __init__
May  5 22:36:36 ip-172-31-74-2 web: self._execute_child(args, executable, preexec_fn, close_fds,
May  5 22:36:36 ip-172-31-74-2 web: File "/usr/lib64/python3.8/subprocess.py", line 1704, in _execute_child
May  5 22:36:36 ip-172-31-74-2 web: raise child_exception_type(errno_num, err_msg, err_filename)
May  5 22:36:36 ip-172-31-74-2 web: OSError: [Errno 26] Text file busy: '/home/webapp/.local/share/undetected_chromedriver/undetected_chromedriver'


```

### Discussed in https://github.com/ultrafunkamsterdam/undetected-chromedriver/discussions/1063

<div type='discussions-op-text'>

<sup>Originally posted by **ben-elbert** February 10, 2023</sup>
Hello, Im using UC in a multi-threaded manner. 
Ever since this update, (and im quoting):
```
3.4.0
Big update! be careful as it -potentially- could break your code.

rewritten the anti-detection mechanism instead of removing and renaming variables, we just keep them, but prevent them from being injected in the first place. This will keep us safe from detection at least for the near future.

rewritten the file naming, to prevent ending up with 1000 of {randomstring}_chromedriver.exe 's instead it is just called undetected_chromedriver.exe
```

I get this error (And for a logical reason):
OSError: [Errno 26] Text file busy: ‘/root/.local/share/undetected_chromedriver/undetected_chromedriver’

Thanks in advance!</div>

**Comment by mdmintz** [comment]
You might be able to use [github.com/seleniumbase/SeleniumBase](https://github.com/seleniumbase/SeleniumBase) in ``--uc`` mode:

Run the following using ``python`` or ``pytest -n4`` after ``pip install seleniumbase``:

```python
from parameterized import parameterized
from seleniumbase import BaseCase

if __name__ == "__main__":
    from pytest import main
    main([__file__, "--uc", "-s", "-n4"])

class UC_MultiTests(BaseCase):
    @parameterized.expand([[]] * 4)
    def test_uc_mode_multithreaded(self):
        if not self.undetectable:
            self.get_new_driver(undetectable=True)
        self.open("https://nowsecure.nl/#relax")
        self.assert_text("OH YEAH, you passed!", "h1", timeout=7.25)
        self.sleep(4)
```

Repeats the test 4 times in ``--uc`` mode with parameterization and parallel runs.

**Comment by RealKien** [comment]
Hi @mdmintz, thank you for your solution but it doesn't really work for my case because  esentially, I have 
`
def initialize_driver():
current_active_threads = max_threads - thread_pool._work_queue.qsize()
print("Current active threads:", current_active_threads, "/5")
opts = uc.ChromeOptions()
opts.add_argument("--disable-blink-features=AutomationControlled")
opts.set_capability("detach", True)
opts.add_argument("--disable-dev-shm-usage")
opts.add_argument('--ignore-certificate-errors')
opts.add_argument('--disable-gpu')
opts.add_argument('--log-level=3')
opts.add_argument('--disable-notifications')
opts.add_argument('--disable-popup-blocking')
driver = [uc.Chrome](http://uc.chrome/)(options=opts, version_main=111)
return driver, then @search_blueprints.route('/search/collect_data', methods=['POST'])
`
and
`
def collect_data():
start_time = time()
print("collecting data")
query = request.form['query']
print("Collect Data", query)
# Get the current number of active threads
# Submit the driver initialization task to the thread pool
future = thread_pool.submit(initialize_driver)
driver = future.result()
`
the collect_data data function is the one that listens to web request, and right now, if 2 users go to my website [xyz.com/search/collect_data](http://xyz.com/search/collect_data) at the same time,none of them would work and meets the  TextFileBusy error above

**Comment by nullANzero** [comment]
> Привет @mdmintz, спасибо за ваше решение, но в моем случае оно на самом деле не работает, потому что, по сути, у меня есть
> 
> ```
> def initialize_driver():
>     current_active_threads = max_threads - thread_pool._work_queue.qsize()
>     print("Current active threads:", current_active_threads, "/5")
>     opts = uc.ChromeOptions()
>     opts.add_argument("--disable-blink-features=AutomationControlled")
>     opts.set_capability("detach", True)
>     opts.add_argument("--disable-dev-shm-usage")
>     opts.add_argument('--ignore-certificate-errors')
>     opts.add_argument('--disable-gpu')
>     opts.add_argument('--log-level=3')
>     opts.add_argument('--disable-notifications')
>     opts.add_argument('--disable-popup-blocking')
>     driver = [uc.Chrome](http://uc.chrome/)(options=opts, version_main=111)
> return driver, then @search_blueprints.route('/search/collect_data', methods=['POST'])
> ```
> 
> и
> 
> ```
> def collect_data():
>   start_time = time()
>   print("collecting data")
>   query = request.form['query']
>   print("Collect Data", query)
>   
>   future = thread_pool.submit(initialize_driver)
>   driver = future.result()
> ```
> 
> функция сбора данных collect_data - это та, которая прослушивает веб-запрос, и прямо сейчас, если 2 пользователя перейдут на мой веб-сайт[xyz.com/search/collect_data ](http://xyz.com/search/collect_data)в то же время ни один из них не будет работать и соответствует приведенной выше ошибке TextFileBusy

Here is the answer

https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1041

(at the end)

**Comment by RealKien** [comment]
Thank you!
