### ISSUE TITLE
v2 doesn't find elements?

### ISSUE THREAD

**Issue by NeuroscienceScripts** [ultrafunkamsterdam/undetected-chromedriver#124]
It's possible I'm doing something wrong, but I think I've implemented things correctly.  

```
import time
from configparser import ConfigParser
import undetected_chromedriver.v2 as uc

class AddCartbot():
	def __init__(self,config):
		options = uc.ChromeOptions()
		options.add_argument("--disable-blink-features=AutomationControlled")
		self.driver = uc.Chrome(options=options)
		#XXX
		self.url="XXX"
		with self.driver:
			self.driver.get(self.url)
		time.sleep(10)

	def tryToAdd(self):
		add_to_cart = self.driver.find_elements_by_partial_link_text('/cart/add')
		print(len(add_to_cart))

print("Starting Bot")
config_file = ConfigParser()
config_file.read("config.ini")
bot = AddCartbot(config_file)

incart = False
while not incart:
	time.sleep(3)
	bot.tryToAdd()

```
The above code fails to find any of the elements even though there are 11 of them.

**Comment by ultrafunkamsterdam** [comment]
PLease guys. stop Adding options like `--disable-blink-features=AutomationControlled` . This is not neccesary when using v2. The time.sleep(10) should not be used either. That is already taken care of by using `with driver`. And thirdly, i think `find_elements_by_partial_link_text('/cart/add')` is not going to work. You shoud enter the exact text (and i couldn't imagine someone would write /card/add on their button or link.

Hopefully after taking care of this points. you should be okay.

**Comment by NICK-CHAOS-DEMON** [comment]
> PLease guys. stop Adding options like `--disable-blink-features=AutomationControlled` . This is not neccesary when using v2. The time.sleep(10) should not be used either. That is already taken care of by using `with driver`. And thirdly, i think `find_elements_by_partial_link_text('/cart/add')` is not going to work. You shoud enter the exact text (and i couldn't imagine someone would write /card/add on their button or link.
> 
> Hopefully after taking care of this points. you should be okay.

Sorry, your codes look like shit!

**Comment by NICK-CHAOS-DEMON** [comment]
And you look like shit! Comon guys!
