### ISSUE TITLE
Session not created exception: Loader has changed while resolving nodes

### ISSUE THREAD

**Issue by rafamelo01** [ultrafunkamsterdam/undetected-chromedriver#1257]
During the try to open a uc.Chrome instance in a specific directory. 

This line of execution: 
    **return uc.Chrome(user_data_dir), options=setarPerfil(), version_main=113, user_multi_procs=True)**

And this exception occur:
STACK TRACE:

    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from no such execution context: loader has changed while resolving nodes
  (Session info: chrome=113.0.5672.93)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x009D8893+48451]
        (No symbol) [0x0096B8A1]
        (No symbol) [0x00875058]
        (No symbol) [0x008779D6]
        (No symbol) [0x00879631]
        (No symbol) [0x008796D0]
        (No symbol) [0x008C1A58]
        (No symbol) [0x008C047C]
        (No symbol) [0x008BA0B6]
        (No symbol) [0x00897E08]
        (No symbol) [0x00898F2D]
        GetHandleVerifier [0x00C38E3A+2540266]
        GetHandleVerifier [0x00C78959+2801161]
        GetHandleVerifier [0x00C7295C+2776588]
        GetHandleVerifier [0x00A62280+612144]
        (No symbol) [0x00974F6C]
        (No symbol) [0x009711D8]
        (No symbol) [0x009712BB]
        (No symbol) [0x00964857]
        BaseThreadInitThunk [0x756E6709+25]
        RtlGetFullPathName_UEx [0x76F67CCD+173]
        RtlGetFullPathName_UEx [0x76F67C9B+123]

What can be wrong?

**Comment by rafamelo01** [comment]
No, different windows, but this error occurred before the new propertie user_multi_procs=True

**Comment by rafamelo01** [comment]
Im quitting and reopening the instances in certain periods of time, can this cause this type of error?

**Comment by desis123** [comment]
I am having the same issue

**Comment by desis123** [comment]
Okay pip install undetected-chromedriver solved my issue.. First time I was using pip install undetected-chromedriver==2.1.1 , which was casuing issue

**Comment by rafamelo01** [comment]
pip install version 3.4.5 apparently solve!
