### ISSUE TITLE
How to use add_extension?

### ISSUE THREAD

**Issue by joska1993** [ultrafunkamsterdam/undetected-chromedriver#126]
How can I add an extension with v2?

.add_extension ¿?

**Comment by arigatou** [comment]
If you're trying to use extensions, typically I use the following launch argument:

"--disable-extensions-except={PATH_TO_EXTENSION_HERE}"

You can use multiple extensions, just separate them by commas, eg; 

"--disable-extensions-except=/extensions/ublock,/extensions/httpseverywhere,/extensions/asd123"

**Comment by joska1993** [comment]
> If you're trying to use extensions, typically I use the following launch argument:
> 
> "--disable-extensions-except={PATH_TO_EXTENSION_HERE}"
> 
> You can use multiple extensions, just separate them by commas, eg;
> 
> "--disable-extensions-except=/extensions/ublock,/extensions/httpseverywhere,/extensions/asd123"

In undetected-chromedriver.v2 it does not work for me

**Comment by ultrafunkamsterdam** [comment]
There aren't any claims made that they would work. V2 is to "pass" the heaviest mitigations. It also works totally different than "v1", where chrome is started by the webdriver executable. V2 launches chrome onder it's own process and then connects the webdriver. There will certainly be ways to do it such as altering code such that  the argumentens used to lunch chrome. Also check this https://chromedriver.chromium.org/extensions  

However, the main goal of the package here is trying to be undetected, using extensions could (will) break it, and guess who gets all the "issues" ?   Furthermore you supplied 0 info on what you are trying to accomplish and/or tried (+ code)
