### ISSUE TITLE
Detected when Getting Browser Attributes by Distil

### ISSUE THREAD

**Issue by lellywang** [ultrafunkamsterdam/undetected-chromedriver#127]
Getting .page_source for example, will trigger detection by Distil. 

To replicate, go to a ticketmaster event using driver.get(). Get the .page_source in the code. Then try to open the same link on the same driver.

**Comment by lellywang** [comment]
SOLVED: Issue caused by using a proxy extension

**Comment by lellywang** [comment]
Nevermind about closing this, issue is with selenium still

**Comment by lellywang** [comment]
Solved

**Comment by ultrafunkamsterdam** [comment]
Fyi: just tested : driver.get("view-source:https://google.com")

**Comment by FranciscoPalomares** [comment]
@lellywang how did you solve it? thank you
