### ISSUE TITLE
headless mode not pass

### ISSUE THREAD

**Issue by m9w** [ultrafunkamsterdam/undetected-chromedriver#129]
I use master branch (27.03.21).
In first tab never "5 sec" test not pass in headless mode.
But work only in "head" mode:

`import undetected_chromedriver as uc
import time
driver = uc.Chrome()
driver.execute_script("window.open('https://doge.click/bc/0','_blank');")
time.sleep(7)
print(1)
driver.get('https://doge.click/bc/0')

while True:
    print(driver.title)
    time.sleep(1)`

And not work:
`import undetected_chromedriver as uc
import time
options = uc.ChromeOptions()
options.headless = True
options.add_argument('--headless')
driver = uc.Chrome(options=options)
driver.execute_script("window.open('https://doge.click/bc/0','_blank');")
time.sleep(7)
print(1)
driver.get('https://doge.click/bc/0')

while True:
    print(driver.title)
    time.sleep(1)`

Manual open always successful pass.
v2 not allow pop-ups new tabs.
And is it possible to use incognito mode?

**Comment by ultrafunkamsterdam** [comment]
Yep. I never stated that would work in headless. Those 2 are such a world apart. Only running them and directly dump the Window object. Huge difference in values. I'm busy getting the environments more alike.

**Comment by Avnsx** [comment]
> Yep. I never stated that would work in headless. Those 2 are such a world apart. Only running them and directly dump the Window object. Huge difference in values. I'm busy getting the environments more alike.

@ultrafunkamsterdam I would be incredibly pleased if you could get v2 working in headless mode soon, because unfortunately I'm facing [the cloudflare hcaptcha site](https://i.imgur.com/drQr8f1.png) in v1's headless mode.

**Comment by m9w** [comment]
> > Ага. Я никогда не заявлял, что будет работать без головы. Эти двое - такой особенный мир. Только запускать их и напрямую выгружать объект Window. Огромная разница в ценностях. Я занят тем, чтобы сделать окружающую среду более похожей.
> 
> @ultrafunkamsterdam Я был бы невероятно рад, если бы вы могли скоро заставить v2 работать в безголовом режиме, потому что, к сожалению, я сталкиваюсь [с сайтом cloudflare hcaptcha](https://i.imgur.com/drQr8f1.png) в безголовом режиме v1.

I have only infinity reload every 12 seconds.

**Comment by ultrafunkamsterdam** [comment]
window.open  and all those sleeps is very bad practise. 

just use ```driver.tab_new("https://www.pornhub.com")```



and i see you're using old code. try this:

```python
import undetected_chromedriver.v2 as uc
driver = uc.Chrome()
with driver:
    driver.get('https://nowsecure.nl')
 ```

**Comment by lamyipming** [comment]
> window.open and all those sleeps is very bad practise.
> 
> just use `driver.tab_new("https://www.pornhub.com")`
> 
> and i see you're using old code. try this:
> 
> ```python
> import undetected_chromedriver.v2 as uc
> driver = uc.Chrome()
> with driver:
>     driver.get('https://nowsecure.nl')
> ```



I found one issue log stating that this is the proper way
```python
with driver:
    driver.get('https://nowsecure.nl')
time.sleep(x)
```
instead of 
```python
with driver:
    driver.get('https://nowsecure.nl')
    time.sleep(x)
```
I guess some magic happened in the with statement.
do we need to use with whenever driver is called upon?
like
```python
with driver:
    driver.get('https://nowsecure.nl')
    driver.find_element().click()
```
or is this fine too?
```python
with driver:
    driver.get('https://nowsecure.nl')
driver.find_element().click()
```
the question is, should I use with driver: driver.tab_new() or just simply driver.tab_new() without the "with:"?
or more generally, when to use with?
is it required whenever we direct ourselves into a new page?

**Comment by IamZiroToxic** [comment]
> window.open and all those sleeps is very bad practise.
> 
> just use `driver.tab_new("https://www.pornhub.com")`
> 
> and i see you're using old code. try this:
> 
> ```python
> import undetected_chromedriver.v2 as uc
> driver = uc.Chrome()
> with driver:
>     driver.get('https://nowsecure.nl')
> ```

Bro wtf the new tab URL 😂
