### ISSUE TITLE
Using custom chromedrivers

### ISSUE THREAD

**Issue by tabsandspaces** [ultrafunkamsterdam/undetected-chromedriver#130]
It would be really cool if there was an option for using a locally saved chromedriver binary (or specifying a custom download URL). This will allow using the package on systems for which there are no official chromedrivers available (for example, 32-bit Raspberry Pi OS).

**Comment by ultrafunkamsterdam** [comment]
`Chrome(executable_path="./yourdriver")`

**Comment by albertoZurini** [comment]
I'm having a similar issue: I'm running selenium on docker, but this library is looking for `chromedriver.exe` and then throws (I'm on Ubuntu right now). Tomorrow I will fork this and try to figure out what is wrong....

**Comment by albertoZurini** [comment]
![image](https://user-images.githubusercontent.com/24524861/112748853-e1377b80-8fbe-11eb-8fb0-06723c815968.png)

As of now I've noticed this line throws, can be fixed using `shutils`

**Comment by ultrafunkamsterdam** [comment]
you need to upgrade . this runs on win,linux,macos . the filename it searches for depends on the platform you're on. so for linux it will look for chromedriver (no .exe)
