### ISSUE TITLE
How can I get the current Chrome version in order to add it automatically?

### ISSUE THREAD

**Issue by juanfrilla** [ultrafunkamsterdam/undetected-chromedriver#1302]
Sometimes my code breaks because the downloaded chromedriver and Chrome browser versions dont match, with errors like this:
```
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:44193
from session not created: This version of ChromeDriver only supports Chrome version 111
Current browser version is 113.0.5672.126
```
I have understood that uc downloads Chrome and chromedriver everytime it starts, so how can I get the downloaded google-chrome version to autoset in the version_main?

  I did  something like this, tell me if there could be a better approach

```python
            self._driver = uc.Chrome(
                desired_capabilities=self._capabilities,
                options=self._options,
                version_main=self.get_chrome_version(),
            )
            
          
          def get_chrome_version(self):
          path = chromedriver_autoinstaller.install()
          return path.split("/")[-2]
```

**Comment by juanfrilla** [comment]
thanks @mdmintz i'll try that stuff, and do seleniumbase support working with multiple browsers at the same time like undetected-chromedriver?

**Comment by mdmintz** [comment]
@juanfrilla Yes, via pytest-multithreading. Eg. ``pytest -n4``. If that's what you want to do, you'll need to use a different Syntax Format from the ones that use ``Driver`` or ``DriverContext``. See https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md for all formats. (Use a format that inherits ``BaseCase``, or one that uses the ``sb`` pytest fixture.)

**Comment by juanfrilla** [comment]
@mdmintz thanks once again, I'm not going to use them with pytest but with scrapy spiders, I mean, run multiple of them in the scrapy spiders that are thrown with `scrapy crawl nameofthespider`

**Comment by ultrafunkamsterdam** [comment]
You could just use Chrome(version_main=109) to pinpoint the version (this example 109)

**Comment by ultrafunkamsterdam** [comment]
It does not download chrome by the way so you know in advance which version you got and set the driver accordingly
