### ISSUE TITLE
How can I add a proxy in undetected chromedriver?

### ISSUE THREAD

**Issue by juanfrilla** [ultrafunkamsterdam/undetected-chromedriver#1306]
It does not work with seleniumwire options like normal selenium and it does not work with this  `options.add_argument(f'--proxy-server={proxy}')`

**Comment by Hao-Kang** [comment]
Actually, it does work with that option. Can you double check if your proxy server is working correctly? And maybe you might confider adding the port number as well!
```
options = uc.ChromeOptions()
options.add_argument(f'--proxy-server={host}:{port}')
browser = uc.Chrome(options, version_main=113)
```

**Comment by juanfrilla** [comment]
thanks @Hao-Kang @ultrafunkamsterdam the `{proxy}` value is like this https://127.0.0.1:8800

**Comment by sujaykhandekar** [comment]
it works fine for me like this
```options.add_argument(f'--proxy-server={proxy_address}:{proxy_port}')
```
just make sure to whitelist the IP from which you are running the script

**Comment by skyl3** [comment]
if you need auth proxy, use this code 
`import seleniumwire.undetected_chromedriver as uc

options = uc.ChromeOptions()
proxy_options = {
    'proxy': {
        'https': f'http://{proxy_username}:{proxy_password}@{proxy_host}:{proxy_port}',
    }
}

driver = uc.Chrome(options=options, version_main=114, seleniumwire_options = proxy_options)`

**Comment by desis123** [comment]
This Worked for me 
```
import os 
options = uc.ChromeOptions()
PROXY_FOLDER = os.path.join('extension', 'proxy_folder')
PROXY_HOST = *.*.*.*"
PROXY_PORT = "1234"
PROXY_USER = "username"
PROXY_PASS = "password"
manifest_json = """
{
    "version": "1.0.0",
    "manifest_version": 2,
    "name": "Chrome Proxy",
    "permissions": [
        "proxy",
        "tabs",
        "unlimitedStorage",
        "storage",
        "<all_urls>",
        "webRequest",
        "webRequestBlocking"
    ],
    "background": {
        "scripts": ["background.js"]
    },
    "minimum_chrome_version":"22.0.0"
}
"""

background_js = """
var config = {
        mode: "fixed_servers",
        rules: {
        singleProxy: {
            scheme: "http",
            host: "%s",
            port: parseInt(%s)
        },
        bypassList: ["localhost"]
        }
    };

chrome.proxy.settings.set({value: config, scope: "regular"}, function() {});

function callbackFn(details) {
    return {
        authCredentials: {
            username: "%s",
            password: "%s"
        }
    };
}

chrome.webRequest.onAuthRequired.addListener(
            callbackFn,
            {urls: ["<all_urls>"]},
            ['blocking']
);
""" % (PROXY_HOST, PROXY_PORT, PROXY_USER, PROXY_PASS)
with open(f"{PROXY_FOLDER}/manifest.json","w") as f:
    f.write(manifest_json)
with open(f"{PROXY_FOLDER}/background.js","w") as f:
    f.write(background_js)   
    
    
  options.add_argument(f"--load-extension={PROXY_FOLDER}")  
```

**Comment by sSuHao** [comment]
> if you need auth proxy, use this code
> 
> ```
> import seleniumwire.undetected_chromedriver as uc
> 
> options = uc.ChromeOptions()
> proxy_options = {
>     'proxy': {
>         'https': f'http://{proxy_username}:{proxy_password}@{proxy_host}:{proxy_port}',
>     }
> }
> 
> driver = uc.Chrome(options=options, version_main=114, seleniumwire_options = proxy_options)
> ```

I tried this but it threw me this error

Exception ignored in: <function Chrome.__del__ at 0x000002A3003B11C0>
Traceback (most recent call last):
  File "undetected_chromedriver\__init__.py", line 800, in __del__
  File "seleniumwire\webdriver.py", line 67, in quit
  File "undetected_chromedriver\__init__.py", line 763, in __getattribute__
AttributeError: 'Chrome' object has no attribute 'backend'

**Comment by pedrofnts** [comment]
> 
could you help me implementing this?

**Comment by juanfrilla** [comment]
@pedrofnts test this:
```python
options = uc.ChromeOptions()
options.add_argument(f'--proxy-server=http://host:port')

driver = uc.Chrome(
        options=options,
    )
```

**Comment by pedrofnts** [comment]
@juanfrilla I need to add an authenticated proxy.

**Comment by HamiguaLu** [comment]
Tested almost one day, it seems it's true that  **Chrom doesn't support socks5 proxy with AUTH**

**Comment by Kuhicop** [comment]
> os.path.join('extension', 'proxy_folder')

PROXY_FOLDER = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'proxy_folder')

**Comment by damodhar131787** [comment]
> This Worked for me
> 
> ```
> import os 
> options = uc.ChromeOptions()
> PROXY_FOLDER = os.path.join('extension', 'proxy_folder')
> PROXY_HOST = *.*.*.*"
> PROXY_PORT = "1234"
> PROXY_USER = "username"
> PROXY_PASS = "password"
> manifest_json = """
> {
>     "version": "1.0.0",
>     "manifest_version": 2,
>     "name": "Chrome Proxy",
>     "permissions": [
>         "proxy",
>         "tabs",
>         "unlimitedStorage",
>         "storage",
>         "<all_urls>",
>         "webRequest",
>         "webRequestBlocking"
>     ],
>     "background": {
>         "scripts": ["background.js"]
>     },
>     "minimum_chrome_version":"22.0.0"
> }
> """
> 
> background_js = """
> var config = {
>         mode: "fixed_servers",
>         rules: {
>         singleProxy: {
>             scheme: "http",
>             host: "%s",
>             port: parseInt(%s)
>         },
>         bypassList: ["localhost"]
>         }
>     };
> 
> chrome.proxy.settings.set({value: config, scope: "regular"}, function() {});
> 
> function callbackFn(details) {
>     return {
>         authCredentials: {
>             username: "%s",
>             password: "%s"
>         }
>     };
> }
> 
> chrome.webRequest.onAuthRequired.addListener(
>             callbackFn,
>             {urls: ["<all_urls>"]},
>             ['blocking']
> );
> """ % (PROXY_HOST, PROXY_PORT, PROXY_USER, PROXY_PASS)
> with open(f"{PROXY_FOLDER}/manifest.json","w") as f:
>     f.write(manifest_json)
> with open(f"{PROXY_FOLDER}/background.js","w") as f:
>     f.write(background_js)   
>     
>     
>   options.add_argument(f"--load-extension={PROXY_FOLDER}")  
> ```

This is working fine to me

**Comment by M1croINT** [comment]
guys i cant do that, how can i use seleniumwire proxy with undetected chromedriver???

**Comment by caenrigen** [comment]
for the latest manifest version V3, you will need this manifest:

```json
{
  "version": "1.0.0",
  "manifest_version": 3,
  "name": "Chrome Proxy",
  "permissions": [
    "proxy",
    "tabs",
    "storage",
    "webRequest",
    "webRequestAuthProvider"
  ],
  "host_permissions": [
    "<all_urls>"
  ],
  "background": {
    "service_worker": "background.js"
  },
  "minimum_chrome_version": "22.0.0"
}
```

Tested with Chrome `Version 122.0.6261.129`

**Comment by juanfrilla** [comment]
> for the latest manifest version V3, you will need this manifest:
> 
> ```json
> {
>   "version": "1.0.0",
>   "manifest_version": 3,
>   "name": "Chrome Proxy",
>   "permissions": [
>     "proxy",
>     "tabs",
>     "storage",
>     "webRequest",
>     "webRequestAuthProvider"
>   ],
>   "host_permissions": [
>     "<all_urls>"
>   ],
>   "background": {
>     "service_worker": "background.js"
>   },
>   "minimum_chrome_version": "22.0.0"
> }
> ```
> 
> Tested with Chrome `Version 122.0.6261.129`

Thanks @caenrigen , do you think with this itll bypass cloudflare?

For me it's not working anymore. With normal uc I keep getting the cloudflare message to click on the button

**Comment by caenrigen** [comment]
> Thanks @caenrigen , do you think with this itll bypass cloudflare?
> 
> For me it's not working anymore. With normal uc I keep getting the cloudflare message to click on the button

Sorry, mate. That is a different problem. I don't have expertise on that. If you proxy's IP has been blacklisted by cloudflare... not much you will be able to do, maybe different proxies. I would suggest for you to try using the internet connection of your mobile phone as a reference case to know if it `uc` is still working. Good luck!

**Comment by ooojustin** [comment]
For whatever reason, the `--proxy-server` argument worked for me with a proxy being hosted on `localhost`, but didn't work with a remote proxy URL. The extension-based approach did work with both.

**Comment by pankajkalania** [comment]
If there any way we change proxy in this extension on the fly, without closing the browser?

**Comment by pYashXds** [comment]
> options.add_argument(f'--proxy-server={proxy_address}:{proxy_port}')

Can you provide the exact structure... I want to use it.

**Comment by tomdav999** [comment]
Hello everyone. as of today, the chrome extension approach (background.js w/ manifest.json) is no longer working for me.  It was working fine for a long time, but all of a sudden in the middle of running a script this morning it stopped working.   I made no changes to anything.  I suspect it has to do with the June 2025 depreciation of manifest v2, but I am using the manifest v3 code above.  I can only get proxy to work with undetected chromedriver by whitelisting my IP and using `options.add_argument(f'--proxy-server={proxy_address}:{proxy_port}')`

Is it just me?  Anyone else?

**Comment by tomdav999** [comment]
> If there any way we change proxy in this extension on the fly, without closing the browser?

No, it's pretty much a limitation of chrome driver.  You can get creative with pac stript, use a squid proxy, etc. but If you just want to rotate IP the easiest way is to use a rotating proxy provider (I recommend dataimpulse).  You will also need to flush the port after the proxy provider has rotated the IP for the port.  There may be a better way to do this but this works for me:

```
# example uses static porxy port 12345
options.add_argument('--proxy-server=gw.dataimpulse.com:12345') # authentication via IP whitelist
driver = uc.Chrome(options = options)

# do some stuff

# rotate the ip for the port
driver.get('https://gw.dataimpulse.com:777/api/rotate_ip?port=12345') # authentication via IP whitelist

# flush the socket after rotating IP or chrome driver will hold on to the original socket and IP
driver.get('chrome://net-internals/dns#sockets')
driver.find_element(By.ID, 'sockets-view-flush-button').click()
```

The same issue arises with a rotating proxy port.  Even though the proxy provider is constantly rotating the IP, you will find that cbrome driver holds on to the original socket and the IP does not rotate until you flush the port.  So you don't necessarily have to use a static port and rotate via api, just use a rotating port, and effectively rotate IP by flushing the socket.

**Comment by raff-s** [comment]
> [@tomdav999](https://github.com/tomdav999) seeing the same thing, the manifest solution [@ooojustin](https://github.com/ooojustin) posted above is unfortunately not working anymore either.

Same here, the plugin doesn't get loaded, chrome 139.0.7258.139
