### ISSUE TITLE
How to install/load many extensions on undetected-chromedriver

### ISSUE THREAD

**Issue by bluebee2013** [ultrafunkamsterdam/undetected-chromedriver#1329]
I installed many extensions on chromedriver .
options = webdriver.ChromeOptions()
options.add_extension("path/file1.crx")
options.add_extension("path/file2.crx")
or:
options.add_argument('--load-extension=path/folder1')
options.add_argument('--load-extension=path/folder2')  ( extract folder1.zip and folder2.zip)

They work good !

But then I use undetected-chromedriver to install/load many extensions not work
options = uc.ChromeOptions()
options.add_extension("path/file1.crx") (not work)
options.add_extension("path/file2.crx") (not work)
or:
options.add_argument('--load-extension=path/folder1')  (not work)
options.add_argument('--load-extension=path/folder2')  ( work second extension only)
Please, help me this problem ( tested on undetected-chromedriver 2.x and 3.x)

**Comment by bluebee2013** [comment]
Solved !!!!

**Comment by deniskzt** [comment]
How did you decide?
Can you write an example?
