### ISSUE TITLE
Doesnt pass Cloudflare DDOS Protection

### ISSUE THREAD

**Issue by w3bprinz** [ultrafunkamsterdam/undetected-chromedriver#134]
Chromedriver stucks on Cloudflare DDOS Protection-Screen when trying to access a specific website.

<img width="875" alt="Bildschirmfoto 2021-03-30 um 18 33 16" src="https://user-images.githubusercontent.com/34249794/113024481-142c6b80-9187-11eb-883c-6ca1dc0f9ad8.png">

**Comment by ultrafunkamsterdam** [comment]
No code, nothing.. v2 here still passes happily.

**Comment by w3bprinz** [comment]
`import undetected_chromedriver.v2 as uc
driver = uc.Chrome()
with driver:
    driver.get('https://coinfaucet.eu')  # known url using cloudflare's "under attack mode"`
    
Im using also v2 as described here, but it doenst work. Do I need any other stuff or things ?

**Comment by w3bprinz** [comment]
Found the issue...

**Comment by ultrafunkamsterdam** [comment]
Care to share?
