### ISSUE TITLE
Setting capabilities: `log type 'performance' not found`

### ISSUE THREAD

**Issue by vvatelot** [ultrafunkamsterdam/undetected-chromedriver#1352]
When I upgrade to UC 3.5.0 I now have an issue when trying to access performance logging. It worked well since there, but now I have the message:

```
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: log type 'performance' not found
```

Here is how I implement my driver:

```python
from selenium.webdriver import DesiredCapabilities
import undetected_chromedriver as uc

chrome_options = uc.ChromeOptions()
chrome_options.headless = True
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--ignore-certificate-errors")

capbs = DesiredCapabilities.CHROME.copy()
capbs["goog:loggingPrefs"] = {"performance": "ALL"}

driver = uc.Chrome(
    options=chrome_options,
    desired_capabilities=capbs,
)

driver.get(url)
performance_logs = driver.get_log("performance")
```

Anyone with this issue ?

**Comment by GabeMillikan** [comment]
javascript approach:
```py
import json

# ...

performance_logs = json.loads(
    driver.execute_script(
        """
        const performanceEntries = window.performance.getEntries();
        return JSON.stringify(performanceEntries);
        """
    )
)
```

You can also grab the logs from an iframe by doing
```js
const frame = document.querySelector('#the-iframe');
const performanceEntries = frame.contentWindow.performance.getEntries();
return JSON.stringify(performanceEntries);
```

**Comment by 332123342** [comment]
> javascript approach:
> 
> ```python
> import json
> 
> # ...
> 
> performance_logs = json.loads(
>     driver.execute_script(
>         """
>         const performanceEntries = window.performance.getEntries();
>         return JSON.stringify(performanceEntries);
>         """
>     )
> )
> ```
> 
> You can also grab the logs from an iframe by doing
> 
> ```js
> const frame = document.querySelector('#the-iframe');
> const performanceEntries = frame.contentWindow.performance.getEntries();
> return JSON.stringify(performanceEntries);
> ```

but this performance_logs does not have requestId, how can get request Id and response?

**Comment by vvatelot** [comment]
Hello, thank you both for your reply! :)
Unfortunately, I am not looking for a workaround as I am looking for an answer why this works with UC 3.4.7 and not with UC 3.5.0... If anyone has the answer?

**Comment by ultrafunkamsterdam** [comment]
Because there has been some changes in what parameters selenium takes. Your best bet is to try selenium.webdriver.chromium.ChromiumOptions and pass that.

**Comment by danielWagnerr** [comment]
Did you manage to fix this? I haven't figured it out yet...

**Comment by vvatelot** [comment]
Hello @ultrafunkamsterdam @danielWagnerr thanks for your reply. Really sorry for not coming back sooner. I still did not have time to test your solution. I try to have a look this week :disappointed:

**Comment by RoySean6** [comment]
New update in[ selenium4 ](https://www.selenium.dev/blog/2022/legacy-protocol-support/)
replace
`capabilities['goog:loggingPrefs'] = {'performance': 'ALL'}`
to
`options.set_capability('goog:loggingPrefs', {'performance': 'ALL'})`
