### ISSUE TITLE
Cannot start browser again when forcely stopping .(sometimes)

### ISSUE THREAD

**Issue by zhaodice** [ultrafunkamsterdam/undetected-chromedriver#1357]
It is a weird problem, sometimes when I kill the browser , I will be welcomed by "Message: unknown error: cannot connect to chrome a" if I start selenium again, but `from selenium import webdriver` works fine!
I must remove the `user data` folder in that fix it...
I guess the `user data` folder has some dirty data that can prevent undetected-chromedriver start.

I confirm that the driver version is same as browser

**Comment by rafamelo01** [comment]
Same issue here, finding ways to dribble but is hard!
