### ISSUE TITLE
Chromedriver detected when run via SSH, but works well via RDP

### ISSUE THREAD

**Issue by gusd1994** [ultrafunkamsterdam/undetected-chromedriver#1383]
Good afternoon, I caught a strange error on Windows Server 2016
I'm trying to parse the site after they installed a new protection and successfully pass the protection using UC if I run the code from under the RDP session, however, when I try to run the same script using SSH, I immediately catch the lock. I am attaching a video to help you understand.
I first run the script from an RDP shell and then I use SSH to connect to the remote server where the script is running
in the first case, the defense is passed in the second - block

I am attaching my code.
I also want to note that I tried everything I can, compared the env of the RDP session and SSH, checked each chromedrive option, changed the server ip addresses, window sizes, used both headless and windowed mode, used different proxies (only residential private proxies ) and got the same result everywhere. I get the feeling that there is a rendering check via fingerprint and it is somehow different when UC is launched via SSH
Or perhaps the check goes to the debug port

Thanks in advance to @ultrafunkamsterdam for an amazing free product and I'm very sorry if I'm wasting your time on a trifling question, but I spent more than a day figuring it out.

P.S. protection is configured in such a way that the site may not open from European and American ip when you try to check it

```
import undetected_chromedriver as uc
import time
if __name__ == '__main__' :
	driver = uc.Chrome(headless=True,version_main=112)
	driver.get('https://leroymerlin.ru/')
	time.sleep(2)
	driver.save_screenshot('result.png')
	driver.close()
```

https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/46750997/797937b3-73fc-4ab1-84a1-e0741849114f

https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/46750997/afef8f93-b45e-4370-aa32-7b05f5d3f245

Server Configuration : Windows Server 2016
The machine to which RDP and SSH connection is made Windows 10
Version undetected_chromedriver 3.5.0
chromedriver version 112
selenium version 4.1.0

**Comment by ultrafunkamsterdam** [comment]
I'm not aware of Windows Server supporting incoming ssh connections? Am I missing something here?

**Comment by gusd1994** [comment]
Yes, I used the protocol Openssh
I have also tried connecting directly with Powershell From my home computer to my WS2016 And got the same result

**Comment by ultrafunkamsterdam** [comment]
By using any sort of shell, you have to keep in mind if the shell can start the Chrome browser gui. Usually this only works when you have a desktop environment , like physical on the console or RDP. Having no desktop means you can't start chrome (unless using headless, which is made for the purpose)

**Comment by gusd1994** [comment]
Unfortunately, I received two absolutely identical logs

[example_bad.log](https://github.com/ultrafunkamsterdam/undetected-chromedriver/files/11971074/example_bad.log)
[example_good.log](https://github.com/ultrafunkamsterdam/undetected-chromedriver/files/11971075/example_good.log)

**Comment by gusd1994** [comment]
at the moment the same problem is observed from under Linux, I tried to roll on a clean system
and it was also possible to pass protection through xRDP, but when accessing via SSH, no

**Comment by gusd1994** [comment]
WOW, that was crazy, but i finaly pass it
The resource checked for the presence of a taskbar on the rendering screen
after i add desktop env to my xvfb session it make me pass
