### ISSUE TITLE
Temporary workaround for captcha solving error.

### ISSUE THREAD

**Issue by benkrej** [ultrafunkamsterdam/undetected-chromedriver#1390]
Solution 1:
I found out that if you open a new tab with js it passes cloudflare captchas. You can close the old tab and use the new one.

``` 
driver.execute_script('''window.open("http://nowsecure.nl","_blank");''') # open page in new tab
time.sleep(5) # wait until page has loaded
driver.switch_to.window(window_name=driver.window_handles[0])   # switch to first tab
driver.close() # close first tab
driver.switch_to.window(window_name=driver.window_handles[0] )  # switch back to new tab
time.sleep(2)
driver.get("https://google.com")
time.sleep(2)
driver.get("https://nowsecure.nl") # this should pass cloudflare captchas now

_Originally posted by @benkrej in https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1388#issuecomment-1632000503_ 
```

Solution 2:
`chrome_options.add_argument("--auto-open-devtools-for-tabs")  # automatically open dev tools on every new tab`
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1388#issuecomment-1631477896

**Comment by benkrej** [comment]
Opened a new issue for better visibility, see [original issue](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1388)

**Comment by leesanghyone** [comment]
Cool!

**Comment by pedro-peixot0** [comment]
Adding this to the driver configs helped me a lot more in avoiding cloudflare

`chrome_options.add_argument("--auto-open-devtools-for-tabs")  # automatically open dev tools on every new tab`

**Comment by benkrej** [comment]
> Adding this to the driver configs helped me a lot more in avoiding cloudflare
> 
> `chrome_options.add_argument("--auto-open-devtools-for-tabs") # automatically open dev tools on every new tab`

I have added it now

**Comment by dushaofan** [comment]
so cool!

**Comment by NCLnclNCL** [comment]
> 

i dont like this

**Comment by benkrej** [comment]
@NCLnclNCL me neither

**Comment by NCLnclNCL** [comment]
> @NCLnclNCL me neither

do you know why opening devtool helps to pass cloudflare challenge??

**Comment by benkrej** [comment]
> > @NCLnclNCL me neither
> 
> 
> 
> do you know why opening devtool helps to pass cloudflare challenge??
> 
> 

There might be a parameter about who created the window - if that's not the user or js cf captcha gets triggered

**Comment by rcarvalho16** [comment]
This workaround looks great, however I am having some problems with it as I get an exception telling me I have an invalid session id. Has anyone had this issue as well?

**Comment by epicmatthew23** [comment]
Im curious as to why this works. Something to do with the inner width is suppose?

**Comment by Laishiji** [comment]
Why suddenly can be detected?

**Comment by benkrej** [comment]
> This workaround looks great, however I am having some problems with it as I get an exception telling me I have an invalid session id. Has anyone had this issue as well?

I suppose your chromedriver is not properly initialised and started

**Comment by rcarvalho16** [comment]
> > This workaround looks great, however I am having some problems with it as I get an exception telling me I have an invalid session id. Has anyone had this issue as well?
> 
> I suppose your chromedriver is not properly initialised and started

The first solution gives me that `session id` error, the second one works fine so far.

**Comment by damodharheadrun** [comment]
2nd solution is working fine, opening a Dev tools
1st solution still got clodfare captcha page.

i love the services that UC-chromedriver team.

**Comment by mir3u** [comment]
> Adding this to the driver configs helped me a lot more in avoiding cloudflare
> 
> `chrome_options.add_argument("--auto-open-devtools-for-tabs") # automatically open dev tools on every new tab`

this has not worked for me, are you running undetected headful with xvfb or headless?

**Comment by benkrej** [comment]
> > Adding this to the driver configs helped me a lot more in avoiding cloudflare
> 
> > 
> 
> > `chrome_options.add_argument("--auto-open-devtools-for-tabs") # automatically open dev tools on every new tab`
> 
> 
> 
> this has not worked for me, are you running undetected headful with xvfb or headless?

Works with both xvfb and headless

**Comment by SrMilton** [comment]
Solution 2 was not enough to bypass cloudflare Captcha but with Solution 1 worked fine

![image](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/35127424/d6e0148c-1a38-4b7e-a866-345bdb014835)

**Comment by benkrej** [comment]
It seems like the dev-tools solution was patches tonight and is no longer working.

**Comment by luluhoc** [comment]
> It seems like the dev-tools solution was patched tonight and is no longer working.

Can confirm that I get undefined_error from turnstile it was patched like 2h ago, any solutions?

**Comment by NCLnclNCL** [comment]
> > It seems like the dev-tools solution was patched tonight and is no longer working.
> 
> Can confirm that I get undefined_error from turnstile it was patched like 2h ago, any solutions?

Yes , solution not working with me

**Comment by chaiwebs** [comment]
Not working anymore

**Comment by SrMilton** [comment]
Solution 1 still working to me

**Comment by luluhoc** [comment]
> It seems like the dev-tools solution was patched tonight and is no longer working.

Any workaround?

**Comment by benkrej** [comment]
> > > > @NCLnclNCL me neither
> > > 
> > > 
> > > do you know why opening devtool helps to pass cloudflare challenge??
> > 
> > 
> > There might be a parameter about who created the window - if that's not the user or js cf captcha gets triggered - opening dev tools could change the param as well
> 
> Could you speak more about this? What else changes the param? I think They patched it

I tested a bit around and it seems like if selenium touches the window in any way it gets detected by cf. If you open a new tab with js you can bypass turnstile but as soon as you switch to it with `driver.switch_to.window` it gets detected again.

**Comment by alexliu0809** [comment]
Solution 1 works for me, except that I made the wait time longer for the page to load and closes the second tab instead of the first

```python3
import time
from selenium.webdriver.chrome.options import Options
import undetected_chromedriver as uc
chrome_options = Options()
chrome_options.add_argument('--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36')
chrome_options.add_argument("--lang=en-us")
chrome_options.add_argument("--headless=new")
driver = uc.Chrome(options=chrome_options)
driver.execute_script('''window.open("url","_blank");''') # open page in new tab
time.sleep(15)
driver.switch_to.window(window_name=driver.window_handles[0])   # switch to first tab
driver.get("url") # this should pass cloudflare captchas now
time.sleep(15)
driver.page_source
```

**Comment by IAISI** [comment]
> > > > > @NCLnclNCL me neither
> > > > 
> > > > 
> > > > do you know why opening devtool helps to pass cloudflare challenge??
> > > 
> > > 
> > > There might be a parameter about who created the window - if that's not the user or js cf captcha gets triggered - opening dev tools could change the param as well
> > 
> > 
> > Could you speak more about this? What else changes the param? I think They patched it
> 
> I tested a bit around and it seems like if selenium touches the window in any way it gets detected by cf. If you open a new tab with js you can bypass turnstile but as soon as you switch to it with `driver.switch_to.window` it gets detected again.

That is interesting... so they're listening to something chromedriver is triggering with JS? I got same result with selenium and playwright...

**Comment by luluhoc** [comment]
> > > > > > @NCLnclNCL me neither
> 
> > > > > 
> 
> > > > > 
> 
> > > > > do you know why opening devtool helps to pass cloudflare challenge??
> 
> > > > 
> 
> > > > 
> 
> > > > There might be a parameter about who created the window - if that's not the user or js cf captcha gets triggered - opening dev tools could change the param as well
> 
> > > 
> 
> > > 
> 
> > > Could you speak more about this? What else changes the param? I think They patched it
> 
> > 
> 
> > I tested a bit around and it seems like if selenium touches the window in any way it gets detected by cf. If you open a new tab with js you can bypass turnstile but as soon as you switch to it with `driver.switch_to.window` it gets detected again.
> 
> 
> 
> That is interesting... so they're listening to something chromedriver is triggering with JS? I got same result with selenium and playwright...

Are there any tools available to deobfuscate the ray script?

**Comment by benkrej** [comment]
> > > > > > @NCLnclNCL me neither
> > > > > 
> > > > > 
> > > > > do you know why opening devtool helps to pass cloudflare challenge??
> > > > 
> > > > 
> > > > There might be a parameter about who created the window - if that's not the user or js cf captcha gets triggered - opening dev tools could change the param as well
> > > 
> > > 
> > > Could you speak more about this? What else changes the param? I think They patched it
> > 
> > I tested a bit around and it seems like if selenium touches the window in any way it gets detected by cf. If you open a new tab with js you can bypass turnstile but as soon as you switch to it with `driver.switch_to.window` it gets detected again.
> 
> That is interesting... so they're listening to something chromedriver is triggering with JS? I got same result with selenium and playwright...

You misinterpretated my answer. Js amd user inputs doesn't get detected, if selenium does anything it gets detected.

**Comment by ParhamSobhan** [comment]
anyone have fast solution for this problem dm me im gonna buy

**Comment by ultrafunkamsterdam** [comment]
```driver.tab_new("https://google.com")```

Exist just for this purpose

**Comment by luluhoc** [comment]
>  ```driver.tab_new("https://google.com")```
> 
> 
> 
> Exist just for this purpose 

@ultrafunkamsterdam is there an equivalent of this in puppeteer?

**Comment by luluhoc** [comment]
I don't know if it will help you but this are the gist of the data that CF sends through ray.

First data to send and then block
https://gist.github.com/luluhoc/d3475707c6b7c03f11a19959a1c19786

Second data

https://gist.github.com/luluhoc/70f9dfca0a350c050cae6ea747bbe881

**Comment by ultrafunkamsterdam** [comment]
> > `driver.tab_new("https://google.com")`
> > Exist just for this purpose
> 
> @ultrafunkamsterdam is there an equivalent of this in puppeteer?

I only know the plain cdp command Target.createTarget(url, new_window=false)

From top of my head...but in the car atm can't verify

**Comment by NCLnclNCL** [comment]
> I don't know if it will help you but this are the gist of the data that CF sends through ray.
> 
> First data to send and then block https://gist.github.com/luluhoc/d3475707c6b7c03f11a19959a1c19786
> 
> Second data
> 
> https://gist.github.com/luluhoc/70f9dfca0a350c050cae6ea747bbe881

Data encoded by private key

**Comment by rcarvalho16** [comment]
Yea, no workaround is live right now. It's getting detected again

**Comment by digitalnomad91** [comment]
Same here, I tried pulling flaresolverr's latest push which included both "workarounds" (the dev console + the new tab thing) and it's failing like before, with a 60 second timeout and a 500 error repsonse.

**Comment by digitalnomad91** [comment]
Same here, I tried pulling flaresolverr's latest push which included both "workarounds" (the dev console + the new tab thing) and it's failing like before, with a 60 second timeout and a 500 error repsonse.

**Comment by dioginn** [comment]
It's still not working for me with any of the workarounds. Any news from anyone?
