### ISSUE TITLE
How to use proxy with authentication [oxylabs]?

### ISSUE THREAD

**Issue by pedrofnts** [ultrafunkamsterdam/undetected-chromedriver#1407]
Hello. How I can use proxy with authentication with undetected-chromedriver?

I tried using seleniumwire, but it fails to target the website.

Any other solution?

**Comment by Z-Guo** [comment]
Hi was this resolved?

**Comment by pedrofnts** [comment]
I've resolved loading the proxy through a chrome extension.

**Comment by Z-Guo** [comment]
thanks!

**Comment by pedrofnts** [comment]
See https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1399#issuecomment-1642013876
