### ISSUE TITLE
Not working in Realestate.com.au anymore (Protected by Kasada)

### ISSUE THREAD

**Issue by hnandarusdy** [ultrafunkamsterdam/undetected-chromedriver#1412]
Suddenly not working at realestate.com.au which is supported by Kasada

![image](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/14065403/b4f946ff-ed88-4c86-825c-687bb1439550)

tried updated the version to the latest but no luck. 
Any chance can bypass kasada?

**Comment by leesanghyone** [comment]
There's a fee, but https://www.zenrows.com
to take on the challenge.

**Comment by hnandarusdy-myob** [comment]
no luck, thanks for the url though. 

response: 
{"code":"RESP001","instance":"/v1","status":422,"title":"Could not get content (RESP001)","type":"https://www.zenrows.com/documentation/api-error-codes#RESP001"}
