### ISSUE TITLE
User auth proxies are no longer working

### ISSUE THREAD

**Issue by KhushC-03** [ultrafunkamsterdam/undetected-chromedriver#142]
I have tried the user auth argument when adding options but it no longer works. what is the best way for user auth proxies to be used? with V2 by the way.

**Comment by lazarostso** [comment]
What method did you use before?

**Comment by Avnsx** [comment]
> I have tried the user auth argument when adding options but it no longer works. what is the best way for user auth proxies to be used? with V2 by the way.

https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/82#issuecomment-817049203

**Comment by lazarostso** [comment]
> 
> 
> > I have tried the user auth argument when adding options but it no longer works. what is the best way for user auth proxies to be used? with V2 by the way.
> 
> [#82 (comment)](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/82#issuecomment-817049203)
I have tried 

options.add_argument("--proxy-server=https://username:password@proxy_ip:proxy_pass")

But i am getting:

This site can’t be reachedThe webpage at https://instagram.com/ might be temporarily down or it may have moved permanently to a new web address.
ERR_NO_SUPPORTED_PROXIES

**Comment by Avnsx** [comment]
> > > I have tried the user auth argument when adding options but it no longer works. what is the best way for user auth proxies to be used? with V2 by the way.
> > 
> > 
> > [#82 (comment)](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/82#issuecomment-817049203)
> > I have tried
> 
> options.add_argument("--proxy-server=https://username:password@proxy_ip:proxy_pass")
> 
> But i am getting:
> 
> This site can’t be reachedThe webpage at https://instagram.com/ might be temporarily down or it may have moved permanently to a new web address.
> ERR_NO_SUPPORTED_PROXIES

https://github.com/wkeeling/selenium-wire#proxies

**Comment by lazarostso** [comment]
> 
> 
> > > > I have tried the user auth argument when adding options but it no longer works. what is the best way for user auth proxies to be used? with V2 by the way.
> > > 
> > > 
> > > [#82 (comment)](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/82#issuecomment-817049203)
> > > I have tried
> > 
> > 
> > options.add_argument("--proxy-server=https://username:password@proxy_ip:proxy_pass")
> > But i am getting:
> > This site can’t be reachedThe webpage at https://instagram.com/ might be temporarily down or it may have moved permanently to a new web address.
> > ERR_NO_SUPPORTED_PROXIES
> 
> https://github.com/wkeeling/selenium-wire#proxies

### I tested:

import logging
logging.basicConfig(level=logging.INFO)
logging.getLogger('undetected_chromedriver').level = logging.INFO

from seleniumwire import webdriver
import time

proxy = 'http://username:pass@prox_ip:proxy_port'
options = {
    'suppress_connection_errors': False,
    'auto_config': False,
    'addr': '0.0.0.0',
    'port': 8087,
    'proxy': {
        'http': proxy,
        'https': proxy
    },
}

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--proxy-server=kubernetes-service-name:8087')
chrome_options.add_argument('--ignore-certificate-errors')

browser = webdriver.Chrome(desired_capabilities=chrome_options.to_capabilities(), seleniumwire_options=options)
time.sleep(1)
browser.get("https://whatismyipaddress.com/")
time.sleep(10)

but log info shows something like: 
INFO:seleniumwire.proxy.handler:Capturing request: https://whatismyipaddress.com/favicon.ico

I have used pip install undetected-chromedriver but I assume that undetected-chromedriver is not activated.

**Comment by Avnsx** [comment]
@lazarostso 
```python
import undetected_chromedriver as uc
from seleniumwire import webdriver

chrome_options = webdriver.ChromeOptions()
chrome_options.headless = False
seleniumwire_options = {'proxy': {'https': 'type://proxy:port',}} #or type://username:password@host:port
driver = uc.Chrome(options=chrome_options, seleniumwire_options=seleniumwire_options)

driver.get('https://whatismyipaddress.com/')
```

**Comment by ultrafunkamsterdam** [comment]
I tested (and working also in v2): 

```python
In [4]: import undetected_chromedriver.v2 as uc

# ... some stuff to start proxies...

In [8]: proxypool.current_proxy_addr
Out[8]: ('127.0.0.1', 22225)

In [9]: opts = uc.ChromeOptions()
In [10]: opts.add_argument('--proxy-server=socks5://127.0.0.1:22225')
In [11]: driver = uc.Chrome(options=opts)
In [12]: driver.get('http://httpbin.org/ip')
In [13]: driver.page_source
Out[13]: '<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{\n  "origin": "104.244.75.80"\n}\n</pre></body></html>'
In [14]: driver.quit()


In [15]: next(proxypool.pool)
Out[15]: ('127.0.0.1', 22226)
In [16]: opts = uc.ChromeOptions()
In [17]: opts.add_argument('--proxy-server=socks5://127.0.0.1:22226')
In [18]: driver = uc.Chrome(options=opts)
In [19]: driver.get('http://httpbin.org/ip')
In [20]: driver.page_source
Out[20]: '<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{\n  "origin": "51.210.80.127"\n}\n</pre></body></html>'
```

**Comment by merry75** [comment]
@ultrafunkamsterdam your example is not working when you want to use with username/password auth proxy

**Comment by daruizr** [comment]
> @ultrafunkamsterdam your example is not working when you want to use with username/password auth proxy

I am also having the same problem, with an user and pass it's not working

**Comment by Jamie4224** [comment]
@ultrafunkamsterdam I have the same problem, I can't get authenticated proxies to work, they give a credentials dialog. The extension method doesn't work, and the selenium wire method doesn't either.

**Comment by sunny9495-dev** [comment]
How to kill browser when using undetected chromedriver libraray, i use os.system("taskkill /F /IM chromedriver.exe /T")
the chromedriver.exe is killing, but the browser is still appears

**Comment by lazarostso** [comment]
> How to kill browser when using undetected chromedriver library, i use os.system("taskkill /F /IM chromedriver.exe /T") the chromedriver.exe is killing, but the browser is still appears

browser.quit() can do the job

**Comment by nomorehumor** [comment]
The solution given here seems not to work in ^3.1.0 anymore. And I find it bad, because exactly that version has given me a real anti bot protection on one website.
