### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by ming-zhao** [ultrafunkamsterdam/undetected-chromedriver#1421]
import undetected_chromedriver as uc
driver = uc.Chrome()
driver.get('https://rebaid.com/login')

It is stuck at "Checking if the site connection is secure"

**Comment by ming-zhao** [comment]
Find solution

**Comment by endydeveloper** [comment]
What solution?

**Comment by nghilethanh-atherlabs** [comment]
no solution 🗡️
