### ISSUE TITLE
i think this is how cloudflare detect UC

### ISSUE THREAD

**Issue by NCLnclNCL** [ultrafunkamsterdam/undetected-chromedriver#1426]
if i go to https://hmaker.github.io/selenium-detector/
i will detected with info Either Devtools Console is open or CDP Runtime Domain is enabled
if i kill chromedriver and f5, i is passed
if i use js to go to it. i is passed
source https://github.com/HMaker/HMaker.github.io

**Comment by ultrafunkamsterdam** [comment]
That's exactly what `with driver` context manager is for. It disconnects right after navigation and then reconnect. Thanks for your free analysis. But that's not what issue trackers are for. I answered the "how" part in another question. Also check announcements.
