### ISSUE TITLE
Custom user data/profile not working

### ISSUE THREAD

**Issue by ammarsys** [ultrafunkamsterdam/undetected-chromedriver#1435]
![image](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/69536330/aad2f97d-f39b-4db8-a2de-8ad88477edb3)

Hi, I'm trying to use a custom profile so that I'm logged into a site I'm visiting. However, it does not seem to work. I see no errors.

```py
PROFILE = 'C:\\Users\\user\\AppData\\Local\\Google\\Chrome\\User Data\\Default'

driver = Chrome(user_data_dir=PROFILE)
```

I have verified that this is indeed the correct path via `chrome://settings`. I have the latest chromedriver and package version.

**Comment by NCLnclNCL** [comment]
Remove default

**Comment by ammarsys** [comment]
yup, if youre a maintainer you can close this issue
