### ISSUE TITLE
Java support

### ISSUE THREAD

**Issue by BenjaminJacober** [ultrafunkamsterdam/undetected-chromedriver#144]
Not too familiar with GitHub yet, but i didn't find a different way to reach out.
Is there something similar for Java, or maybe is there a way to use this for Java aswell?

**Comment by HMaker** [comment]
It can be ported to java yes, the codebase is short, just a few hundred of lines. Just apply settings and patching done in Java version. It can be ported for any language selenium project supports.

**Comment by BenjaminJacober** [comment]
I don't fully understand how it works. As far as i can tell its: 
1. Downloading the newest version of ChromeDriver
2. Patching it like this: https://stackoverflow.com/questions/33225947/can-a-website-detect-when-you-are-using-selenium-with-chromedriver
3. Setting webdriver to false whenever it opens a new website. (Which i already tried some time ago on Java but didnt get to work)
4. Removing headless from the fingerprint, which im not using anyway because you're more likely to get detected.
5. Its NOT applying any ChromeOptions.

thing is, using this version of ChromeDriver allows me to access toppreise.ch without getting blocked, when i start it in Java with a ChromeDriver i copied or a self patched one i can't. What is it, that im doing wrong, i know toppreise is secured by dataDome but i used to be able to scrape up to 20 website requests without ever getting in trouble back when i was using geckoDriver. (Which i can't get to work on Linux sadly)

**Comment by BenjaminJacober** [comment]
I have done almost everything described here:
https://piprogramming.org/articles/How-to-make-Selenium-undetectable-and-stealth--7-Ways-to-hide-your-Bot-Automation-from-Detection-0000000017.html
https://stackoverflow.com/questions/33225947/can-a-website-detect-when-you-are-using-selenium-with-chromedriver
---
`This is my code:      
        
        System.setProperty("webdriver.chrome.driver", "./src/main/resources/chromedriver");
        ChromeOptions options = new ChromeOptions();

        // Fixing 255 Error crashes
        options.addArguments("--no-sandbox");
        options.addArguments("--disable-dev-shm-usage");

        // Options to trick bot detection
            // Removing webdriver property
        options.addArguments("--disable-blink-features=AutomationControlled");
        options.setExperimentalOption("excludeSwitches", Collections.singletonList("enable-automation"));
        options.setExperimentalOption("useAutomationExtension", null);

            // Changing the user agent / browser fingerprint
        options.addArguments("window-size=1920,1080");
        options.addArguments("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36");

        // Other
        options.addArguments("disable-infobars");`

**Comment by HMaker** [comment]
> Its NOT applying any ChromeOptions.
Are you sure? just [read](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/master/undetected_chromedriver/__init__.py#L107) the code.

**Comment by HMaker** [comment]
If you don't know python it will be hard because some patches are applied to selenium package, that patching is known as metaprogramming or "reflection" in Java world. Some classes from selenium are replaced.

**Comment by BenjaminJacober** [comment]
`instance.add_argument("start-maximized")
 instance.add_experimental_option("excludeSwitches", ["enable-automation"])
 instance.add_argument("--disable-blink-features=AutomationControlled")`

Those seem to be the options, but i am using those in my code aswell. I didn't see them the first time i read the code.
I read the code again, i still dont understand everything but the only thing i seem to be missing is this part:
`        

       def _get_wrapped(*args, **kwargs):
            if instance.execute_script("return navigator.webdriver"):
                instance.execute_cdp_cmd(
                    "Page.addScriptToEvaluateOnNewDocument",
                    {
                        "source": """

                                   Object.defineProperty(window, 'navigator', {
                                       value: new Proxy(navigator, {
                                       has: (target, key) => (key === 'webdriver' ? false : key in target),
                                       get: (target, key) =>
                                           key === 'webdriver'
                                           ? undefined
                                           : typeof target[key] === 'function'
                                           ? target[key].bind(target)
                                           : target[key]
                                       })
                                   });
                               """
                    },
                )
            return instance._orig_get(*args, **kwargs)

        instance.get = _get_wrapped
        instance.get = _get_wrapped
        instance.get = _get_wrapped

        original_user_agent_string = instance.execute_script(
            "return navigator.userAgent"
        )
        instance.execute_cdp_cmd(
            "Network.setUserAgentOverride",
            {
                "userAgent": original_user_agent_string.replace("Headless", ""),
            },
        )
        if emulate_touch:
            instance.execute_cdp_cmd(
                "Page.addScriptToEvaluateOnNewDocument",
                {
                    "source": """
                                   Object.defineProperty(navigator, 'maxTouchPoints', {
                                       get: () => 1
                               })"""
                },
            )
        logger.info(f"starting undetected_chromedriver.Chrome({args}, {kwargs})")
        return instance`

i think it basically listens if "return navigator.webdriver" is called and then fakes the return values. i have no idea why instance.get is set to "__get_wrapped" three times.  I also don't know what maxTouchPoints is, i found this though: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/maxTouchPoints and https://developer.mozilla.org/en-US/docs/Web/API/Navigator/maxTouchPoints and google make me think it has something to do with touchscreen capabilities. Also it seems to only be enabled if i want to emulate touch which i didn't do and it still worked. (I tried the undetected_chromedriver in python and it worked well)

**Comment by ultrafunkamsterdam** [comment]
https://www.rubydoc.info/gems/selenium-webdriver/Selenium%2FWebDriver%2FChrome%2FDriver:execute_cdp

execute_cdp is executing scripts just before page load. 

I overloaded ( monkeypatched ) the get() method to include a call to execute_cdp first, before calling the orignal .get()

**Comment by ultrafunkamsterdam** [comment]
found this also.. seems like java syntax
 ```java
  var parameters = new Dictionary<string, object>
    {
        ["source"] = "Object.defineProperty(navigator, 'webdriver', { get: () => undefined })"
    };
    var driver = new ChromeDriver(@"c:\bin\", options);
    driver.ExecuteChromeCommand("Page.addScriptToEvaluateOnNewDocument", parameters);
```

**Comment by BenjaminJacober** [comment]
I think thats JavaScript syntax but thanks anyway. I'll update you once i continue with this project. (A scraprr that gets pc part costs doesn't really make sense when the market is empty/inflated)

**Comment by elmanorc** [comment]
> ## I have done almost everything described here:
> https://piprogramming.org/articles/How-to-make-Selenium-undetectable-and-stealth--7-Ways-to-hide-your-Bot-Automation-from-Detection-0000000017.html
> https://stackoverflow.com/questions/33225947/can-a-website-detect-when-you-are-using-selenium-with-chromedriver
> `This is my code:
> 
> ```
>     System.setProperty("webdriver.chrome.driver", "./src/main/resources/chromedriver");
>     ChromeOptions options = new ChromeOptions();
> 
>     // Fixing 255 Error crashes
>     options.addArguments("--no-sandbox");
>     options.addArguments("--disable-dev-shm-usage");
> 
>     // Options to trick bot detection
>         // Removing webdriver property
>     options.addArguments("--disable-blink-features=AutomationControlled");
>     options.setExperimentalOption("excludeSwitches", Collections.singletonList("enable-automation"));
>     options.setExperimentalOption("useAutomationExtension", null);
> 
>         // Changing the user agent / browser fingerprint
>     options.addArguments("window-size=1920,1080");
>     options.addArguments("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36");
> 
>     // Other
>     options.addArguments("disable-infobars");`
> ```

This worked for me. Thanks.

**Comment by BenjaminJacober** [comment]
> @BenjaminJacober 
> 
> I have trying to do the same thing in Java/Kotlin. I have followed your snippets and using the modified chromedriver derived from the python code and I still get detected while trying to sign into Google.
> 
> However when I run it with Python, the same driver is not detected doing so.

I haven't worked on this in a year. I'd probably just use python for it nowadays. + As some other guy said, try to rewrite the entire repo in java, not just the options and arguments for the chromedriver.

**Comment by Shinji-Mimura** [comment]
> ## I have done almost everything described here:
> https://piprogramming.org/articles/How-to-make-Selenium-undetectable-and-stealth--7-Ways-to-hide-your-Bot-Automation-from-Detection-0000000017.html
> https://stackoverflow.com/questions/33225947/can-a-website-detect-when-you-are-using-selenium-with-chromedriver
> 
> `This is my code:
> 
> ```
>     System.setProperty("webdriver.chrome.driver", "./src/main/resources/chromedriver");
>     ChromeOptions options = new ChromeOptions();
> 
>     // Fixing 255 Error crashes
>     options.addArguments("--no-sandbox");
>     options.addArguments("--disable-dev-shm-usage");
> 
>     // Options to trick bot detection
>         // Removing webdriver property
>     options.addArguments("--disable-blink-features=AutomationControlled");
>     options.setExperimentalOption("excludeSwitches", Collections.singletonList("enable-automation"));
>     options.setExperimentalOption("useAutomationExtension", null);
> 
>         // Changing the user agent / browser fingerprint
>     options.addArguments("window-size=1920,1080");
>     options.addArguments("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36");
> 
>     // Other
>     options.addArguments("disable-infobars");`
> ```

didn't work for me. someone have a suggestion?

**Comment by QazCetelic** [comment]
> Thanks man. I have rewrite the entire repo in Kotlin but it is just not working. If I could make it work, I will publish it XD.

Have you found a way to make it work?
