### ISSUE TITLE
(3.5.1)AttributeError: 'Patcher' object has no attribute 'user_multiprocs'

### ISSUE THREAD

**Issue by 362227** [ultrafunkamsterdam/undetected-chromedriver#1441]
3.5.1
`Traceback (most recent call last):
  File "/home/runner/work/Python-Selenium-Action-UC/Python-Selenium-Action-UC/uc.py", line [46](https://github.com/wedcf120/Python-Selenium-Action-UC/actions/runs/5792664495/job/15699281391#step:8:47), in run_all
    browser = uc.Chrome(options=self.set_chrome_option())
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 257, in __init__
    self.patcher.auto()
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/undetected_chromedriver/patcher.py", line 119, in auto
    if self.user_multiprocs:
AttributeError: 'Patcher' object has no attribute 'user_multiprocs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/Python-Selenium-Action-UC/Python-Selenium-Action-UC/uc.py", line 59, in <module>
    demo.main()
  File "/home/runner/work/Python-Selenium-Action-UC/Python-Selenium-Action-UC/uc.py", line 55, in main
    self.run_all()
  File "/home/runner/work/Python-Selenium-Action-UC/Python-Selenium-Action-UC/uc.py", line [52](https://github.com/wedcf120/Python-Selenium-Action-UC/actions/runs/5792664495/job/15699281391#step:8:53), in run_all
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment
Error: Process completed with exit code 1.`

3.5.0 works fine

**Comment by 12flo02** [comment]
Line 119 of file patcher.py : change self.user_multiprocs into self.user_multi_procs

**Comment by seanwachs** [comment]
Update to the newest version. This was fixed recently: https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/1439/commits/f3a8a62908c4b0f7dbf4c25bac33c8eebae3f98a

**Comment by brngylni** [comment]
> > Upgrade to the newest version. This was fixed recently: [f3a8a62](https://github.com/ultrafunkamsterdam/undetected-chromedriver/commit/f3a8a62908c4b0f7dbf4c25bac33c8eebae3f98a)
> 
> What do you mean by newest version? I get this error with Selenium 4.11.2 and UC 3.5.1.

Me too

**Comment by kskk96** [comment]
> > > Upgrade to the newest version. This was fixed recently: [f3a8a62](https://github.com/ultrafunkamsterdam/undetected-chromedriver/commit/f3a8a62908c4b0f7dbf4c25bac33c8eebae3f98a)
> > 
> > 
> > What do you mean by newest version? I get this error with Selenium 4.11.2 and UC 3.5.1.
> 
> Me too

me too...

**Comment by Krylanc3lo** [comment]
install the version from git instead of pure "pip install package" and you will hae the latest version (3.5.1a),

**Comment by Kinuseka** [comment]
is `3.5.1a0` working? is the `3.5.1` only the one having issues?

**Comment by Kinuseka** [comment]
Hi please do not rerelease the fix as 3.5.1, mark it as broken and release it as 3.5.2 to keep the version semantics.

**Comment by javakam** [comment]
The same error appears in Github Actions ...

**Comment by Kinuseka** [comment]
For anyone having dependency issue with 3.5.1, you can simply ignore it with
`undetected-chromedriver>=3.4.0,!=3.5.1`
It will update to the latest version except 3.5.1

**Comment by 0xtahaeth** [comment]
i have the same problem

**Comment by ultrafunkamsterdam** [comment]
Sorry guys. Will fix this on pypa later today. Meanwhile you can install it using ```pip install undetected-chromedriver==3.5.1a0```

**Comment by saroar** [comment]
still same issue I just try

**Comment by saroar** [comment]
this is code I am trying to run 

```
import undetected_chromedriver as uc

def main():
    driver = uc.Chrome(headless=True, use_subprocess=False)
    driver.get("https://www.google.com")
    print(driver.title)
    driver.quit()

if __name__ == '__main__':
    main()
    
```

    driver = uc.Chrome(headless=True, use_subprocess=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 257, in __init__
    self.patcher.auto()
  File "/usr/local/lib/python3.11/site-packages/undetected_chromedriver/patcher.py", line 119, in auto
    if self.user_multiprocs:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Patcher' object has no attribute 'user_multiprocs'. Did you mean: 'user_multi_procs'?

**Comment by Krylanc3lo** [comment]
no problem @ultrafunkamsterdam, thanks for all the hard work. are you aware of any CF sites not bypassed by any chance? I am still not able to reach some pages

**Comment by ultrafunkamsterdam** [comment]
3.5.2 aired.


> no problem @ultrafunkamsterdam, thanks for all the hard work. are you aware of any CF sites not bypassed by any chance? I am still not able to reach some pages

I am totally aware. however there was a big change in detection land with regards to ip information. I suddenly got captchas using regular browser with nordvpn (never had them). When running chrome from a datacenter server (no vpn), which always went fine, boom captcha's.  However i dont know if you checked the announcements lately? I'm rounding off and finishing version 4 which adds a second module, no driver, blazing fast, bypasses everything   (if not run from a datacenter or vpn).  video is in announcements.

**Comment by Krylanc3lo** [comment]
@ultrafunkamsterdam yes I saw the post, it is truly amazing (thanks so much for taking the time to develop it). I saw it was the 3.5.1 not a new v4, I will wait then.

if we can help in any way, let us know

**Comment by Kinuseka** [comment]
I believe this issue can now be closed
