### ISSUE TITLE
Temporaly Workaround bypass cloudflare

### ISSUE THREAD

**Issue by devCanario** [ultrafunkamsterdam/undetected-chromedriver#1442]
I tried this code and bypassed all the cloudflare captchas,
try this and tell me if it also works
import undetected_chromedriver as uc
driver = uc.Chrome()
driver.reconnect()

**Comment by ParhamSobhan** [comment]
yes it works

**Comment by Krylanc3lo** [comment]
Not for me unfortunately, with chrome 115 and the latest uc version (3.5.1a)

**Comment by canarioPorCanarias** [comment]
> Not for me unfortunately, with chrome 115 and the latest uc version (3.5.1a)

i think the problem you have is chrome 115, try using a portable chrome 114 or install chrome 114 and try again

**Comment by Krylanc3lo** [comment]
Thank you, I will try

**Comment by NCLnclNCL** [comment]
> I tried this code and bypassed all the cloudflare captchas, try this and tell me if it also works import undetected_chromedriver as uc driver = uc.Chrome() driver.reconnect()

Use chrome version 102, it can pass

**Comment by Krylanc3lo** [comment]
It does not work with 114 or 102, I will continue to investigate

**Comment by NCLnclNCL** [comment]
> It does not work with 114 or 102, I will continue to investigate

With me It is working with 102

**Comment by canarioPorCanarias** [comment]
> > It does not work with 114 or 102, I will continue to investigate
> 
> With me It is working with 102

also works for me

**Comment by NCLnclNCL** [comment]
> when I try 102, I get a message saying it requires 114 to work

User driver 102 to working

**Comment by mdmintz** [comment]
I'm using https://github.com/seleniumbase/SeleniumBase in undetected-chromedriver mode, and this works for me:
(`pip install seleniumbase` and run with `python`)

```python
from seleniumbase import SB

with SB(uc=True) as sb:
    sb.open("https://www.japscan.lol/lecture-en-ligne/eden-s-zero/240/")
    import pdb; pdb.set_trace()
```

That bypasses detection, and then stops at the breakpoint. Use ``sb.driver`` to access the raw `driver`.

**Comment by purr** [comment]
> I'm using https://github.com/seleniumbase/SeleniumBase in undetected-chromedriver mode, and this works for me: (`pip install seleniumbase` and run with `python`)
> 
> ```python
> from seleniumbase import SB
> 
> with SB(uc=True) as sb:
>     sb.open("https://www.japscan.lol/lecture-en-ligne/eden-s-zero/240/")
>     import pdb; pdb.set_trace()
> ```
> 
> That bypasses detection, and then stops at the breakpoint. Use `sb.driver` to access the raw `driver`.

i gotta know if you came here out of curiosity or to plug your own repo

**Comment by mdmintz** [comment]
@purr I came here to help. That code works. I'm actually one of the maintainers of Python `selenium`: https://github.com/SeleniumHQ/selenium/pulls?q=is%3Apr+author%3Amdmintz+is%3Aclosed+
Through that, I've reached all Python selenium users, but I do also build frameworks on top of plain Python selenium.

**Comment by Krylanc3lo** [comment]
thanks a lot for the help, I will play with it

**Comment by AntidetectBrowser** [comment]
use this bro https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1456#issuecomment-1672650070

**Comment by saroar** [comment]
@mdmintz not work for me
