### ISSUE TITLE
CF can be bypassed currently but fails for datadome

### ISSUE THREAD

**Issue by donggoing** [ultrafunkamsterdam/undetected-chromedriver#1448]
version: [3.5.1a](https://github.com/ultrafunkamsterdam/undetected-chromedriver/commit/1f3d410763bff9689d9dc0a3bfb9298c17e661d6)

**Comment by Gait0fH3ll** [comment]
Not able to be bypassed for me. Still get the Cloudflare turnstile continuously looping after being clicked.

**Comment by donggoing** [comment]
I just find out something wired that it works for me in some sites protected by CF before(i am not sure if they change) but not for https://nowsecure.nl/
