### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by amitalokbera** [ultrafunkamsterdam/undetected-chromedriver#145]
Hi,
Is there any update on using a proxy server without breaking the v2 undetected chromedriver Cloudflare bypass?
Thank You

**Comment by playset** [comment]
> Hi,
> Is there any update on using a proxy server without breaking the v2 undetected chromedriver Cloudflare bypass?
> Thank You

hello, text me telegram @nfnyu

**Comment by Avnsx** [comment]
> > Hi,
> > Is there any update on using a proxy server without breaking the v2 undetected chromedriver Cloudflare bypass?
> > Thank You
> 
> hello, text me telegram @nfnyu

If I was you I wouldn't text him, people like this mostly try to sell something you want to you and scam you meanwhile. Else he could just solve it in an issue comment

**Comment by playset** [comment]
> > > Hi,
> > > Is there any update on using a proxy server without breaking the v2 undetected chromedriver Cloudflare bypass?
> > > Thank You
> > 
> > 
> > hello, text me telegram @nfnyu
> 
> If I was you I wouldn't text him, people like this mostly try to sell something you want to you and scam you meanwhile. Else he could just solve it in an issue comment
no, i can post code here, i would like to know what project he make

**Comment by playset** [comment]
> > > Hi,
> > > Is there any update on using a proxy server without breaking the v2 undetected chromedriver Cloudflare bypass?
> > > Thank You
> > 
> > 
> > hello, text me telegram @nfnyu
> 
> If I was you I wouldn't text him, people like this mostly try to sell something you want to you and scam you meanwhile. Else he could just solve it in an issue comment



no, i can post code here, i would like to know what project he make

**Comment by playset** [comment]
```
opts = uc.ChromeOptions()
proxy = "--proxy-server=" + self.proxyIP
 opts.add_argument(proxy)
driver = uc.Chrome(options=opts, executable_path='chromedriver')
```

its working for me with v2

**Comment by playset** [comment]
> Hi,
> Is there any update on using a proxy server without breaking the v2 undetected chromedriver Cloudflare bypass?
> Thank You

write me in telegram @nfnyu
if we are trying to bypass not the same site, I will throw off the solution for you for free

**Comment by ultrafunkamsterdam** [comment]
Working here as well

```python
In [4]: import undetected_chromedriver.v2 as uc

... some stuff to start proxies...

In [8]: proxypool.current_proxy_addr
Out[8]: ('127.0.0.1', 22225)

In [9]: opts = uc.ChromeOptions()
In [10]: opts.add_argument('--proxy-server=socks5://127.0.0.1:22225')
In [11]: driver = uc.Chrome(options=opts)
In [12]: driver.get('http://httpbin.org/ip')
In [13]: driver.page_source
Out[13]: '<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{\n  "origin": "104.244.75.80"\n}\n</pre></body></html>'
In [14]: driver.quit()


In [15]: next(proxypool.pool)
Out[15]: ('127.0.0.1', 22226)
In [16]: opts = uc.ChromeOptions()
In [17]: opts.add_argument('--proxy-server=socks5://127.0.0.1:22226')
In [18]: driver = uc.Chrome(options=opts)
In [19]: driver.get('http://httpbin.org/ip')
In [20]: driver.page_source
Out[20]: '<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{\n  "origin": "51.210.80.127"\n}\n</pre></body></html>'
```

**Comment by amitalokbera** [comment]
> Working here as well
> 
> ```python
> In [4]: import undetected_chromedriver.v2 as uc
> 
> ... some stuff to start proxies...
> 
> In [8]: proxypool.current_proxy_addr
> Out[8]: ('127.0.0.1', 22225)
> 
> In [9]: opts = uc.ChromeOptions()
> In [10]: opts.add_argument('--proxy-server=socks5://127.0.0.1:22225')
> In [11]: driver = uc.Chrome(options=opts)
> In [12]: driver.get('http://httpbin.org/ip')
> In [13]: driver.page_source
> Out[13]: '<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{\n  "origin": "104.244.75.80"\n}\n</pre></body></html>'
> In [14]: driver.quit()
> 
> 
> In [15]: next(proxypool.pool)
> Out[15]: ('127.0.0.1', 22226)
> In [16]: opts = uc.ChromeOptions()
> In [17]: opts.add_argument('--proxy-server=socks5://127.0.0.1:22226')
> In [18]: driver = uc.Chrome(options=opts)
> In [19]: driver.get('http://httpbin.org/ip')
> In [20]: driver.page_source
> Out[20]: '<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{\n  "origin": "51.210.80.127"\n}\n</pre></body></html>'
> ```

proxy server do works, but when i use it with v2, it doesn't bypass the cloudflare protection. please check on this link [https://www.mueller.de/p/pokemon-sammelkartenspiel-schwert-schild-elite-trainer-box-plus-1-stueck-sortiert-2673465/](link)

Thank You

**Comment by ultrafunkamsterdam** [comment]
I got the same "issue" but i'm quite certain this is due the proxy ip reputation as i'm using Tor, which is like double red flag.
