### ISSUE TITLE
ChromeDriver cannot specify version for v2

### ISSUE THREAD

**Issue by Lolkekzor** [ultrafunkamsterdam/undetected-chromedriver#147]
```
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 90
Current browser version is 89.0.4389.128 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
```

I've checked the source code for v2 and it doesn't seem to let me to specify that I want to get version 89 of the chromedriver, not 90. Am I missing something obvious or does this feature not exist? Here's my code:

```
import undetected_chromedriver.v2 as uc
uc.TARGET_VERSION = 89
driver = uc.Chrome()
```

It doesn't seem to do anything though. This actually does not work for me even if I remove the .v2 part

**Comment by dotSpectrum** [comment]
Getting this issue as well on MacOS. Was working yesterday April 12th and was fine for weeks until today.

```
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:51334
from session not created: This version of ChromeDriver only supports Chrome version 90
Current browser version is 89.0.4389.128
```

**Comment by Avnsx** [comment]
I solved this by just entirely deleting chromedriver in every location and then waiting for uc to download the correct version into current work dir.

Simply not specifiying anything at all;
```python
import undetected_chromedriver as uc
driver = uc.Chrome()
```

**Comment by Lolkekzor** [comment]
Awesome, thanks for this. I had to delete the chromedriver
