### ISSUE TITLE
Support Chrome >114

### ISSUE THREAD

**Issue by macalinao** [ultrafunkamsterdam/undetected-chromedriver#1475]
There is a new place to download the Chromedriver binaries for Chrome >114:

https://chromedriver.chromium.org/downloads/version-selection

**Comment by hkrcs96** [comment]
hello, sorry for my english, chrome has updated and undetected-chromedriver is not opening anymore, does anyone know how to solve this?

**Comment by mshot** [comment]
working solution imho:
https://stackoverflow.com/a/76830878/5003770
````
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import urllib.request

#...

try:
    service = Service(ChromeDriverManager().install())
except ValueError:
    latest_chromedriver_version_url = "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"
    latest_chromedriver_version = urllib.request.urlopen(latest_chromedriver_version_url).read().decode('utf-8')
    service = Service(ChromeDriverManager(version=latest_chromedriver_version).install())
````

creating driver with path from webdriver-manager
`driver_executable_path=service.path`

**Comment by jdholtz** [comment]
Hey @macalinao, would you be able to try the attached PR to see if the fix is working for you?

**Comment by hkrcs96** [comment]
I still don't understand, ChromeDriverManager won't work with uc.ChromeOptions, can you explain or give an example

**Comment by mshot** [comment]
in my case its something like this:
```
import undetected_chromedriver as webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import urllib.request


try:
    service = Service(ChromeDriverManager().install())
except ValueError:
    latest_chromedriver_version_url = "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"
    latest_chromedriver_version = urllib.request.urlopen(latest_chromedriver_version_url).read().decode('utf-8')
    service = Service(ChromeDriverManager(version=latest_chromedriver_version).install())
	
port = 9222
options = webdriver.ChromeOptions()
options.add_argument(f'--remote-debugging-port={port}')

class My_Chrome(webdriver.Chrome):
    def __del__(self):
        pass
        
driver = My_Chrome(options = options, port=port, use_subprocess=True, driver_executable_path=service.path)

adress = f"https://github.com"
driver.get(adress)
```

**Comment by nradosevic** [comment]
Tried that, but got this:

```
File "/Users/nikola/IT Projects/temp/chatgpt-automation/venv/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 122, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /Users/nikola/.wdm/drivers/chromedriver/mac64/116.0.5845.96/chromedriver-mac-arm64/chromedriver
```

**Comment by farmer1234** [comment]
> in my case its something like this:
> 
> ```
> import undetected_chromedriver as webdriver
> from selenium.webdriver.chrome.service import Service
> from webdriver_manager.chrome import ChromeDriverManager
> import urllib.request
> 
> 
> try:
>     service = Service(ChromeDriverManager().install())
> except ValueError:
>     latest_chromedriver_version_url = "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"
>     latest_chromedriver_version = urllib.request.urlopen(latest_chromedriver_version_url).read().decode('utf-8')
>     service = Service(ChromeDriverManager(version=latest_chromedriver_version).install())
> 	
> port = 9222
> options = webdriver.ChromeOptions()
> options.add_argument(f'--remote-debugging-port={port}')
> 
> class My_Chrome(webdriver.Chrome):
>     def __del__(self):
>         pass
>         
> driver = My_Chrome(options = options, port=port, use_subprocess=True, driver_executable_path=service.path)
> 
> adress = f"https://github.com"
> driver.get(adress)
> ```

This worked for me in bypassing ' https://nowsecure.nl ', however when i use it in my code the url i'm trying to access is stuck on refreshing and only when i reload the page the code processes further.
