### ISSUE TITLE
Version of Chrome only supports version 90

### ISSUE THREAD

**Issue by dotSpectrum** [ultrafunkamsterdam/undetected-chromedriver#148]
I have tried installing Chromium v90, adding a chrome driver v90, and adding it to my path but that did not work as well. Also tried deleting the chrome driver on my working directory. Using MacOS Big Sur if that helps. If you need any additional information, let me know.

```
import undetected_chromedriver.v2 as uc
from selenium.common.exceptions import NoSuchElementException

chrome_options = uc.ChromeOptions()
driver = uc.Chrome(options=chrome_options)
with driver:
	driver.get(url)

...


selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:51334
from session not created: This version of ChromeDriver only supports Chrome version 90
Current browser version is 89.0.4389.128
```

**Comment by Avnsx** [comment]
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/147#issuecomment-819259943

**Comment by dotSpectrum** [comment]
Thank you, removing the binary chromedriver in /usr/loca/bin did the trick.

**Comment by dotSpectrum** [comment]
@Avnsx I'm getting this error again... Not sure what is happening. But I do not have chromedriver in my working directory nor in my $PATH. Any advise? Or is it downloading the wrong version every time I load my script?

**Comment by Avnsx** [comment]
> @Avnsx I'm getting this error again... Not sure what is happening. But I do not have chromedriver in my working directory nor in my $PATH. Every time it fails, I go ahead and delete chromedriver.
> 
> Any advise? Or is it downloading the wrong version every time I load my script?

I have no clue, that never happend to me at all. If you didn't try yet, you could attempt to set target version to download like this:
```python
import undetected_chromedriver as uc
uc.TARGET_VERSION = 90
driver = uc.Chrome()
```
