### ISSUE TITLE
 chrome 116. Will UC work?

### ISSUE THREAD

**Issue by leesanghyone** [ultrafunkamsterdam/undetected-chromedriver#1480]
I can't get it to work...

**Comment by mshot** [comment]
u can try 
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1475#issuecomment-1680925178
or try fix with something like this PR
https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/1478

**Comment by Matt10233** [comment]
https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/1478 this worked for me

**Comment by ultrafunkamsterdam** [comment]
**3.5.3** just updated and on pypi
