### ISSUE TITLE
tutti.ch detects the undetected-chromedriver

### ISSUE THREAD

**Issue by daybyter** [ultrafunkamsterdam/undetected-chromedriver#151]
Seems like after loading, the browser is stuck in a infinite loop instead of getting redirected to the actual website.

Thanks for your efforts!

**Comment by ultrafunkamsterdam** [comment]
not caused by undetected-chromedriver v2.

**Comment by daybyter** [comment]
So it works for you?

**Comment by daybyter** [comment]
Just tested this code:

`import undetected_chromedriver.v2 as uc
driver = uc.Chrome()
with driver:
    driver.get('https://www.tutti.ch/de/li/zuerich/fahrzeuge')`

Doesn't work for me.

Entering the same URL manually in google-chrome works. So I guess the driver is detected?
