### ISSUE TITLE
not working on CloudFlare

### ISSUE THREAD

**Issue by adfnekc** [ultrafunkamsterdam/undetected-chromedriver#1517]
here is my code
```
import undetected_chromedriver as uc

options = uc.options.ChromeOptions()
driver = uc.Chrome(options=options,headless=False,driver_executable_path="drive/chromedriver-linux64/chromedriver",browser_executable_path="drive/chrome-linux64/chrome")
driver.get('https://breachforums.is/Forum-Databases')
```
wont get into the real web page

**Comment by CreataUsername** [comment]
try this ，it works for me  [https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1497#issuecomment-1688195547](url)

**Comment by CreataUsername** [comment]
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1497#issuecomment-1688195547

**Comment by pilotbird-Truphena-Lwanga** [comment]
I am facing the same issue with the website:_**https://www.sotwe.com/**_  that uses CloudFlare .After the upgrade of the library to version 3.5.3 , chromedriver :116.0.5845.96 and google-chrome:117.0.5938.92-1 I am no longer able to bypass Cloudflare protection
