### ISSUE TITLE
Distill detects now on UC

### ISSUE THREAD

**Issue by lellywang** [ultrafunkamsterdam/undetected-chromedriver#152]
Try to go to any Ticketmaster event on undetected Chrome. Refresh after it opens if not blocked yet, will get blocked. Same on V2, used working proxies as well. Was working before Wednesday. 
Chrome V90 
```

import undetected_chromedriver as uc
driver = uc.Chrome()
driver.get("https://www.ticketmaster.com/the-weeknd-chicago-illinois-01-23-2022/event/04005851B6124555")
```

**Comment by merry75** [comment]
same

**Comment by ultrafunkamsterdam** [comment]
use v2

**Comment by FranciscoPalomares** [comment]
@ultrafunkamsterdam not works now, no reserve tickets for example
