### ISSUE TITLE
Cannot add Extension to chrome V2

### ISSUE THREAD

**Issue by canonsky1992** [ultrafunkamsterdam/undetected-chromedriver#154]
chrome_options = Options()
chrome_options.add_argument('user-data-dir='+profiles[i])
chrome_options.add_extension('data/exten.crx')
driver = uc.Chrome(options=chrome_options)
Why v2 cannot add extension?

**Comment by KawasakiMotorsEurope** [comment]
Because ext are in your profile,which cannot be existing, atm.

**Comment by rnyPlanet** [comment]
> chrome_options = Options()
> chrome_options.add_argument('user-data-dir='+profiles[i])
> chrome_options.add_extension('data/exten.crx')
> driver = uc.Chrome(options=chrome_options)
> Why v2 cannot add extension?

I have the same problem. did you solve it?

**Comment by rnyPlanet** [comment]
@ultrafunkamsterdam hi thanks for chromedriver. I also cannot add an extension. Is this a bug? @ultrafunkamsterdam extensions work for you?

**Comment by ultrafunkamsterdam** [comment]
No. Extensions do not work in combination with remote debugging (which is used by this module).

**Comment by rnyPlanet** [comment]
got it.  maybe there is some way out to add auth proxy?  (I tried seleniumwire - there is a problem with mitmproxy that changes fingerprint and cloudflare returns 503 error. I also thought about an extension that would help with a proxy - but remote debugging does not work with the extension).  you have more knowledge - is there any way out?  v2 works fine, but damn I need to work with auth proxy

**Comment by ultrafunkamsterdam** [comment]
Fingerprint is not a network thing so mitm proxy wouldn't change it. That's for sure 😉

**Comment by rnyPlanet** [comment]
well i don't have enough knowledge, and i read this there [mitm](https://github.com/mitmproxy/mitmproxy/issues/4575) and [selenium-wire](https://github.com/wkeeling/selenium-wire/issues/215#issuecomment-835737447).

**Comment by rnyPlanet** [comment]
no solutions at all? (

**Comment by rnyPlanet** [comment]
@ultrafunkamsterdam Sorry to bother you, I guess I'm already bored you) I found a couple of possibilities [1](https://github.com/tebeka/selenium/issues/201#issuecomment-690003981) and [2](https://stackoverflow.com/questions/25064523/load-extension-parameter-for-chrome-doesnt-work) (use --load-extension to load the extension for the remote debugging browser, [this line with arguments](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/master/undetected_chromedriver/v2.py#L298)), I tried but got an error ```ERR_SOCKS_CONNECTION_FAILED```. I wanted to ask if you tried this? if not, is there a chance that it will help?

**Comment by ultrafunkamsterdam** [comment]
You can definitly add extensions. But you'll need a steady profile as extensions are kept in the profile.

![image](https://user-images.githubusercontent.com/21027969/118255232-49c5b380-b4ac-11eb-82d7-79dce4de3eeb.png)

**Comment by the-white-light** [comment]
I've managed to load extensions by extracting the CRX file into a folder and then using `--load-extension`.

**Comment by vancouverjackluo** [comment]
> I've managed to load extensions by extracting the CRX file into a folder and then using `--load-extension`.

Hello @the-white-light , can you elaborate how you approached it with `--load-extension`? 
I have the following code, doesn't work:
`options.add_argument('--load-extension = C:\Code\project_MP\ABC.crx')`

**Comment by vancouverjackluo** [comment]
> 

Can you kindly explain in detail how this works? a sample code will be much appreciated.

Thanks

**Comment by the-white-light** [comment]
You had it mostly right, but as I said before you need to _extract_ the extension first, then direct the code to the destination folder. 

I extracted the .crx file to `./MultiPass`

**Comment by vancouverjackluo** [comment]
> You had it mostly right, but as I said before you need to _extract_ the extension first, then direct the code to the destination folder.
> 
> I extracted the .crx file to `./MultiPass` and then did `opt.add_argument('--load-extension=./MultiPass')`

@the-white-light  so it will something like:
`options.add_argument('--load-extension = ./ABC.crx')`

tried it...still doesn't work. Here is my entire code:




import undetected_chromedriver as uc
import time
from selenium import webdriver
from selenium.webdriver.common.by import By

def main():
    options = uc.ChromeOptions()
    options.add_argument("--no-sandbox --no-first-run --no-service-autorun --password-store=basic")
    driver = uc.Chrome(options=options) 
    options.add_experimental_option('excludeSwitches', ['enable-logging'])
    options.add_argument('--load-extension = ./abc.crx')

if __name__ == '__main__':
    main()

**Comment by the-white-light** [comment]
Please re-read what I wrote. You need to extract the crx, and it is not used in the code.

**Comment by vancouverjackluo** [comment]
> Please re-read what I wrote. You need to extract the crx, and it is not used in the code. You _downloaded_ the crx file, which is basically just a zip file. _Extract_ it then point your code to the destination folder.

did that.

**Comment by the-white-light** [comment]
1. No you didn't. You still are using the crx file in your code, see the line I posted — no crx. 
2. You added it to `options` _after_ initializing the chromedriver, it needs to be before the `driver =` line.

**Comment by vancouverjackluo** [comment]
> 2\. _er_ initializing the chro

@the-white-light  thanks, my mistake. does the .crx file needs to be the only file in the subfolder?

**Comment by the-white-light** [comment]
No, you just extract it into a folder and point your code to that.

**Comment by vancouverjackluo** [comment]
> No, you just extract it into a folder and point your code to that.

damn, found it, but got this error instead...the .crx file should be fine since I just used it in a headless browser test...let me try something else

![image](https://user-images.githubusercontent.com/32807093/147376915-015c903f-ef43-47e7-b46e-a106e49c8735.png)

**Comment by 90xboy** [comment]
> > No, you just extract it into a folder and point your code to that.
> 
> damn, found it, but got this error instead...the .crx file should be fine since I just used it in a headless browser test...let me try something else
> 
> ![image](https://user-images.githubusercontent.com/32807093/147376915-015c903f-ef43-47e7-b46e-a106e49c8735.png)

hey mate, did you solve this error? i also can not add extension.

**Comment by danielafriyie** [comment]
I know it's late to add this comment but it might help something in the future. When you extract the extension, point your code to the full path of the extracted folder like 'C:\Users\yourproject\extension'. It worked for me!!!

**Comment by ribonred** [comment]
i found the soultion of this

> > > No, you just extract it into a folder and point your code to that.
> > 
> > 
> > damn, found it, but got this error instead...the .crx file should be fine since I just used it in a headless browser test...let me try something else
> > ![image](https://user-images.githubusercontent.com/32807093/147376915-015c903f-ef43-47e7-b46e-a106e49c8735.png)
> 
> hey mate, did you solve this error? i also can not add extension.

i got the solution using this..
try download the extension as zip.. then extract to some folder

then you can 
options.add_argument('--load-extension = ./extraction_folder')

should not .crx file

**Comment by 90xboy** [comment]
> i found the soultion of this
> 
> > > > No, you just extract it into a folder and point your code to that.
> > > 
> > > 
> > > damn, found it, but got this error instead...the .crx file should be fine since I just used it in a headless browser test...let me try something else
> > > ![image](https://user-images.githubusercontent.com/32807093/147376915-015c903f-ef43-47e7-b46e-a106e49c8735.png)
> > 
> > 
> > hey mate, did you solve this error? i also can not add extension.
> 
> i got the solution using this.. try download the extension as zip.. then extract to some folder
> 
> then you can options.add_argument('--load-extension = ./extraction_folder')
> 
> should not .crx file

hi mate, i can kindly share a sample code, i try but still get error. I newbie in python selenium, tks for your help
**Here my code:**
from selenium.webdriver.common import keys
import undetected_chromedriver.v2 as uc
import time
if __name__ == '__main__':
    options = uc.ChromeOptions()
    options.add_argument("--disable-notifications")
    options.add_argument('--load-extension =C:\python\myproject\Extract file') # extract file zip to directory
    # setting profile
    options.user_data_dir = "c:\\temp\\profile18"
    driver = uc.Chrome(options=options,version_main=97)
    time.sleep(2)
    input('ok')

**Comment by ribonred** [comment]
`
ext
├── pass
│   ├── 47a1591dea3b6d1f42f9b3cd0673f69c.svg
│   ├── background.js
│   ├── icons
│   │   ├── 128
│   │   │   ├── gold.png
│   │   │   └── grey.png
│   │   ├── 32
│   │   │   ├── gold.png
│   │   │   └── grey.png
│   │   ├── 48
│   │   │   ├── gold.png
│   │   │   └── grey.png
│   │   └── 64
│   │       ├── gold.png
│   │       └── grey.png
│   ├── manifest.json
│   ├── popup.css
│   ├── popup.html
│   └── popup.js
└── solver
    ├── content
    │   ├── hcaptcha.js
    │   ├── model.js
    │   └── tf.js
    ├── images
    │   ├── icon_128.png
    │   ├── icon_16.png
    │   ├── icon_32.png
    │   └── icon_48.png
    ├── manifest.json
    ├── model
    │   ├── group1-shard1of5
    │   ├── group1-shard2of5
    │   ├── group1-shard3of5
    │   ├── group1-shard4of5
    │   ├── group1-shard5of5
    │   └── model.json
    └── worker.js
`



ext is root folder of extension..
inside ext folder pass and solver are extracted extension

**Comment by ribonred** [comment]
> ```
> ext
> ├── pass
> │   ├── 47a1591dea3b6d1f42f9b3cd0673f69c.svg
> │   ├── background.js
> │   ├── icons
> │   │   ├── 128
> │   │   │   ├── gold.png
> │   │   │   └── grey.png
> │   │   ├── 32
> │   │   │   ├── gold.png
> │   │   │   └── grey.png
> │   │   ├── 48
> │   │   │   ├── gold.png
> │   │   │   └── grey.png
> │   │   └── 64
> │   │       ├── gold.png
> │   │       └── grey.png
> │   ├── manifest.json
> │   ├── popup.css
> │   ├── popup.html
> │   └── popup.js
> └── solver
>     ├── content
>     │   ├── hcaptcha.js
>     │   ├── model.js
>     │   └── tf.js
>     ├── images
>     │   ├── icon_128.png
>     │   ├── icon_16.png
>     │   ├── icon_32.png
>     │   └── icon_48.png
>     ├── manifest.json
>     ├── model
>     │   ├── group1-shard1of5
>     │   ├── group1-shard2of5
>     │   ├── group1-shard3of5
>     │   ├── group1-shard4of5
>     │   ├── group1-shard5of5
>     │   └── model.json
>     └── worker.js
> ```
> 
> ext is root folder of extension.. inside ext folder pass and solver are extracted extension
> then load the extension like this 
> ```
>options.add_argument('--load-extension=./ext/solver,./ext/pass')
>```
> i use 2 extension here, so is separated by coma in argument



> > i found the soultion of this
> > > > > No, you just extract it into a folder and point your code to that.
> > > > 
> > > > 
> > > > damn, found it, but got this error instead...the .crx file should be fine since I just used it in a headless browser test...let me try something else
> > > > ![image](https://user-images.githubusercontent.com/32807093/147376915-015c903f-ef43-47e7-b46e-a106e49c8735.png)
> > > 
> > > 
> > > hey mate, did you solve this error? i also can not add extension.
> > 
> > 
> > i got the solution using this.. try download the extension as zip.. then extract to some folder
> > then you can options.add_argument('--load-extension = ./extraction_folder')
> > should not .crx file
> 
> hi mate, i can kindly share a sample code, i try but still get error. I newbie in python selenium, tks for your help **Here my code:** from selenium.webdriver.common import keys import undetected_chromedriver.v2 as uc import time if **name** == '**main**': options = uc.ChromeOptions() options.add_argument("--disable-notifications") options.add_argument('--load-extension =C:\python\myproject\Extract file') # extract file zip to directory # setting profile options.user_data_dir = "c:\temp\profile18" driver = uc.Chrome(options=options,version_main=97) time.sleep(2) input('ok')
