### ISSUE TITLE
Cannot set option "detach" in uc.ChromeOptions().

### ISSUE THREAD

**Issue by jahid1o** [ultrafunkamsterdam/undetected-chromedriver#1547]
When using `set_capability("detach", True)`
getting error:
>selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: unrecognized capability: detach

When using `.add_experimental_option("detach", True)`
getting error:
>selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: goog:chromeOptions from invalid argument: unrecognized chrome option: detach

**This might be related to another  issue: #1536**

**Comment by FelipeSL** [comment]
I'm having the same isue here. 

Any clue in how to solve it?

**Comment by FelipeSL** [comment]
"I found a solution to this by setting use_subprocess=True in driver = uc.Chrome(use_subprocess=True).

This keeps the browser open after the code runs. There's no need to use .add_experimental_option("detach", True) or set_capability("detach", True).

**Comment by jahid1o** [comment]
> I found a solution to this by setting use_subprocess=True in driver = uc.Chrome(use_subprocess=True).
> 
> This keeps the browser open after the code runs. There's no need to use .add_experimental_option("detach", True) or set_capability("detach", True).

Unfortunately, it's not working for me.

Chrome version 117.0.5938.62
selenium==4.12.0
undetected-chromedriver==3.5.3
OS=Ubuntu 22.04.3 LTS

**Comment by hmtvg** [comment]
You could try
driver = uc.Chrome(enable_cdp_events=True)
and don't use driver.quit() at end of script

**Comment by jahid1o** [comment]
> You could try driver = uc.Chrome(enable_cdp_events=True) and don't use driver.quit() at end of script

Thanks, Mate!
It worked.

**Comment by Rye-Guy** [comment]
I experienced the same problem with the same issue and it was fixed by @hmtvg suggestion thanks a lot!. 

WSL:Ubuntu 22.04 LTS
undetected-chromedriver==3.5.5
selenium=4.18.1
