### ISSUE TITLE
Can't bypass nowsecure.nl

### ISSUE THREAD

**Issue by Terminator98** [ultrafunkamsterdam/undetected-chromedriver#1561]
```python
import undetected_chromedriver as uc
driver = uc.Chrome()
driver.get('https://nowsecure.nl')
```
I have been trying with the code for long time on MacOS but it's still being detected and cannot bypass the simple bot detection layer from nowsecure.nl

![image](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/43156062/9a1ff1ae-c339-46f2-a908-eee848a54691)

**Comment by ortizjeison** [comment]
Which version of chrome are u using? because yesterday they released the 117 (stable) and UC is not working as expected

**Comment by Terminator98** [comment]
I'm using Chrome v117

**Comment by max32002** [comment]
windows platform downgrade chrome to 116 and 115 still be detected.
```
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5791.0/win64/chrome-win64.zip
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5791.0/win64/chromedriver-win64.zip

https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.90/win64/chrome-win64.zip
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.90/win64/chromedriver-win64.zip
```

**Comment by ortizjeison** [comment]
That's true @max32002, but in linux you can use 116 and it performs well. 

What I've experienced on windows until this moment, is that it works well when headless=False, when True it gets detected, I really hope they fix this soon.
