### ISSUE TITLE
UC updating chromedriver to 117

### ISSUE THREAD

**Issue by vndhote** [ultrafunkamsterdam/undetected-chromedriver#1564]
My code sucks in chromium 117 version so i decided to stay in 116, but uc needs 117 chromium version. How can I make it such that in %APPDATA%/undetected_chromedriver/undetected_chromedriver.exe it does not update the driver. I tried making the folder read only which does not seem to work. I just want to stay on chromedriver 116

**Comment by LUXTACO** [comment]
driver = uc.Chrome(options=options, use_subprocess=True, version_main=116)
use that, it fixed it for me!

**Comment by vndhote** [comment]
Thank you so much ! You just saved my day it's working

**Comment by LUXTACO** [comment]
No worries, just here to help, if you need more help feel free to add me on discord or msg me thru here!

**Comment by Beetroit** [comment]
> driver = uc.Chrome(options=options, use_subprocess=True, version_main=116) use that, it fixed it for me! if it didnt work dm me on discord #.takkeshi and I may be able to help you!

This worked, Thank you.

**Comment by LUXTACO** [comment]
Remember to close the issue, just so that Leo can focus on non solved problems!

**Comment by vndhote** [comment]
> Remember to close the issue, just so that Leo can focus on non solved problems!

Yea ok
