### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by xuehue** [ultrafunkamsterdam/undetected-chromedriver#157]
I'm doing everything right, I'm in a virtual enviroment and I tried installing it like 5 times already, but i still get the error "Unable to import undetected_chromedriver"
No idea why

**Comment by ultrafunkamsterdam** [comment]
Then you are probably doing everything wrong instead. 😅 also no code, errors whatsoever supplied. Closed until a  better "issue" is raised

**Comment by xuehue** [comment]
there were no errors, only "unable to import"

**Comment by xuehue** [comment]
I set up my virtual enviroment wrong... I'm a dumbass, sorry
