### ISSUE TITLE
Can not use experimental option "debuggerAddress" in v2

### ISSUE THREAD

**Issue by david-jng** [ultrafunkamsterdam/undetected-chromedriver#160]
I want to use the debuggerAddress experimental option in V2 but it seems that this feature has no effect.

```
import undetected_chromedriver.v2 as uc
uc.TARGET_VERSION = 90
chrome_options = uc.ChromeOptions()
chrome_options.add_experimental_option("debuggerAddress", "127.0.0.1:1000")
driver = uc.Chrome(options=chrome_options)
driver.get("chrome://version")
time.sleep(6000)
```

![image](https://user-images.githubusercontent.com/41423063/116261720-33afb780-a778-11eb-8a0d-e101e9dc868f.png)

**Comment by ultrafunkamsterdam** [comment]
You don't need to and you even must not do it. Package does it all for you ( from downloading and patching driver, to setting up your options to.... well just run. You can use options, but do not touch these debugger options since that is used by the package.

There you go:
```python
import undetected_chromedriver.v2 as uc
driver = uc.Chrome()
driver.get('https://somewebsite.xyz')

# if site is protected by hCaptcha/Cloudflare
with driver:
    driver.get('https://cloudflareprotectedsite.xyz')

```

**Comment by shivams** [comment]
@ultrafunkamsterdam In that case, how would we be able to attach our driver to a running Chrome instance which we manually started with the `--remote-debugging-port` option?

**Comment by gqchishti** [comment]
@shivams did you find the solution. I am trying to achieve the exact same thing.
