### ISSUE TITLE
AttributeError: 'ChromeOptions' object has no attribute 'headless'

### ISSUE THREAD

**Issue by mominurr** [ultrafunkamsterdam/undetected-chromedriver#1607]
import undetected_chromedriver as uc

def uc_driver():
    try:
        options = uc.ChromeOptions()
        options.add_argument("--excludeSwitches=enable-automation")
        options.add_argument("--excludeSwitches=enable-logging")
        driver = uc.Chrome(options=options)
        driver.maximize_window()
        driver.set_page_load_timeout(60)
        return driver
    except:
        sys.stderr = open('error.log', 'a+',encoding='utf-8')
        traceback.print_exc()
        sys.stderr.close()
        pass
        

driver=uc_driver()

For this code give me this error :

Traceback (most recent call last):
  File "D:\Web Scraping Project\betonline.ag\betonline-scraper.py", line 16, in uc_driver
    driver = uc.Chrome(options=options)
  File "D:\Web Scraping Project\betonline.ag\env\lib\site-packages\undetected_chromedriver\__init__.py", line 398, in __init__
    if headless or options.headless:
AttributeError: 'ChromeOptions' object has no attribute 'headless'

**Comment by ArthurVerrez** [comment]
See [this issue](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1603).
Basically it's an incompatibility with some newer versions of Selenium, a quick fix is to downgrade to Selenium 4.12.0.

**Comment by mominurr** [comment]
> See [this issue](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1603). Basically it's an incompatibility with some newer versions of Selenium, a quick fix is to downgrade to Selenium 4.12.0.

**Comment by mominurr** [comment]
> See [this issue](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1603). Basically it's an incompatibility with some newer versions of Selenium, a quick fix is to downgrade to Selenium 4.12.0.

thanks . Now work my script.
