### ISSUE TITLE
It seems that we can not pass HCaptcha at CloudFlare with it, please help

### ISSUE THREAD

**Issue by deriklogov** [ultrafunkamsterdam/undetected-chromedriver#162]
Hi,
I am trying to get pass captcha at cloudflare protection , its asking to do Hcaptcha.
It gets in loop (solving captcha and starting over again).
I tried both versions ( normal and v2).
Nothing helps.
I can pass captcha by just opening page and solving it, but it wont let me solve it once i open that that with chrome driver.
Somehow it gets detected.
Please help

**Comment by chwba** [comment]
Yeah CF is rip again, even after solving the captcha it doesn't redirect again

**Comment by ultrafunkamsterdam** [comment]
Normally you would only get js challenge, so that means your ip has bad rep!

**Comment by chwba** [comment]
In fact you are right, should have tested with a different one before replying, just tested with a residential IP and not even getting a CAPTCHA, thanks for the hint!

**Comment by shavenne** [comment]
What if I have this problem without an IP with bad rep? I tried several IPs (from real ISPs). I can solve the captcha and get to the page I want with a real chromium but as soon I use undetected chromedriver I get this hcaptcha loop even if I'm solving it manually.

I'm using "--disable-blink-features=AutomationControlled" as an argument and Python 3.9.9.
