### ISSUE TITLE
Proxy passthrough with ChromeOptions no longer works in

### ISSUE THREAD

**Issue by jorgeluisdelgado** [ultrafunkamsterdam/undetected-chromedriver#164]
Example:
```
import undetected_chromedriver.v2 as webdriver

ChromeOptions = webdriver.ChromeOptions()
ChromeOptions.add_argument('--proxy-server=%s' % Proxy)
driver = webdriver.Chrome(options=ChromeOptions)
```

Will not pass the proxy settings through to undetected-chromedriver. This works in v1, but not in v2.  Tested in 90.0.4430.93.

**Comment by ultrafunkamsterdam** [comment]
You're trying to format to string a Proxy class. It accepts strings only

**Comment by jorgeluisdelgado** [comment]
@ultrafunkamsterdam Not exactly sure what you mean. Proxy is just a variable named Proxy which is a string. I am using %s as a placeholder. 
What I am doing is the same as: 

`'--proxy-server=' + str(Proxy)`

**Comment by ultrafunkamsterdam** [comment]
Ive got mine working using "--proxy-server=socks5://ip:port" .  Also try not to double quote as it won't work like '--proxy-server="xyz"' .
Make sure the proxy address is valid and ports are not blocked.. more there is not to it..   ah well you could try chromium as last resort

**Comment by jorgeluisdelgado** [comment]
I'm not entirely sure why this isn't working in v2. It works in v1 and also using the stock chromedriver.  The website loads, but the IP is not masked. The ports are not being blocked, and the proxy address is valid. 

I have tried running side-by-side tests with chrome/v1/v2 and only v2 is presenting this issue.

**Comment by ultrafunkamsterdam** [comment]
Looks mostly like syntax error. Then chrome won't error out and just continue without using the proxy.

Check also here maybe https://www.linuxbabe.com/desktop-linux/configure-proxy-chromium-google-chrome-command-line/amp

**Comment by jorgeluisdelgado** [comment]
Are there any debug commands you would suggest to assist in identifying this in v2? If it was a syntax error, I'm not sure how it would work in v1 and stock chromedriver but not in v2.

**Comment by ultrafunkamsterdam** [comment]
Might be even just http proxying not working.. as chromedriver also needs the http connection to drive chrome. I actually only tested socks5...

**Comment by ultrafunkamsterdam** [comment]
Because v2 starts a browser by itself and connects to it via the driver  using debugger addr. (dev tools protocol). V1 spawns the chrome window itself .

**Comment by rnyPlanet** [comment]
is there any solution to use socks5 with a password and login?

**Comment by ultrafunkamsterdam** [comment]
yes use  add_argument("--proxy-server=socks5://username:password@ip:port")

> is there any solution to use socks5 with a password and login?

**Comment by rnyPlanet** [comment]
ok. I tried it, but now it does not load. as I understand it writes that there is no access to the Internet. proxy works 100%

![Screenshot_1](https://user-images.githubusercontent.com/33624178/116870720-af4bb180-ac1b-11eb-8415-3dac34135777.png)

**Comment by ultrafunkamsterdam** [comment]
```python

# some custom code 

def start_chromedriver(proxy_addr):
     options = uc.ChromeOptions()
     options.add_argument('--proxy-server=%s' % proxy_addr)
     driver = uc.Chrome(options=options)
     driver.get('https://httpbin.org/ip')
     print('Response:', driver.page_source)
     driver.quit()


 def test_chromedriver():

     tor = start_aiotor()
     for x in tor.proxies:
         start_chromedriver(x.addr)

test_chromedriver()
```
```
Response: <html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{
  "origin": "45.154.255.73"
}
</pre></body></html>
Response: <html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{
  "origin": "185.220.103.5"
}
</pre></body></html>
Response: <html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{
  "origin": "185.220.102.7"
}
</pre></body></html>
Response: <html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{
  "origin": "185.220.100.246"
}
</pre></body></html>
Response: <html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{
  "origin": "193.218.118.90"
}
</pre></body></html>
Response: <html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{
  "origin": "185.220.101.145"
}
</pre></body></html>
Response: <html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{
  "origin": "199.249.230.153"
}
</pre></body></html>
Response: <html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{
  "origin": "176.10.99.200"
}
</pre></body></html>
Response: <html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{
  "origin": "167.88.7.134"
}
</pre></body></html>
Response: <html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{
  "origin": "185.220.102.246"
}
</pre></body></html>
```

**Comment by rnyPlanet** [comment]
bro, what else can I do?) I have already tried everything - it does not give access to sites... maybe you have something additionally installed that proxies work for you?

**Comment by rnyPlanet** [comment]
undetected_chromedriver works with proxies that do not have a password. solved the authorization problem https://github.com/wkeeling/selenium-wire
