### ISSUE TITLE
Incapsula detecting browser

### ISSUE THREAD

**Issue by rsbotmoo** [ultrafunkamsterdam/undetected-chromedriver#165]
I have been using this awesome repo for over a year now but I have noticed since last week my browser is being detected by Incapsula.

I have done some tests with Chrome and Brave on residential IP and proxies, all getting detected.

To reproduce:

```
import undetected_chromedriver.v2 as uc

driver = uc.Chrome()
with driver:
    driver.get('https://secure.runescape.com/m=account-creation/a=13/create_account?theme=oldschool')
```
What the website should look like:

![image](https://user-images.githubusercontent.com/26330995/116826309-ac0ce300-ab93-11eb-897c-0b671878b479.png)

What it looks like being detected:

![image](https://user-images.githubusercontent.com/26330995/116826319-b6c77800-ab93-11eb-890b-2a89e6c086ec.png)

Thanks for your work!

**Comment by ultrafunkamsterdam** [comment]
`pip install -U undetected-chromedriver`  to get yesterdays update

**Comment by rsbotmoo** [comment]
@ultrafunkamsterdam  I was running on latest version before making this issue. (undetected-chromedriver 2.2.7)

**Comment by rsbotmoo** [comment]
> `pip install -U undetected-chromedriver` to get yesterdays update

@ultrafunkamsterdam Could you check if the above snippet works for you?

My config was: undetected-chromedriver 2.2.7 and chrome 90.0.4430.93 (also tried Brave and chrome 89.x before)

Thx

**Comment by ultrafunkamsterdam** [comment]
And risk my ip gets flagged as well? You're probably a nice guy, but no. Because that is what happens. Read the message. Who guarantees you the proxy IP is clean? The provider? Your data center?  The only way to be reasonably sure is to proxy your mobile phone connection (4g, not wifi).

**Comment by rsbotmoo** [comment]
@ultrafunkamsterdam My IP doesn't get flagged, if I manually visit the URL on my chrome browser it works. (I test on my home IP) Selenium is just not working that's the problem. (also tested V2)
I am 100% sure this is not an IP problem. I have read V2 is actually using my Chrome browser, but it is still getting detected. (Manually is works)

Maybe you know any other website that uses Incapsula to test the detection. It all worked until last week.

Thx
