### ISSUE TITLE
SendKeys does not send keys like ą ć ź ż 

### ISSUE THREAD

**Issue by KaBreaK** [ultrafunkamsterdam/undetected-chromedriver#1676]
I am trying to send text but in my text are polish letter. exmaple input "fgsafasfaaą śs ćc żz źz ńn" output " śs cz z ńn"

**Comment by Noodles0x00** [comment]
I am not sure if there is a direct fix for it in Chromedriver but I usually set the value of the text directly via javascript and it works well, especially with emojis

**Comment by KaBreaK** [comment]
yah but on website that i am trying to use is blocking that type of writing

**Comment by KaBreaK** [comment]
At facebook I have been trying to add comment. I used simple document.querySelector("#mount_0_0_vA > div > div:nth-child(1) > div > div.x9f619.x1n2onr6.x1ja2u2z > div > div > div > div.x78zum5.xdt5ytf.x1t2pt76.x1n2onr6.x1ja2u2z.x10cihs4 > div.x1qjc9v5.x78zum5.xl56j7k.x193iq5w.x1t2pt76 > div > div > div > div > div > div > div > div > div > div > div > div > div > div:nth-child(8) > div > div > div:nth-child(4) > div > div > div.x1pi30zi.x1swvt13.x1n2onr6 > div.x1gslohp > div.x1iyjqo2 > div > div > div > div > div > div.x1r8uery.x1iyjqo2.x6ikm8r.x10wlt62.x4uap5 > form > div > div.x78zum5.x13a6bvl > div.x1ed109x.xdl72j9.x1iyjqo2.xs83m0k.x6prxxf.x6ikm8r.x10wlt62.x1y1aw1k.xn6708d.xwib8y2.x1ye3gou > div > div > p > span").textContent = "example" and nothing happened

**Comment by KaBreaK** [comment]
i solve that by changing attributes in selenium.webdriver.common.keys on keys i want
