### ISSUE TITLE
v2 doesn't respect options, no default profile.

### ISSUE THREAD

**Issue by ShoGinn** [ultrafunkamsterdam/undetected-chromedriver#168]
Im testing this on macOS and using just the basic setup as described, it never opens the web driver, only says that 'google chrome is setup'

Also when I click past that, if chrome options are set they are not passed to the web driver.

More specifically user-agent. I emulate a certain browser and want to continue using that function.

**Comment by ultrafunkamsterdam** [comment]
If you get a screen "Google Chrome is setup" , you meen chrome did start and showed you the kindof welkome page? Please attach something.

Aside: if you want to change user agent and "emulate a certain browser" , i dont quite see the the fit for using this package over the official one.

**Comment by ShoGinn** [comment]
![image](https://user-images.githubusercontent.com/2660603/117554239-65503a80-b024-11eb-98c0-5a97c6d40927.png)

Well using this package for emulating a different browser is just extra protection since it modifies the chrome driver etc.

**Comment by petzi75** [comment]
Hi,
I have a very similar problem so I decided to hang on here ...
first of all: Great work @ultrafunkamsterdam ! Thanks for this unbelievable package. I have tried a lot, that I can login in my older google acc on a chromium based browser, but never success - maybe this is the ultimate challenge - only ff works, but too slow for my opinion
So you have my greatest respect!

But it seems to be, that none of my given options take effect... I try it in this way:

        import undetected_chromedriver.v2 as webdriverUC
        Chromeoptions = webdriverUC.ChromeOptions()
        Chromeoptions.add_experimental_option("credentials_enable_service", False)
        Chromeoptions.add_experimental_option("profile.password_manager_enabled", False)
        Chromeoptions.add_argument("--window-size=1920,1080")
        driver = webdriverUC.Chrome()

but nothing changes... last argument is only for testing, if I can something simple change... What I try is to block especially the asking of saving the login infos/passwords... it doesn`t make sense and is a little bit annoying when it pops up after every login. Extra question: isn`t it be better, to block this by default?

**Comment by petzi75** [comment]
edit: i mean:

![Unbenannt](https://user-images.githubusercontent.com/83897832/117562550-10520a00-b0a0-11eb-8e0c-25551e10786c.png)
 
also google translate pops up with questions to translate the page....
this also makes processing more error-prone and complicated

**Comment by ultrafunkamsterdam** [comment]
> Hi,
> I have a very similar problem so I decided to hang on here ...
> first of all: Great work @ultrafunkamsterdam ! Thanks for this unbelievable package. I have tried a lot, that I can login in my older google acc on a chromium based browser, but never success - maybe this is the ultimate challenge - only ff works, but too slow for my opinion
> So you have my greatest respect!
> 
> But it seems to be, that none of my given options take effect... I try it in this way:
> 
> ```
>     import undetected_chromedriver.v2 as webdriverUC
>     Chromeoptions = webdriverUC.ChromeOptions()
>     Chromeoptions.add_experimental_option("credentials_enable_service", False)
>     Chromeoptions.add_experimental_option("profile.password_manager_enabled", False)
>     Chromeoptions.add_argument("--window-size=1920,1080")
>     driver = webdriverUC.Chrome()
> ```
> 
> but nothing changes... last argument is only for testing, if I can something simple change... What I try is to block especially the asking of saving the login infos/passwords... it doesn`t make sense and is a little bit annoying when it pops up after every login. Extra question: isn`t it be better, to block this by default?

Thank you! I believe the only workaround for this, which is far from ideal, is using a regular chrome (create new profile), log on to your google services, close chrome and copy over the profile and load it in chromedriver.

**Comment by ultrafunkamsterdam** [comment]
Using a profile will also stop most of the popups.

**Comment by petzi75** [comment]
Thanks for feedback and help. I know, but it´s the only solution I´ve found for me to prevent recaptcha puzzles..

Ok, have created blank profil with no adds only google login

        import undetected_chromedriver.v2 as webdriverUC
        Chromeoptions = webdriverUC.ChromeOptions()
        Chromeoptions.add_argument("user-data-dir=C:/Users/Admin/AppData/Local/Google/Chrome/User Data/Default")
        driver = webdriverUC.Chrome()

but nothing changes - if I take a look at version, the profilepath shows me only the temporary path, not my given userpath:
![Unbenannt2](https://user-images.githubusercontent.com/83897832/117613215-d435ac80-b166-11eb-8d09-85c40cd84873.png)

is there something more, I have to do?

**Comment by lucicop** [comment]
driver = webdriverUC.Chrome(options=Chromeoptions) ?

**Comment by ultrafunkamsterdam** [comment]
> driver = webdriverUC.Chrome(options=Chromeoptions) ?

Thanks. that in fact is something :)

**Comment by petzi75** [comment]
> driver = webdriverUC.Chrome(options=Chromeoptions) ?

yes, of course, you`re right! Thanks, this is really a shame...
