### ISSUE TITLE
Adapt code to PEP 632 (Python 3.12)

### ISSUE THREAD

**Issue by felipe-adeildo** [ultrafunkamsterdam/undetected-chromedriver#1688]
Hi.

Basically in Python 3.12 the package `desutils` has been deprecated, so the Pytohn's creators suggests to replace this lib for `packaging` package;

Following the suggests showed [here](https://peps.python.org/pep-0632/#migration-advice), the module `patche.py` can be rewritten which the first line can be like this

`from distutils.version import LooseVersion`

can be rewrite to

`from packaging.version import parse`

which all occurrences of `LooseVersion` can be replaced to `parse` function.

this function returns a `packaging.version.Version` object (if you need use in docstring...).

Is it, I think.

Sorry for my bad english, I'm English beginner.

**Comment by Chetan11-dev** [comment]
Hi Everyone, I recommend giving Botasaurus a try. It's an Anti Detection library that will help you bypass bot detection. It also doesn't cause distutils error. Here's how you can use it to visit https://nowsecure.nl/:

1. **Install Botasaurus**
```bash
python -m pip install botasaurus
```

2. **Bypass https://nowsecure.nl/**
```python
from botasaurus import *
from botasaurus.create_stealth_driver import create_stealth_driver

@browser(
    create_driver=create_stealth_driver(
        start_url="https://nowsecure.nl/",
    ),
)
def scrape_heading_task(driver: AntiDetectDriver, data):
    driver.prompt()
    heading = driver.text('h1')
    return heading

scrape_heading_task()    
```

![Now Secure Bypass](https://raw.githubusercontent.com/omkarcloud/botasaurus/master/images/now-secure-bypass.gif)

I suggest learning about bypassing various Cloudflare protections [here.](https://github.com/omkarcloud/botasaurus/tree/master#can-you-bypass-cloudflareimperva-challenges)

## If this has been a lifesaver for you, I would greatly appreciate a [Star here :)](https://github.com/omkarcloud/botasaurus)
