### ISSUE TITLE
[ Version Freeze ] How to prevent ChromeDriver from automatic updates !!?

### ISSUE THREAD

**Issue by sdfgsdfgd** [ultrafunkamsterdam/undetected-chromedriver#1690]
@ultrafunkamsterdam  

hey Leon, 

for 3-4 weeks until now : 
- undetected-chromedriver pip package frozen/set to 3.5.4  (do not update it, ever..)
- apt-mark hold google-chrome-stable 119  (do not update it, ever.......)

Now today I restart my script and I suddenly find this: 

`
Dec 06 14:43:29 w python3.11[3180254]: selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:34867
Dec 06 14:43:29 w python3.11[3180254]: from session not created: This version of ChromeDriver only supports Chrome version 120
`

I thought the 2 points I've addressed would definitely cover this, I don't understand how this could have happened. Is undetected-chromedriver using a ChromeDriver instance inside the script that automatically updates the driver and then EXPECTS the browser to be the same version ? 

if that's the case then how do I hold the version on it ?

**Comment by sdfgsdfgd** [comment]
this discussion thread seems to address it ?

https://github.com/ultrafunkamsterdam/undetected-chromedriver/discussions/1664

**Comment by lolren** [comment]
Just got the same issue now. I`m very happy to make it update manually, but for the moment I just need to make it rock solid. Having error at random times everytime Chrome needs to update is not fun :)

**Comment by ultrafunkamsterdam** [comment]
I don't manage ppa. LoL? You can use version_main=   in constructor

**Comment by sdfgsdfgd** [comment]
![pika](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/16299826/e17d8581-d420-4140-a71f-37ca4060744d)


> I don't manage ppa. LoL? You can use version_main= in constructor

that works the best ! awesome man
