### ISSUE TITLE
Headless mode

### ISSUE THREAD

**Issue by chemeng** [ultrafunkamsterdam/undetected-chromedriver#17]
hallo and goedenavond,

thanks for the repo, it's great. I got a question that is not really an issue but maybe you can help me. I'm trying to scrape a few websites that use distil network protection using your chromedriver and rotating proxies and I'm observing the following strange behavior: If I run the exact same code in headless mode I'm getting detected after a few webpages but if I run without headless on a regular display I don't get detected. Detection happens if I use a virtual display as well. 

Is there any test that can detect the presence of an actual display that's not patched yet? Or anything else you might think that could cause this?

Thanks

**Comment by ultrafunkamsterdam** [comment]
Pretty sure they can detect display resolution,pixel density and so on and using proxies is never a good idea tbh. Could you provide the <relevant> code u used?
