### ISSUE TITLE
mobile emulation not working

### ISSUE THREAD

**Issue by arthurmad** [ultrafunkamsterdam/undetected-chromedriver#170]
I'm facing this issue when I try to use mobile emulation with undetected chromedriver
**selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: unrecognized chrome option: mobileEmulation**

```
import undetected_chromedriver.v2 as uc
from selenium import webdriver
import time

options = webdriver.ChromeOptions()
mobile_emulation = { "deviceName": "Nexus 5" }
options.add_experimental_option("mobileEmulation", mobile_emulation)
driver = uc.Chrome(options=options)
driver.get('https://google.com')
time.sleep(120)
```

**Comment by ultrafunkamsterdam** [comment]
please check out:

https://www.google.com/search?q=unrecognized+chrome+option%3A+mobileEmulation

This seems not related to undetected-chromedriver itself.

**Comment by ultrafunkamsterdam** [comment]
https://github.com/SeleniumHQ/selenium/commit/a22d0fd220abf69e7ad32100f6f60a426dfba9c6

**Comment by wazoooo** [comment]
> [SeleniumHQ/selenium@a22d0fd](https://github.com/SeleniumHQ/selenium/commit/a22d0fd220abf69e7ad32100f6f60a426dfba9c6)

Actually, I tried it out with regular chromedriver, and it worked.

**Comment by wazoooo** [comment]
> please check out:
> 
> https://www.google.com/search?q=unrecognized+chrome+option%3A+mobileEmulation
> 
> This seems not related to undetected-chromedriver itself.

> [SeleniumHQ/selenium@a22d0fd](https://github.com/SeleniumHQ/selenium/commit/a22d0fd220abf69e7ad32100f6f60a426dfba9c6)

Actually, I tried it out with regular chromedriver, and it worked.

**Comment by m369848622** [comment]
me too

**Comment by kaliiiiiiiiii** [comment]
@arthurmad @wazoooo @m369848622 
you can use [Selenium_Profiles](https://github.com/kaliiiiiiiiii/Selenium-Profiles)
still in progress//working on btw
