### ISSUE TITLE
botprotect.io ask to disable extensions to verify device

### ISSUE THREAD

**Issue by SergeyDoronovych** [ultrafunkamsterdam/undetected-chromedriver#171]
Hello!

Thanks for the useful repo.

I had a problem when checking through botprtect.io:
![image](https://user-images.githubusercontent.com/14842141/117762184-57bbd000-b231-11eb-9af5-d4994f7de212.png)

The message asks to disable extensions that can interfere with scanning, but I use default uc configurations with the addition of one flag **--disable-dev-shm-usage**, which specifies to use the file system instead of RAM for general use. 

![image](https://user-images.githubusercontent.com/14842141/117762532-0829d400-b232-11eb-9c51-aa9ced1df0eb.png)

Please tell me what could be the problem.

**Comment by ultrafunkamsterdam** [comment]
this is not all of your code...


```python
import undetected_chromedriver.v2 as uc
driver = uc.Chrome()
with driver:
    driver.get('https://lhcdn.botprotect.io') 
```

**Comment by ultrafunkamsterdam** [comment]
NotProtect

![image](https://user-images.githubusercontent.com/21027969/118253717-885a6e80-b4aa-11eb-9878-3cedae6e8901.png)
