### ISSUE TITLE
Bug - Everything in the same folder as script will be deleted

### ISSUE THREAD

**Issue by Tony-PA-1** [ultrafunkamsterdam/undetected-chromedriver#173]
I was trying to use version 2 with proxies but it wouldn't work so I tried the following:
```
import undetected_chromedriver.v2 as uc2
import undetected_chromedriver as uc

options = uc.ChromeOptions()
options.add_argument("start-maximized")
options.add_argument(f'--proxy-server={PROXY}')
driver = uc2.Chrome(options=options)
```

If/when you run this chrome will close, a few exceptions will be thrown and everything in the same folder as the script will be deleted.

Reproduced this twice

**Comment by ultrafunkamsterdam** [comment]
1- update to latest version.
2 - do not import both v1 and v2. use either one of them but both have different default options.
