### ISSUE TITLE
not possible to set proxy with auth

### ISSUE THREAD

**Issue by merry75** [ultrafunkamsterdam/undetected-chromedriver#175]
chrome_options.add_argument(f'--proxy-server=http://{user}:{pw}@{proxy_host}:{proxy_port}') simply not working

**Comment by merry75** [comment]
or chrome_options.add_argument(f'--proxy-server=http://{proxy_host}:{proxy_port}') also not working

no idea what to do

**Comment by the-white-light** [comment]
I'm encountering the same issue. The only workaround I've found so far is to do this:
Download and extract the following extension: [MultiPass](https://chrome.google.com/webstore/detail/multipass-for-http-basic/enhldmjbphoeibbpdhmjkchohnidgnah) - [download extension](https://chrome-extension-downloader.com/)
```python
import undetected_chromedriver.v2 as webdriver
hst = "127.0.0.1"
prt = 42069
usr = "username"
pas = "password"
xid = "extension_id" #I don't know if there's a way to get this programmatically, so I found it manually
opt = webdriver.ChromeOptions()
opt.add_argument(f'--proxy-server=https://{hst}:{prt}')
opt.add_argument('--load-extension=./MultiPass')
driver = webdriver.Chrome(options=opt)
driver.get(f"chrome-extension://{xid}/options.html");
driver.find_element_by_id("url").send_keys('.'); # URLs are regex-matched, so . matches all
driver.find_element_by_id("username").send_keys(usr);
driver.find_element_by_id("password").send_keys(pas);
driver.find_element_by_class_name("credential-form-submit").click();
driver.get('https://httpbin.org/ip') # proxy IP
```

**Comment by HMaker** [comment]
Webdrivers actually can't interact with password filling boxes prompted by browser.

**Comment by ultrafunkamsterdam** [comment]
switch_to.<> ?

https://stackoverflow.com/questions/37989650/unable-to-set-prompt-box-value-using-selenium-chrome-driver
