### ISSUE TITLE
test website not working 

### ISSUE THREAD

**Issue by canarioPorCanarias** [ultrafunkamsterdam/undetected-chromedriver#1756]
the test website does not appear to have captcha https://nowsecure.nl
i can bypass with raw selenium
or event with raw http request
![image](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/45081046/625257ea-6e88-4e2a-9405-f91bf4ae1fe3)

**Comment by mdmintz** [comment]
Saw this a week ago in https://github.com/seleniumbase/SeleniumBase/issues/2501, but not everyone experienced it at that time. I think there's a limit as to how many times an IP Address can hit the Turnstile on that page before not hitting a Turnstile at all anymore.

Might be part of the Free / Tier 1 plan. After X number of Turnstiles, maybe there's an option for the website owner to either pay for more Turnstiles, or not have a Turnstile show at all anymore.

It's the same story if you have a security guard: You either pay the guard, or the guard goes away.
