### ISSUE TITLE
Prompted to make default browser and report faults. 

### ISSUE THREAD

**Issue by acryptopatriot** [ultrafunkamsterdam/undetected-chromedriver#179]
When using the undetected chromedriver in place of the selenium chromedriver. This blocks the webdriver. How do I prevent it from being displayed?

![image](https://user-images.githubusercontent.com/79184610/119246745-a890ca00-bb49-11eb-8025-01c0cecde1d2.png)

**Comment by srkeyan** [comment]
Same issue, feeling so bad

**Comment by ultrafunkamsterdam** [comment]
I'd start by trying one of there, especially the last one seems reasonable :) 
--disable-default-apps    --disable-extensions    --disable-infobars    --disable-notifications    --disable-password-generation --disable-password-manager-reauthentication    --disable-password-separated-signin-flow    --disable-popup-blocking    --disable-save-password-bubble    --disable-translate    --incognito    --mute-audio    --no-default-browser-check

**Comment by acryptopatriot** [comment]
How do you pass the --no-default-browser-check? And where did you find these switches?

**Comment by ultrafunkamsterdam** [comment]
just tested. this workds:

```python
import undetected_chromedriver.v2 as uc

o = uc.ChromeOptions()
o.user_data_dir = 'c:\\temp\\profile1'
o.add_argument('--no-default-browser-check')
driver = uc.Chrome(options=o)
```

**Comment by USTAADCOM** [comment]
@ultrafunkamsterdam First of thank you save my time. But I have another question it open my default profile but I also want it should display my extensions tab also as on my default browser profile.
