### ISSUE TITLE
Chromedriver detected

### ISSUE THREAD

**Issue by Zeprix** [ultrafunkamsterdam/undetected-chromedriver#1799]
![Capture](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/63049096/eb8794e0-bb29-4bac-a0f8-b383a7f540ee)
When trying to auto-checkout I seem to get detected by the captcha of Adyen checkout. I have tried to checkout on my normal browser and it worked. Also when I just launch the browser and go to checkout myself I still get detected.

**Comment by JakobReal-rgb** [comment]
Same Problem here. Is there a fix?
