### ISSUE TITLE
Google seems to be able to detect WebDriver usage somehow

### ISSUE THREAD

**Issue by jcastrejana** [ultrafunkamsterdam/undetected-chromedriver#18]
Hello!

This is a great project and seems to work great indeed for sites that use Distil etc, but, it seems that Google itself is able to detect it.

This can be observed by going to the Google login page at e.g. https://accounts.google.com/, entering a username, and clicking next. When the browser is being controlled by the Web Driver (even with the undetected-chromedriver) it will take you to a "This browser is not safe" page, and not allow you to login. 

Note that they seem to be using some kind of heuristic system to decide whether or not to block the login attempt, so when  trying to login to certain accounts, it will actually let you through (either with undetected-chromedriver or with the default one). In order to reproduce the issue it is thus best to pick an account at random (e.g., "randomaccount5", or any name that exists). 

Do you know how they could be detecting it, and/or whether it would also be possible to implement countermeasures with this project? 

I've tried to have a look at the Google login code without much luck (it's somewhat obfuscated and all), but you're definitely an expert at this.

Thanks & best regards!

**Comment by ultrafunkamsterdam** [comment]
Hi and thanks! This issue is discussed earlier so please check closed issues (for a workaround). However i dont know what you're up to with automation and google accounts , but take my word: dont even bother trying ;)
