### ISSUE TITLE
Nodriver: memory leak on Chromium 122.0.6261.128

### ISSUE THREAD

**Issue by nhanvu327** [ultrafunkamsterdam/undetected-chromedriver#1801]
The memory consumption increases over time through each URL until all memory (8GB) runs out, initially, my application only consumes around 500MB.

My machine: Raspberry Pi 4 with 8GB ram
OS: Ubuntu
Chromium version: 122.0.6261.128

**Comment by ultrafunkamsterdam** [comment]
how much time, how many urls?

**Comment by ultrafunkamsterdam** [comment]
code example?

**Comment by nhanvu327** [comment]
@ultrafunkamsterdam  have any ideas why it happens ?

**Comment by binhotvn** [comment]
lol thanks for the batdongsan.com.vn crawler code

**Comment by nhanvu327** [comment]
> lol thanks for the batdongsan.com.vn crawler code

you're welcome, do you have the memory leak issue ?

**Comment by nhanvu327** [comment]
Found the solution: close tabs regularly to clean up memory.
