### ISSUE TITLE
Nodriver: await browser.cookies.load() doesn't work

### ISSUE THREAD

**Issue by HaneulNakamoto** [ultrafunkamsterdam/undetected-chromedriver#1817]
browser = await start()
tab = await browser.get("https://site.com")
await browser.cookies.load()

nothing reload last login

**Comment by usr741852** [comment]
it's working for me. You need to save to a file path, then load from that file again. I  am not aware of being able to do this without specifying a file

**Comment by HaneulNakamoto** [comment]
> it's working for me. You need to save to a file path, then load from that file again. I am not aware of being able to do this without specifying a file

but on my end nothing happened. could you show little sample for me, btw I run on windows.

**Comment by usr741852** [comment]
I'm on windows too.

`import asyncio
import nodriver as uc
import time


async def main():
    browser = await uc.start()
    #after run the first time uncomment the line below and you will be logged in with the session file
    #browser.cookies.load("file=e:/twitter.session.data")
    page = await browser.get('https://www.twitter.com/') 
    print("sleep 60s")
    time.sleep(60)
    #here I manually logged in
    browser.cookies.save("file=e:/twitter.session.data")
    
if __name__ == '__main__':
    # since asyncio.run never worked (for me)
    uc.loop().run_until_complete(main())
    `

**Comment by HaneulNakamoto** [comment]
> I'm on windows too.
> 
> ```
> import asyncio
> import nodriver as uc
> import time
> 
> 
> async def main():
>     browser = await uc.start()
>     #after run the first time uncomment the line below and you will be logged in with the session file
>     #await browser.cookies.load(file="e:/twitter.session.data")
>     page = await browser.get('https://www.twitter.com/') 
>     print("sleep 60s")
>     time.sleep(60)
>     #here I manually logged in
>     await browser.cookies.save(file="e:/twitter.session.data")
>     
> if __name__ == '__main__':
>     # since asyncio.run never worked (for me)
>     uc.loop().run_until_complete(main())
> ```

let me check sir and thanks before

**Comment by ultrafunkamsterdam** [comment]
You should indeed save first before you can load. If no filename is specified it saves it in .session.dat

**Comment by HaneulNakamoto** [comment]
> You should indeed save first before you can load. If no filename is specified it saves it in .session.dat

work perfectly and smooth. btw great work legend

**Comment by marioeivissa** [comment]
AttributeError: module 'nodriver' has no attribute 'loop'

**Comment by OriolOrtiz** [comment]
> AttributeError: module 'nodriver' has no attribute 'loop' and also AttributeError: module 'nodriver' has no attribute 'start' anybody now the solution of this errors??

I know its late. But for people having same problem. Mine was becasue I named the script file as nodriver.py. That makes python try to import itself instead of the module so it says that there is no attribute. Try to change the script filename.
