### ISSUE TITLE
Error 1015

### ISSUE THREAD

**Issue by Connect55555** [ultrafunkamsterdam/undetected-chromedriver#1822]
IDK Why Its Show Ray ID: 87112b988bb74b53 "You are being rate limited What happened?
The owner of this website (example.com) has banned you temporarily from accessing this website."

**Comment by Connect55555** [comment]
![Screenshot 2024-04-08 163026](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/166381659/b878f49c-7a3f-430a-938a-a36ab21fae40)

**Comment by ultrafunkamsterdam** [comment]
It is exactly what it says. You made too many requests in certain timespan. Don't open issues for this

**Comment by huyumniy** [comment]
Don't know if this post will be relevant, but I had an issue with this 1015 error. If your script uses proxy or if you have a proxy extensions in browser then this may be the issue. You can use desktop vpn or desktop proxyswitcher to bypass it.
