### ISSUE TITLE
driver.quit() does not end the Chrome process fully

### ISSUE THREAD

**Issue by PostMalone** [ultrafunkamsterdam/undetected-chromedriver#1836]
For the past 2-3 days I've had this issue with Selenium + Undetectable ChromeDriver. Each time my Bot closes and opens Browser, the Chrome process in Task manager does not get "killed" fully, causing my CPU to spike all the way to 100% after 3-4 repeats. This started happening roughly 2 or 3 days ago. I have not done any changes to my code, neither did I update Chrome or anything.

Here's a part of my code responsible for Closing and Opening Browser:

    while True:
        try:
            twitter_bot.sendReply()

            # Increment the iteration count
            twitter_bot.iteration_count += 1

            # Check if the restart condition is met
            if twitter_bot.iteration_count >= twitter_bot.restart_interval:
                print(f'Restarting session after {twitter_bot.restart_interval} iterations...')
                twitter_bot.driver.quit()  # Close the current session
                time.sleep(twitter_bot.sleepTime * 2)
                twitter_bot = TwitterBot()  # Start a new session
                twitter_bot.iteration_count = 0

        except Exception as e:
            print(f'Something went wrong: {e}. Restarting browser session...')
            twitter_bot.driver.quit()  # Close the current session
            time.sleep(twitter_bot.sleepTime * 2)
            twitter_bot = TwitterBot()  # Start a new session
            time.sleep(twitter_bot.sleepTime * 2)

I'm closing "Current browser" after every 8 checks, Bot then opens the Browser again after some sleep time. However, when the Bot is closing the Browser, it does not kill the process, even though I'm using `driver.quit()` to do so.

Which then causes this:
![cFaPsca](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/33808805/2bb593c5-1862-4801-8ae1-a0d70e2ed046)

Does anyone have any idea what could be wrong? I also have `self.options.add_argument('--disable-gpu')` added.

**Comment by cbgz121** [comment]
set this option 
`option = uc.ChromeOptions()
option.add_argument("--disable-gpu")
driver = uc.Chrome(options=option)`

**Comment by PostMalone** [comment]
> set this option `option = uc.ChromeOptions() option.add_argument("--disable-gpu") driver = uc.Chrome(options=option)`

I tried that and it did not work. Chrome processes are still open in the background.
![19ELPGi](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/33808805/565d6050-08a8-4588-bd8a-2366c41c5127)

**Comment by cbgz121** [comment]
> > set this option `option = uc.ChromeOptions() option.add_argument("--disable-gpu") driver = uc.Chrome(options=option)`
> 
> I tried that and it did not work. Chrome processes are still open in the background. ![19ELPGi](https://private-user-images.githubusercontent.com/33808805/324429945-565d6050-08a8-4588-bd8a-2366c41c5127.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTc4NzgsIm5iZiI6MTcxMzc5NzU3OCwicGF0aCI6Ii8zMzgwODgwNS8zMjQ0Mjk5NDUtNTY1ZDYwNTAtMDhhOC00NTg4LWJkOGEtMjM2NmM0MWM1MTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE0NTI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNTY1YzYwNmM2Njk1NWNiZjU3YzUwZTA0ZjcwZjdiNWJkMjBlY2Y3ZjU0NGZhNzNmNjIyY2RhNGNiZjcyZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DAKbEr3hsY0kQVGy5k1U0nKjVIkE_wFRxYCCvJb5h4A)

you can try this #1767 #1723

**Comment by PostMalone** [comment]
Thank you for linking me https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1767#issuecomment-2016930462 

I "fixed" my problem with the help of their code.

Now after my Bot executes the driver.quit() - it also terminates the chrome.exe processes.

I fixed by adding this:

    def cleanup_processes(self):
        try:
           
            tasks = subprocess.check_output(['tasklist'], encoding='utf-8')

           
            if 'chrome.exe' in tasks:
                subprocess.run(["taskkill", "/F", "/IM", "chrome.exe", "/T"], check=True)
                logging.info("Chrome processes killed.")
            else:
                logging.info("No Chrome processes found.")

           
            if 'chromedriver.exe' in tasks:
                subprocess.run(["taskkill", "/F", "/IM", "chromedriver.exe", "/T"], check=True)
                logging.info("Chromedriver processes killed.")
            else:
                logging.info("No Chromedriver processes found.")

        except subprocess.CalledProcessError as e:
            logging.error(f"Error checking or killing processes: {e}")

And then:



    logging.basicConfig(filename='twitter_bot.log', level=logging.INFO, format='%(asctime)s - %(levelname)s: %(message)s')

    twitter_bot = TwitterBot()

    try:
        while True:
            twitter_bot.sendReply()

            # Increment the iteration count
            twitter_bot.iteration_count += 1

            # Check if the restart condition is met
            if twitter_bot.iteration_count >= twitter_bot.restart_interval:
                print(f'Restarting session after {twitter_bot.restart_interval} iterations...')
                twitter_bot.driver.quit()  # Close the current session
                time.sleep(twitter_bot.sleepTime * 2)
                twitter_bot.cleanup_processes()  # Cleanup Chrome and Chromedriver processes
                twitter_bot = TwitterBot()  # Start a new session
                twitter_bot.iteration_count = 0

    except Exception as e:
        logging.error(f'Something went wrong: {e}. Restarting browser session...')
        twitter_bot.driver.quit()  # Close the current session
        time.sleep(twitter_bot.sleepTime * 2)
        twitter_bot.cleanup_processes()  # Cleanup Chrome and Chromedriver processes
        twitter_bot = TwitterBot()  # Start a new session

**Comment by 0x1991** [comment]
The only way I fixed this issue was calling `close()` before `quit()` like:

```
driver.close()
driver.quit()
```

**Comment by kim-chung-man** [comment]
> The only way I fixed this issue was calling `close()` before `quit()` like:
> 
> ```
> driver.close()
> driver.quit()
> ```

I did as you suggested, but it didn't work.

Is there any other way other than forcefully terminating the process?
Does anyone know why this problem suddenly occurred?

**Comment by kim-chung-man** [comment]
> > The only way I fixed this issue was calling `close()` before `quit()` like:
> > ```
> > driver.close()
> > driver.quit()
> > ```
> 
> I did as you suggested, but it didn't work.
> 
> Is there any other way other than forcefully terminating the process? Does anyone know why this problem suddenly occurred?

There was something I missed. 
I tried following your advice and it worked. 
I searched and found that this bug occurred in Chrome version 124 or higher.

@0x1991 thank you
