### ISSUE TITLE
Add cookies to nodriver from httpx or requests

### ISSUE THREAD

**Issue by phaeton1199** [ultrafunkamsterdam/undetected-chromedriver#1837]
The documentation specifies how to use nodriver cookies in other libraries like requests. Could someone explain how to do the reverse process? That is, we obtain cookies from httpx or requests and load them into the nodriver browser. I have looked at the classes in core/browser.py and have not been able to load cookies in any way (set_all, load...).

**Comment by usr741852** [comment]
I just answered same question in a different issue

https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1838

**Comment by phaeton1199** [comment]
@usr741852 thank you so much for your help! I thought the issue was with how I was passing the cookies, and it turns out I was right. Thanks to your guidance, everything is working now.
