### ISSUE TITLE
SNKRS Infinite Loop Thingy

### ISSUE THREAD

**Issue by ralgorithms** [ultrafunkamsterdam/undetected-chromedriver#184]
Hello everyone, 

I am building or have built a sneaker buying bot for SNKRS. I have ran into a slight dilemma. An infinite loading screen when trying to sign-in. Now I know Akamai has been monitoring bot activity for Nike login requests and I have a theoretical solution (slightly tested) where I am thinking of using mechanical soup to login users and then some how passing the rest of the tasks to selenium. I have attached two videos showing the issue I am referring to and images of my setup and outputs (which shows no exceptions from selenium, just my except logic. 

I am using UC (since April), which was getting me through the login session request like butter at first but now it works here and there, but that's only because of the cookies I am feeding into selenium. Any ideas on how I can combat this issue? Your feedback will be appreciated. I want to keep using UC because this is an awesome repo!

https://user-images.githubusercontent.com/77365474/119419677-d05a6c00-bcc8-11eb-82e4-03527c5bc45a.mov

https://user-images.githubusercontent.com/77365474/119419689-d5b7b680-bcc8-11eb-9fab-deab9f0e057b.mov

![Screen Shot 2021-05-24 at 7 01 02 PM](https://user-images.githubusercontent.com/77365474/119419729-e5cf9600-bcc8-11eb-921d-f0c33db0400a.png)
![Screen Shot 2021-05-24 at 7 03 45 PM](https://user-images.githubusercontent.com/77365474/119419744-e9fbb380-bcc8-11eb-9b1a-a201779f7f71.png)

**Comment by ultrafunkamsterdam** [comment]
previously i encountered at logon a message "could not connect to server", while now i'm getting invalid username/pass, which i'm also getting in regular browser. Might be worth updating and trying again.

![image](https://user-images.githubusercontent.com/21027969/119609894-9f795480-bdf8-11eb-8fda-2909b3714322.png)

**Comment by ralgorithms** [comment]
Ok! Will give it a try. Thank you!

**Comment by david-jng** [comment]
I tried it and it didn't work. Could you try with valid login data @ultrafunkamsterdam ?

**Comment by ralgorithms** [comment]
@david-jng Yeah, didn't work for me neither. Creating a workaround now
