### ISSUE TITLE
How to default to a different browser than chrome? 

### ISSUE THREAD

**Issue by Zorral** [ultrafunkamsterdam/undetected-chromedriver#186]
I realized that this driver supports brave browser but was wondering how i could specify in my code to make it default to brave as opposed to chrome, any solutions? Thanks in advance!

**Comment by ultrafunkamsterdam** [comment]
Use ChromeOptions to set binary_location
```
options = uc.ChromeOptions()
options.binary_location = "C:/Program Files/Brave/xyz/abc/brave.exe" #use the path to brave
driver = uc.Chrome(options=options)
```

**Comment by Zorral** [comment]
thank you so much!

**Comment by Zorral** [comment]
im not 100% but i feel like the browser cache is getting wiped everytime i open it up, and thus the cookies, and already logged in accounts doesnt work, how could i fix that?
