### ISSUE TITLE
"Enhanced ad privacy in Chrome" pop-up

### ISSUE THREAD

**Issue by SgtSobieski** [ultrafunkamsterdam/undetected-chromedriver#1891]
Hi there,

I get the followig pop up and cant control them through that manuell technique which checks the browser informations ( I dont actually know how it is called).
(e.g.     def tryDismissGerPrivacyScroll(self):
        # Try to dimiss the privacy banner in Germany
         with contextlib.suppress(Exception):
            self.webdriver.find_element(By.ID, "viewManager").find_element(
                 By.ID, "moreButton").click()
)

This popup wont vanish automatically and creates itself on each new instance if no choice has been made. I found this issue also described here [https://github.com/seleniumbase/SeleniumBase/issues/2201](url), but dont know if I could merge this information with this repository. Any help what I could do, where I could research or similar are much appreciated!

![privacy](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/125480018/3b0f277d-580e-4f7d-aba5-a11ea7ce4bc6)
![privacy2](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/125480018/ad03af37-fa1a-4b4a-bb16-caa009054151)

**Comment by ronakpp** [comment]
Try this: chrome_options.add_argument('--disable-features=PrivacySandboxSettings4')

**Comment by SgtSobieski** [comment]
> Try this: chrome_options.add_argument('--disable-features=PrivacySandboxSettings4')

Exactly. Thanks!
