### ISSUE TITLE
Patch remote selenium

### ISSUE THREAD

**Issue by ggalan87** [ultrafunkamsterdam/undetected-chromedriver#19]
Hello and thank you for the great project. Patching perfectly bypasses the detection in my use case. However I also use the Remote class to connect to the remote selenium standalone server. I assume something similar to what is done in the function patch_selenium_webdriver needs to be done explicitly in  corresponding [source code](https://github.com/SeleniumHQ/selenium/tree/master/java/server/src/org/openqa/selenium/remote/server). Am I correct? Do you have any indication what needs to be modified?

**Comment by ultrafunkamsterdam** [comment]
Hi @ggalan87 , i am not familiar with the selenium standalone server. But i assume the server is meant so you can control the driver remotely. so you have to find out where the chromedriver binary is, which is being used by server, and patch it.. or replace :)

**Comment by ggalan87** [comment]
Yes, I already had patched the corresponding binary but I think I need to also modify the server's code with stuff that you do in https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/9d7259b46df0f75abfe15a7be7d2b9b924c0de00/undetected_chromedriver/__init__.py#L50 I think that it can't be done exclusively with its command line parameters.

**Comment by ggalan87** [comment]
Or maybe not, since setup of the remote for the case of ChromeDriver is in the python side as it is mentioned in the [docs](https://github.com/SeleniumHQ/selenium/wiki/RemoteWebDriver#remotewebdriver-modes). I will test it and report back.
