### ISSUE TITLE
AttributeError: module 'subprocess' has no attribute 'CREATE_NEW_PROCESS_GROUP'

### ISSUE THREAD

**Issue by tonko22** [ultrafunkamsterdam/undetected-chromedriver#190]
Using ubuntu 18.04 and Python 3.7.0 got this error while executing `driver = uc.Chrome()`:

```
undetected_chromedriver/v2.py in __init__(self, executable_path, port, options, enable_cdp_events, service_args, desired_capabilities, service_log_path, keep_alive, log_level, headless, delay)
    271             stdout=subprocess.PIPE,
    272             stderr=subprocess.PIPE,
--> 273             creationflags=subprocess.CREATE_NEW_PROCESS_GROUP,
    274             close_fds=True,
    275         )
```

**`AttributeError: module 'subprocess' has no attribute 'CREATE_NEW_PROCESS_GROUP'`**

Google got me to https://www.reddit.com/r/learnpython/comments/3c5nty/why_isnt_this_subprocess_constant_importing/cssgvu2?utm_source=share&utm_medium=web2x&context=3 from which i can conclude undetected-chromedriver is not supported on unix systems. Is that correct and if yes, will there be a unix version of undetected-chromedriver?

**Comment by ultrafunkamsterdam** [comment]
This is already fixed, but need to push it, which i will do - combined - . You can update now using `pip install -U git+https://github.com/ultrafunkamsterdam/undetected-chromedriver`
