### ISSUE TITLE
"Choose your search engine" popup 

### ISSUE THREAD

**Issue by SgtSobieski** [ultrafunkamsterdam/undetected-chromedriver#1918]
Hi,

since some weeks I got these popups coming up. Does anyone know how it would be possible to turn them off?

![337196793-99f6cd38-328f-4775-b5ac-3b2593b8156c](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/125480018/9ccce9b4-f825-4981-b6b9-3854b573c8d7)
![337196880-031de0bc-a3d9-4162-9055-3e740c39815b](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/125480018/8eaf1368-bc4b-470b-b8f7-1f12cc4ebf6c)

Has been an topic here: https://support.google.com/chrome/thread/278310235/choose-your-search-engine-pop-up-shown-while-default-engine-is-already-chosen?hl=en

Thanks in advance!

**Comment by sayfamedall** [comment]
https://stackoverflow.com/questions/78787332/selecting-default-search-engine-is-needed-for-chrome-version-127

**Comment by SgtSobieski** [comment]
> https://stackoverflow.com/questions/78787332/selecting-default-search-engine-is-needed-for-chrome-version-127

With the essence of the answer, quoted from stackoverflow:

Just need to add this Chrome Options:
options.addArguments("--disable-search-engine-choice-screen");

If you are using selenium with python, you have to use:
options.add_argument("--disable-search-engine-choice-screen")
