### ISSUE TITLE
[NODRIVER] VERY IMPORTANT MEMORY LEAK FIX

### ISSUE THREAD

**Issue by zxsleebu** [ultrafunkamsterdam/undetected-chromedriver#1922]
@ultrafunkamsterdam i have **found a fix** for the **memory leak** everybody was experiencing.
here is the link to my comment in another issue. i hope you'll take a look at this
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1851#issuecomment-2167380451
only 1 missing line of code causes memory leak

**Comment by jwwq** [comment]
Thank you so much, man, for that fix! I just encountered a memory leak in a method and had to use a dirty hack with a run in multiprocessing. Without much hope, I entered nodriver and found your solution in capslock. Thanks!!!

**Comment by jwwq** [comment]
Thank you so much, man, for that fix! I'm really tired of the fact that parsing a few hundred pages completely drains memory, and today I was forced to use a dirty hack with running nodriver in separate process to completely clear memory. Without much hope, I entered "nodriver memory leak" and found your solution that you posted just two days ago! God bless you!

**Comment by zxsleebu** [comment]
> Thank you so much, man, for that fix!
> I'm really tired of the fact that parsing a few hundred pages completely drains memory. Today I've narrowed down the leak to tab.query_selector (and hence to CDP call that returns items), but tired as hell, used a dirty hack with running nodriver in separate process to completely clear memory, did a reprex for the bug report, and without much hope, I entered "nodriver memory leak" and found your solution that you posted **just two days ago**! What a happy coincidence!
> 
> God bless you!

I'm glad I helped you and I really hope that the lead developer pushes this fix ASAP. thank you for the kind words!

**Comment by FDDQA** [comment]
Thanks a lot for the fix! The memory leak remains if you restart the browser. For each restart of the browser, about 100mb goes away.

**Comment by FDDQA** [comment]
Fortunately, this fix doesn't work. I also tried using a temporary file and adding a line to the library file - each time a browser.get(url) consumes about 100 KB. Also didn't help: page.close, page del, gc.collect(), etc.

**Comment by ultrafunkamsterdam** [comment]
this is implemented. thanks @zxsleebu

**Comment by zxsleebu** [comment]
> this is implemented. thanks @zxsleebu 

glad that you approved this fix. thanks for the library!
