### ISSUE TITLE
[NODRIVER] Cross-origin iframes not working

### ISSUE THREAD

**Issue by RandomStrangerOnTheInternet** [ultrafunkamsterdam/undetected-chromedriver#1928]
Hello, currently it seems that cross-origin iframes are not interactable by `select_all`, `find`. Would love to be able to interact with this, and I'm hoping someone is able to provide some assistance with this (I've checked all current issues, but I was not able to find a solution that works).

Below is a code-snippet in order to reproduce this.

```
import nodriver
import os


async def main():
	config = nodriver.Config()
	config.add_argument('--disable-web-security')
	config.user_data_dir = os.path.join(os.getcwd(), 'test')
	browser = await nodriver.start(config=config)

	page = await browser.get('https://csreis.github.io/tests/cross-site-iframe.html')

	cross_site_button = await page.find("Go cross-site (complex page)", best_match=True)
	await cross_site_button.mouse_click()

	search = await page.select_all('p', include_frames=True)
	print('Total number of p tags:', len(search))

	await page.sleep(60 * 60)


if __name__ == "__main__":
	nodriver.loop().run_until_complete(main())
```

**Comment by RandomStrangerOnTheInternet** [comment]
Does anyone happen to have a solution regarding this?

**Comment by pythonlw** [comment]
`import json
from nodriver import start, cdp, loop
import nodriver as uc

async def switch_to_frame(browser, frame):
    """
    change iframe
    let iframe = document.querySelector("YOUR_IFRAME_SELECTOR")
    let iframe_tab = iframe.contentWindow.document.body;
    """
    iframe_tab: uc.Tab = next(
            filter(
                lambda x: str(x.target.target_id) == str(frame.frame_id), browser.targets
            )
        )
    return iframe_tab


async def main():
    browser_args = ['--disable-web-security']
    browser = await uc.start(browser_args=browser_args)
    tab = browser.main_tab
    tab = await browser.get("http://www.yescaptcha.cn/auth/login")
    for _ in range(10):
        await tab.scroll_down(50)
    await tab
    await tab.sleep(15)

    #solve Ordinary iframe
    # query_selector = await tab.select_all('button[class="widgetLabel moveFromRightLabel-enter-done"]', include_frames=True)
    # print('query_selector:', query_selector)
    # if len(query_selector) == 1:
    #     await query_selector[0].click()
   
    #solve  Cross-origin iframe
    recaptcha0 = await tab.select('iframe[title="reCAPTCHA"]')
    print('recaptcha0:', recaptcha0.frame_id)
    # # for tar in browser.targets:
    # #     print('target_id:', tar.target.target_id)
    iframe_tab = await switch_to_frame(browser, recaptcha0)
    print('iframe_tabwebsocket_url:', iframe_tab.websocket_url)
    iframe_tab.websocket_url = iframe_tab.websocket_url.replace("iframe", "page")
    button = await iframe_tab.select("span#recaptcha-anchor")
    await button.click()
    input('stop')



if __name__ == "__main__":
    loop().run_until_complete(main())`

**Comment by pythonlw** [comment]
![image](https://github.com/user-attachments/assets/a6a491fc-5d33-469e-a025-ece109e09b27)

**Comment by ultrafunkamsterdam** [comment]
``` browser = await start(browser_args=['--disable-web-security', '--disable-site-isolation-trials']) ```

**Comment by fred-bao** [comment]
The problem is iframe is not in browser.targets, so that it can not be shifted, how this can be fixed?

**Comment by RandomStrangerOnTheInternet** [comment]
Even with the `--disable-site-isolation-trials` I'm getting the same results, it's not finding the `p` tags inside of the `iframe`.
