### ISSUE TITLE
[nodriver] Handling of CDP commands that don't have a corresponding response message in protocol (hangs indefinitely)

### ISSUE THREAD

**Issue by epicwhale** [ultrafunkamsterdam/undetected-chromedriver#1973]
I've noticed that certain CDP commands, like [cdp.fetch.continue_request](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#method-continueRequest), don't trigger a corresponding response message from the browser.

This causes the `await tx` at https://github.com/ultrafunkamsterdam/nodriver/blob/main/nodriver/core/connection.py#L411 to hang indefinitely - it's never resolved after the socket message is sent in `.send(..)`. As shown in an example in: https://github.com/ultrafunkamsterdam/undetected-chromedriver/discussions/1972

To address this, I think it would be very useful to have a way to send a CDP command without waiting for a transaction response or acknowledgement (via 'id' mapping) after the websocket.send(tx.message).

What do you think? cc: @ultrafunkamsterdam hope my evaluation here is accurate!

**Potential solutions:**

1. Modify the send(..) function to have an `_expects_response = True` which if False, skips adding the transaction to the transaction `mapper` and `return None` after websocket.send

```python
    async def send(
        self, cdp_obj: Generator[dict[str, Any], dict[str, Any], Any], _is_update=False,
        _expects_response = True # <--- set to False if the command isn't expected to have any response msg
    ) -> Any:
       # .... 
            if _expects_response: 
                self.mapper.update({tx.id: tx})

       # .... 
            await self.websocket.send(tx.message)

       # .... 

            if not _expects_response:
                return None
```

2. Find some way to reflect this behavior in Transaction class or CDP object, and modify how send(..) handles it: I wasn't sure how to identify which CDP commands fall under this behavior, or identify a different signature for such commands in the generated type wrappers for the commands. 
For example page.reload `-> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:` has the same return type as fetch.continue_request `-> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:

**Comment by epicwhale** [comment]
@sohaib17 that's a good shout actually! will play around with your approach instead. thanks :)

**Comment by ultrafunkamsterdam** [comment]
> I've noticed that certain CDP commands, like [cdp.fetch.continue_request](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#method-continueRequest), don't trigger a corresponding response message from the browser.
> 
> This causes the `await tx` at https://github.com/ultrafunkamsterdam/nodriver/blob/main/nodriver/core/connection.py#L411 to hang indefinitely - it's never resolved after the socket message is sent in `.send(..)`. As shown in an example in: #1972
> 
> To address this, I think it would be very useful to have a way to send a CDP command without waiting for a transaction response or acknowledgement (via 'id' mapping) after the websocket.send(tx.message).
> 
> What do you think? cc: @ultrafunkamsterdam hope my evaluation here is accurate!
> 
> **Potential solutions:**
> 
> 1. Modify the send(..) function to have an `_expects_response = True` which if False, skips adding the transaction to the transaction `mapper` and `return None` after websocket.send
> 
> ```python
>     async def send(
>         self, cdp_obj: Generator[dict[str, Any], dict[str, Any], Any], _is_update=False,
>         _expects_response = True # <--- set to False if the command isn't expected to have any response msg
>     ) -> Any:
>        # .... 
>             if _expects_response: 
>                 self.mapper.update({tx.id: tx})
> 
>        # .... 
>             await self.websocket.send(tx.message)
> 
>        # .... 
> 
>             if not _expects_response:
>                 return None
> ```
> 
> 2. Find some way to reflect this behavior in Transaction class or CDP object, and modify how send(..) handles it: I wasn't sure how to identify which CDP commands fall under this behavior, or identify a different signature for such commands in the generated type wrappers for the commands.
>    For example page.reload `-> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:` has the same return type as fetch.continue_request `-> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:

No. You always get a response, but it's None . If there is no response at all, it will hang , but then you sent a malfunction command
