### ISSUE TITLE
Wrong Version Download

### ISSUE THREAD

**Issue by dickermoshe** [ultrafunkamsterdam/undetected-chromedriver#198]
After installing, I'm getting this error

`...super().start_session(capabilities, browser_profile)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException:`

`Message: unknown error: cannot connect to chrome at 127.0.0.1:54960
from session not created: This version of ChromeDriver only supports Chrome version 91
Current browser version is 90.0.4430.212`

I currently have Chrome v90. However shouldn't "undetected-chromedriver" be installing the correct version for my system ?
If "undetected-chromedriver" is only compatible for v91 it should be in the docs.

**Comment by ultrafunkamsterdam** [comment]
`driver = uc.Chrome(version_main=90)`

**Comment by Kzapas** [comment]
This does not work. Even after installing directly from the github repository and rewriting the executable path to the newest chromedriver.

**Comment by ultrafunkamsterdam** [comment]
Do not specify path to chromedriver. Just use driver=uc.Chrome(version_main=90) and if that "not working",  use
 `driver = uc.Chrome(version_main=90, patcher_force_close=True)
`

**Comment by Kzapas** [comment]
Thanks. Seems to be working now.

**Comment by dickermoshe** [comment]
Thanks
