### ISSUE TITLE
[nodriver] open mozila firefox  with strong protection (a different fingerprint every time you start it)

### ISSUE THREAD

**Issue by Deswer60871** [ultrafunkamsterdam/undetected-chromedriver#1983]
Good day, I would like to ask if there is any possibility to open Mozilla Firefox or Brave so that the browser fingerprints change with each launch. These browsers have this protection built-in, but Selenium is detected, so I would really appreciate it if it could be run in Nodriver as well. I have a problem getting data precisely because of the fingerprints.

**Comment by Aperico-com** [comment]
Did you find an answer to this? I would also like to use Firefox instead of Chrome so I would appreciate if you wanted to share your findings.

**Comment by mighty-phoenix** [comment]
+1 @Deswer60871

**Comment by castilla204** [comment]
Any solution for this?

**Comment by zerxdapro** [comment]
any solution?
