### ISSUE TITLE
[nodriver] interacting with cloudflare iframe

### ISSUE THREAD

**Issue by the-Jamz** [ultrafunkamsterdam/undetected-chromedriver#1998]
Hi, I'm trying to simulate a click on the cloudflare challenge.

When I create the browser I run:
```python
options.add_argument("--disable-web-security")
options.add_argument("--disable-site-isolation-trials")
...

await self.browser.main_tab.send(
    cdp.page.enable()
)
await self.browser.main_tab.send(
    cdp.page.add_script_to_evaluate_on_new_document(
        source="""
        Element.prototype._as = Element.prototype.attachShadow;
        Element.prototype.attachShadow = function (params) {
            return this._as({mode: "open"})
        };"""
    )
)

# Method 1: works but yields `cdp.runtime.RemoteObject`, which I'm not sure how to interact with
shadow_element = await driver.main_tab.send(cdp.runtime.evaluate("document.querySelector('div:not(:has(div))').shadowRoot.firstChild;"))

# Method 2: both find nothing
iframes = await tab.query_selector("iframe")
iframes = await tab.select("iframe")

# Method 3: yields frame data but not sure how to use the `id` or `loaderId`
frame_data = await driver.main_tab.send(cdp.page.get_frame_tree())
```

I've seen people switch to an element, but how can I get an element out of these? Or why does the query selector not find them?

**Comment by the-Jamz** [comment]
To add more detail, specifically I'm wondering how I can do the equivalent of switching to the iframe; or interact with it as a tag? Trying to emulate the solution proposed here: https://github.com/FlareSolverr/FlareSolverr/pull/1272/files

**Comment by devblack** [comment]
> To add more detail, specifically I'm wondering how I can do the equivalent of switching to the iframe; or interact with it as a tag? Trying to emulate the solution proposed here: https://github.com/FlareSolverr/FlareSolverr/pull/1272/files

def switch_frame(browser, iframe) -> Tab:
    iframe: Tab = next(
        filter(
            lambda x: str(x.target.target_id) == str(iframe.frame_id), browser.targets
        )
    )
    iframe.websocket_url = iframe.websocket_url.replace("iframe", "page")
    return iframe

**Comment by the-Jamz** [comment]
Thanks for your reply @devblack, but I haven't seen anything named `shadow_roots`, only the `shadowRoots` through the JS which I already get.

This as mentioned yields a `RemoteObject`: `RemoteObject(type_='object', subtype='node', class_name='HTMLIFrameElement', value=None, unserializable_value=None, description='iframe#cf-chl-widget-g8h42', deep_serialized_value=None, object_id=RemoteObjectId('7857353671971129384.1.1'), preview=None, custom_preview=None)`.

Which doesn't have a frame_id and therefore doesn't work with the function, is this what you meant or am I missing something?

**Comment by ultrafunkamsterdam** [comment]
``` 
>>> from nodriver import *
>>> browser = await start(browser_args=['--disable-web-security', '--disable-site-isolation-trials'])
>>> tab = browser.tabs[0]
>>> await tab.get('https://dash.cloudflare.com')
>>> await ( await tab.find('Accept all') ).click()
>>> elems = await tab.query_selector_all('*')
>>> elems_with_shadow_roots = [e for e in elems if e.shadow_roots]
>>> elems_with_shadow_roots[0].shadow_roots
<<<outputs shadow roots for element 0>>>

## however interacting with it it still hard

``` 

A remote object can be resolved to an Node using ```await tab.send(cdp.dom.resolve_node(object_id=someremoteobject.object_id))```

**Comment by the-Jamz** [comment]
Thanks for the advice! This indeed does allow me to get an iframe element, but the tab switching recommended by @devblack doesn't work, I believe because I cannot see the iframe in the browser targets.

Any further advice on how to actually interact with the iframe would be great, I'm just trying to get the position to offset the mouse and perform a click, but not having any luck resolving the position from outside the iframe.

**Comment by mdmintz** [comment]
Getting the position of the element **above** the iframe is no problem (see https://stackoverflow.com/q/42807676/7058266), but since the iframe is hidden behind Shadow-DOM, you'll have to estimate the missing variables (the location of the checkbox relative to the iframe).

The checkbox is in the same place for all Cloudflare iframes (they haven't moved it), so you can use `(40, 40)` for the location of the center of the checkbox relative to the top left coordinates of the element that contains the iframe. Then use `PyAutoGUI` to click the checkbox with the mouse from your `nodriver` / `undetected-chromedriver` window. (I combined `undetected-chromedriver` with `PyAutoGUI` in my framework to do this.)

**Comment by the-Jamz** [comment]
@devblack 
> It works. You have to create a element for the iframe:
> 
> ```python
>         # wait for turnstile
>         await tab.wait(1.7)
> 
>         div_host: Element = await tab.select("div[style*=border]")
>         shadow_roots: Node = div_host.shadow_roots[0]
>         iframe: Node = shadow_roots.children[0]
>         iframe: Element = element.create(iframe, tab, iframe.content_document)
> 
>         iframe: Tab = switch_frame(browser, iframe)
>         # await iframe_tab.get_content()
>         
>         div_host: Element = await iframe.select("body")
>         shadow_roots: Node = div_host.shadow_roots[0]
>         # div => main-wrapper
>         div_: Node = shadow_roots.children[1]
> 
>         wrapper: Element = element.create(div_, iframe, div_.content_document)
>         ## now you can find the input and use mouse_click()
> ```

Thanks again for taking the time but I still have the same issue, the `switch_frame` method errors, presumably because the iframe isn't in the browser targets. It does form the element eg:
```
<iframe src="https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/turnstile/if/ov2/av0/rcv0/0/mmjtr/0x4AAAAAAADnPIDROrmt1Wwj/dark/fbE/normal/auto/" allow="cross-origin-isolated; fullscreen; autoplay" sandbox="allow-same-origin allow-scripts allow-popups" id="cf-chl-widget-mmjtr" tabindex="0" title="Widget containing a Cloudflare security challenge" style="border: none; overflow: hidden; width: 300px; height: 65px;"></iframe>
```

**Comment by the-Jamz** [comment]
> Getting the position of the element **above** the iframe is no problem (see https://stackoverflow.com/q/42807676/7058266), but since the iframe is hidden behind Shadow-DOM, you'll have to estimate the missing variables (the location of the checkbox relative to the iframe).
> 
> The checkbox is in the same place for all Cloudflare iframes (they haven't moved it), so you can use `(40, 40)` for the location of the center of the checkbox relative to the top left coordinates of the element that contains the iframe. Then use `PyAutoGUI` to click the checkbox with the mouse from your `nodriver` / `undetected-chromedriver` window. (I combined `undetected-chromedriver` with `PyAutoGUI` in my framework to do this.)

Thanks for the suggestions; I've seen some other guys using PyAutoGUI but I'm trying to avoid doing so, as I'm running multiple instances on a remote linux machine I only access via SSH.

**Comment by devblack** [comment]
> Thanks again for taking the time but I still have the same issue, the `switch_frame` method errors, presumably because the iframe isn't in the browser targets. It does form the element eg:
> 

You're doing something wrong. Please share a sample of your code.

**Comment by the-Jamz** [comment]
```python
import nodriver as uc
from nodriver import cdp, Element
from nodriver.core.tab import Tab
from nodriver.core.element import Position, create as create_element
from nodriver.core import element
from nodriver.cdp.dom import Node

def switch_frame(browser, iframe) -> uc.Tab:
    iframe: uc.Tab = next(
        filter(
            lambda x: str(x.target.target_id) == str(iframe.frame_id), browser.targets
        )
    )
    iframe.websocket_url = iframe.websocket_url.replace("iframe", "page")
    return iframe

async def click_verify(driver: uc.Browser):
    try:
        tab = driver.main_tab
        div_host: Element = await tab.select("div[style*=border]")
        shadow_roots: Node = div_host.shadow_roots[0]
        iframe: Node = shadow_roots.children[0]
        iframe: Element = element.create(iframe, tab, iframe.content_document)
        await asyncio.sleep(1)
        logging.info("iframe: %s", iframe)

        iframe: Tab = switch_frame(driver, iframe)
        # await iframe_tab.get_content()
        logging.info("formed tab")
        
        div_host: Element = await iframe.select("body")
        shadow_roots: Node = div_host.shadow_roots[0]
        # div => main-wrapper
        div_: Node = shadow_roots.children[1]
        wrapper: Element = element.create(div_, iframe, div_.content_document)
        cf_input = (await wrapper.query_selector_all("input"))[0]
        await cf_input.mouse_click()
    except Exception as e:
        logging.error("couldn't click button: %s", e)
        await asyncio.sleep(600)
```

**Comment by devblack** [comment]
> Will put together a full snipped in the morning, thanks again for the help.

```bash
[2024-08-28]::INFO # created process with pid 29233 
[2024-08-28]::INFO # enabling autodiscover targets
[2024-08-28]::INFO # iframe: <iframe src="https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/turnstile/if/ov2/av0/rcv0/0/t8roz/0x4AAAAAAAAjq6WYeRDKmebM/light/fbE/normal/auto/" allow="cross-origin-isolated; fullscreen; autoplay" sandbox="allow-same-origin allow-scripts allow-popups" id="cf-chl-widget-t8roz" tabindex="0" title="Widget containing a Cloudflare security challenge" style="border: none; overflow: hidden; width: 300px; height: 65px;"></iframe>
[2024-08-28]::INFO # formed tab
[2024-08-28]::INFO # input found
[2024-08-28]::INFO # input clicked
[2024-08-28]::INFO # getting page content...
[2024-08-28]::INFO # <html><head></head><body>No input file specified.
</body></html>
```

Works correctly on https://forum.cfcybernews.eu/

```python
from nodriver import Tab, cdp, Element, Browser, start
from nodriver.core import element
from nodriver.cdp.dom import Node
from logging import basicConfig, INFO, getLogger
from asyncio import run

# Configure logging
basicConfig(format=u'[%(asctime)s]::%(levelname)s # %(message)s', level=INFO)
# instance logger to var
logging = getLogger(__name__)

def switch_frame(browser, iframe) -> Tab:
    iframe: Tab = next(
        filter(
            lambda x: str(x.target.target_id) == str(iframe.frame_id), browser.targets
        )
    )
    iframe.websocket_url = iframe.websocket_url.replace("iframe", "page")
    return iframe

async def click_verify(browser: Browser, tab: Tab):
    try:
        await tab.wait(1.7)

        div_host: Element = await tab.select("div[style*=border]")
        shadow_roots: Node = div_host.shadow_roots[0]
        iframe: Node = shadow_roots.children[0]
        iframe: Element = element.create(iframe, tab, iframe.content_document)
        await tab.sleep(1)
        logging.info("iframe: %s", iframe)

        iframe: Tab = switch_frame(browser, iframe)
        # await iframe_tab.get_content()
        logging.info("formed tab")
        await tab.sleep(1.3)
        div_host: Element = await iframe.select("body")
        shadow_roots: Node = div_host.shadow_roots[0]
        # div => main-wrapper
        div_: Node = shadow_roots.children[1]
        wrapper: Element = element.create(div_, iframe, div_.content_document)
        
        cf_input = await wrapper.query_selector("div label.cb-lb > input")
        cf_input = await wrapper.query_selector("div label.cb-lb > input")
        logging.info("input found")

        await cf_input.mouse_click()
        logging.info("input clicked")

        logging.info("getting page content...")
        await tab.sleep(3)
        logging.info(await tab.get_content())
        
    except Exception as e:
        #logging.error("couldn't click button: %s", e)
        pass


async def main():
    browser = await start(
        headless=False,
        browser_executable_path="/usr/bin/chromium",
        lang="en-GB"
    )

    tab = browser.main_tab

    await tab.send(cdp.page.add_script_to_evaluate_on_new_document(
        source="""
            Element.prototype._as = Element.prototype.attachShadow;
            Element.prototype.attachShadow = function (params) {
                return this._as({mode: "open"})
            };
        """
    ))

    tab = await browser.get("https://forum.cfcybernews.eu/")

    await click_verify(browser, tab)


if __name__ == "__main__":
    run(main())
```

**Comment by the-Jamz** [comment]
@devblack Thanks again for all the help. You are indeed correct. It was the:
`options.add_argument("--disable-site-isolation-trials")` breaking this for me (which I pulled from different issues trying to solve this problem).

**Comment by bbszt** [comment]
> > Will put together a full snipped in the morning, thanks again for the help.
> 
> [2024-08-28]::INFO # created process with pid 29233 
> [2024-08-28]::INFO # enabling autodiscover targets
> [2024-08-28]::INFO # iframe: <iframe src="https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/turnstile/if/ov2/av0/rcv0/0/t8roz/0x4AAAAAAAAjq6WYeRDKmebM/light/fbE/normal/auto/" allow="cross-origin-isolated; fullscreen; autoplay" sandbox="allow-same-origin allow-scripts allow-popups" id="cf-chl-widget-t8roz" tabindex="0" title="Widget containing a Cloudflare security challenge" style="border: none; overflow: hidden; width: 300px; height: 65px;"></iframe>
> [2024-08-28]::INFO # formed tab
> [2024-08-28]::INFO # input found
> [2024-08-28]::INFO # input clicked
> [2024-08-28]::INFO # getting page content...
> [2024-08-28]::INFO # <html><head></head><body>No input file specified.
> </body></html>
> Works correctly on https://forum.cfcybernews.eu/
> 
> from nodriver import Tab, cdp, Element, Browser, start
> from nodriver.core import element
> from nodriver.cdp.dom import Node
> from logging import basicConfig, INFO, getLogger
> from asyncio import run
> 
> # Configure logging
> basicConfig(format=u'[%(asctime)s]::%(levelname)s # %(message)s', level=INFO)
> # instance logger to var
> logging = getLogger(__name__)
> 
> def switch_frame(browser, iframe) -> Tab:
>     iframe: Tab = next(
>         filter(
>             lambda x: str(x.target.target_id) == str(iframe.frame_id), browser.targets
>         )
>     )
>     iframe.websocket_url = iframe.websocket_url.replace("iframe", "page")
>     return iframe
> 
> async def click_verify(browser: Browser, tab: Tab):
>     try:
>         await tab.wait(1.7)
> 
>         div_host: Element = await tab.select("div[style*=border]")
>         shadow_roots: Node = div_host.shadow_roots[0]
>         iframe: Node = shadow_roots.children[0]
>         iframe: Element = element.create(iframe, tab, iframe.content_document)
>         await tab.sleep(1)
>         logging.info("iframe: %s", iframe)
> 
>         iframe: Tab = switch_frame(browser, iframe)
>         # await iframe_tab.get_content()
>         logging.info("formed tab")
>         await tab.sleep(1.3)
>         div_host: Element = await iframe.select("body")
>         shadow_roots: Node = div_host.shadow_roots[0]
>         # div => main-wrapper
>         div_: Node = shadow_roots.children[1]
>         wrapper: Element = element.create(div_, iframe, div_.content_document)
>         
>         cf_input = await wrapper.query_selector("div label.cb-lb > input")
>         cf_input = await wrapper.query_selector("div label.cb-lb > input")
>         logging.info("input found")
> 
>         await cf_input.mouse_click()
>         logging.info("input clicked")
> 
>         logging.info("getting page content...")
>         await tab.sleep(3)
>         logging.info(await tab.get_content())
>         
>     except Exception as e:
>         #logging.error("couldn't click button: %s", e)
>         pass
> 
> 
> async def main():
>     browser = await start(
>         headless=False,
>         browser_executable_path="/usr/bin/chromium",
>         lang="en-GB"
>     )
> 
>     tab = browser.main_tab
> 
>     await tab.send(cdp.page.add_script_to_evaluate_on_new_document(
>         source="""
>             Element.prototype._as = Element.prototype.attachShadow;
>             Element.prototype.attachShadow = function (params) {
>                 return this._as({mode: "open"})
>             };
>         """
>     ))
> 
>     tab = await browser.get("https://forum.cfcybernews.eu/")
> 
>     await click_verify(browser, tab)
> 
> 
> if __name__ == "__main__":
>     run(main())

run with exception, looks like div_host dose not parse right
shadow_roots: Node = div_host.shadow_roots[0]
                         ~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by boludoz** [comment]
That is the key

```
def switch_frame(browser, iframe) -> Tab:
    iframe: Tab = next(
        filter(
            lambda x: str(x.target.target_id) == str(iframe.frame_id), browser.targets
        )
    )
    iframe.websocket_url = iframe.websocket_url.replace("iframe", "page")
    return iframe
```

and always use select.
