### ISSUE TITLE
Chrome freezes after about 10 seconds of launching

### ISSUE THREAD

**Issue by unlucky-kit** [ultrafunkamsterdam/undetected-chromedriver#2002]
A month or so back, on my mac undetected_chromedriver started freezing consistently after about 10 seconds and became unusable. Before that everything worked fine. I thought it was a temporary bug and tried waiting it out. It has been some time but the problem remained. I haven't seen people with the same issue and so I am writing this.

I found a workaround by adding "--disable-gpu" argument on ChromeOptions.

```
def general_browser():
    options = uc.ChromeOptions()
    options.add_argument("--disable-gpu")

    driver = uc.Chrome(options=options)
    driver.get('https://www.google.com')
    input("Enter anything to quit")
    driver.quit()
```
> options.add_argument("--disable-gpu")

Without this line the freeze comes back.

Any ideas why this is happening?

**Comment by ambiguous-cheese** [comment]
Thank you legend I didn’t know anyone else was having this problem

**Comment by unlucky-kit** [comment]
The issue seems to no longer occur. The problem probably had nothing to do with undetected-chromedriver.
