### ISSUE TITLE
Is v2 support --headless?

### ISSUE THREAD

**Issue by shawnsavour** [ultrafunkamsterdam/undetected-chromedriver#203]
I have my code to sign in to Google, it not safe when I use v1, so I can't log in. In v2, I can sign in to Google. But it seems to be not working when I try to add `--headless` into v2. It cannot find the element that trigger by Javascript or especially after entered the email of google and cannot find Element of password to `send_keys`.
I wonder if it is supported in v2?

**Comment by youpsla** [comment]
Just add the following option:
`https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/203`

**Comment by shawnsavour** [comment]
> Just add the following option:
> `https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/203`

What do you mean... What is the think I need to add?

**Comment by youpsla** [comment]
Sorry, my mistake.
