### ISSUE TITLE
[NODRIVER] Is there a way to open a button link in a new tab?

### ISSUE THREAD

**Issue by zerxdapro** [ultrafunkamsterdam/undetected-chromedriver#2038]
Hey, so I was able to extract the href of a button and im basically trying to open that link in a new tab. Im new to nodriver and cant really find anything where you can open the button in a new tab. I have this down right now, if someone could point me in the right direction, it would be really helpful

```py
async def signup():
    # Start the browser with the proxy settings
    browser = await uc.start(browser_args=[f"--proxy-server={PROXY}"])
    main_tab = await browser.get("draft:,")
    await setup_proxy(PROXYUSERNAME, PROXYPASSWORD, main_tab)

    try:
       tab = await browser.get("https://www.hm.com")
       await asyncio.sleep(3)

       sign_up_button = await tab.find("//a[@class='styles__ButtonRoot-sc-1ldytso-0 bzOPhu']")
       print(f"Sign Up Button: {sign_up_button}") # this prints the entire html for the button

       # Open the sign-up URL in a new tab
       sign_up_url = await sign_up_button.get_attribute("href") # most likely wrong
       print(f"Sign Up URL: {sign_up_url}") # does not print

       # Open the sign-up URL in a new tab
       signup_tab = await browser.get(sign_up_url)
       await asyncio.sleep(5)
```
            
the print of "Sign Up Button:" is displayed, shows the entire html for the button, including the href, but for some reason the bot stops there and cant grab the href and open it. Keep getting 
```'NoneType' object is not callable```

**Comment by zerxdapro** [comment]
I extracted href, just dont know how to open it

**Comment by jwwq** [comment]
await browser.get(url, new_tab = true)

**Comment by zerxdapro** [comment]
> await browser.get(url, new_tab = True) or await browser.get(url, new_window = True)

I'm trying to extract the link, I don't know the link since the link changes everytime based on the user. I attempted to get the href value, shown in the code, but I keep getting that error when it attempts to open. Basically saying it hasn't found the link.

**Comment by jwwq** [comment]
<button> have no standard "href" attrubute (it's for <a> only). Post the html of the button here please.

**Comment by jwwq** [comment]
I can't find get_attribute in the list of available methdods, only **get_attributes** that returns the list of attrs.

**Comment by jwwq** [comment]
Try to use button.href or button["href"], both shoud work.

**Comment by zerxdapro** [comment]
> Try to use button.href or button["href"], both shoud work.

In what way?
With browser.get or a different way?

**Comment by jwwq** [comment]
your code sign_up_button.get_attribute("href") is wrong, there is no get_attribute method. just replace it with 
sign_up_url = button["href"]
(without await)

**Comment by zerxdapro** [comment]
> your code sign_up_button.get_attribute("href") is wrong, there is no get_attribute method. just replace it with 
> 
> sign_up_url = button["href"]
> 
> (without await)

So, it would be `sign_up_url = sign_up_button["href]`?

**Comment by jwwq** [comment]
yes

**Comment by zerxdapro** [comment]
> yes

Thanks so much, it worked!
