### ISSUE TITLE
[NODRIVER] change download path and add tag to download automatic

### ISSUE THREAD

**Issue by JoaoSobhie** [ultrafunkamsterdam/undetected-chromedriver#2064]
Hey guys, how's it going? I'm trying to change download dir path and add some tags to make download without asking where to save but I'm not abble to do it. In selenium I user to do like this: 
options.add_experimental_option('prefs', {
            "download.prompt_for_download": False,  # To auto download the file
            "download.directory_upgrade": True,
            "download.default_directory": DOWNLOAD_DIR,
            # It will not show PDF directly in chrome
            "plugins.always_open_pdf_externally": True,
            "safebrowsing.enabled": False
            })
And on playwright I use to send the download dir on browser launch. Is there any way to do something like this on NoDriver?

**Comment by abhash-rai** [comment]
Did you find a way to set the download path on nodriver browser?

**Comment by JoaoSobhie** [comment]
Yes, It's very simple. Basicly what you need to do is:
import pathlib
from nodriver import cdp

path = pathlib.Path("D:/").resolve(strict=False)
await page.send(cdp.browser.set_download_behavior("allow", path, events_enabled=True))
await page.set_download_path(path)

**Comment by abhash-rai** [comment]
```python
async def initialize_worker(self):
        self.set_worker_id_from_server() # Getting worker id

        os.makedirs(Constants.chrome_download_location, exist_ok=True)
        
        self.browser = await uc.start(
            headless = Constants.chrome_headless,
            user_data_dir = Constants.chrome_user_data_directory, # by specifying it, it won't be automatically cleaned up when finished
            lang = "en-US",   # this could set iso-language-code in navigator, not recommended to change
            no_sandbox=True
        )

        asyncio.create_task(self.bind_handlers()) # adding custom handlers automatically to every tabs
        await asyncio.sleep(1)

        asyncio.create_task(self.give_article_response_listner()) # automatically gives responses to server
        await asyncio.sleep(1)
        
        self.current_tab = await self.browser.get('about:blank')
        await asyncio.sleep(1)

        download_path = Path(Constants.chrome_download_location).resolve(strict=False)
        print(f'[Download] Path is set to: "{download_path}"')
        await self.current_tab.send(cdp.browser.set_download_behavior("allow", download_path, events_enabled=True))
        await self.current_tab.set_download_path(download_path)
        await asyncio.sleep(1)
```

I tried above in a class. Everything works expect for the download location. I can't figure out why.

The path in the output is:
```
[Download] Path is set to: "C:\Users\LEGION\Documents\system\undetectablechrome\worker\downloads"
```

The path is correctly given but it doesn't download in that location instead uses the default download location. Any ideas @JoaoSobhie ?
