### ISSUE TITLE
[NODRIVER] - AttributeError: 'NoneType' object has no attribute 'aclose'

### ISSUE THREAD

**Issue by keisunl1** [ultrafunkamsterdam/undetected-chromedriver#2075]
Hi everyone,

Getting this error after pushing and pulling my project onto a new computer. Using Python 3.10.9

Traceback (most recent call last):
  File ****, line 1320, in <module>
    uc.loop().run_until_complete(main_script()) 
  File ****, line 90, in run_until_complete
    return f.result()
  File ****, line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File ****, line 232, in __step
    result = coro.send(None)
  File ****, line 622, in main_script
    bot = await uc.start(no_sandbox=True)
  File ****, line 96, in start
    return await Browser.create(config)
  File ****, line 91, in create
    await instance.start()
  File ****, line 352, in start
    raise Exception(
Exception: 
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True 
                
Exception ignored in atexit callback: <function deconstruct_browser at 0x7fa21a5ba560>
Traceback (most recent call last):
  File ****, line 146, in deconstruct_browser
    _.stop()
  File ****, line 558, in stop
    asyncio.get_event_loop().create_task(self.connection.aclose())
AttributeError: 'NoneType' object has no attribute 'aclose'

I've read some older posts and usually had found that using "pkill -9 -f "Google Chrome" had worked when I encountered this crash on my old computer, but I'm always getting this error now with no workaround on my new computer. I've also seen someone speak about a user_data_dir being corrupted but I'm not sure where to find that or fix it. Any work around for this?

**Comment by therealpurplemana** [comment]
This is a breaking change on the latest chrome caused by websockets

**Comment by RenzoMag** [comment]
> This is a breaking change on the latest chrome caused by websockets. Downgrade to 13.1. Also consider migrating to https://github.com/stephanlensky/zendriver as it has a lot of nodriver bugs resolved.

I have this problem too, if I change to zendrive will I have to rewrite all the code? It's very extensive...

**Comment by therealpurplemana** [comment]
No, drop in replacement

**Comment by keisunl1** [comment]
> This is a breaking change on the latest chrome caused by websockets. Downgrade to 13.1. Also consider migrating to https://github.com/stephanlensky/zendriver as it has a lot of nodriver bugs resolved.

this + downgrading my Chrome version solved the issue. Still get the error from time to time but gets by after killing all zombie processes.
