### ISSUE TITLE
Default chromedriver Zip file is currently corrupt (Nov 13th) 

### ISSUE THREAD

**Issue by econdb** [ultrafunkamsterdam/undetected-chromedriver#2079]
https://googlechromelabs.github.io/chrome-for-testing/

a temporary fix is to hardcode the download URL to point to the beta version of the zip, which is healthy.

In [this line](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/master/undetected_chromedriver/patcher.py#L285), add

```
download_url = 'https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.33/win32/chromedriver-win32.zip'
```

**Comment by lucastayar12** [comment]
Thank you for the solution worked for me!!

**Comment by econdb** [comment]
Closing as Stable link is sorted.
