### ISSUE TITLE
ChromeDriver is up-to date still it says chromedriver version is 114

### ISSUE THREAD

**Issue by majidabbasi788** [ultrafunkamsterdam/undetected-chromedriver#2086]
I have downloaded the latest chromedriver but when I run the script, it still says:
`selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:59122
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 131.0.6778.86`

```
def get_driver():
    print(f'Opening webdriver...')
    path = "chromedriver.exe"
    options = uc.ChromeOptions()
   
    options.add_argument("--start-maximized")
    options.binary_location = path
    options.headless = False
    caps = DesiredCapabilities.CHROME
    caps["acceptInsecureCerts"] = True
    caps['goog:loggingPrefs'] = {'performance': 'ALL'}
    options.set_capability(
    "goog:loggingPrefs", {"performance": "ALL"}
    )

    # try:
    driver = uc.Chrome(executable_path=path,options=options,desired_capabilities=caps)
    print('Webdriver Opened.')
    time.sleep(2)
    return driver
```

**Comment by amirzarbakhsh** [comment]
I think you need to update your operating system browser.

**Comment by DmitrySidorow** [comment]
same bug. i don't have 131 installed. i need 129, but it throw errors

**Comment by majidabbasi788** [comment]
I am closing this issue. The issue was with the Hard disk storage was full so the driver was not loading.
