### ISSUE TITLE
Cloudflare browser check fails when adding delay after navigating

### ISSUE THREAD

**Issue by Emielvr** [ultrafunkamsterdam/undetected-chromedriver#221]
I'm trying to read the contents of a page after the cloudflare browser check. Trying to access the content of the page after calling driver.get() returns Cloudflare's proxy page where it informs the user it's checking the browser, so I'm trying to get around this with delaying any action after navigating. However, this causes the page to get stuck on "Checking your browser before accessing".

The following code from the readme works fine:
```
driver = uc.Chrome()
with driver:
    driver.get('https://nowsecure.nl')
```
But when adding anything that forces the script to wait (time.sleep(), WebDriverWait(), input()...) after opening the web page, the script gets stuck on "Checking your browser before accessing". 
```
driver = uc.Chrome()
with driver:
    driver.get('https://nowsecure.nl')
    time.sleep(1)
```
This seems weird since the waiting call is after the navigation call. I'm not very familiar with Python so am I just missing something or is something else going on?

**Comment by ntony3419** [comment]
try to put sleep() outside of with, example
`
driver = uc.Chrome()
with driver:
    driver.get('https://nowsecure.nl')
time.sleep(100)
`

**Comment by ultrafunkamsterdam** [comment]
Or what about using no sleep? It works without no sleep and the with statement also has some sleep timings so would be double.

**Comment by ultrafunkamsterdam** [comment]
> try to put sleep() outside of with, example
> 
> ```
> 
> driver = uc.Chrome()
> with driver:
>     driver.get('https://nowsecure.nl')       
> time.sleep(100)
> ```
^^^^^ or this.
