### ISSUE TITLE
WebGL and Canvas fingerprint spoof

### ISSUE THREAD

**Issue by eix128** [ultrafunkamsterdam/undetected-chromedriver#226]
Hi , i tried on selenium 

driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
"source": "<content of inject.js>"})

I tried on page for fingerprint dedection:
https://browserleaks.com/canvas
https://browserleaks.com/webgl

//inject.js file begin:
var inject = function () {
  var overwrite = function (name) {
    const OLD = HTMLCanvasElement.prototype[name];
    Object.defineProperty(HTMLCanvasElement.prototype, name, {
      "value": function () {
        var shift = {
          'r': Math.floor(Math.random() * 10) - 5,
          'g': Math.floor(Math.random() * 10) - 5,
          'b': Math.floor(Math.random() * 10) - 5,
          'a': Math.floor(Math.random() * 10) - 5
        };
        var width = this.width, height = this.height, context = this.getContext("2d");
        var imageData = context.getImageData(0, 0, width, height);
        for (var i = 0; i < height; i++) {
          for (var j = 0; j < width; j++) {
            var n = ((i * (width * 4)) + (j * 4));
            imageData.data[n + 0] = imageData.data[n + 0] + shift.r;
            imageData.data[n + 1] = imageData.data[n + 1] + shift.g;
            imageData.data[n + 2] = imageData.data[n + 2] + shift.b;
            imageData.data[n + 3] = imageData.data[n + 3] + shift.a;
          }
        }
        window.top.postMessage("canvas-fingerprint-defender-alert", '*');
        context.putImageData(imageData, 0, 0);
        return OLD.apply(this, arguments);
      }
    });
  };
  overwrite('toBlob');
  overwrite('toDataURL');
  document.documentElement.dataset.cbscriptallow = true;
};

var script_1 = document.createElement('script');
script_1.textContent = "(" + inject + ")()";
document.documentElement.appendChild(script_1);

if (document.documentElement.dataset.cbscriptallow !== "true") {
  var script_2 = document.createElement('script');
  script_2.textContent = `{
    const iframes = window.top.document.querySelectorAll("iframe[sandbox]");
    for (var i = 0; i < iframes.length; i++) {
      if (iframes[i].contentWindow) {
        if (iframes[i].contentWindow.HTMLCanvasElement) {
          let tb = iframes[i].contentWindow.HTMLCanvasElement.prototype.toBlob;
          if (tb !== HTMLCanvasElement.prototype.toBlob) {
            iframes[i].contentWindow.HTMLCanvasElement.prototype.toBlob = HTMLCanvasElement.prototype.toBlob;
            iframes[i].contentWindow.HTMLCanvasElement.prototype.toDataURL = HTMLCanvasElement.prototype.toDataURL;
          }
        }
      }
    }
  }`;
  window.top.document.documentElement.appendChild(script_2);
}
//end of inject.js

Always its returning same fingerprint id.
I cant spoof canvas

But i found some solution like:

//inject2.js :
var original = document.createElement;
document.createElement = function (tag) {
if(tag == 'canvas')alert('Deneme 1 2 3')
return original(tag);
 };
//end of inject2.js

But this only blocks all javascript on page.
So no fingerprint dedected.
But i want random id generated by injecting script.

Did you find any good solution?

**Comment by ultrafunkamsterdam** [comment]
The goal is the other way around. You should appear as regular as possible. Best would be if your fp is the same as another 1000 users. Randomizing makes u unique, and therefore suspicious

**Comment by ultrafunkamsterdam** [comment]
And frankly this is only a educated guess. I can spoof the hell out of everything and still pass. Detection works in a different way
