### ISSUE TITLE
How to use Proxy with authentication

### ISSUE THREAD

**Issue by src-yahiko** [ultrafunkamsterdam/undetected-chromedriver#238]

**Comment by petzi75** [comment]
best thing is to use an extra app calles proxifier. With it, you also have no problems with WebRTC... :)

**Comment by src-yahiko** [comment]
Thank you for the fast reply!
I am currently working on a automated sign-up bot for instagram and want to run many of your chromedrivers simultaneously with different proxies. Seems like proxifier ist not for linux.. also Privoxy (Which was recommended as an alternative) seems not to cut it in my project

I would appreciate any tips from your side and wish you a great day :)

**Comment by petzi75** [comment]
sorry, but I`m only a user too, not ultrafunkamsterdam ;)
maybe you can have a look on selenium-wire, this could perhaps solve your problem (with integrated uc) - but I don`t test this way indeep, because I`m happy with proxifier

have also a great day! :)

**Comment by ultrafunkamsterdam** [comment]
Good luck on your insta bot. Let me know when it works 😅
