### ISSUE TITLE
Mutliprocess your undetectable chromedriver?

### ISSUE THREAD

**Issue by aufknax** [ultrafunkamsterdam/undetected-chromedriver#239]
Hello, 
currently I'm working on a Bot. Therefore I have to be undetectable. Thats why I use your chromedriver, well done. However now I want to multiprocess it, so it uses its full cpu. I can't find what I have to  change so that It works. A response would be really helpfull. Thank you.

**Comment by SilverStrings024** [comment]
How exactly are you trying to multiprocess it? Are you doing different driver instances? Are you executing JS in the same page from different threads? More information would be quite useful.

**Comment by ultrafunkamsterdam** [comment]
This makes no sense at all. Driver and browser are already in different processes. Spawning a process is way more expensive than  sending command to 100 (example) open browsers
