### ISSUE TITLE
Error : undetected_chromedriver/init.py", line 49, in new instance.init(*args, **kwargs) TypeError: init() got an unexpected keyword argument 'options'

### ISSUE THREAD

**Issue by chryahya** [ultrafunkamsterdam/undetected-chromedriver#24]
Hi
![Error bot](https://user-images.githubusercontent.com/69231683/92326779-36706780-f044-11ea-875b-40dc9c60633b.png)

My environement : windows server 2012, Chrome Last version, python 3.7 & python 3.8

My Code :
import undetected_chromedriver as uc
driver = uc.Chrome()
driver.get('https://distilnetworks.com')

The Error :
/python3.8/site-packages/undetected_chromedriver/init.py", line 49, in new instance.init(*args, **kwargs) TypeError: init() got an unexpected keyword argument 'options'

This is the screenshot :
https://i.ibb.co/PMPts9L/Error-bot.png

NOTE :
i have two windows server 2012 with the same configuration and same chrome & python & same code
one of them work well, and the other i have the error.

Thank you

**Comment by ultrafunkamsterdam** [comment]
You write :
```
The Error :
/python3.8/site-packages/undetected_chromedriver/init.py", line 49, in new instance.init(*args, **kwargs) TypeError: init() got an unexpected keyword argument 'options'
```

But i see as posted in your screenshot: "cannot find Chrome binary".  To me it simply looks like you do not have chrome installed  on that server, also due to the lack of an Chrome icon (which may be coincidence, for me, chrome is one of the icons i DO pin on my taskbar :))

**Comment by chryahya** [comment]
Hi, i already have chrome (last version)
i found the solution :
Add your chrome path to ChromeOptions()

Code :
options.binary_location = '{YOUR_CHROME_PATH}/chrome.exe'

it's work fine.

Thank you
