### ISSUE TITLE
It's getting detected by botprotect

### ISSUE THREAD

**Issue by MrBot45** [ultrafunkamsterdam/undetected-chromedriver#25]
It's getting detected by botprotect! https://lhcdn.botprotect.io/

**Comment by blacktippen** [comment]
yes i tried using it to bypass botprotect and it didnt work

**Comment by ultrafunkamsterdam** [comment]
Not at the moment, looks like it's down
![image](https://user-images.githubusercontent.com/21027969/92994644-6a440500-f4fc-11ea-9bb1-d42c6995f522.png)

**Comment by ultrafunkamsterdam** [comment]
```javascript
    location.href = localtion.href + "/" + mypostrequest.responseText.token;
                               // localtion ?
                        
```
got the site "working" now. although they need to fix their script.

they are not detecting automation, rather detect devtools window being opened (even if that is not the case). so this needs investigation.

{"msg":"You are human.","score":99.48960976127279,"details":[],"token":"63cc86489e299ea9b1241547fcfd8da3|C4ZtGX5Tf3nVjZ9g01uRnDFp1Aozb8IU"}

**Comment by MrBot45** [comment]
Can you bypass?

**Comment by ultrafunkamsterdam** [comment]
> Can you bypass?

I've pinpointed the cause. Working on a fix.

**Comment by ultrafunkamsterdam** [comment]
@MrBot45 @blacktippen 

fixed, albeit kind of dirty :)
👍 
![botprotect io](https://user-images.githubusercontent.com/21027969/93015269-637ac800-f5b8-11ea-91cf-394ae4d47c91.png)

**Comment by MrBot45** [comment]
It doesnt work? huh?

**Comment by ultrafunkamsterdam** [comment]
You  need to update to 1.4.0 .

**Comment by MrBot45** [comment]
I did, it doesnt work.

**Comment by MrBot45** [comment]
???

**Comment by MrBot45** [comment]
Can u fix??
