### ISSUE TITLE
ChromeDriver only supports Chrome version 93

### ISSUE THREAD

**Issue by stilljake** [ultrafunkamsterdam/undetected-chromedriver#250]
Every time I try to start I am getting this error:
```
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:50007
from session not created: This version of ChromeDriver only supports Chrome version 93
Current browser version is 92.0.4515.107
```

AFAIK Chrome 93 is only in beta at the moment.

I have tried rolling back to older versions of undeteced-chromedriver but I get the same error.

running on macOS 11.5

**Comment by ditas123** [comment]
I have this same issue

**Comment by stilljake** [comment]
From what I can tell, It is because `patcher.py` is downloading the newest version of chromedriver from https://chromedriver.chromium.org/downloads everytime, which is now ChromeDriver 93.0.4577.15. but unfortunately there is not a release yet available of Chrome 93.

Is there a way to specify which chromedriver to use, or not have it patch automatically?

**Comment by DanForLoop** [comment]
Not a perfect solution but I've found that for now using version 1 fixes this issue, obviously this means losing any features in version 2 though.

**Comment by ditas123** [comment]
How can we use version 1?

**Comment by DanForLoop** [comment]
Instead of:
``` import undetected_chromedriver.v2 as uc ```
do
``` import undetected_chromedriver as uc ```

**Comment by skinner12** [comment]
Same problem here

**Comment by ditas123** [comment]
Hey guys I found an easier fix - just use `version_main=92 `when instantiating the Chrome Driver e.g.

`driver = uc.Chrome(version_main=92, options=options)
`

**Comment by RobbyFrank** [comment]
> Hey guys I found an easier fix - just use `version_main=92` when instantiating the Chrome Driver e.g.
> 
> `driver = uc.Chrome(version_main=92, options=options) `

I have the same issue. 
Unfortunately, this didn't solve it.

**Comment by Hisoka95** [comment]
> Hey guys I found an easier fix - just use `version_main=92` when instantiating the Chrome Driver e.g.
> 
> `driver = uc.Chrome(version_main=92, options=options) `

This works fine, thanx.

**Comment by RobbyFrank** [comment]
> Hey guys I found an easier fix - just use `version_main=92` when instantiating the Chrome Driver e.g.
> 
> `driver = uc.Chrome(version_main=92, options=options) `

Worked :)

**Comment by stilljake** [comment]
> Hey guys I found an easier fix - just use `version_main=92` when instantiating the Chrome Driver e.g.
> 
> `driver = uc.Chrome(version_main=92, options=options)`

Thanks! I didn't notice this in the options before.
