### ISSUE TITLE
Downloads the latest beta chromedriver

### ISSUE THREAD

**Issue by BaconEggCheese777** [ultrafunkamsterdam/undetected-chromedriver#251]
Currently, the lastest stable release for Chrome is v92.
This module downloads v93 which is in beta and isn't currently available for Windows, only ios.
Is there a way to specify which version of Chrome I want to use instead of downloading the latest one every time on startup? I usually wouldn't mind the latest version, but this time it downloaded a driver that's not available for Windows.

**Comment by Tentoxa** [comment]
Same problem here:
`selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:60371
from session not created: This version of ChromeDriver only supports Chrome version 93
Current browser version is 92.0.4515.107`

**Comment by ultrafunkamsterdam** [comment]
you can just initialize Chrome(version_main=92) if you still use 92
