### ISSUE TITLE
Suddenly: This version of ChromeDriver only supports Chrome version 93

### ISSUE THREAD

**Issue by dimitrivisser** [ultrafunkamsterdam/undetected-chromedriver#252]
I was using undetected chromedriver on 2 computers. And suddenly both give an error:

selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:53164
from session not created: This version of ChromeDriver only supports Chrome version 93
Current browser version is 92.0.4515.107

I didn't change anything. 

Of course I tried to do the obvious: Try to find and install Chrome 93. But I could only find 94, and it doesn't look like a solution.

**Comment by KevinLage** [comment]
until this gets fixed you can use

`driver = uc.Chrome(version_main=92)`

**Comment by dimitrivisser** [comment]
Thanks! 

I also found a solution. The developers version of Chrome is version 93.  https://www.google.com/chrome/dev/

I added this to my script:

`options.binary_location = "C:\\Program Files\\Google\\Chrome Dev\\Application\\chrome.exe"`

Now it works again.

**Comment by ultrafunkamsterdam** [comment]
unfortunately there is not something to "fix" . The driver download will pick the one which Chrome sets as it's main version. But in some regions they roll it out  and for others it might be longer. That gap is what is causing this. I also run into this as i'm using the canary and/or chromium base browser :)

@KevinLage his answer is actually more correct  than download some dev version and upgrade the binary_location. Binary location is found automatically anyway. Highest versions first

**Comment by rwguerra** [comment]
current_version = int(driver.capabilities['browserVersion'].split('.')[0])
driver = uc.Chrome(version_main=current_version)

The problem with this solution is that if you never update your browser you will be outdated
