### ISSUE TITLE
Version Issues

### ISSUE THREAD

**Issue by JayBitron** [ultrafunkamsterdam/undetected-chromedriver#257]
Hi,

In `fetch_release_number` it always fetches the latest release number from `https://chromedriver.storage.googleapis.com/LATEST_RELEASE` and in `fetch_package` it fetches the chromedriver based on that release number.

First of all, it return 403 in some countries as it's blocked either by google or goverments, I tried setting `proxy` in `seleniumwire_options` which didn't even use that.

Also it would be great to get the release number based on installed chrome, as sometimes we block updates.

Thanks.

**Comment by JayBitron** [comment]
I actually ran into the same problem as #253 where `LATEST_RELEASE` was wrong, where it was `93.0.4515.107` while current auto updated version was `92.0.4515.107`, so it should rely on version from `chrome.exe`.

**Comment by ultrafunkamsterdam** [comment]
> I actually ran into the same problem as #253 where `LATEST_RELEASE` was wrong, where it was `93.0.4515.107` while current auto updated version was `92.0.4515.107`, so it should rely on version from `chrome.exe`.

See other questions how to easily solve this by setting a parameter. Regarding relying on chrome version : since chrome autoupdates,  everyone who has lower versions is not following best practice.

**Comment by JayBitron** [comment]
Well, If don't want your project get forked a lot you have to make it more customizable, thanks for the respond anyways.
