### ISSUE TITLE
not able to add proxies to UC V2 

### ISSUE THREAD

**Issue by ratz-py** [ultrafunkamsterdam/undetected-chromedriver#266]
This is my code:

import undetected_chromedriver.v2 as uc

options = uc.ChromeOptions()
options.add_argument(f'--proxy-server=http://YOUR_IP:YOUR_PORT')
driver = uc.Chrome(options=options)
driver.get('TARGET_URL')

If I try to retrieve my IP_ADDRESS I notice that proxy is not applied correctly, the strange thing is that if I use "import undetected_chromedriver as uc" instead of "import undetected_chromedriver.v2 as uc" proxy is applied correctly, but unfortunately I get blocked from the target site.

Any hint?

**Comment by HMaker** [comment]
@ratz-py I think you passed wrong format, try
```python
options.add_argument(f"--proxy-server=YOUR_IP:YOUR_PORT")
```
see https://www.chromium.org/developers/design-documents/network-settings

**Comment by ratz-py** [comment]
I managed to solve by loading an extension in this way:

opts.add_argument('--load-extension={}'.format(YOUR_EXT_HERE))
