### ISSUE TITLE
Multi-Tab example

### ISSUE THREAD

**Issue by claudio0603** [ultrafunkamsterdam/undetected-chromedriver#27]
Multi-tab doesn´t work like explained in the **important note** section.

The code I´ve tried looks like this:

`import undetected_chromedriver as uc`
`options = uc.ChromeOptions()`
`chrome = uc.Chrome(options=options)`
`chrome.get('https://example.com')`
`print('Main window detectable: ' + str(chrome.execute_script('return navigator.webdriver')))`
`chrome.execute_script('window.open();')`
`chrome.switch_to.window(chrome.window_handles[1])`
`chrome.get('data:,')`
`chrome.get('https://example.com')`
`print('New tab detectable: ' + str(chrome.execute_script('return navigator.webdriver')))`

Is there some point I´m missing here?
Would it be possible to update the documentation with a working example?

By the way thanks for publishing this repo, it saves my day. :)

**Comment by ultrafunkamsterdam** [comment]
good find!
I've got a patch implemented locally which also fixes the need for that first page. that means you can skip the `data:,` url alltogether, and use chrome.get(url) on the newly opened (and switched_to) tab. Will merge it tomorrow.

```
In [1]: import undetected_chromedriver as uc

In [2]: chrome = uc.Chrome()
Selenium patched. Safe to import Chrome / ChromeOptions
Selenium patched. Safe to import Chrome / ChromeOptions

DevTools listening on ws://127.0.0.1:12188/devtools/browser/2405e496-6c7f-4caa-ae40-9e4daa0fddd3

In [3]: chrome.execute_script('return navigator.webdriver')
Out[3]: True

In [4]: chrome.get('https://www.example.com')

In [5]: chrome.execute_script('return navigator.webdriver')

In [6]: chrome.execute_script('window.open();')

In [7]: chrome.switch_to.window(chrome.window_handles[-1])

In [8]: chrome.execute_script('return navigator.webdriver')
Out[8]: True

In [9]: chrome.execute_script('return navigator.webdriver')
Out[9]: True

In [10]: chrome.get('https://www.example.com')

In [11]: chrome.execute_script('return navigator.webdriver')

In[12]: 
```

**Comment by claudio0603** [comment]
Ok thanks. I´m looking forward to that fix. ;)

**Comment by ultrafunkamsterdam** [comment]
fixed
