### ISSUE TITLE
no action chain in this chromedriver

### ISSUE THREAD

**Issue by mysublimebox** [ultrafunkamsterdam/undetected-chromedriver#272]
original chrome-driver has action chain module, although this chrome driver is undetectable; it does not have action chain module. Can the author add this feature? Thank you.

**Comment by HMaker** [comment]
This chromedriver is the official one, all UC does is just patch the binary to remove a fingerprint. Just import `from selenium.webdriver.common.action_chains import ActionChains`.

**Comment by mysublimebox** [comment]
Bro, I tried but it does not work
    
    from selenium.webdriver.common.action_chains import ActionChains
    from selenium.webdriver.support.ui import WebDriverWait
    from selenium.webdriver.common.keys import Keys
    from selenium import webdriver

    import undetected_chromedriver.v2 as webdriver

    options = webdriver.ChromeOptions();

    driver = webdriver.Chrome(options=options)

    with driver:
        driver.get("https://web.whatsapp.com/")

    actions = ActionChains(driver)

    for part in body.split('\n'):
        action = webdriver.ActionChains(driver)
        action.send_keys(part)
        action.key_down(Keys.SHIFT).key_down(Keys.ENTER).key_up(Keys.ENTER).key_up(Keys.SHIFT).perform()

    actions.send_keys(Keys.ENTER)
    actions.perform()

action = webdriver.ActionChains(driver)
AttributeError: module 'undetected_chromedriver.v2' has no attribute 'ActionChains'

**Comment by HMaker** [comment]
You tried wrong, you need to import only `Chrome` and `ChromeOptions` from UC, all the rest you import from selenium
```python
import undetected_chromedriver.v2 import Chrome, ChromeOptions
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.action_chains import ActionChain
```

**Comment by mysublimebox** [comment]
remove `actions = ActionChains(driver)` solve the issue thx

**Comment by mysublimebox** [comment]
remove `actions = ActionChains(driver)` solve the issue thx
