### ISSUE TITLE
Fingerprint Tracked

### ISSUE THREAD

**Issue by Vexed-Nz** [ultrafunkamsterdam/undetected-chromedriver#275]
Hello I have been using your project for a while I've noticed that a website called https://fingerprintjs.github.io/fingerprintjs/ can track the users fingerprints. I don't know what causes it to be detected but I have tried retesting it with the undetected-chromedriver (V2) with different user-agents to see if I get a different fingerprint on each launch it came to my surprise it was not changing the id. I just wanted to let you know this might be a way sites can still track bots or automated browsers by storing there fingerprints in there server for later use on banning.

Here is an example of the ID:
![Screenshot 2021-08-13 160123](https://user-images.githubusercontent.com/72460819/129412624-84fce941-1044-4175-941d-6b761e6f2034.png)

if there is any thoughts about it be much appreciated thank you.

**Comment by cf313995** [comment]
I have the same problem, how can I solve it? If you know, please tell me, thank you

**Comment by ultrafunkamsterdam** [comment]
your browser is the same, spoofed UA does not change that.

**Comment by mesadhan** [comment]
This is really essential, please anyone knows how to bypass that issue without using any extension? Thanks in advance!
