### ISSUE TITLE
Stops working after Windows RDP logout

### ISSUE THREAD

**Issue by nickgashkov** [ultrafunkamsterdam/undetected-chromedriver#276]
Hello!

Thank's for your library, it is really helpful. I was wondering if you could help to resolve an issue with running the `undetected-chromedriver` on remote windows desktop.

After disconnecting, the basic session remains active but the GUI is deactivated. In such conditions, sadly, my script using `undetected-chromedriver` stops working, but the script based on vanilla `chromedriver` seems to work.

Could you please help to figure this out?

**Comment by ultrafunkamsterdam** [comment]
close RDp by X instead of "disconnect"

**Comment by Mannumanman** [comment]
v2 not wotk after close rdp disconnecting ,Have you solved the problem?

**Comment by adv-zl** [comment]
Try exit from RDP with this bat:

```
for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (  
    %windir%\System32\tscon.exe %%s /dest:console
	C:\QRes.exe /x 1680 /y 1050
) 
```
