### ISSUE TITLE
not bypassing Imperva, blocked when completing ReCaptcha manually

### ISSUE THREAD

**Issue by ndaskalovic** [ultrafunkamsterdam/undetected-chromedriver#278]
I am trying to access [this](https://driverpracticaltest.dvsa.gov.uk/login) site with python but Imperva still shows up and even when I complete the ReCaptcha manually, I get blocked from the site. Am I doing something wrong or am I missing something?

**Comment by pgshow** [comment]
It's the same for me.

**Comment by ultrafunkamsterdam** [comment]
no code, nothing...
