### ISSUE TITLE
Don't work for me

### ISSUE THREAD

**Issue by Impre-visible** [ultrafunkamsterdam/undetected-chromedriver#279]
Hi, i want to bypass a Cloudflare protection for selenium, but it don't work, I done that : 

```
Adblock = r'C:\Users\Chevrier\AppData\Local\Google\Chrome\User Data\Default\Extensions\cjpalhdlnbpafiamejdnhcphjbkeiagm\1.37.2_2' # URL de Adblock

chrome_options = Options()
chrome_options.add_argument('load-extension=' + Adblock) # Ajout de adblock
# chrome_options.add_argument("--headless") # Chrome ne se montre pas
chrome_options.add_argument("--disable-gpu") # Résoud une erreur :D

driver = uc.Chrome(options=chrome_options)
tirexo = "https://www2.tirexo.work/"
driver.create_options()
```

**Comment by Impre-visible** [comment]
hi wanted to try with the v.2 but i got this error

```AttributeError: 'Chrome' object has no attribute 'service'```

**Comment by Impre-visible** [comment]
i worked, but when i start, it open a page for load extension

**Comment by Impre-visible** [comment]
and i cant find an element

```selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="story"]"}```

**Comment by Impre-visible** [comment]
sometimes it work, and sometimes no

**Comment by taytanqbpass** [comment]
I also always encounter this AttributeError: 'Chrome' object has no attribute 'service' error
