### ISSUE TITLE
Its getting Detected By PerimeterX

### ISSUE THREAD

**Issue by RootEncrypter** [ultrafunkamsterdam/undetected-chromedriver#28]
Im try to scrape chegg.com and it has been secured by PerimeterX, Is there any fix to bypass perimeterX?
@ultrafunkamsterdam

**Comment by ultrafunkamsterdam** [comment]
@RootEncrypter Its getting Detected By PerimeterX
not anymore :) see mainpage. 👍

**Comment by RootEncrypter** [comment]
![proof](https://user-images.githubusercontent.com/62509239/93686885-f5ae2f00-fad6-11ea-816b-68b912d2f930.JPG)

It is still getting detected by perimeterX when you try to login, i gave proper delays and virtual clicks and even time to sleep after typing. You can try with this test account . Test Account : wzjxj66@gmail.com:Robin150329. If you can successfully login and enter homepage let me know @ultrafunkamsterdam
