### ISSUE TITLE
Im getting an AttributeError when the driver tries to close.

### ISSUE THREAD

**Issue by Nelson-Morais** [ultrafunkamsterdam/undetected-chromedriver#284]
after my code runs successfully, the driver does not seem to quit as expected. 

> Exception ignored in: <function Chrome.__del__ at 0x7f9b762b6dc0>
> Traceback (most recent call last):
>   File "/home/ohgee/dev/scrapeBay/venv/lib/python3.9/site-packages/undetected_chromedriver/v2.py", line 623, in __del__
>     self.quit()
>   File "/home/ohgee/dev/scrapeBay/venv/lib/python3.9/site-packages/undetected_chromedriver/v2.py", line 581, in quit
>     self.service.process.kill()
> AttributeError: 'NoneType' object has no attribute 'kill'

this is affecting the program in a way that the next time i try to run it the webdriver does not work right, i need to restart the program a couple of times until it works again

**Comment by AccountYi** [comment]
I also encountered this problem. After I set the driver variable to global, I didn't have this error.
``
global driver
driver = uc.Chrome()
```

**Comment by AccountYi** [comment]
I encountered the same problem, and when I set the driver variable to global, I solved this error.
```
global driver 
driver = uc.Chrome()
```

**Comment by omarshamali** [comment]
> I encountered the same problem, and when I set the driver variable to global, I solved this error.
> 
> ```
> global driver 
> driver = uc.Chrome()
> ```

nah, didnt work
