### ISSUE TITLE
Using proxy server authentication

### ISSUE THREAD

**Issue by ankurpandeyvns** [ultrafunkamsterdam/undetected-chromedriver#29]
Is there any way we can include proxy auth from selenium wire and combine it with undetected chromedriver?

**Comment by ultrafunkamsterdam** [comment]
Hi @ankurpandeyvns 
This should be possible looking at their code with little modification.
However no guarantees given and it will not be added  here.  Main focus on this package is (un)discoverability.   You could also use mitmproxy for that sake...

https://github.com/wkeeling/selenium-wire/blob/master/seleniumwire/webdriver/browser.py
