### ISSUE TITLE
Is there any way to Change language?

### ISSUE THREAD

**Issue by Itad0ri** [ultrafunkamsterdam/undetected-chromedriver#296]
driver.execute_script('return navigator.languages') returns this : ['en-GB', 'en-US', 'en']

![RbIRq9HJhK](https://user-images.githubusercontent.com/38765805/132126802-ef1807c5-93e5-4427-8986-5d74f93b21ff.png)

+ Remove en-GB
+ Remove en-US
+ Set language to my local which is en-IN.

I've tried some methods I found on Internet but I'm unable to get the desired results.
--lang=en-IN >> didn't help
--lang=en-US or --lang=en >> Doesn't even remove en-GB

EDIT: After using custom user-agent, en-GB disappeared.

Can someone help? Thanks.

**Comment by OldTiger** [comment]
could u share your solution
