### ISSUE TITLE
Google login

### ISSUE THREAD

**Issue by coderlv** [ultrafunkamsterdam/undetected-chromedriver#3]
Trying to login in Google Account,
Shows:
> This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

**Comment by ultrafunkamsterdam** [comment]
Hi @coderlv . This not really related to this package,  seeing the number of hits on google. I also had this a while ago. Very annoyiny.  If i recall correctly I "fixed" it by either turning on 2fa, or/and creating a chrome profile first without selenium, login to google saving your credentials, and explicitly specify this profile path in webdriver options.
