### ISSUE TITLE
They patched it

### ISSUE THREAD

**Issue by MrBot45** [ultrafunkamsterdam/undetected-chromedriver#30]
They patched it :(
botprotect detect it now :(

**Comment by jckail** [comment]
Any code to share?

**Comment by MrBot45** [comment]
wym

**Comment by HarryBak** [comment]
`import undetected_chromedriver as uc
import pdb
import time
driver = uc.Chrome()
driver.get('https://lhcdn.botprotect.io')
time.sleep(10) ## time for botprotect to check us.
driver.save_screenshot('botprotect_result.png')
pdb.set_trace()`

![botprotect_result](https://user-images.githubusercontent.com/49888747/93968579-0522c600-fdbe-11ea-8d07-8afe2361869e.png)

Also I encounter PerimiterX on zillow when logging in (takes a couple logins before it's flagged)

**Comment by ultrafunkamsterdam** [comment]
What version  of undetected_chromedriver do you use ? it's recently updated. And why do you use time.sleep() ? this will halt the python code which modifies the request/response ...

**Comment by MrBot45** [comment]
Lastest

**Comment by ultrafunkamsterdam** [comment]
That was fast. Like they're reading along 🤔😋, which wouldn't even surprise me, sinds it's a startup.  Anyhow they're having hard times securing their own stuff obviously,  so i'm working on a patch using their onobfuscated code.

**Comment by MrBot45** [comment]
Where is that code? I want to take a look tho. Can you send it?

**Comment by HarryBak** [comment]
> What version of undetected_chromedriver do you use ? it's recently updated. And why do you use time.sleep() ? this will halt the python code which modifies the request/response ...

Good to know! Was using that so the screenshot wouldn't just be 'We're checking if you are a bot' how would you suggest taking a screenshot in this instance then?

Latest version, thats the whole code I'm using, removing the .exe from the local folder each time.

**Comment by Limes420** [comment]
Yea, I am having the same issue I want to "Pentest" botprotect :) for educational purposes obviously

**Comment by MistikSenpa** [comment]
I just tested and BotProtect detects this

**Comment by Limes420** [comment]
> I just tested and BotProtect detects this

Yea

**Comment by ultrafunkamsterdam** [comment]
@MrBot45  aka one of the devs of botprotect

**Comment by MrBot45** [comment]
?
