### ISSUE TITLE
user-data-dir can't be changed. Always sets to new temp folder

### ISSUE THREAD

**Issue by catchpa** [ultrafunkamsterdam/undetected-chromedriver#307]
Code:

import undetected_chromedriver.v2 as uc
options = uc.ChromeOptions()
options.add_argument('--user-data-dir=c:\temp\profile2')
driver = uc.Chrome(options=options)

Output from chrome://version: 
Command Line	"C:\Program Files\Google\Chrome\Application\chrome.exe" **--user-data-dir="C:\Users\me\AppData\Local\Temp\tmpf756efzq"** --remote-debugging-host=127.0.0.1 --remote-debugging-port=62397 --log-level=3  **--user-data-dir="c:\temp\profile2"** --flag-switches-begin --flag-switches-end
Executable Path	C:\Program Files\Google\Chrome\Application\chrome.exe
Profile Path	C:\Users\me\AppData\Local\Temp\tmpf756efzq\Default

I've tried using options.user_data_dir = "c:\temp\profile2" but it turns out the same. 

It always defaults to \AppData\Local\Temp\tmpXXXXXX for the user-data-dir instead of the one set in options.

**Comment by TrueObsidian** [comment]
Try this: `options.add_argument(r'--user-data-dir=c:\temp\profile2')`

**Comment by catchpa** [comment]
> Try this: `options.add_argument(r'--user-data-dir=c:\temp\profile2')`

thanks for replying. This did not work, still seems to be forced to a tmp folder

**Comment by ujjwalkirorimal** [comment]
Use double slashes in such cases like : ` options.add_argument('--user-data-dir=c:\\temp\\profile2')`

**Comment by catchpa** [comment]
"--disable-features=InfiniteSessionRestore" fixed my issue
