### ISSUE TITLE
my browser detected when use install()

### ISSUE THREAD

**Issue by Nux-xader** [ultrafunkamsterdam/undetected-chromedriver#312]
i try use this code
import undetected_chromedriver as uc
uc.install()

from selenium.webdriver import Chrome
driver = Chrome()
driver.get('any site')

but my driver has detected

**Comment by ultrafunkamsterdam** [comment]
because default chromedriver needs the path to the file. i recommend using the easier way.

**Comment by Nux-xader** [comment]
> because default chromedriver needs the path to the file. i recommend using the easier way.

if i not use install(). i cant run with multithreads mode
