### ISSUE TITLE
zodgame.xyz detect it.

### ISSUE THREAD

**Issue by tyIceStream** [ultrafunkamsterdam/undetected-chromedriver#315]
When I run this to get "https://zodgame.xyz"
The WebDriver shows me unlimited redirection redirection redirection.
Cloud you help me about this?

`import undetected_chromedriver.v2 as uc`
`driver = uc.Chrome()`
`driver.get("https://zodgame.xyz")`

**Comment by ODtian** [comment]
You've solved it? How?

**Comment by tyIceStream** [comment]
@ODtian 
No, zodgame rollback their function, my code in previous version works now.

**Comment by ODtian** [comment]
哈哈，真的耶，还好我暂时没搞这玩意，要不然就白费心思了
