### ISSUE TITLE
403 Error: Nike

### ISSUE THREAD

**Issue by Lesspeaker44** [ultrafunkamsterdam/undetected-chromedriver#32]
hello I am currently getting detected using the undetected_chromedriver, I have been using it for a couple weeks now... it ran flawlessly a day or two ago though when tested today on the same instance (website/drop style) I got detected this time.  Would appreciate the help when you get the chance, I ran the navigator command to see if the flag was true, it returns undetected despite the error log.

NOTE: I did not update to the new version when first receiving the error, I was using 1.3.7 though updating to the latest version did not change anything

[www.nike.com-1601653606474.log](https://github.com/ultrafunkamsterdam/undetected-chromedriver/files/5318981/www.nike.com-1601653606474.log)

![samesite](https://user-images.githubusercontent.com/72268768/94943360-945a6880-04a5-11eb-8268-02bf63fe1ce5.png)

![script](https://user-images.githubusercontent.com/72268768/94944203-e9e34500-04a6-11eb-947e-673bcb8521f2.png)

Update: I believe I have figured out the same-cookie issue I took a screen shot of above, I do not think it relates to the "bigger picture" (why I am getting detected on nike) I am receiving error similar to the log above the file above is with the cookie error
[fullLOG.log](https://github.com/ultrafunkamsterdam/undetected-chromedriver/files/5319217/fullLOG.log)
this is the full log without receiving the same-site cookie error

**Comment by ultrafunkamsterdam** [comment]
these cookies are not related in any way. You'll most of times get them in regular sessions as well. In your logs i only see  regular console log messages from the site, not any signal you are detected. HOWEVER: sites can detect whether you have devtools open, especially the console. so that could be something.... in the latest version the console is disabled by default.
