### ISSUE TITLE
WebdriverWait and stuff

### ISSUE THREAD

**Issue by Vinyzu** [ultrafunkamsterdam/undetected-chromedriver#321]
this code:
webdriver.support.ui.WebDriverWait(driver, 10).until(EC.element_to_be_clickable((webdriver.common.by.By.XPATH, "/html/body/div/div/div/header/div[3]/button[1]"))).click()
throws a error:
AttributeError: module 'undetected_chromedriver.v2' has no attribute 'support'
theres also no docs so i cant look it up :(

**Comment by Vinyzu** [comment]
Or should i then use the normal selenium webdriver to do such Waiting?

**Comment by frederikme** [comment]
You only use the undetected_chromedriver to start your driver/browser. From then on you can simply use selenium libraries. In your case the following should do the trick.
```
import undetected_chromedriver.v2 as uc
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.common.exceptions import TimeoutException

# initiate driver with the undetected chromedriver, you can add the path to the executable or add options if necessary
driver = uc.Chrome()

try:
    xpath = '//*[@id="example"]'
    
    WebDriverWait(driver, 5).until(EC.presence_of_element_located(
                (By.XPATH, xpath)))
    element = driver.find_element(By.XPATH, xpath)

except TimeoutException:
    print('WebdriverWait period exceeded. Element Probably not there.')

```
