### ISSUE TITLE
undected_chromedriver with torpy

### ISSUE THREAD

**Issue by AmFearLiath** [ultrafunkamsterdam/undetected-chromedriver#325]
Hello everyone. I would like to try using this tool on the Tor network for some testing purposes. However, I'm not able to use undetected_chromedriver with torpy. Can someone help me with that?

**Comment by frederikme** [comment]
Were you able to make torpy work with the 'normal' chromedriver and selenium framework? 
Also try to include some more information on what you've tried so far.

**Comment by AmFearLiath** [comment]
yeah, torpy is working for me so far... also i've got undected_chromedriver running. Its just to combine both of them. Maybe its pretty easy, but i'm starting with python at moment and dont know exactly how to do.

this is my code for torpy, to load a page through TOR

```
import undetected_chromedriver.v2 as uc
from torpy import TorClient
from torpy.http import requests
from torpy.http.adapter import TorHttpAdapter

driver = uc.Chrome()
host = "https://ifconfig.me/ip"

with TorClient() as tor:
    with tor.get_guard() as guard:
        adapter = TorHttpAdapter(guard, 3)
        with requests.Session() as sess:
            sess.headers.update({'User-Agent': 'Mozilla/5.0'})
            sess.mount('http://', adapter)
            sess.mount('https://', adapter)

            resp = sess.get(host, timeout=10)
            print(resp.text)
```

here
```
resp = sess.get(host, timeout=10)
```
i want to use undected_chromedriver, to load the page which is protected by cloudflare

**Comment by ultrafunkamsterdam** [comment]
lol. even using genuine browser with tor always results in a captcha.
tor exit node ip addresses are published, so anyone is free to block it.
