### ISSUE TITLE
Is there anyway to use this with node js? 

### ISSUE THREAD

**Issue by matifdev** [ultrafunkamsterdam/undetected-chromedriver#326]
The title is self explanatory

**Comment by baptx** [comment]
Related: https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/821

**Comment by baptx** [comment]
You closed the issue because you found a solution?
There is a related issue: https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/821
