### ISSUE TITLE
New protection, not bypassable?

### ISSUE THREAD

**Issue by chwba** [ultrafunkamsterdam/undetected-chromedriver#33]
Nice work on this one!

There are two websites: https://www.mc-market.org and https://v3rmillion.net, it doesnt seem to work on these ones, what I see in the network traffic is that there are some 503 errors and the page keeps reloading.

Seems you are an expert in this field, do you have any idea what this could be?

EDIT: Found another site with this protection, seems like its from cloudflare: https://www.sythe.org/login/login

**Comment by ultrafunkamsterdam** [comment]
fixed in 1.5.0

**Comment by lazidoca** [comment]
It seems like the version 1.5.0 doesn't work for mentioned sites by OP

**Comment by chwba** [comment]
> fixed in 1.5.0

Confirmed, that it works with 1.5.0
