### ISSUE TITLE
Release patched Drivers

### ISSUE THREAD

**Issue by ImAnOwl** [ultrafunkamsterdam/undetected-chromedriver#36]
Hi,

could you upload already patched drivers for all common browsers?
So it could be used in any language! Currently searching such a solution for NodeJS.

Regards

p.s.:
sorry for issuing, but did not find any contacts from you :(

**Comment by chwba** [comment]
What do you mean by "all common browsers"?

**Comment by ultrafunkamsterdam** [comment]
@ImAnOwl  it doesn't work that way. Patching is only part of the solution.   I think it is perfectly possible to rewrite the methods in node.
