### ISSUE TITLE
Cloudfare protection

### ISSUE THREAD

**Issue by Hernandiaz035** [ultrafunkamsterdam/undetected-chromedriver#37]
The driver is still detected by cloudfare protection, [Platzi](https://platzi.com) is a website im trying to web-scrap  and i haven't been able to.

**Comment by chwba** [comment]
mc-market.org seems to be working with 1.5.0 (and wasnt with the previous version) but I noticed, that as soon as I activate https://antcpt.com/eng/download/google-chrome-options.html it will lock again.

**Comment by czoins** [comment]
Apparently passing your own Options() overrides the options in __init__.py. You should manually add them until he fixes the issue:
```
instance.add_argument("start-maximized")
instance.add_experimental_option("excludeSwitches", ["enable-automation"])
instance.add_argument("--disable-blink-features=AutomationControlled")
```

**Comment by ultrafunkamsterdam** [comment]
the _ after self is intended

**Comment by ultrafunkamsterdam** [comment]
> instance.add_argument("start-maximized")
> instance.add_experimental_option("excludeSwitches", ["enable-automation"])
> instance.add_argument("--disable-blink-features=AutomationControlled")

These are the default, so no need to overwrite. All that is non-standard is unsupported.


Regarding platzi, get another ip, since yours might be flagged.

cannot reproduce the issue 

```
In [1]: import undetected_chromedriver as uc

In [2]: driver = uc.Chrome()
Selenium patched. Safe to import Chrome / ChromeOptions
Selenium patched. Safe to import Chrome / ChromeOptions

DevTools listening on ws://127.0.0.1:19576/devtools/browser/642a3b15-d112-42bf-b222-9b89ae83649b
In [3]: driver.get('https://platzi.com/')

In [4]: driver.save_screenshot('platzi.png')
Out[4]: True
```
![platzi](https://user-images.githubusercontent.com/21027969/95882980-9f9d7600-0d7a-11eb-9748-63aff3e3d610.png)
