### ISSUE TITLE
enable_cdp_events not working with execute_cdp_cmd in uc v2

### ISSUE THREAD

**Issue by Avnsx** [ultrafunkamsterdam/undetected-chromedriver#387]
Trying to block specific urls from loading, with v2, literally does nothing. All urls still load.
Incase you're wondering why I'm using main https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/384
```python
import undetected_chromedriver.v2 as uc
if __name__ == '__main__':
    driver = uc.Chrome(enable_cdp_events=True)
    driver.execute_cdp_cmd('Network.setBlockedURLs', {"urls": ['*png','*woff2','*woff','*jpg','https://www.apple.com/ac/globalnav/7/en_US/styles/ac-globalnav.built.css']})
    driver.execute_cdp_cmd('Network.enable', {})
    driver.get('https://apple.com/')
```

But it works, as intended, in uc v1:
```python
import undetected_chromedriver as uc
driver = uc.Chrome()
driver.execute_cdp_cmd('Network.setBlockedURLs', {"urls": ['*png','*woff2','*woff','*jpg','https://www.apple.com/ac/globalnav/7/en_US/styles/ac-globalnav.built.css']})
driver.execute_cdp_cmd('Network.enable', {})
driver.get('https://apple.com/')
```

It even works in normal chromedriver
```python
from selenium import webdriver
driver = webdriver.Chrome()
driver.execute_cdp_cmd('Network.setBlockedURLs', {"urls": ['*png','*woff2','*woff','*jpg','https://www.apple.com/ac/globalnav/7/en_US/styles/ac-globalnav.built.css']})
driver.execute_cdp_cmd('Network.enable', {})
driver.get('https://apple.com/')
```

Network.setBlockedURLs is a experimental, but very usefull when for example using with slow proxies to reduce page load time, function in chromedriver, documented here: https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setBlockedURLs

I just tested the code from your ReadMe regarding cdp, those work ... ?

Env: Python 3.8.10, Windows 10

@ultrafunkamsterdam @TJM4 please fix 🙏🏼

**Comment by jglorioso** [comment]
I am looking into a similar issue with trying to set a user agent override with `driver.execute_cdp_cmd("Network.setUserAgentOverride", ...)` which no longer works after version `3.0.3`.

I believe it has to do with the commits in `3.0.4` to move to fully detached and the driver not being able to execute cdp commands. I will let you know if I find a work around or have a suggested fix.

**Comment by jglorioso** [comment]
Update to my above. I noticed that the `driver.execute_cdp_cmd` seems to work if I manually delay before calling driver.get. Maybe the execute_cdp_cmd is async and is not complete before it hits the get call?

**Comment by jglorioso** [comment]
Nevermind, looks like only the first page request does what is expected. It seems like subsequent calls for images/css/etc do not send the overridden user agent.

**Comment by Avnsx** [comment]
@ultrafunkamsterdam Hey any updates on this? 🙏

**Comment by Avnsx** [comment]
Not sure why but now this magically started to work again with the ``3.1.5.post4`` version

**Comment by Avnsx** [comment]
Not sure why but now this magically started to work again with the 3.1.5.post4 version

**Comment by MacMarde** [comment]
> Nevermind, looks like only the first page request does what is expected. It seems like subsequent calls for images/css/etc do not send the overridden user agent.

I have the same problem using latest version of SeleniumBase with UC.
