### ISSUE TITLE
Does it support remotedebugging mode?

### ISSUE THREAD

**Issue by jerrycgc** [ultrafunkamsterdam/undetected-chromedriver#39]
I tried to attach driver to an existing chrome process, but failed. 
codes :
   options = uc.ChromeOptions()
    options.add_experimental_option("debuggerAddress", "127.0.0.1:8999")
    driver = uc.Chrome(options=options)
======
error message:
Message: invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: unrecognized chrome option: excludeSwitches

**Comment by ultrafunkamsterdam** [comment]
yes you need to ```del options.experimental_options['excludeSwitches']``` assuming your options object is called `options`
This is something that plays quite a large role in coming v2
