### ISSUE TITLE
Detected "Access denied" by cloudflare as soon as I use a proxy

### ISSUE THREAD

**Issue by Mmalherbe** [ultrafunkamsterdam/undetected-chromedriver#396]
Hey gang!

So I had a hairpulling issue.. ( I tried to see the important note at the bottom of the readme, but it doesn't exist).

I can use the UC just fine, it doesn't get flagged or whatever on the webpage I'm trying to use it on.
Right until I use a proxy through : 
` 
import undetected_chromedriver.v2 as uc
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.common.exceptions import TimeoutException

       options = uc.ChromeOptions()
# another way to set profile is the below (which takes precedence if both variants are used
        options.add_argument('--user-data-dir=c:\\temp\\profile2')

# just some options passing in to skip annoying popups
       
        options.add_argument(f"--proxy-server=http://{proxy}")
        self.driver = uc.Chrome(options=options)
        self.driver.get('inserturl here')
`
(It's a code snipped.. I took parts out that don't matter)

Now I'm facing the issue I get flagged as access denied when using said Proxy
I checked through https://browserleaks.com/ip and made sure the browser isn't leaky through proxy

Anyone has any tips to counter this issue? Or has anyone been able to get UC working with proxy.

I know it could be possible that all my proxies are flagged .. But I just want to rule out some things before I go on a massive buying spree to find a proxy that will work.. As my only option for testing if the proxy works is by buying and running them through a small test code.

**Comment by zeyad-mansour** [comment]
It's your proxy.

**Comment by Mmalherbe** [comment]
> 

I thought so.. any tips on finding the correct supplier ? I hate buying them and testing to find out they don’t work

**Comment by zeyad-mansour** [comment]
Some services have trials.

**Comment by Avnsx** [comment]
> > 
> 
> I thought so.. any tips on finding the correct supplier ? I hate buying them and testing to find out they don’t work

I can only recommend https://brightdata.com/ they've the best proxies by far.

**Comment by crane-denny** [comment]
This is not a bug in this lib. So this ticket can safely be closed and shouldnt even exist.
Try it on [reddit](https://www.reddit.com/r/webscraping) and/or [this](https://discord.gg/u759hFk) discord server. There you will get answers to all of your questions.

And now to your question. There is no such thing as the "correct supplier". It's a trial and error until you find a good match.
You could use something like tor as a low budged proxy. But most of them will probably be filtert or have higher restrictions to the page. If you have some spare money you could go for any VPN provider and try it there. Or you could setup your own proxy server.
I went with one of my projects to AWS. My requirements was that I have a big pool of IPs I can access and fastly switch to new ones. That's how I evade any detection on my project. And I pay less than 4$ a month for this proxy. 
But there is no gurantee on that any of this is working for you. You simply have to try and figure out what they are using to detect your proxy. 

Good luck :)

**Comment by Mmalherbe** [comment]
> 

Thanks! 

I'm on the discords as "Maxtest#9229", mind DMing me. I'm interested in testing the one you're using 


I'll close the issue as it is indeed not as issue (as supposed to be on here), but I couldn't find a better use in finding people also using this plugin.
