### ISSUE TITLE
Undetected chromedriver launches 2 instances of chrome on every run. MacOS Big Sur.

### ISSUE THREAD

**Issue by andycccccccc** [ultrafunkamsterdam/undetected-chromedriver#397]
Hello,

Every time I run a script with undetected chromebrowser I get 2 instances of chrome launching instead of one. 

- The first instance is always "fresh" - in that is acts like it's chrome's first launch ever. Its profile path is always in the self-destructing temp directory of MacOS.
- The second instance launches properly - it uses the assigned profile path, and everything is kosher .

Why are 2 instances launching? I'm basically using the example script:

```
def test_uc():
    import undetected_chromedriver.v2 as uc
    driver = uc.Chrome()

    chrome_options = uc.ChromeOptions()
    chrome_options.user_data_dir = "cookies_test_uc"
    
    driver = uc.Chrome(options=chrome_options)

    time.sleep(30000) #just so it doesn't close immediately, for testing
if __name__ == '__main__':
    test_uc()

**Comment by KristN1** [comment]
This is because you start the driver twice with `uc.Chrome()`

You should remove the third line of your code.
``` py
def test_uc():
    import undetected_chromedriver.v2 as uc

    chrome_options = uc.ChromeOptions()
    chrome_options.user_data_dir = "cookies_test_uc"
    
    driver = uc.Chrome(options=chrome_options)

    time.sleep(30000) #just so it doesn't close immediately, for testing
if __name__ == '__main__':
    test_uc()```

**Comment by andycccccccc** [comment]
> This is because you start the driver twice with `uc.Chrome()`
> 
> You should remove the third line of your code.
> 
> ```python
> def test_uc():
>     import undetected_chromedriver.v2 as uc
> 
>     chrome_options = uc.ChromeOptions()
>     chrome_options.user_data_dir = "cookies_test_uc"
>     
>     driver = uc.Chrome(options=chrome_options)
> 
>     time.sleep(30000) #just so it doesn't close immediately, for testing
> if __name__ == '__main__':
>     test_uc()
> ```

Doh, you're totally right. Fixed it and now it works fine. Tyvm!
