### ISSUE TITLE
C#?

### ISSUE THREAD

**Issue by krysis-dev** [ultrafunkamsterdam/undetected-chromedriver#4]
I know this is not an issue, but I did not find any way to contact you.

First of all, I love this repo! But my question is if I patch it before using it in python, would I be able to use that patched chromedriver.exe within a C# project?

Thanks!

**Comment by ultrafunkamsterdam** [comment]
Hi, thanks for your interest. Yes, however you need to setup your selenium webdriver object like it is done here so it would help if there is a .net selenium package (i think there is, not sure from the back of my head) 
. The actual binary patching is a simple function which replaces a chunk of bytes, as can be seen in patch_binary somewhere near the end of the code. That as well can easily be accomplished in one's language of choice.
