### ISSUE TITLE
Issue: Cannot set default download folder.

### ISSUE THREAD

**Issue by ntpapatheodorou** [ultrafunkamsterdam/undetected-chromedriver#406]
I have tried the common code for setting default folder of downloads.

like 
```
preferences = {"download.default_directory": download_dir ,
                   "directory_upgrade": True,
                   "safebrowsing.enabled": True }
options.add_experimental_option("prefs", preferences)
```

and the broswer crashes

**Comment by fastlaner** [comment]
options = uc.ChromeOptions()
options.add_argument("--download.default_directory --C:\your\Downloads\path")
 driver = uc.Chrome(options=options)

**Comment by ntpapatheodorou** [comment]
@fastlaner Merry Christmas !!
Sadly it doesnt work !

**Comment by fastlaner** [comment]
> @fastlaner Merry Christmas !! Sadly it doesnt work !

Merry Christmas to you too! (late)

Well, I'm not sure then because it worked for me, it was on the latest pip release, not sure if that makes a difference. If the browser is crashing, then something else may be your problem.

**Comment by ntpapatheodorou** [comment]
I just upgraded it.
my command is options.add_argument(r"--download.default_directory --C:\Users\username\Desktop")
it doesnt make a change. Does it matter if im in incognito ? I dont think so

**Comment by fastlaner** [comment]
remove the r from the argument, not sure if it will do anything but you dont need it. Not sure if incognito mode matters or not.

**Comment by ntpapatheodorou** [comment]
doesnt work either... is there any other solution ?

**Comment by ultrafunkamsterdam** [comment]
solution: read the selenium webdriver docs

**Comment by ntpapatheodorou** [comment]
I have already read the webdriver docs. It works properly on selenium but not on UC

**Comment by imoonkey** [comment]
@ntpapatheodorou have you found a solution to this problem? I am experiencing the same issue. The setting works for normal selenium but not uc.

**Comment by AttaM1rza** [comment]
I have the same problem ...

**Comment by singletonerik** [comment]
I have the same problem as well
