### ISSUE TITLE
Please help, error: AttributeError module 'undetected_chromedriver' has no attribute 'Chrome'

### ISSUE THREAD

**Issue by BenoitYU** [ultrafunkamsterdam/undetected-chromedriver#415]
![image](https://user-images.githubusercontent.com/22321344/147300389-761e7ed2-ad18-419a-a88c-3225d9fd3c0a.png)

Sorry but I really can't find out why. Any suggestions would be appreciated.

**Comment by ultrafunkamsterdam** [comment]
you shouldn't call your script undetected_chromedriver.py
