### ISSUE TITLE
[AliExpress Bonus Buddies] Selenium Getting Dectected

### ISSUE THREAD

**Issue by Syntist** [ultrafunkamsterdam/undetected-chromedriver#42]
So, I did some search like you said, I use the vanilla way tested everything.. it's undetected on most of the bot protection site.
But as soon I use driver.get('https://sale.aliexpress.com/__mobile/daily-cash-out-gaming_m.htm?_addShare=no') or the ref link.
AliExpress blocks my account as it detect it, now after even if I change the ip and anything it will always give system error
So basically account become useless. 

![image](https://user-images.githubusercontent.com/24858150/96733724-36011580-13d3-11eb-8f4d-03b8114ff038.png)
I get this system error, no use as it I even do a manually click after opening the ref link it will give this error, but If i paste the link manually it will work! 
Link: Will only work in mobile view!

**Comment by ultrafunkamsterdam** [comment]
It could be aliexpres is blocking all clients directly making a request to that url (that is, without a referer or origin header). That's all for this case.. i'm not supporting these individual edge cases which are not (or hardly) reproducable, and this does not look like legitimate too

**Comment by ceres-c** [comment]
Man, you gotta click. This driver works, it's not detected, you're just not human enough.
Click. A lot. Randomly.

**Comment by Syntist** [comment]
> Man, you gotta click. The driver itself is fine, it's not detected: you're just not human enough.
> Click. A lot. Randomly.

Sorry.. can you explain a bit? by what you mean click alot randomly? I would like to have a solution for this problem! As i wanna run it in headless mode.

**Comment by Syntist** [comment]
I have wrote a test case, which make the issue reproducible, So mainly the issue I am having is, If I click through driver I endup getting security reason, but If I click directly it get accepted.. @ultrafunkamsterdam would mean alot if you can look into it!
If you manage to open the bonus, you have to get new email/pass which haven't started bonus, so I can provide more.
You have to solve captcha manually! 

`import undetected_chromedriver as uc
from undetected_chromedriver import ChromeOptions
uc.install()
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver import TouchActions
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import time

options = ChromeOptions()
tempoptions = Options()
caps = DesiredCapabilities().CHROME
caps["pageLoadStrategy"] = "eager"
options.add_experimental_option('w3c', False)
mobile_emulation = { "deviceName": "iPhone X" }
options.add_experimental_option("mobileEmulation", mobile_emulation)
options.add_argument('--lang=en')
options.add_argument("--log-level=3")
count = 0

driver = webdriver.Chrome(executable_path='./chromedriver.exe', desired_capabilities=caps, chrome_options=options)
driver.set_page_load_timeout(60)
driver.get("https://login.aliexpress.com/h5.htm?type=login&fromMsite=true")


WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.ID, 'fm-login-id'))
    ).send_keys('syntist03@protonmail.com')

WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.ID, 'fm-login-password'))
    ).send_keys('zoner123')


input('pause')

WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, '.fm-button'))
    ).click()

time.sleep(4)

driver.get("https://sale.aliexpress.com/__mobile/daily-cash-out-gaming_m.htm?_addShare")


touch_actions = TouchActions(driver)

element = WebDriverWait(driver, 10).until(
            EC.presence_of_all_elements_located((By.CSS_SELECTOR , '.goBtn___3aVca'))
    )[2]
time.sleep(5)
element.click()

input('pause')`

**Comment by bhoken94** [comment]
@Syntist Can you have done the script? How you manage it? Can you pass me the script you wrote?

**Comment by SinanHasSped** [comment]
Fr pls gimme that code

**Comment by Syntist** [comment]
Is bonus buddy still working? I thought it got shutdown.
