### ISSUE TITLE
Issue with no install 

### ISSUE THREAD

**Issue by Eleskinex** [ultrafunkamsterdam/undetected-chromedriver#422]
ModuleNotFoundError: No Module named 'undetected_chromedriver'

Or 

AttributeError: module 'undetected_chromedriver' has no attribute 'install'

import undetected_chromedriver as uc
uc.install()

That is my code at the top of my python script

Yes i have correct version of chromedriver installed and google chrome

**Comment by brandfocus** [comment]
Have you run `pip3 install undetected_chromedriver`?

**Comment by ultrafunkamsterdam** [comment]
uc.install() is depreciated. sorry need to update readme

**Comment by eytannnaim** [comment]
Is the option to "patch" specific driver (https://pypi.org/project/selenium-wire/ in this case) obsolete?
