### ISSUE TITLE
chromedriver zip cache

### ISSUE THREAD

**Issue by Azureit** [ultrafunkamsterdam/undetected-chromedriver#427]
To avoid downloading the same chromedriver zip file, what about caching it at `data_path`
the name of the zip file cache file could be `"%s/%s_%s" % (self.data_path, self.version_full.vstring, self.zip_name)`
then after check the latest chromedriver version, it would be a mere check if file exists.

**Comment by zariradvance** [comment]
Yeah. I also wanna a solution about this. It's downloading every time I run the program. and takes some times (30sec).

**Comment by ultrafunkamsterdam** [comment]
https://pypi.org/project/selenium/
