### ISSUE TITLE
OSError: [Errno 8] Exec format error: 'CHROMEDRIVERLOCATION'

### ISSUE THREAD

**Issue by HeldGames** [ultrafunkamsterdam/undetected-chromedriver#435]
EDIT: It doesn't seem as if selenium will ever work with a raspberry pi/arm processor. So use Pyppeteer instead.

Hey,

Im running UC on a raspberry pi 4(running raspberry Pi OS)  (Arm processor)

Im trying to run:
```
import undetected_chromedriver as uc
driver = uc.Chrome()
driver.get("http://www.google.com")
```

Another way I thought it might work:
```
import undetected_chromedriver as uc
driver = uc.Chrome(browser_executable_path='/usr/lib/chromium-browser/chromedriver')
driver.get("http://www.google.com")
```

Outputs same error:
```
Traceback (most recent call last):
  File "/home/pi/Desktop/Test.py", line 2, in <module>
    driver = uc.Chrome()
  File "/home/pi/.local/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 369, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__
    self.service.start()
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/.local/share/undetected_chromedriver/chromedriver'
```
(However it still opens chromium, but opens default window(chrome://whats-new/?auto=true) (Not google.com))

Actually working example in Selenium:
```
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

service = Service('/usr/lib/chromium-browser/chromedriver')
driver = webdriver.Chrome(service=service)
driver.get("http://www.google.com")
```

Current version of chromium:
ChromeDriver 95.0.4638.78 (4cfe4a3e1a37cb8d4d57324c584f81aafc35a81b-refs/branch-heads/4638@{#1010})
Chromium-browerser 95.0.4638.78

Can someone tell me, what I'm missing?
Let me know if you need more info

Thanks
-Held

EDIT:
I think the issue might lie in the way the patch works. A Raspberry PI is using an arm-processor. However, as I understand the code, UC looks for a 64Bit file... If someone has a workaround/another idea please let me know
[
    if platform.endswith("linux"):
        zip_name %= "linux64"
        exe_name %= ""](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/a4cc4a8b72691a3f5462b6f23973727e2b03da9e/undetected_chromedriver/patcher.py#L29-L31)

**Comment by nirvana1122** [comment]
I had the same issue, and updating chrome to the latest version 97 fixed the issue. 97 was released on 2022-01-04. hence the issue. 
[
(https://en.wikipedia.org/wiki/Google_Chrome_version_history)
]

**Comment by minibox161** [comment]
> I had the same issue, and updating chrome to the latest version 97 fixed the issue. 97 was released on 2022-01-04. hence the issue.

He has a raspberry pi .What does this have to do with the chromium version? He is asking how to run uc.Chrome() with the existing chromedriver

**Comment by HeldGames** [comment]
> 

Well as @minibox161 explained I have a Raspberry Pi, meaning I'm running Chromium insted.
Can however inform you that the current version is the newest (95.0.4638.78-rpt5)

Thanks for the suggestion though

**Comment by kzodda** [comment]
@HeldGames How did you fix this issue? Wondering for my own project.
