### ISSUE TITLE
Chromedriver raspberry pi issue

### ISSUE THREAD

**Issue by loss-and-quick** [ultrafunkamsterdam/undetected-chromedriver#436]
I have a project and I want to run it on a raspberry pi,also I have a ready-made chromedriver,but how can I run undetect_chromedriver with a ready-made binary

**Comment by HeldGames** [comment]
@minibox161 if you get it working on a Pi please let me know

**Comment by minibox161** [comment]
> @minibox161 if you get it working on a Pi please let me know

@HeldGames ,I don't think it will work on the raspberry pi because the authors removed the ability to patch the prepared driver

**Comment by HeldGames** [comment]
@minibox161 Use Pyppeteer instead.

**Comment by loss-and-quick** [comment]
> @minibox161 Use Pyppeteer instead.

Thanks,but there is more better option,ulixee hero
