### ISSUE TITLE
Being detected by cloudflare for controller.com

### ISSUE THREAD

**Issue by PeterNSteinmetz** [ultrafunkamsterdam/undetected-chromedriver#437]
Using version 3.1.3. When attempting to access https://controller.com it is being detected despite using this driver.

    options = webdriver.ChromeOptions()
    options.add_argument("start-maximized")
    driver = uc.Chrome(options=options)
    driver.get('https://www.controller.com/listings/search?Category=6&ModelGroup=35%20BONANZA&Manufacturer=BEECHCRAFT')

    time.sleep(10)  # Let the user actually see something!

Just shows their usual anti-bot page.

**Comment by PeterNSteinmetz** [comment]
Not sure of this yet. I realized I may not be able to use a pre-existing search URL, like that.

**Comment by PeterNSteinmetz** [comment]
I tested it again, and it is being detected and showing the anti-bot page even for the url 'https://www.controller.com'. It appears to first be producing a 403 error. 

How is cloudflare doing this?

**Comment by sufyanhamid** [comment]
@PeterNSteinmetz try this one.

import undetected_chromedriver as uc
import time

options = uc.ChromeOptions(delay=0)
options.add_argument('--user-data-dir=c:\\temp\\profile2')
options.add_argument('--no-first-run --no-service-autorun --password-store=basic')
driver = uc.Chrome(options=options)
driver.get('https://www.controller.com/')

**Comment by PeterNSteinmetz** [comment]
That seems to have done the trick. It now leaves the page open as long as the program waits. After the wait is over, the program finishes and then the browser goes to the pardon our interruption page.

**Comment by pjrobertson** [comment]
> options = uc.ChromeOptions(delay=0)

This gives `TypeError: __init__() got an unexpected keyword argument 'delay'` - not sure what version of Selenium/uc you're using?

I'm on UC 3.1.3 and Selenium 4.1.0

**Comment by sufyanhamid** [comment]
@pjrobertson share the full code.

**Comment by pjrobertson** [comment]
```python
import undetected_chromedriver as webdriver
options = webdriver.ChromeOptions(delay=0)
```
