### ISSUE TITLE
Still gets detected with Recaptcha v3

### ISSUE THREAD

**Issue by Avnsx** [ultrafunkamsterdam/undetected-chromedriver#44]
Any website that uses recaptcha v3 and which I try to automate with this "undetected" version of the chromedriver just makes recaptcha v3 respond with "There was an error trying to send your message. Please try again later."

So I'm sure it's detected :)

**Comment by TJM4** [comment]
Recaptcha v3 works for me (and returns a score of 0.9) as long as your not in headless mode

**Comment by Avnsx** [comment]
@TJM4 The point of this python code, is to basicaly use selenium, chromedriver go to the website and enter a name & email and get a free Trial from them. I've additionaly switched IP with NordVpn, everything was pretty much useless... The website uses recaptcha v3, and yes for me I've done the same https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php gives me a score of 0.9 but it doesn't matter; the website always errors out with "There was an error trying to send your message. Please try again later." which is, as I think caused by recaptcha v3 as when you press that Send/Submit button it re-validates your submit through recaptcha and it fails there. File with the python code inside should be attached within this response.
If you bother to help in any way, thanks in advance. ✌
[undetectedChromedriverTest.txt](https://github.com/ultrafunkamsterdam/undetected-chromedriver/files/5472686/undetectedChromedriverTest.txt)

**Comment by TJM4** [comment]
When I run that code I think it works, I get "Thank you for your message. It has been sent."

Are you running the latest version of undetected chromedriver?

**Comment by Avnsx** [comment]
> When I run that code I think it works, I get "Thank you for your message. It has been sent."
@TJM4 I am very confused, the code wasn't working for me yesterday. I've just tried it myself again just **now**, I don't really know why, but it appears to work for me aswell... 👀 Well, I guess it has been an temporary issue / block yesterday, within the website itsself then. Anyways thanks for taking your time and attempting to help me out 👌 

One more question, how is the further detection of undetected chrome driver handled? If I don't update chrome or chromedriver and keep sticking to this version, will it stay undetected forever or do I need to pull updates, or does your undetected chromedriver update itsself, when y'all release an update for it?

**Comment by TJM4** [comment]
No problem, it's worth updating it incase any patches are made to hide new detection methods
