### ISSUE TITLE
SeleniumWire AuthProxy Not Working

### ISSUE THREAD

**Issue by Vinyzu** [ultrafunkamsterdam/undetected-chromedriver#442]
This is my code:
```
from multiprocessing import freeze_support
if __name__=='__main__':
    freeze_support()
    import seleniumwire.undetected_chromedriver as uc
    from seleniumwire import webdriver

    chrome_options = webdriver.ChromeOptions()
    chrome_options.headless = False
    seleniumwire_options = {
    'disable_capture': True,
    'proxy': {
        'http': 'http://...',
        'https': 'http://...',
        }
    }
    # seleniumwire_options = {'proxy': {'https': 'http://...','http': 'http://...'}}
    driver = uc.Chrome(options=chrome_options, seleniumwire_options=seleniumwire_options)

    driver.get('https://api.myip.com/')
    input()
```
My proxy is US but when i look at the page i see country is germany (my ips country)
I tried everything i have the newest version of uc and seleniumwire but i just cant get it to work :/
wtf am i doing wrong

**Comment by Vinyzu** [comment]
Ive triplechecked my proxy and everything i cant help myself

**Comment by webdeveloperlv** [comment]
the same problem here

**Comment by webdeveloperlv** [comment]
any news?

**Comment by webdeveloperlv** [comment]
This is quite an important function. Could you fix it?

**Comment by adv-zl** [comment]
Same issue

**Comment by adv-zl** [comment]
Starting from version 3.0.6, proxy stopped working

**Comment by RedGlare96** [comment]
Still works if you use v2. Just change the import statement to:

```
import seleniumwire.undetected_chromedriver.v2 as uc
```
Proxy does not work with the new version 3 of UC unfortunately

**Comment by ultrafunkamsterdam** [comment]
> > Starting from version 3.0.6, proxy stopped working
> 
> Tried to install older undetected_chromedriver with pip `pip install undetected_chromedriver==`3.0.5`, but get an error.
> 
> ```
> ERROR: No matching distribution found for undetected-chromedriver==3.0.5
> ```
> 
> Isn't it possible to install an older version?

install undetected-chromedriver (dash not underscore)
