### ISSUE TITLE
Install more

### ISSUE THREAD

**Issue by intopes** [ultrafunkamsterdam/undetected-chromedriver#45]
Hello!

Have a possibility to install and execute this "undetected-chromedriver" like a "original Chromedriver" ?? Install and execute without any command line "pip"?  

Only download the archive and then execute via python + selenium point via executable_path ?
It would be possible?

Many thanks!

**Comment by ultrafunkamsterdam** [comment]
don't know exactly what you mean. but i'll try:

1 - yes just run this program first. patched driver will be in the current working directory. but probably is not going to work since you're missing some pre processing.  

2 - copy and paste source code

3 - you can use:

```python
import undetected_chromedriver as uc
uc.install()

from selenium.webdriver import Chrome
driver = Chrome()```
