### ISSUE TITLE
Parallelization does not work as expected

### ISSUE THREAD

**Issue by KrzysztofKalisiak** [ultrafunkamsterdam/undetected-chromedriver#451]
Hi, I tried to open multiple Chrome drivers using multiprocessing/threads and scrap sites at once while starting each driver with different option. 
My idea was to fill screen with small browsers and scrap them parallelly allowing user to monitor if no driver is blocked (ideally each through different proxy) and eventually fill reCaptha manually.
Sadly I am facing at least few problems connected with parallel:
1. Pools are not allwed to have children
2. Even if I am able to spawn processes using threads chromedriver seems to be locked by one process 
3. Even if not 1 and 2, chromedriver is throwing random errors.
Linux btw
There is no sense for now to show code and fails as its quite complicated, is there anyone who figured out how to do it correctly?

**Comment by ultrafunkamsterdam** [comment]
you could try using Chrome(use_subprocess=True)  - this makes sure there are no parentless children spawned. 

that having said:

You're making it too hard on yourself. 
Chrome is already managing processes. Watch htop (shift H/K , iirc).
MultiProcess chromedrivers makes no sense as it's purely some IO. Chrome is doing the heavy lifting, so why just don't use main thread and use multiple windows and tabs?

Been there done that, the only result was more headaches.

```python
In [1]: import undetected_chromedriver as uc

In [2]: driver = uc.Chrome()

# new window
In [3]: driver.execute_cdp_cmd(
   ...:     "Target.createTarget", {"url": "https://newwindow.com", "newWindow": True}
   ...: )
Out[3]: {'targetId': '584B669457E275BA1371BC789D59909C'}

In [4]: driver.window_handles
Out[4]: 
['CDwindow-7236A77AD48EBFCB359D786A4D512CDC',
 'CDwindow-584B669457E275BA1371BC789D59909C']

# switch between windows
In [5]: driver.switch_to.window(driver.window_handles[-1])
In [6]: driver.get("https://pornhub.com")

# create extra tab in current window, as many as you'd like
In [7]: driver.execute_cdp_cmd(
    ...:     "Target.createTarget", {"url": "https://newtab.com", "newWindow": False}
    ...: )
Out[7]: {'targetId': 'F194B52134B8F486036AD2FBA22336E2'}


In [8]: driver.switch_to.window(driver.window_handles[0])
In [9]: driver.get("https://xnxx.com")

```

**Comment by youpsla** [comment]
Here is my working solution:
```python
from multiprocessing import Pool
import undetected_chromedriver as uc
import time


def parse_using_selenium(url):
    cpt = 0
    driver = uc.Chrome(use_subprocess=True)
    while cpt < 5:
        cpt += 1
        driver.get(url)
        time.sleep(2)
    

if __name__ == "__main__":
    urls = ['https://google.com', 'https://yahoo.com', 'https://pastebin.com']
    pool = Pool()

    for url in urls:
        result = pool.apply_async(parse_using_selenium, [url])

    pool.close()
    pool.join()
```

Notice `use_subprocess=True` as `uc.Chrome()` parameter.

**Comment by ultrafunkamsterdam** [comment]
Here is a working solution too, without using multiple processes to do dome basic input/output

```python
import asyncio
import undetected_chromedriver as uc

driver = uc.Chrome()
urls = ["https://google.com", "https://yahoo.com", "https://pastebin.com"]

async def parse(url, window):
    cpt = 0
    while cpt < 5:
        cpt += 1
        driver.switch_to.window(window)
        driver.get(url)
        await asyncio.sleep(2)

for url in urls:
    driver.execute_cdp_cmd("Target.createTarget", {"url": url, "newWindow": False})

url_handle_pairs = list(zip(urls, driver.window_handles)) # bundles url and window id

asyncio.run(asyncio.wait(map(lambda _: parse(*_), url_handle_pairs)))

for _ in reversed(driver.window_handles): # shutdown
    driver.switch_to.window(_)
    driver.close()
```

**Comment by adv-zl** [comment]
> Here is a working solution too, without using multiple processes to do dome basic input/output
> 
> ```python
> import asyncio
> import undetected_chromedriver as uc
> 
> driver = uc.Chrome()
> urls = ["https://google.com", "https://yahoo.com", "https://pastebin.com"]
> 
> async def parse(url, window):
>     cpt = 0
>     while cpt < 5:
>         cpt += 1
>         driver.switch_to.window(window)
>         driver.get(url)
>         await asyncio.sleep(2)
> 
> for url in urls:
>     driver.execute_cdp_cmd("Target.createTarget", {"url": url, "newWindow": False})
> 
> url_handle_pairs = list(zip(urls, driver.window_handles)) # bundles url and window id
> 
> asyncio.run(asyncio.wait(map(lambda _: parse(*_), url_handle_pairs)))
> 
> for _ in reversed(driver.window_handles): # shutdown
>     driver.switch_to.window(_)
>     driver.close()
> ```

What if you need unique proxy on each tab?

**Comment by ultrafunkamsterdam** [comment]
> > Here is a working solution too, without using multiple processes to do dome basic input/output
> > ```python
> > import asyncio
> > import undetected_chromedriver as uc
> > 
> > driver = uc.Chrome()
> > urls = ["https://google.com", "https://yahoo.com", "https://pastebin.com"]
> > 
> > async def parse(url, window):
> >     cpt = 0
> >     while cpt < 5:
> >         cpt += 1
> >         driver.switch_to.window(window)
> >         driver.get(url)
> >         await asyncio.sleep(2)
> > 
> > for url in urls:
> >     driver.execute_cdp_cmd("Target.createTarget", {"url": url, "newWindow": False})
> > 
> > url_handle_pairs = list(zip(urls, driver.window_handles)) # bundles url and window id
> > 
> > asyncio.run(asyncio.wait(map(lambda _: parse(*_), url_handle_pairs)))
> > 
> > for _ in reversed(driver.window_handles): # shutdown
> >     driver.switch_to.window(_)
> >     driver.close()
> > ```
> 
> What if you need unique proxy on each tab?

Maybe i missed something, but how do you set proxies per tab (the native way, no addons) ?

the multiprocessing/threading "issue" is resolved in the coming update. Easily by randomizing the chromedriver filename.
