### ISSUE TITLE
Service /root/.local/share/undetected_chromedriver/chromedriver unexpectedly exited. Status code was: -6

### ISSUE THREAD

**Issue by DiTo97** [ultrafunkamsterdam/undetected-chromedriver#454]
I tried to make use of your modified Selenium's Chrome driver to scrape a Cloudfare-protected auction website. In all my web-scraping projects until now (just a handful), I always used the standard Selenium package with a custom proxy rotator of mine that tries to hide my IP address systematically upon request. It is kind of a gimmick, but it has always worked so far. This time it has been trickier, and somewhat deceiving, because sometimes it runs smoothly as expected (on **Google Colab**), while some other times I get blocked by the anti-bot logic beforehand no matter what I do. Since I require more consistent results, I decided to switch to your custom package, as it seemed to have everything that I was looking for. Unfortunately, I cannot make it to run even with the sample endpoint from the docs, because as soon as I run it, the error in the title pops up.

I am not sure if you consider this a replica of #163, but I think it's not, because I have actual experience working with Selenium web-drivers on Google Colab unlike the other poster, and I know for a fact that they are not blocked by Google.

```console
foo@bar:~$ apt-get update && \
           apt install chromium-chromedriver
```

For reference, I will paste below my inconsistent, but running, code with the original Selenium package...

```console
foo@bar:~$ cp /usr/lib/chromium-browser/chromedriver /usr/bin
foo@bar:~$ pip install -U pip selenium==4.1.0
```

```python
import sys

sys.path.insert(0, '/usr/bin/chromedriver')

from selenium import webdriver


options = webdriver.ChromeOptions(...)

.
.
.

driver = webdriver.Chrome('chromedriver', options=options)
driver.get('https://nowsecure.nl')
```

...and the equivalent non-functioning code with your package:

```console
foo@bar:~$ cp /usr/lib/chromium-browser/chromedriver /usr/bin
foo@bar:~$ pip install -U pip undetected-chromedriver==3.1.3
```

```python
import sys

sys.path.insert(0, '/usr/bin/chromedriver')

import undetected_chromedriver as uc


driver = uc.Chrome()
driver.get('https://nowsecure.nl')
```

When using your package, I tried both with installing Chromium's driver via apt call, as shown at the beginning, as well as with letting your package's pip call do all the work in the background, but I get the very same exception when I run it.

Do you have any idea why this might be the case? I understand that your package is not supposed to run everywhere, but there are a few inherent advantages in running such a program on Google Colab, rather than on local machinery. If you could share your thoughts on the issue, I could try to solve it on my own by submitting a PR to your repository.

**Comment by DiTo97** [comment]
On a side note, I just tried turning headless mode on and off, but nothing changes.

**Comment by FloatingMind12** [comment]
It's been months but the answer is in #108
