### ISSUE TITLE
Is it possible to run it on raspberry?

### ISSUE THREAD

**Issue by framilano** [ultrafunkamsterdam/undetected-chromedriver#459]
It works perfectly on Windows and Linux 64bit but I'm getting
`OSError: [Errno 8] Exec format error: '/home/pi/.local/share/undetected_chromedriver/chromedriver'`
whenever I launch my script on Raspberry Pi, any idea?

**Comment by ArevomEisvolk** [comment]
Hello, the Pi have an armvl7 processor.
The Chromedriver in this repo is not compatible.
You can use this: 
https://github.com/ArevomEisvolk/undetected-chromedriver

**Comment by framilano** [comment]
Perfect thanks!

**Comment by juhacz** [comment]
@ArevomEisvolk Hi, I'm begginer in python, how can I install this  on my rp4 from this forked repo?

**Comment by ArevomEisvolk** [comment]
@juhacz you must clone the repo and go in the folder. Then run pip3 install .

**Comment by juhacz** [comment]
I try, installed successful, but my program doesn't work:
When I usung 3.0.3 with executable_path
driver = Chrome(options=options, executable_path=driver_path)
All working great.

Error when runing:
---------------
Traceback (most recent call last):
  File "get_json.py", line 319, in <module>
    main(cats)
  File "get_json.py", line 175, in main
    driver = Chrome(options=options)
  File "/home/pi/python/allegronew/lib/python3.7/site-packages/undetected_chromedriver/__init__.py", line 212, in __init__
    patcher.auto()
  File "/home/pi/python/allegronew/lib/python3.7/site-packages/undetected_chromedriver/patcher.py", line 148, in auto
    release = self.fetch_release_number()
  File "/home/pi/python/allegronew/lib/python3.7/site-packages/undetected_chromedriver/patcher.py", line 170, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by ArevomEisvolk** [comment]
Can you show me your Code?

**Comment by ArevomEisvolk** [comment]
Hey Sry it is my failure.
I fixed the URL failure but dont except that all functions are working.

**Comment by juhacz** [comment]
Now I have error 

selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:41071
from session not created: This version of ChromeDriver only supports Chrome version 94
Current browser version is 92.0.4515.98


I check apt list --upgradable
and no new version of Chrome not found.

**Comment by ArevomEisvolk** [comment]
Hello, I added  more chrome versions

**Comment by juhacz** [comment]
I check, now it's runing, but it did't work with selenium-wire?
I'm using selenium-wire  with inrecept request headers,
https://pypi.org/project/selenium-wire/#example-add-a-request-header

`from seleniumwire.undetected_chromedriver import Chrome, ChromeOptions`

and chromedriver ignoring intercepted headers :(

**Comment by ArevomEisvolk** [comment]
Sry, i can't help you with this problem.

**Comment by juhacz** [comment]
Ok, thank You for help!

**Comment by rtrive** [comment]
Hi guys, is there any chance to support rasp? I'm running it but unfortunately, the chrome driver binary downloaded is not the right version

**Comment by ovciina** [comment]
Is this still supported??

**Comment by JakobReal-rgb** [comment]
> 

^what do you mean with run pip3 install?
