### ISSUE TITLE
Can uc be implemented into GoLogin? 

### ISSUE THREAD

**Issue by fantarics** [ultrafunkamsterdam/undetected-chromedriver#461]
I have tried connectin the GoLogin with selenium (original) and it worked fine. However, the website I need access to is using CloudFlare protection. Here is the working code: 
`    
    import time
    from selenium import webdriver
    from selenium.webdriver.common.by import By
    from selenium.webdriver.chrome.service import Service
    from selenium.webdriver.chrome.options import Options
    from gologin import GoLogin

    if __name__ == '__main__':
    
        #gl = GoLogin({
        #'token': 'some_token',
        # 'profile_id': 'some_profile_id',
        #})
        chrome_driver_path = 'something/chromedriver.exe'

        debugger_address = gl.start()
        chrome_options = Options()
        chrome_options.add_experimental_option("debuggerAddress", debugger_address)
        driver = webdriver.Chrome(executable_path=chrome_driver_path, options=chrome_options)
        driver.get("https://protectedsite.com/login")
`
    
This works well: it opens a Orbita-browser and then opens a website through the orbita browser

This is the code when I try using the UC with gologin: 

`    
    import time
    from sys import platform
    import undetected_chromedriver as uc
    from gologin import GoLogin

    if __name__ == '__main__':

        gl = GoLogin({
         'token': 'some_token',
         'profile_id': 'some_profile_id',
        })

        chrome_driver_path = 'something/chromedriver.exe'

        debugger_address = gl.start()
        chrome_options = uc.ChromeOptions()
        chrome_options.add_experimental_option("debuggerAddress", debugger_address)
        driver = uc.Chrome(executable_path=chrome_driver_path, options=chrome_options)

        driver.get("https://protectedsite.com/login")
        driver.implicitly_wait(10)
`

When I execute this code, the orbita-browser opens (gl.start() is what opens it) and then the driver.get() command opens another Chrome window that opens the website. The code seems identical to the code with selenium, is there something I missed?
Is it because of the add_experimental_option()

**Comment by ultrafunkamsterdam** [comment]
yes. using UC you don't specify path to webdriver , no executable path. and surely no debugger.  all is managed inside. and will might interfere

**Comment by fantarics** [comment]
so, is there any way to do it with the uc?

**Comment by Tatuck** [comment]
Hello. Have you found out how to use an executable path?
