### ISSUE TITLE
I want to port it to .NET need help

### ISSUE THREAD

**Issue by nimix3** [ultrafunkamsterdam/undetected-chromedriver#469]
Hello dude,

I'm not familiar too much with Py and really want to port this project to .NET based languages (C#), I need some helps if anyone can help me please let me know, I worked with Selenium and mechanism to be undetectable before and how patch it.

Thanks in advance

**Comment by henzycuong1** [comment]
I have tried but not worked well. You should open chrome browser by the process after that connecting chrome driver to the browser by remote-debug

**Comment by nimix3** [comment]
I do it very well in C# .NET and tested works fine. It is really different way and methods than Py but same mechanism used.
I can help anyone need helps

**Comment by okrulik** [comment]
@nimix3  can you share with  me your  C# implementation?  Thanks...

**Comment by emre-gon** [comment]
Porting the patcher requires a binary string regex replace. 

Is there an equivalent in C# for Python's b'string'?
