### ISSUE TITLE
Post request

### ISSUE THREAD

**Issue by luistiagos** [ultrafunkamsterdam/undetected-chromedriver#473]
I need do a post request in webdriver, but dont had this function inside? 
What I can do to make a post request with undetected-chromedriver?

With firefox driver I can do this:
from seleniumrequests import Firefox

webdriver = Firefox()
response = webdriver.request('POST', 'url here', data={"param1": "value1"})
print(response)

But this is not undetectable.
What I can do to make a post request with this webdriver?

**Comment by advaitkanthalia** [comment]
+1, any way to do a post request?

**Comment by oneandonlyjason** [comment]
Anyone knows a Way?

**Comment by ultrafunkamsterdam** [comment]
driver.execute_script(""""return  fetch(url, {method:"POST", 
... options})"""")    ?

**Comment by ShaneOss** [comment]
import undetected_chromedriver as uc
from selenium.webdriver.common.by import By

class CustomUCWebDriver(uc.Chrome):
    def post(self, url, data):
        return self.execute_script(f"""
            return fetch("{url}", {{
                method: "POST",
                body: '{data}',
                headers: {{
                    "Content-Type": "application/json;charset=UTF-8"
                }}
            }})
            .then(response => response.text());
        """)


# Create an instance of CustomUCWebDriver
options = uc.ChromeOptions()
options.add_argument("--headless=new")  # for hidden mode
driver = CustomUCWebDriver(options=options)

# Make a POST request and capture the response
response_data = driver.post("https://example.com", '{"key": "value"}')

# Print the response data
print(response_data)

**Comment by lexuantaypro** [comment]
greate !

> ```
> import undetected_chromedriver as uc
> from selenium.webdriver.common.by import By
> 
> class CustomUCWebDriver(uc.Chrome):
>     def post(self, url, data):
>         return self.execute_script(f"""
>             return fetch("{url}", {{
>                 method: "POST",
>                 body: '{data}',
>                 headers: {{
>                     "Content-Type": "application/json;charset=UTF-8"
>                 }}
>             }})
>             .then(response => response.text());
>         """)
> 
> 
> # Create an instance of CustomUCWebDriver
> options = uc.ChromeOptions()
> options.add_argument("--headless=new")  # for hidden mode
> driver = CustomUCWebDriver(options=options)
> 
> # Make a POST request and capture the response
> response_data = driver.post("https://example.com", '{"key": "value"}')
> 
> # Print the response data
> print(response_data)
> ```

nice !

**Comment by nagarou-fr** [comment]
Hello, I tried to make a post request with the code but I got an error: Exception has occurred: JavascriptException Message: javascript error: Failed to fetch Thank you for your help
