### ISSUE TITLE
What can I do to keep the driver from shutting down?

### ISSUE THREAD

**Issue by elventyildiran** [ultrafunkamsterdam/undetected-chromedriver#476]
Hello, for example, when I want to connect to "https://google.com", I automatically connect with undetected-chromedriver, but when I connect, the drive shuts down.
```
import undetected_chromedriver as uc

if __name__ == '__main__':
    driver = uc.Chrome()
    driver.get('https://google.com')
```
Actually, I can add the code "time.sleep(10) etc." here and create a standby. But that's not the way I want it. How do I ensure that it does not turn off after connecting to the site until I issue a command?

**Comment by sebdelsol** [comment]
learn [python](https://www.programiz.com/python-programming/methods/built-in/input) ?

**Comment by elventyildiran** [comment]
> 

I think I know enough and at a basic level. Isn't it more reasonable to say "investigate this matter" instead of saying it?

**Comment by itsBIllyZee** [comment]
A way to prevent the driver from quitting is to monkey patch the __del__ method and setting use_subprocess to True:

```
import undetected_chromedriver as webdriver

class UC(webdriver.Chrome):
    def __init__(self, teardown):
        self.teardown = teardown
        super().__init__(use_subprocess=True)

    def __del__(self):
        if self.teardown:
            self.quit()

if __name__ == '__main__':
    with UC(teardown=False) as bot:
        bot.get("http://www.google.com/")
```
