### ISSUE TITLE
In Windows, multiprocess sometimes wont let drivers start due to PermissionsError in patcher

### ISSUE THREAD

**Issue by opqpop** [ultrafunkamsterdam/undetected-chromedriver#479]
I use multiprocess to start multiple undetected_chromedriver in each process, so that I can parallelize the work

However, for my windows computer (never happens with mac), sometimes some process will just not start the chrome driver, and I believe it's due to a PermissionsError not being able to open up the downloaded and unzipped file. Here's a stack trace:

```
  File "C:\Users\Mark\scraper\venv\lib\site-packages\undetected_chromedriver\__init__.py", line 208, in __init__
    patcher.auto()
  File "C:\Users\Mark\scraper\venv\lib\site-packages\undetected_chromedriver\patcher.py", line 121, in auto
    self.unzip_package(self.fetch_package())
  File "C:\Users\Mark\scraper\venv\lib\site-packages\undetected_chromedriver\patcher.py", line 175, in unzip_package
    zf.extract(self.exe_name, os.path.dirname(self.executable_path))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1616, in extract
    return self._extract_member(member, path, pwd)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1687, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Mark\\appdata\\roaming\\undetected_chromedriver\\chromedriver.exe'
2022-02-03 01:10:09 [twisted] CRITICAL:
```

The first process that calls this however will always go through, and the chrome window pops up, but sometimes subsequent processes never pops a window and exits with this error. 

Any ideas what I can do to try to fix this? I've tried setting browser_executable_path but that seems to still allow patcher to keep trying to patch. Should I try to disable the patcher and always have it use the latest chromedriver downloaded in my local folder? Let me know if there's anything else I can provide / help out with. Love this project and its critical to some of our workload!

Code
```
 options = uc.ChromeOptions()

            options.add_argument("--disable-extensions")
            options.add_argument("--disable-popup-blocking")
            options.add_argument("--profile-directory=Default")
            options.add_argument("--ignore-certificate-errors")
            options.add_argument("--disable-plugins-discovery")


            dr = uc.Chrome(
                options=options,
                # tried adding this but didnt do anything, I think because it only sets the option binary in the uc init, while the patcher continues to run
                # browser_executable_path=cfgutil.get_chrome_driver_path(),
            )

**Comment by albrechtmate** [comment]
Hello, have you solved the multiprocessing problem? I still need some help with it :/

**Comment by sebdelsol** [comment]
you could create the drivers first then launch your processes. But using processes seems like overkill when threads are good enough and undetected_chromedriver already creates a subprocess for its driver.
```python
from concurrent.futures import ThreadPoolExecutor, as_completed
import undetected_chromedriver as webdriver

def create_driver():
    options = webdriver.ChromeOptions()
    return webdriver.Chrome(options=options)


def scrape_job(driver):
    print("scraping...")

    driver.quit()
    return "scrape result"


if __name__ == "__main__":
    N_SCRAPE_JOBS = 3
    with ThreadPoolExecutor(max_workers=N_SCRAPE_JOBS) as executor:
        futures = (
            executor.submit(scrape_job, create_driver()) for _ in range(N_SCRAPE_JOBS)
        )

        for future in as_completed(futures):
            print(future.result())
```

**Comment by sebdelsol** [comment]
if your really need to create drivers in your threads or processes, you want to patch chromedriver.exe first then change its permission to read-only so that any further drivers creation [won't patch it](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/a4cc4a8b72691a3f5462b6f23973727e2b03da9e/undetected_chromedriver/patcher.py#L109)

```python
import os
import stat
import undetected_chromedriver as webdriver

if __name__ == "__main__":
    patcher = webdriver.Patcher()
    # add write permission to chromdriver.exe and patch it
    os.chmod(patcher.executable_path, stat.S_IREAD + stat.S_IWRITE)
    patcher.auto()
    # make chromedriver.exe read-only to prevent any further patch
    os.chmod(patcher.executable_path, stat.S_IREAD)

    # then launch your threads that create drivers
```

**Comment by opqpop** [comment]
Thanks, I've since found another problem with a 12 process mac I'm using: sometimes 2-4 drivers start and just sit there and do nothing, because it ran into this issue:

```
Traceback (most recent call last):
  File "/Users/markx/undetected-chromedriver/undetected_chromedriver/__init__.py", line 375, in __init__
    super(Chrome, self).__init__(
  File "/Users/markx/scraper/venv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/Users/markx/scraper/venv/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__
    self.service.start()
  File "/Users/markx/scraper/venv/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/Users/markx/scraper/venv/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /Users/markx/Library/Application Support/undetected_chromedriver/chromedriver unexpectedly exited. Status code was: -9
```

I was able to fix this by modifying uc driver init to skip the patching, and just use an already patched chromedriver path.

This was before I saw your above solution to do an initial patch and lock it to prevent the processes from doing their own patches. However, just tried above solution and for some reason it's still getting this error code. Any ideas?

I will continue digging to check whether making it read-only truly prevents the patcher from not doing anything. Thanks for the help so far

**Comment by opqpop** [comment]
re: passing in the drivers to the processes, I've tried that in the past to conclude that webdrivers aren't pickle-able, so that it just crashes trying to pass it as a parameter. However, I haven't tried your suggested solution to see whether it gets around this problem, will give it a shot soon

**Comment by opqpop** [comment]
> if you really need to instantiate drivers in your threads or processes, you want to patch chromedriver.exe first then make it read-only so that any further driver instantiations [won't patch it](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/a4cc4a8b72691a3f5462b6f23973727e2b03da9e/undetected_chromedriver/patcher.py#L109)
> 
> ```python
> import os
> import stat
> import undetected_chromedriver as webdriver
> 
> patcher = webdriver.Patcher()
> # add write permission to chromdriver.exe and patch it
> os.chmod(patcher.executable_path, stat.S_IREAD + stat.S_IWRITE)
> patcher.auto()
> # make chromedriver.exe read-only to prevent any further patch
> os.chmod(patcher.executable_path, stat.S_IREAD)
> 
> # then launch your threads that instantiate drivers
> ```

hmm it seems like making it read-only doesnt prevent the unlink from happening (doesnt return PermissionsError, it just deletes the file and keeps going)

```
(Pdb) os.stat(patcher.executable_path)
os.stat_result(st_mode=33024, st_ino=249507007, st_dev=16777222, st_nlink=1, st_uid=501, st_gid=20, st_size=16498136, st_atime=1644116290, st_mtime=1644116290, st_ctime=1644116290)
(Pdb) os.unlink(patcher.executable_path)
(Pdb)
```

**Comment by sebdelsol** [comment]
good catch. Actually it works fine on Windows but it's different for POSIX. So it would be something like this:
```python
import os
import stat
import undetected_chromedriver as webdriver


def lock_file(filename, lock=True):
    permissions = stat.S_IREAD
    if not lock:
        permissions += stat.S_IWRITE

    if webdriver.IS_POSIX:
        filename = os.path.dirname(filename)
    os.chmod(filename, permissions)


if __name__ == "__main__":
    patcher = webdriver.Patcher()
    # unlock chromdriver.exe and patch it
    lock_file(patcher.executable_path, lock=False)
    patcher.auto()
    # lock chromedriver.exe to prevent any further patch
    lock_file(patcher.executable_path)

   # instanciate and use drivers in threads 

```
The only caveat is that if you run concurrently a lot of chromedriver.exe with the same signature you might end up being detected. In that case you would need to patch a different chromedriver.exe for each thread

**Comment by opqpop** [comment]
> The only caveat is that if you run a lot of chromedriver.exe concurrently with the same signature you might end up being detected. In that case you would need to patch a different chromedriver.exe for each thread, and I don't see a solution for that without modifying patcher.py or monkey patching Patcher.

That's a very interesting point! I'd definitely want this so will give it a try. Just to make sure I understand, if I'm doing say 12 processes, I'd patch 12 times, but make sure they put the chromedriver in a different path to not overwrite each other. Now they will each use a different signature because they are using a different chromedriver.

And because they no longer share the file, there would not be a need to do the locking solution above anymore, since hopefully the "chromedriver unexpectedly exited. Status code was: -9" and "PermissionError: [Errno 13] Permission denied:"  errors would no longer happen.

Does my understanding sound correct? I'll play around with this approach today.

**Comment by sebdelsol** [comment]
that's exactly the idea and it would be even better to download the zip only once.

**Comment by sebdelsol** [comment]
oh I've found another potential permission error : after failing to delete the driver the patcher checks if the driver is patched and only then it returns without any more file operation on the driver. But `Patcher.is_binary_patched` has to open the file to read it and it's not thread safe... so after patching the driver your need to monkey patch this method to always return `True` .
```python
Patcher.is_binary_patched = lambda self: True
```
