### ISSUE TITLE
py to exe file not working

### ISSUE THREAD

**Issue by albrechtmate** [ultrafunkamsterdam/undetected-chromedriver#483]
Hello,

I was trying to convert .py to .exe with two different methods(auto-py-to-exe, pyinstaller). The conversation was successfully but when I start the exe file the chromedriver doesnt shows up.

Can anybody fix this problem?

**Comment by SoHardDay** [comment]
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/405#issuecomment-1030774173

**Comment by emanrodriguez** [comment]
Any solution found? I'm experiencing the same issue. Even with reverting back to 3.0.3 same error occurs.
