### ISSUE TITLE
Auth Proxies

### ISSUE THREAD

**Issue by JuandeJuni** [ultrafunkamsterdam/undetected-chromedriver#49]
There's any possibility to run the browser with auth Proxies? (the ones with this format ip:port:user:pass)

**Comment by ultrafunkamsterdam** [comment]
yes, check example.

**Comment by MennovDijk** [comment]
Hi @JuandeJuni, did you git this working? I am finding it difficult to get get it to work myself. 
This is the code I am using currently:

`options.add_argument(f'--proxy-server=https://{proxyuser}:{proxypass}@{proxyip}:{proxyport}')`

**Comment by JuandeJuni** [comment]
> Hi @JuandeJuni, did you get this working? I am finding it difficult to get get it to work myself.
> This is the code I am using currently:
> 
> `options.add_argument(f'--proxy-server=https://{proxyuser}:{proxypass}@{proxyip}:{proxyport}')`

Yeah i have the same issues i'm able to run with a no authentification proxy but when i try authentificated it dosen't work. Owner said I should check example but the example is without authenticated proxy

**Comment by MennovDijk** [comment]
Alright, so you didn't get it to work I assume. Too bad since I only use authenticated proxies. @ultrafunkamsterdam any plans to release an option to use authenticated proxies in the near future? Would be really nice to have!

**Comment by MennovDijk** [comment]
@JuandeJuni I got it working by switching from username:pass authenticated proxies, to IP authenticated proxies. I'm not sure if your proxy provider allows IP authentication, but if you would use it like that you should be able to use this.
