### ISSUE TITLE
Detection.

### ISSUE THREAD

**Issue by edenfluger** [ultrafunkamsterdam/undetected-chromedriver#5]
Hello! Tested now your chromedriver and it's detected on nike.com

**Comment by KawasakiMotorsEurope** [comment]
```
In [1]: import undetected_chromedriver as uc

In [2]: uc.TARGET_VERSION = 83

In [3]: c = uc.Chrome()

In [4]: c.get('https://nike.com')

In [5]: c.save_screenshot('nike.com.png')
```
![nike com](https://user-images.githubusercontent.com/60424635/82488040-8f40e200-9adf-11ea-82cc-33cd02e8a70a.png)

**Comment by ultrafunkamsterdam** [comment]
```
In [1]: import undetected_chromedriver as uc

In [2]: uc.TARGET_VERSION = 83

In [3]: c = uc.Chrome()

In [4]: c.get('https://nike.com')

In [5]: c.save_screenshot('nike.com.png')
```
![nike com](https://user-images.githubusercontent.com/60424635/82488040-8f40e200-9adf-11ea-82cc-33cd02e8a70a.png)

![nike com](https://user-images.githubusercontent.com/21027969/82488157-bb5c6300-9adf-11ea-8cb3-b2356148dbe6.png)
