### ISSUE TITLE
Most common way to make this completely undetectable.

### ISSUE THREAD

**Issue by theseoler** [ultrafunkamsterdam/undetected-chromedriver#50]
Hey there ! 

What are (except from Request Header, different UserAgents, using HQ Proxies (Residential,Mobile), Delay requests) 

The most common ways for a crawler build with this module to make it as hard detectable as possible ? 

We try to make it as sophisticated and hidden as possible.

What are your suggestions ? 

Best regards

**Comment by ultrafunkamsterdam** [comment]
Behaviour. 
- Act like human = speed like human
- Always enter website by normal url instead of direct login url
