### ISSUE TITLE
Headless not supported

### ISSUE THREAD

**Issue by chrisspen** [ultrafunkamsterdam/undetected-chromedriver#509]
This is more of a warning, but if you specify `opts.headless = True`, then that defeats everything in this package, as it appears Google explicitly checks for this option, assumes automation, and throws up its bogus splash page.

If you want to use UC as headless, which most people usually do, you'll need to use it with `opt.headless = False` bu with a Xvfb wrapper, like `pyvirtualdisplay`, so Google thinks you're on a conventional desktop. That worked for me, and bypasses all of Google's nonsensical checks, but only when using `undetected-chromedriver`.

**Comment by achmang** [comment]
very cool, could you please provide an example of how you done this?

**Comment by chrisspen** [comment]
It's just the standard usage mentioned in the [docs](https://github.com/ponty/pyvirtualdisplay/tree/3.0) Put your UC code in between `start()` and `stop()`.
