### ISSUE TITLE
Path to Chromedriver 

### ISSUE THREAD

**Issue by krypterro** [ultrafunkamsterdam/undetected-chromedriver#512]
We are having issues with running a large number of concurrent instances on a single Ubuntu server. It seems that we can not set the path to Chromedriver, so no matter what we do, hundreds of instances are competing for the same executable. 

[Errno 26] Text file busy: '/root/.local/share/undetected_chromedriver/chromedriver'

How can we specify a path to Chromedriver in our project directory?

**Comment by QIN2DIM** [comment]
Interesting topic. https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/434

**Comment by sebdelsol** [comment]
Please check #528

**Comment by ultrafunkamsterdam** [comment]
fixed
