### ISSUE TITLE
Attribute error: module Undetected_chromedriver has no attribute 'Chrome'

### ISSUE THREAD

**Issue by tommyct614** [ultrafunkamsterdam/undetected-chromedriver#513]
Works fine on Windows 11. But on an Ubuntu droplet, I get this error.
Can someone help? Thanks

**Comment by ultrafunkamsterdam** [comment]
`pip install -U undetected-chromedriver` 

i suspect you used pip install undetected_chromedriver    (i know, the naming is not ideal here)
