### ISSUE TITLE
How to change chrome download location?

### ISSUE THREAD

**Issue by Avnsx** [ultrafunkamsterdam/undetected-chromedriver#517]
Tried changing default download folder, with adding experimental option prefs, but that doesn't work anymore

**Comment by sebdelsol** [comment]
Check [here](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/524#issuecomment-1058340938) how to add `"prefs"`. Or use this [workaround](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/260#issuecomment-901276808)

**Comment by Avnsx** [comment]
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/260#issuecomment-901276808
Works pretty well
