### ISSUE TITLE
nowsecure pass failed

### ISSUE THREAD

**Issue by traffhub** [ultrafunkamsterdam/undetected-chromedriver#521]
import undetected_chromedriver as uc
from tech_files.ways import BROWSER_PATH

options = uc.ChromeOptions()
options.headless=False

driver = uc.Chrome()

driver.get('https://nowsecure.nl')

![image](https://user-images.githubusercontent.com/66271425/155905996-f36510e7-e70a-4892-9e5c-622cc37ebe89.png)

**Comment by sebdelsol** [comment]
You'll have to be patient for 5 seconds to pass the test...
![nowsecure](https://user-images.githubusercontent.com/6039281/156206267-c6a78dfb-756e-4acf-a3ce-1ce11cc29b9e.JPG)

**Comment by Lekhansh-dev** [comment]
Nah man, it's not working

**Comment by sebdelsol** [comment]
If it’s not working for you, you might want to give some more informations like which OS, selenium version, chrome version, the exact code, what’s happening…

**Comment by DiMiTriFrog** [comment]
> Nah man, it's not working

Sure, it's not working...

**Comment by DiMiTriFrog** [comment]
> > Nah man, it's not working
> 
> Sure, it's not working...

Here the 

> Nah man, it's not working

Here the fix!
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/246#issuecomment-889656587

**Comment by sebdelsol** [comment]
Are you sure you've upgraded your undetected-chromedriver ?
Because this was before version 3.1.0 that restored the driver get() method to original, and now it works like a charm...

**Comment by ultrafunkamsterdam** [comment]
for these cases, if this script (windows) 

https://raw.githubusercontent.com/ultrafunkamsterdam/undetected-chromedriver/master/undetected_chromedriver/tests/cloudflare_iauam_bypass_check.cmd 

also not passes CF, you are running in an IP reputation issue. Don't know what you are doing, but i pass even on nordvpn and on tor ip.

**Comment by traffhub** [comment]
> for these cases, if this script (windows)
> 
> https://raw.githubusercontent.com/ultrafunkamsterdam/undetected-chromedriver/master/undetected_chromedriver/tests/cloudflare_iauam_bypass_check.cmd
> 
> also not passes CF, you are running in an IP reputation issue. Don't know what you are doing, but i pass even on nordvpn and on tor ip.

Nope, Ip is clear, cause I passed CF without UC

**Comment by traffhub** [comment]
Platform - WIndows. 
Chrome - 99

**Comment by traffhub** [comment]
> If it’s not working for you, you might want to give some information like which OS you're using, which Selenium version and Chrome version, what's the exact code that triggers it, what’s actually happening… because it’s very easy to be detected by this site if you use the wrong options or a dumb `time.sleep()` that triggers CF infinite loop. "It's not working, duh" is just negative signal-to-noise ratio...

How exactly can CF determine time.sleep ? Thank u for reply
