### ISSUE TITLE
chrome driver patch

### ISSUE THREAD

**Issue by MonkeeMan1** [ultrafunkamsterdam/undetected-chromedriver#526]
Hey. I've just restarted my script and Im now getting the error 
`this version of chrome driver only supports chrome 97, current browser version is 99.0...`

I am using uc.Chrome(version_main99) and i still get this error. What should I do?

![image](https://user-images.githubusercontent.com/98274841/156801243-47761593-3d0c-4501-afb4-c0465ae0b870.png)

**Comment by sebdelsol** [comment]
#523
