### ISSUE TITLE
Undetected chromedriver: uc.ChromeOptions() doesn't works

### ISSUE THREAD

**Issue by RealKien** [ultrafunkamsterdam/undetected-chromedriver#527]
Hi,

I'm trying to use uc.ChromeOptions() to do some options.add_argument() to change the user agent of my Selenium bot and a long with a few other things. However, based on the page source I got from https://httpbin.org/anything, my user-agent was not changed and is the same user-agent of my google chrome browser. Also, when my driver is first load, there are 3 tabs, one with the user-agent as the url, one with "http://disable-notifications/" (which laters turn into the correct url https://httpbin.org/anything), and one with "disable-popup-blocking/". uc.ChromeOptions() in my case is clearly not working... 

Could someone pls point out where I am wrong and how I can fix this? Thank you very much.
Below is my code:

```
from fake_useragent import UserAgent
import undetected_chromedriver as uc

if __name__ == "__main__":
    opts = uc.ChromeOptions()
    ua = UserAgent()
    #add fake user agent to my driver
    opts.add_argument(str(ua['google chrome']))
    # block pop-up and notifications:
    opts.add_argument("disable-popup-blocking")
    opts.add_argument("disable-notifications")

    driver = uc.Chrome(version_main=98, options=opts)

    driver.get("https://httpbin.org/anything ")

    print(driver.page_source)

```

**Comment by sebdelsol** [comment]
You have to use the correct [command line switch](https://peter.sh/experiments/chromium-command-line-switches/#user-agent):

```python
from fake_useragent import UserAgent
import undetected_chromedriver as uc

if __name__ == "__main__":
    ua = UserAgent()
    wanted_user_agent = ua["google chrome"]
    print(f"{wanted_user_agent=}")

    options = uc.ChromeOptions()
    options.add_argument(f'--user-agent={wanted_user_agent}')
    driver = uc.Chrome(options=options)

    driver.get("https://httpbin.org/anything ")

    # it works !
    actual_user_agent = driver.execute_script("return navigator.userAgent")
    print(f"{actual_user_agent=}")
```

**Comment by RealKien** [comment]
@sebdelsol You are a legend! Thank you so much!!

**Comment by sebdelsol** [comment]
btw changing your user agent might make you [unique](https://amiunique.org/fp) hence easier to detect...

**Comment by RealKien** [comment]
@sebdelsol Really..? I thought that changing user agent helps my ip address to get harder to detect (as it can make website thinks that I'm from a proxy server or VPN)... Do you think the pros of doing it outweight its cons? I so far am still running from the same ip address and want to minimize chance to get noticed/detected by a website.

**Comment by sebdelsol** [comment]
it depends on what you're doing:  a lot of requests from the same IP with different user agents is very suspicious. Besides there are ways to [detect user agent spoofing](https://chris124567.github.io/2021-06-15-websites-lying-user-agent/)

**Comment by RealKien** [comment]
Damn, there are basically almost as much anti-bot measures as anti-anti-bot measures :) It's really interesting because they are all created by human. I'm only faking user agent that have the same Google Chrome browser as my user agent, and plus, my amount of requests should be less than 1000 times/day for a website. If this is the case, should I still fake my user agent or just not do it at all?
