### ISSUE TITLE
Cannot run multiple instances of script which use UC

### ISSUE THREAD

**Issue by JulesSoulfly** [ultrafunkamsterdam/undetected-chromedriver#528]
Good day!

Well, I'm using undetected-chromedriver in script which should be running several times in parallel (OS Windows 10, python 3.9).
Since recently only one instance/process working good, the others throws an error:
 - Message: 'chromedriver.exe' executable may have wrong permissions. Please see https://chromedriver.chromium.org/home
or sometimes:
- [Errno 13] Permission denied: 'C:\\Users\\NNN\\appdata\\roaming\\undetected_chromedriver\\chromedriver.exe'

In fact, arguments 'executable_path' and 'browser_executable_path' are not working - script doesn't see my instance of chromedriver.exe.
```
import seleniumwire.undetected_chromedriver as webdriver
driver = webdriver.Chrome(options = options, seleniumwire_options = seleniumwire_options, executable_path=chromedriver_path, version_main = 98)
```
I also tried to create two different folders and place two copies of script with copies of chromedriver.exe - still got same errors above. The same picture is observed if I use UC without seleniumwire.

Any solutions, friends?
What I must to do to run multiple copies of script which uses UC?
  
  

UPD.
WELL. I forked undetected-chromedriver project on github, added 'executable_path' argument into \_\_init\_\_ and handed it to patcher... Seems to work, but I don't really like this solution.

**Comment by sebdelsol** [comment]
You could use this [solution](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/479#issuecomment-1030814150) if you don't want to have a fork to maintain.

**Comment by sebdelsol** [comment]
The bug is that Chrome doesn't forward the [executable_path](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/a4cc4a8b72691a3f5462b6f23973727e2b03da9e/undetected_chromedriver/__init__.py#L208) parameter to the `Patcher`.
As a quickworkaround you can monkey patch the `Patcher` class to force a default `executable_path` when the `Patcher` is instantiated with a `None` one:
```python
import shutil
import tempfile

import undetected_chromedriver as webdriver


def force_patcher_to_use(executable_directory):
    # copy the chromedriver in executable_directory
    src = os.path.join(webdriver.Patcher.data_path, webdriver.Patcher.exe_name)
    executable_path = os.path.join(executable_directory, webdriver.Patcher.exe_name)
    shutil.copyfile(src, executable_path)

    class PatcherWithForcedExecutablePath(webdriver.Patcher):
        def __init__(self, *args, **kwargs):
            kwargs["executable_path"] = executable_path
            super().__init__(*args, **kwargs)

    # monkey patch the Patcher class
    webdriver.Patcher = PatcherWithForcedExecutablePath

    return executable_path


if __name__ == "__main__":
    # create a tmp dir where the driver will be put
    executable_directory = os.path.normpath(tempfile.mkdtemp())
    executable_path = force_patcher_to_use(executable_directory)

    driver = webdriver.Chrome(options=options, executable_path=executable_path)
 
    # when you're done 
    driver.quit() 
    os.remove(executable_path)
    os.rmdir(executable_directory)

```

**Comment by JulesSoulfly** [comment]
> As you've found out the bug is that `Chrome` [doesn't forward](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/a4cc4a8b72691a3f5462b6f23973727e2b03da9e/undetected_chromedriver/__init__.py#L208) the executable_path parameter to the `Patcher`. The fix is a one-liner but it involves a fork... A quick workaround is to patch the `Patcher` class to force `executable_path` to be set. Here's a working example how it can be done:
> 
> ```python
> import os
> import shutil
> import tempfile
> 
> import undetected_chromedriver as webdriver
> 
> 
> def force_patcher_to_use(directory):
>     # copy the chromedriver in directory
>     exe = webdriver.Patcher.exe_name
>     src = os.path.join(webdriver.Patcher.data_path, exe)
>     executable_path = os.path.join(directory, exe)
>     shutil.copyfile(src, executable_path)
> 
>     # monkey patch the Patcher class
>     class PatcherWithForcedExecutablePath(webdriver.Patcher):
>         def __init__(self, *args, **kwargs):
>             kwargs["executable_path"] = executable_path
>             super().__init__(*args, **kwargs)
> 
>     webdriver.Patcher = PatcherWithForcedExecutablePath
> 
>     return executable_path
> 
> 
> if __name__ == "__main__":
>     # create a tmp dir where the driver will be put
>     tmp_directory = os.path.normpath(tempfile.mkdtemp())
>     executable_path = force_patcher_to_use(tmp_directory)
> 
>     driver = webdriver.Chrome(executable_path=executable_path)
>  
>     # some cleanup when done 
>     driver.quit() 
>     os.remove(executable_path)
>     os.rmdir(tmp_directory)
> ```

Thanks you, good sir!

**Comment by ultrafunkamsterdam** [comment]
fixed in latest
