### ISSUE TITLE
Driver detected by Cloudflare

### ISSUE THREAD

**Issue by KakTakTo3** [ultrafunkamsterdam/undetected-chromedriver#530]
Here is my code
`driver = uc.Chrome(browser_executable_path='C:\\Program Files\\Google\\Chrome Beta\\Application\\chrome.exe')
    driver.set_window_size(1920, 1080)`
In the window that opens, I go to a site protected by CloudFlare. The message "checking your browser before accessing url" appears. And every 5 seconds the site auto-updates. That is, the download is stuck on this inscription.
I tried to access the site through a browser without a driver - it enters the site normally. That is, it is in the driver. Doesn't depend on IP either.
Data:
OS - Windows 11
Browser - Chrome 99 (Beta)
undetected_chromedriver version - latest

**Comment by KakTakTo3** [comment]
Update: the site comes in 10-15 minutes. But without a driver it comes in 3-5 seconds, so the problem is relevant

**Comment by sebdelsol** [comment]
Could you please post some code showing how to reproduce the issue ?

**Comment by KakTakTo3** [comment]
> Could you please post some code showing how to reproduce the issue ?

I just create a browser window with the code above. Then I enter the site address on my own, go to it and get the problem above. Site protected by CloudFlare, for example: sandbox .game

**Comment by KakTakTo3** [comment]
I just tried to do the same but adding:
`driver.get('https://sandbox.game')`
And he goes to the site! I don't know how it works. Why, if you enter the address manually, there is a problem. And if you do the same with the code - everything works. I think the topic is closed
