### ISSUE TITLE
Running undected-chromedriver in main()

### ISSUE THREAD

**Issue by reach4bawer** [ultrafunkamsterdam/undetected-chromedriver#531]
When I try to run the following code -

```
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
import undetected_chromedriver.v2 as uc
from time import sleep

if __name__ == '__main__':
    options = uc.ChromeOptions()
    options.add_argument('--no-first-run --no-service-autorun --password-store=basic')
    driver = uc.Chrome(browser_executable_path='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', options=options)
    driver.get('xxxxx')
    # sleep(15)
    title_to_find = 'xxxx'
    try:
        print("Trying this..!!")
        WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.LINK_TEXT, title_to_find)))
        element = driver.find_element(By.LINK_TEXT, title_to_find)
        element.click()
        sleep(15)
    except Exception as e:
        print("Exception:", e)

```

I am trying to run the above code on Macbook with `undetected-chromedriver==3.1.3` if I remove the sleep the program does not run or even click on the element. Do I need to do something differently?

Also, if I don't utilize main function I cannot run this in PyCharm.

**Comment by sebdelsol** [comment]
when your script runs and exits, chrome exits because undetected chromdriver register a cleanup method with [atexit](https://docs.python.org/fr/3/library/atexit.html) to [kill the browser process](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/77509e6da2aa14ae8f6f5ff49f8af6dba27e05e9/undetected_chromedriver/dprocess.py#L75)

**Comment by reach4bawer** [comment]
Is sleep is the only way to hold off on the clean up process from being triggered?

**Comment by sebdelsol** [comment]
If you don’t want your script to exit right away, you can add a mere [`input`](https://docs.python.org/3/library/functions.html#input) or wait for the browser to be closed by the user:
``` python
def wait_for_browser_closed(driver):
    disconnected_msg = "disconnected: not connected to DevTools"
    while True:
        time.sleep(0.5)
        if msg := driver.get_log("driver"):
            if disconnected_msg in msg[-1]["message"]:
                Print("Chrome window closed by user")
                break
```

**Comment by reach4bawer** [comment]
This works. Thank you.
