### ISSUE TITLE
Undetected Chromedriver multiple instances kill?

### ISSUE THREAD

**Issue by sunny9495-dev** [ultrafunkamsterdam/undetected-chromedriver#532]
Hi,

Is there any solution to kill undetected chromedriver multiple instances, i tried,

`os.system("taskkill /F /IM chromedriver.exe /T")`

but the browser is not quitting, any help would be appreciated

**Comment by sebdelsol** [comment]
Why do you need to kill those ? **You'd better use the driver [quit()](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/a4cc4a8b72691a3f5462b6f23973727e2b03da9e/undetected_chromedriver/__init__.py#L561) method**.

I had only one contrived (valid?) case where I had to kill those: in a multi threaded environment where a lot of drivers were spawned and I didn't want the user to wait for a driver creation to finish and exit right away from the script. 

_This is absolutely not recommended and involves a lot of mutex safety and errors catching in other part of your script and it's very hard to be sure you've covered all the caveats : I'm still wary of this part of the code after months of using it._ 

**Again, use `driver.quit()` instead, it's much safer**.

Anyway here's how I did it, use this piece of code at your own risk...
```python
import psutil
import undetected_chromedriver as webdriver


def terminate_spawned_drivers():
    """
    terminate all chromedrivers spawned by this process
    !! it will raise errors in ongoing driver operations !!
    !! it might end up with the chromedriver file unclosed or other caveats !!
    """
    exe_name = webdriver.Patcher.exe_name
    current_proc = psutil.Process()
    for child in current_proc.children(recursive=True):
        if exe_name in child.name().lower():
            print(f"TERMINATE {child.name()} {child.pid}")
            child.terminate()
```

**Comment by sunny9495-dev** [comment]
Hi @sebdelsol Thanks for the help, but the issue is

I have created a tool for google thing with start stop button

https://i.imgur.com/LtyTN7U.png

when user click on stop, it has to stop the current running browsers.

I see it was closing chromedriver.exe, but not the browser, the browser still appears

**Comment by sebdelsol** [comment]
I'm not sure what you're doing, it seems you try to externally terminate your script or the drivers. 
But you'll definitely end up with a lot of caveats, like opened browsers, running chromedrivers or worse...
So you should [catch a signal](https://stackoverflow.com/a/1112350/3692322) in your python script and properly handle the driver cleanup by calling its `driver.quit()` method.

**Comment by sunny9495-dev** [comment]
Hi @sebdelsol

I found a solution for the issue, but got a new issue, if i tried this patcher in new machine, iam getting error following error

`FileNotFoundError: [Errno 2] No such file or directory`

I use the following code

`import os
import stat
import undetected_chromedriver as webdriver


def lock_file(filename, lock=True):
    permissions = stat.S_IREAD
    if not lock:
        permissions += stat.S_IWRITE
    if webdriver.IS_POSIX:
        filename = os.path.dirname(filename)
    os.chmod(filename, permissions)


if __name__ == "__main__":
    patcher = webdriver.Patcher()
    # unlock chromdriver.exe and patch it
    lock_file(patcher.executable_path, lock=False)
    patcher.auto()
    # lock chromedriver.exe & monkey patch Patcher 
    # to prevent the patcher from reading or writing it
    lock_file(patcher.executable_path)
    webdriver.Patcher.is_binary_patched = lambda self: True

   # now you can instantiate and use drivers in threads without random PermissionError
   # instantiation is way faster since there are no more download and patch ops.`

Can you help me to download the chromedriver before run

**Comment by sebdelsol** [comment]
this code assume that the `chromedriver` already exists, which not always the case, so you need to test that:
```python
def lock_file(filename, lock=True):
    permissions = stat.S_IREAD
    if not lock:
        permissions += stat.S_IWRITE
    if webdriver.IS_POSIX:
        filename = os.path.dirname(filename)
    if os.path.exists(patcher.executable_path):
        os.chmod(filename, permissions)
```

**Comment by sunny9495-dev** [comment]
Thanks, it worked sebdelsol, Jesus bless you
