### ISSUE TITLE
Chrome Driver Crashing on Windows 

### ISSUE THREAD

**Issue by nirvana1122** [ultrafunkamsterdam/undetected-chromedriver#534]
It started happening since the latest chrome release a few days back. I have tried to uninstall and reinstall the chrome with no success. 

log file : XXXX_20220307_062243.log
2022-03-07 06:22:44,352 -  INFO - https://www.nasdaq.com/market-activity/earnings
2022-03-07 06:22:44,355 -  INFO - https://www.nasdaq.com/market-activity/earnings
Browsing to https://www.nasdaq.com/market-activity/earnings ..
2022-03-07 06:23:28,046 -  INFO - Getting data on 03/07/2022
2022-03-07 06:23:33,364 -  ERROR - Fatal Error in earnings downloads
Traceback (most recent call last):
  File "YXXXXearningsFetcher.py", line 306, in <module>
    main(logger)
  File "YXXXXearningsFetcher.py", line 286, in main
    fetch_earnings(eventDate,asOfDate, url, logger)
  File "YXXXX/earningsFetcher.py", line 165, in fetch_earnings
    driver.execute_script("return document.getElementsByClassName('date-picker__toggle')[0].click()")
  File "C:\Anaconda3\envs\base_small\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 874, in execute_script
    'args': converted_args})['value']
  File "C:\Anaconda3\envs\base_small\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Anaconda3\envs\base_small\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=99.0.4844.51)
Stacktrace:
Backtrace:
	Ordinal0 [0x003E9943+2595139]
	Ordinal0 [0x0037C9F1+2148849]
	Ordinal0 [0x002743F0+1065968]
	Ordinal0 [0x00265A97+1006231]
	Ordinal0 [0x00264AD0+1002192]
	Ordinal0 [0x002650D8+1003736]
	Ordinal0 [0x0026F7EF+1046511]
	Ordinal0 [0x0027A22B+1090091]
	Ordinal0 [0x0027CB10+1100560]
	Ordinal0 [0x002653A6+1004454]
	Ordinal0 [0x00279E67+1089127]
	Ordinal0 [0x002CBA17+1423895]
	Ordinal0 [0x002BB806+1357830]
	Ordinal0 [0x00296086+1204358]
	Ordinal0 [0x00296F96+1208214]
	GetHandleVerifier [0x0058B232+1658114]
	GetHandleVerifier [0x0064312C+2411516]
	GetHandleVerifier [0x0047F261+560433]
	GetHandleVerifier [0x0047E366+556598]
	Ordinal0 [0x0038286B+2173035]
	Ordinal0 [0x003875F8+2192888]
	Ordinal0 [0x003876E5+2193125]
	Ordinal0 [0x003911FC+2232828]
	BaseThreadInitThunk [0x76F7FA29+25]
	RtlGetAppContainerNamedObjectPath [0x771A7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x771A7A6E+238]

**Comment by sebdelsol** [comment]
This site works fine with me, could you please give more information like: your OS, your chrome options and some minimal code to reproduce the issue ? Your chrome crashes (that's not an undetected chromedriver bug btw), it might be due to insufficient disk space or running out of memory... it's very hard to tell without knowing more.

**Comment by nirvana1122** [comment]
Hi,

The code below recreates the error on my windows 10 server. The server has 2X-Xeons with 112GB of RAM.

import undetected_chromedriver.v2 as uc
from time import sleep
import datetime as dt
EARNINGS_URL = "https://www.nasdaq.com/market-activity/earnings"
driver = uc.Chrome()
sleep(10)
driver.get(EARNINGS_URL)


sleep(3)

wait = WebDriverWait(driver, 10)
dayD = dt.date(2022,3,10)
dateSTR = dayD.strftime("%m/%d/%Y")
print(f'Getting data on {dateSTR}')
driver.execute_script("return document.getElementsByClassName('date-picker__toggle')[0].click()")
driver.implicitly_wait(20)

**Comment by nirvana1122** [comment]
It still keeps crashing for me at _driver.get(url)_. I also do not see any spike in memory when I run the script. Let me restart the server. It's a bit confusing because the problem started after the latest Chrome update.

**Comment by sebdelsol** [comment]
what's your selenium version ?

**Comment by nirvana1122** [comment]
"--disable-gpu" didn't help. 
I have Selenium 4.0.0, and the latest is 4.1.2. Shall I update it?

**Comment by nirvana1122** [comment]
Restart seemed to have fixed the problem. Go figure.
