### ISSUE TITLE
Issues with user_data_dir

### ISSUE THREAD

**Issue by ramadan8** [ultrafunkamsterdam/undetected-chromedriver#549]
I have the following code snippet.

```python
if __name__ == "__main__":
    data_dir = Path.home() / ".ramadan" / "voter" / "profile"

    if not data_dir.exists():
        os.makedirs(data_dir)

    driver = uc.Chrome(user_data_dir=data_dir)
    driver.get("https://google.com")
```

I have Chrome open in the background. If I use the `user_data_dir` parameter, it will open a new regular Chrome window as if I was making a new window on my regular browser. It then hangs there without moving on. However, if I remove this parameter, then a webdriver window will open as expected.

This also happens when the `profile` folder does not exist at first or is empty.

I'm not sure if this is how it is intended to work, hence why I'm making this issue. Help would be appreciated.

**Comment by ramadan8** [comment]
The reply to issue #120 [here](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/120#issuecomment-848240798) helped me out, I now have the following code and it works fine, opening the correct Chrome program with the profile.

```python
options = uc.ChromeOptions()
options.add_argument(f"--user-data-dir={data_dir}")

driver = uc.Chrome(options=options)
```

However, I'd still like to use the standard `user_data_dir` parameter if possible.

**Comment by ultrafunkamsterdam** [comment]
you can't open the default user profile while already open. I'd suggest trying to copy the profile to another folder and specify that in the options. also note the profile folder has a subfolder "Default". I don't know from the top of my head which one you should pick. you can show the exact folder in a regular chrome browser In chrome://version

**Comment by ultrafunkamsterdam** [comment]
Just tested it. Made a copy of my user profile folder.
(on windows)
`C:\users\username\AppData\Local\Google\Chrome\User Data`
to 
`C:\users\username\AppData\Local\Google\Chrome\User Data Copy`
and used it like
```python
import undetected_chromedriver as uc
opts = uc.ChromeOptions()
opts.add_argument("--user-data-dir=C:\\Users\\username\\AppData\\Local\\Google\\Chrome\\User Data - Copy")
driver = uc.Chrome(opts)
```

**Comment by zhu6201976** [comment]
json.decoder.JSONDecodeError: Extra data: line 1 column 71929 (char 71928)
because you unicode chars \U or /U
modify save path name like this: /Data

opts.add_argument("--user-data-dir=C:\\Users\\username\\AppData\\Local\\Google\\Chrome\\Data")
