### ISSUE TITLE
Cannot Reuse the ChromeOptions object

### ISSUE THREAD

**Issue by saifiipedia** [ultrafunkamsterdam/undetected-chromedriver#555]
My Script is used to open an email,
Type username and password
Login
and close the driver.
Re open the driver and repeat the steps.

My Code Works fine while using Incognito option. But when I use data profile its giving me this error

\__init__.py", line 244, in __init__
    raise RuntimeError("you cannot reuse the ChromeOptions object")
RuntimeError: you cannot reuse the ChromeOptions object

**Comment by sebdelsol** [comment]
Please check the [code](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/b2e804e977c9cf3dd9c845474752cac142a72508/undetected_chromedriver/__init__.py#L240) you'll see the solution : you need to instantiate a new `ChromeOptions()` object from scratch instead of reusing the old one because:
```
    #  prevent reuse of options,
    #  as it just appends arguments, not replace them
    #  you'll get conflicts starting chrome
```

**Comment by saifiipedia** [comment]
yes i get it. but i am unable to figure it out how to do it. i have never
experienced this before. If you don't mind can you please share some code
or tips to tackle this? Thanks a bunch for your help.

**Comment by saifiipedia** [comment]
and that solved my problem. i wasn't using it in __main__ Thank you so much for support.

**Comment by taytanqbpass** [comment]
> ```python
> import undetected_chromedriver as webdriver
> 
> 
> if __name__ == "__main__":
>     for _ in range(5):
>         options = webdriver.ChromeOptions()  # create a new ChromeOptions instance each iteration :)
>         options.add_argument("--start-maximized")
> 
>         driver = webdriver.Chrome(options=options)
>         driver.quit()
> ```

I was doing this and still got the error message "
Cannot Reuse the ChromeOptions object"
