### ISSUE TITLE
Undetected Chromedriver gets detected by Cloudflare and Botfront

### ISSUE THREAD

**Issue by sirgoogleadmin** [ultrafunkamsterdam/undetected-chromedriver#57]
When trying to visit a Website protected by cloudflare such as https://beta.welovecloudflare.de it just reloads the 5sec UAM Site.
Doesn't happen with when using my real browser.
Another example would be https://lhcdn.cloud/.
These Sites are Dstats and are mostly there to see if you are able to bypass them.
The undetected Chrome driver isnt going past this.
Any Idea why this happens?

Anyways this a very cool project and works mostly!
edit: i am using the updated version btw, it should be headless as well muchos lovos <3

**Comment by ultrafunkamsterdam** [comment]
Ah... there you are again.. MrBot of botprotect.io

**Comment by ultrafunkamsterdam** [comment]
```
import undetected_chromedriver as uc
import threading
driver = uc.Chrome()
driver.get('https://beta.welovecloudflare.de')
threading.Timer(7, lambda: driver.save_screenshot('ilovecloudflaretoo.png')).start()
```
![ilovecloudflaretoo](https://user-images.githubusercontent.com/21027969/100574912-4f9f5200-32db-11eb-8549-099789808ef7.png)

**Comment by fingoldo** [comment]
I feel like it's happening again with Cloudflare and undetected-chromedriver-3.0.6
Any clues? (

**Comment by vedodedo** [comment]
it is happening again :(

**Comment by SalmanTahir786** [comment]
it is happening again :(

**Comment by qwillio-live** [comment]
its not passing Cloudflare again

**Comment by nuclear-bean** [comment]
> its not passing Cloudflare again
@qwillio-live 
Works for me (chrome 108.x). Check your user agent and try a fresh (high-quality) IP.
