### ISSUE TITLE
proxy doesn't work

### ISSUE THREAD

**Issue by xtekky** [ultrafunkamsterdam/undetected-chromedriver#574]
Hi! Whenever I try to use a proxy with undetected-chromedriver it just doesn't work, the page loads but instead of the proxy ip, my real ip is displayed.

The script I use:
```python
from time import sleep
import undetected_chromedriver as uc

#ip_port = "ip:port"

chrome_options = uc.ChromeOptions()
#hrome_options.add_argument('--proxy-server=%s' % ip_port)
chrome_options.add_argument('--proxy-server=136.243.174.243:1080')
driver = uc.Chrome(use_subprocess=True, chrome_options=chrome_options)

driver.get('https://www.myexternalip.com/raw')
sleep(999)
```
Am I doing anything wrong, or is there another way to use proxies, I don't know about?

**Comment by darkspecs** [comment]
I believe you're using the chrome proxy args wrong. I'm assuming you're using a socks5 proxy

instead of 

`chrome_options.add_argument('--proxy-server=136.243.174.243:1080')`

it should be 

`chrome_options.add_argument('--proxy-server=socks5://136.243.174.243')`

**Comment by sebdelsol** [comment]
Thanks @darkspecs, that’s another non-bug that should be closed right away.

**Comment by xtekky** [comment]
it worked fo me, thanks

**Comment by eidelee** [comment]
how can i add a https proxy with auth?

**Comment by eidelee** [comment]
how can i use http proxy with auth?
here is my code



options = uc.ChromeOptions()
seleniumwire_options = {
            'proxy':
                {'http': f'http://{acc}:{pw}@{proxy}:{port}',
                 'https': f'http://{acc}:{pw}@{proxy}:{port}',
                 'no_proxy': 'localhost,127.0.0.1'}
        }
driver = uc.Chrome(options=options, version_main=99, seleniumwire_options=seleniumwire_options)
  driver.get('https://api.ipify.org?format=json')

**Comment by TheGrandNobody** [comment]
For any beginners who have tried @darkspecs method and still had no success, you likely forgot the port (which isn't in his example). As such, the correct format is 
`chrome_options.add_argument('--proxy-server=socks5://IP:PORT')`
or using the example from @darkspecs and @xtekky this would be
`chrome_options.add_argument('--proxy-server=socks5://136.243.174.243:1080')`

**Comment by faaizazizpf** [comment]
I am facing an issue with proxy authentication! can you help, please?
[How can I access proxy alert](https://stackoverflow.com/questions/73179051/how-can-i-access-proxy-alert)
