### ISSUE TITLE
Does not always fill in forms

### ISSUE THREAD

**Issue by mvanhare** [ultrafunkamsterdam/undetected-chromedriver#575]
I have a problem that happens very frequently where I am trying to fill out a form with the undetected chromedriver  and it does not fill about half the time.  This does not happen when I am using the normal chromedriver.

**Comment by sebdelsol** [comment]
Unfortunately if you share nothing else, we'd have a hard time helping you... Please explain how to reproduce your issue.

**Comment by mvanhare** [comment]
My things were not updated.  Closing this.
