### ISSUE TITLE
Got a question!

### ISSUE THREAD

**Issue by Avnsx** [ultrafunkamsterdam/undetected-chromedriver#58]
Hey guys!
I'm visiting a website with selenium, which has a livestream running on it.
The website recognises my account - which I logged in with before - with selenium and counts me as active viewer.
Now I want to keep alive the entire Network traffic from that site, even If I closed the tab.
To basicaly make the website think i'm still actively viewing and I'm still on the website, but I would not be since selenium is closed.

For performance reasons I'm forced to close the entire selenium session, so I can't just go headless mode.

Is there a way to export the entire Network tab or something from Devtools and somehow keep traffic alive, even if selenium was closed?

Thanks in advance!

**Comment by ultrafunkamsterdam** [comment]
Now i dont know what the question was 🤣

**Comment by Avnsx** [comment]
> Now i dont know what the question was 🤣

press on "edited" next to commented 3 days ago, to see the original post
