### ISSUE TITLE
what version does it work on now 

### ISSUE THREAD

**Issue by vitalisc** [ultrafunkamsterdam/undetected-chromedriver#585]
please am here to ask what version of chrome does it work with?, 

import undetected_chromedriver as uc
driver = uc.Chrome()
driver.get('https://nowsecure.nl')

i ran the code above but it wont open my  chrome browser to navigate  to nowsecure.nl

i want to know if its the chrome browser version issue or am i missing something

**Comment by TemaLin** [comment]
try adding `use_subprocess=True`,
helped me
But I don't know what it means

**Comment by vitalisc** [comment]
> try adding `use_subprocess=True`, helped me But I don't know what it means

please can you share me code sample 

i did this  code below but it still wont open

import undetected_chromedriver.v2 as uc
use_subprocess = True
driver = uc.Chrome()
driver.get('https://nowsecure.nl')

**Comment by TemaLin** [comment]
> 

It helps me to run two versions of the code
1:
```
if __name__ == '__main__':
    import undetected_chromedriver.v2 as uc
    driver = uc.Chrome()# version_main allows to specify your chrome version instead of following chrome global version
    driver.get('https://nowsecure.nl')
```

2:
```
import undetected_chromedriver.v2 as uc

driver = uc.Chrome(use_subprocess=True)

driver.get('https://nowsecure.nl')
```

Both options work.

ChromeOptions() doesn't work for me.

**Comment by sebdelsol** [comment]
@vitalisc, Please be aware that there are bare minimum requirements before raising a bug on any repo.

You're supposed to have at least : 
* **learned** basic Python _idioms_, you need [this one](https://docs.python.org/3/library/__main__.html#idiomatic-usage).
* **checked** the _error_ you've encountered, you'd have seen it actually gives you the answer to your "issue".
* **searched** the _bug database_, you'd have seen this "issue" has been raised and answered countless times, for instance [here](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/561#issuecomment-1075363395).
* **read** the _documentation_. you'd have learned how to import this package [here](https://github.com/ultrafunkamsterdam/undetected-chromedriver#310).
* **read** the _docstring_ of the classes you use and you'd have learned what the `use_subprocess` parameter does and why you shouldn't use it ([here](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/b2e804e977c9cf3dd9c845474752cac142a72508/undetected_chromedriver/__init__.py#L209)).

**Please close this bug it's anything but that.**

**Comment by vitalisc** [comment]
i figured out it was my internet that was messing with me
