### ISSUE TITLE
Question about possibilities of detecting this driver

### ISSUE THREAD

**Issue by Ryxwaer** [ultrafunkamsterdam/undetected-chromedriver#595]
Hello,

I am using this driver in python script for automating joining discord servers by invite link. Long story shorts I got banned after a few hours of testing it :D. Now the question is what detected me. I have 3 suspects what could cause this:

- hCaptcha was solved automatically with chrome extension based on speech recognition and then clicking tiles.
- sleep time in between most of the click events was in some cases just 0.1s
- I used undetected_chromedriver with fake user and these parameters:
```python
options = uc.ChromeOptions()
options.add_argument('--window-size=1080,1920')
options.add_argument('--window-position=0,0')
user_agent = 'Mozilla/5.0 (Windows NT 6.2; Win64; x64;) Gecko/20100101 Firefox/20.0'
options.add_argument(f'user-agent={user_agent}')
options.add_argument('--disable-popup-blocking')
options.add_argument('--load-extension=./src/hCaptcha-Solver')
options.set_capability('unhandledPromptBehavior', 'dismiss')
options.set_capability('pageLoadStrategy', 'none')
driver = uc.Chrome(options=options)
```
I want want to exclude things that was all right and improve that lacking something. I already added some sleep time but I am wondering what else could detect me so I decided to come here and ask about this people who much more knowledge in this than I have. English is not my first language so I hope it is readable for you. I would be glad for any help.

**Comment by QIN2DIM** [comment]
https://bot.sannysoft.com/

**Comment by Ryxwaer** [comment]
Thanks for the quick response. But I don't see anything wrong with this scann you posted. Is there anything that I am missing which is rendering me as a bot? Or should I change fake user agent parameter be closer to my real one?

**Comment by sebdelsol** [comment]
You should not spoof your user agent since it's easy to detect the inconsistency client side.

**Comment by ultrafunkamsterdam** [comment]
User agent does  **nothing** for detection.

test  (windows):


**this first step is important, since setting user agent only works for new chrome process. so you have to make sure all chrome processes are killed**

launch
`
cmd.exe
`
`
taskkill /f /im chrome* 
`
`
"X:\Path\To\Google\Chrome\Application\chrome.exe" --user-agent="my user agent"
`
`
navigate to https://testnet.coinfaucet.eu  or https://nowsecure.nl
`
`
find out that it works fine
`
