### ISSUE TITLE
UC driver hangs during initialization when run by Discord Bot

### ISSUE THREAD

**Issue by logam555** [ultrafunkamsterdam/undetected-chromedriver#597]
When trying to create the UC driver the program comes to a halt, no matter how long I wait it stays stuck at the uc.Chrome() call. When I CTRL + C the program returns this:
![Screenshot 2022-04-16 225528](https://user-images.githubusercontent.com/33184510/163698359-68ef582c-0377-47d6-a0e7-8342e9575145.png)

**Comment by sebdelsol** [comment]
weird, is the Chrome or Chromium process actually running ? 
what's you Python, undetectect-chromedriver and Selenium version ?
what's your OS ?

**Comment by logam555** [comment]
Chrome is not spawned when it hangs. FYI, all the packages are inside a venv except for Chrome itself. Also, just to make sure that the other package versions worked with each other I did test using the Selenium webdriver, instead of UC, and Chrome did spawn then. I also tried to pip install UC 3.1.0 since it looked to be the most recent but it failed, so I just pip installed the most recent version pip recognized.

Versions:
Python 3.10.4
Undetected-Chromedriver 3.1.5.post4
Selenium 4.1.3
Chromedriver 100.0.4896.60
Chrome 100.0.4896.88

OS: Windows 10

**Comment by sebdelsol** [comment]
does `find_chrome_executable()` [here](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/b2e804e977c9cf3dd9c845474752cac142a72508/undetected_chromedriver/__init__.py#L659) returns a valid path to your installed Chrome ?

**Comment by logam555** [comment]
Yes, it does. This is what it prints: 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'

**Comment by sebdelsol** [comment]
Thanks for your answer. At the moment I don't know what could prevent Chrome from launching without raising any errors.
Please check this Chrome correctly start when launched by hand. 
Could you provide some code to reproduce your issue ?

**Comment by logam555** [comment]
Results of 'pip install undetected_chromedriver -U': 
![Screenshot 2022-04-17 180929](https://user-images.githubusercontent.com/33184510/163734034-a6d7135a-4086-4bbc-844e-0ef9d07a66a4.png)

That Chrome.exe does launch properly. I do not have several chromes installed. The code I was using is based off this discord bot  https://github.com/pritam20ps05/mcscraper

Where I am specifically running into the issue is inside the aternosapi's __init__

I have not made any alterations to the original code yet, as I was trying to get it to work before messing with it.

**Comment by sebdelsol** [comment]
This is not really minimum code to reproduce the issue...
Please try (and tell me if Chrome starts):
```python3
import undetected_chromedriver as uc

if __name__ == "__main__":
    driver = uc.Chrome()
```

I guess it will, in this case you'll have to raise an issue in the relevant repo : I would protect the main entry point in bot.py to prevent an endless loop due to multiprocessing :)

**Comment by logam555** [comment]
The code you sent did actually work, which is weird since the repo I mentioned although has a bit of code shouldn't cause any problems as even just changing it to normal webdriver chrome will work. So I did some testing and I think the issue might be somewhat related to api/class structure. For example

`import undetected_chromedriver as uc
from test1 import Test1

if __name__ == "__main__":
    api = Test1()
    print("it works")
    while(True):
        continue;`

and 

`import undetected_chromedriver as uc

class Test1():
    def __init__(self):
        self.driver = uc.Chrome
        self.driver.get('https://nowsecure.nl')`

returns error in powershell of
![Screenshot 2022-04-19 131458](https://user-images.githubusercontent.com/33184510/164059168-5f92f5a6-7af7-48b3-a3d4-79cccbd263ad.png)
 
 I will continue to mess with the code till I can get it to hang like the original issue (with minimal code) instead of through an arg exception.

**Comment by QIN2DIM** [comment]
`uc.Chrome` --> `uc.Chrome()`

**Comment by logam555** [comment]
That... yeah. Just woke up sorry for that one (yes it did fix it).  If I am unable to reproduce the issue with minimal code by end of the day I will close the thread.

**Comment by QIN2DIM** [comment]
我根据你提供的截图找到了你在使用的项目 [mscraper](https://github.com/pritam20ps05/mcscraper/blob/master/aternosapi/__init__.py)，我尝试复现了你遇到的问题，我觉得你遇到的根本问题是：本地网络欠佳。

你可以将如下代码注释掉:
`L10: chrome_options.add_argument("--headless")`

改动如下代码：
`L19: self.driver = uc.Chrome(options=chrome_options)`
↓
`self.driver = uc.Chrome(options=chrome_options, headless=False)`

call it:
```python
if __name__ == '__main__':
    AternosAPI({}, )

```

**Comment by QIN2DIM** [comment]
`Unable to initialize UC driver` may be an illusion. If there isn't any runtime log and you can't see it running, you'd think it wasn't starting.

**Comment by logam555** [comment]
I'll try that in a second (I have done it with headless before, also having a print after the driver call, but I still get nothing), just want to report that I was able to reproduce the hanging bug. If I pair UC with Discord it happens. This code is self contained (no need for separate classes)

```
import undetected_chromedriver as uc
from discord.ext import commands

bot = commands.Bot(command_prefix='!')

@bot.command(name="test", pass_context=True, help="tests things")
async def test(ctx):
    self.driver = uc.Chrome()
    self.driver.get('https://nowsecure.nl')
    await print("it works")

bot.run(<Insert Discord Bot Token Here>)
```

This results in the hand on the driver call. Not sure why this interaction happens yet. Will check QIN2DIM's answer, although I am pretty sure nothing will change.

**Comment by logam555** [comment]
I tested QIN2DIM's solution and it does start Chrome, as expected, but since the issue seems to be Discord bot interaction it doesn't help the originally hang issue.

**Comment by QIN2DIM** [comment]
so。。。You can go to that repository to leave issues, I have not used the tool and do not understand their underlying implementation.😂

**Comment by QIN2DIM** [comment]
btw What does `hangs` mean

**Comment by logam555** [comment]
First the issue isn't the mcscraper bot just discord bots in general when running UC. Also when we say hangs we mean that it is like an infinite loop. It enters `driver = uc.Chrome()` but then nothing, it gets caught inside that command and stops the program from ever continuing until forcibly closed (never throwing an error either). For example in the previous minimal code to reproduce 

```
async def test(ctx):
    driver = uc.Chrome()
    driver.get('https://nowsecure.nl')
    await print("it works")
```

it would hang at the `driver = uc.Chrome()` and never reach `driver.get('https://nowsecure.nl')` or `await print("it works")`

**Comment by logam555** [comment]
Since discord is related to the issue, my discord API version is 1.7.3 (will edit that up top with all the other versions)

**Comment by QIN2DIM** [comment]
Is this a multi-process project?

**Comment by logam555** [comment]
It involved async so I would guess so?

I did just find a workaround though. If I start UC before entering the discord bot routine it seems to work alright (as long as I have the script sleep for a few seconds so chrome gets bootstrapped). 

Test code:
```
import asyncio
import undetected_chromedriver as uc
from discord.ext import commands

bot = commands.Bot(command_prefix='!')

@bot.command(name="test", pass_context=True, help="tests things")
async def test(ctx):
    await driver.get('https://nowsecure.nl')

async def wait3():
    await asyncio.sleep(3)

if __name__ == '__main__':
    driver = uc.Chrome()
    asyncio.run(wait3())
    bot.run(<Insert Discord Bot Token Here>)
```

**Comment by logam555** [comment]
I'll use my workaround to redesign the original bot. 

sebdelsol if you want my help in trying to track down the issue further to fix it for UC, or even just talk about it further, let me know. 

I will leave the issue open in case you want to keep it as a known unfixed bug, otherwise, you can close it.

**Comment by QIN2DIM** [comment]
This is clearly a single-process project(GIL). The async event loop causes UC's time-consuming tasks to be constantly discarded and lagged.

```python
import asyncio

import undetected_chromedriver as uc
from webdriver_manager.chrome import ChromeDriverManager


async def stest():
    print(">> Enter `stest` function")
    driver = uc.Chrome(
        headless=True,
        driver_executable_path=ChromeDriverManager(log_level=0).install()
    )
    try:
        driver.get('https://nowsecure.nl')
    finally:
        print(f"{driver.title=}")
        driver.quit()
        print(">> Drive Exit")


async def factorial(name, number):
    print(name, number)
    while True:
        # 1. await asyncio.sleep(0.1)
        # 2. pass or time.sleep(0.1)
        # 3.
        pass


async def main():
    # Schedule three calls *concurrently*:
    await asyncio.gather(
        stest(),
        factorial("A", 2),
        factorial("B", 3),
        factorial("C", 4),
        # stest(), # Putting stest() in this will have a different start sequence
    )


if __name__ == '__main__':
    asyncio.run(main())


```

**Comment by QIN2DIM** [comment]
You need to be very careful when developing asynchronous programs in Python; once you encounter a lock you can't unlock (like `while True`), the program falls crash.

**Comment by sebdelsol** [comment]
In **mcscraper/aternosapi/__init__.py** line 19 [here](https://github.com/pritam20ps05/mcscraper/blob/21f1f71193d157d2fb35cfb51710edecc7f59275/aternosapi/__init__.py#L20) could you try to switch:

```python3
        self.driver = uc.Chrome(options=chrome_options)
```
with
```python3
        self.driver = uc.Chrome(options=chrome_options, use_subprocess=True)
```

**Comment by QIN2DIM** [comment]
@sebdelsol I suddenly found this to be a very interesting topic.

- https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/470

I asked a question about UC asynchronous collaboration a long time ago in this project. But no one paid attention to me for a long time, and at the same time I had other solutions and closed that topic. 😂

If you run the following code, the UC does 「hang」 and the process does not exit properly.

```bash
pip install loguru gevent
```

```python
# undetected_chromedriver v3.1.5.post4
# python v3.10
from gevent import monkey

monkey.patch_all()
from loguru import logger
import undetected_chromedriver as uc

from urllib3.exceptions import RequestError


@logger.catch()
def demo():
    ctx = uc.Chrome(headless=True)
    try:
        ctx.get("https://www.google.com")
        logger.debug(ctx.title)
    finally:
        ctx.quit()

    logger.success(f">> Driver Exit << ")

    for _ in range(2):
        try:
            logger.debug(ctx.current_url)
        except RequestError as err:
            logger.error(err)

    logger.debug(">> Return <<")


if __name__ == '__main__':
    logger.debug(">> Awesome <<")
    demo()
    logger.debug(">> Down? <<")

```
I think the problem is much less simple than it seems, and I tried to read the source code of UC in the days when the issue was raised, but did not find the root cause of the problem.

**Comment by logam555** [comment]
In my case, the `use_subprocess=True` does actually solve the issue. It does start chrome and It doesn't get detected as a bot, so looks like that does fix the issue.

As for QIN2DIM's case, I don't know anything about gevent so I cannot help there.
