### ISSUE TITLE
Fail to click in headless or minimization mode

### ISSUE THREAD

**Issue by donggoing** [ultrafunkamsterdam/undetected-chromedriver#598]
i am doing something with geetest captcha, when i click the verification button, it should show the captcha with images but it doesn't in headless or minimization mode. While it works fine when the browser is visible or using the normal webdriver in headless mode.

**Comment by donggoing** [comment]
Does anybody have any ideas？Thanks in advance！

**Comment by QIN2DIM** [comment]
Can you provide me with some test environments to replicate, such as a pristine captcha site?

**Comment by donggoing** [comment]
> Can you provide me with some test environments to replicate, such as a pristine captcha site?

Like this [site](https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMAFzLgJAHPdNIASt4UGg%3D%3D&hash=4797D6E193ECA8320444B1243C4609&cid=.CzjV1WIKgNPKa.bkwBCb0gvY-~Ta7gMRDzd5CpRG8QpG8ijYuy~vBXHbArVbjler.KdxY~EWK7.gOnsMio3pgf2Kt3ySCJaMmA0ml-mPj4xHRndkLPlc3_0K6HDDaix&t=fe&referer=https%3A%2F%2Ffr.shopping.rakuten.com%2Fmfp%2F7316376%2Fxiaomi-redmi-10%3Fpid%3D7165265912&s=379). What i want to do is to click the .geetest_radar_btn button, then get images in div.geetest_widget like .geetest_canvas_bg's image. But in headless mode, it seems doesn't work. When i click, div.geetest_widget just doesn't show up, while it works when the browser is visible.

**Comment by donggoing** [comment]
btw, the version i'm using is the latest(3.1.5.post4).

**Comment by QIN2DIM** [comment]
> When i click, div.geetest_widget just doesn't show up,

whats mean,Are you saying that the box won't load, or that the image won't render.

**Comment by QIN2DIM** [comment]
I have done similar work (homework, I will send  a demo repository here.

**Comment by donggoing** [comment]
> > When i click, div.geetest_widget just doesn't show up,
> 
> whats mean,Are you saying that the box won't load, or that the image won't render.

the box won't load.

**Comment by QIN2DIM** [comment]
https://github.com/QIN2DIM/armour-geetest

**Comment by QIN2DIM** [comment]
蚌珠了，难道是核善的网友。

**Comment by donggoing** [comment]
> 蚌珠了，难道是核善的网友。

哈哈哈哈，我之前不用undetected_chromedriver的时候时可以的，就是反爬升级换到这个driver之后只要最小化或者headless点击geetest_radar_btn不弹出图片框。

**Comment by QIN2DIM** [comment]
极验和 `Google reCAPTCHA` 以及 `hCaptcha` 都差远了，两者都不是一个段位的，只有后面说的这两种以及 `FunCaptcha` 需要使用 `undetected_chromedriver` 隐藏浏览器特征。

极验前端不存在检测用户行为代码，它相当于是直接插入在前端网页中的模块，在配置 `ChromeOptions()` 时需要留意，否则挑战需要用到的图片以及渲染脚本会被禁止运行。

至于 `undetected_chromedriver headless` 无法弹出拼图窗口的情况我还没测试过，也可能是你的打开方式不太对。

**Comment by donggoing** [comment]
之前我用官方的webdriver一直是可以的，最近突然不行了（就是开启某个使用极验服务的[网页](https://www.fnac.com/mp45042255/Robot-Aspirateur-Roborock-S7-Application-Alexa-2500Pa/w-4#omnsearchpos=15)就显示ip被封了，也可能是datadome的问题？不大清楚）。

主要我不清楚具体是哪里被检测出来了，但是换成undetected_chromedriver就可以了，现在就是需要解决headless的问题就好了（

**Comment by sebdelsol** [comment]
Please try `options.add_argument("--start-maximized")`.
If I remember correctly, even headless you have to have your element "shown" in the canvas to be clickable.

**Comment by donggoing** [comment]
> Please try `options.add_argument("--start-maximized")`. If I remember correctly, even headless Chrome needs to have an element "shown" in the canvas to be clickable.

I tried, but it doesn't work neither.

**Comment by donggoing** [comment]
I figure it out...
I thought this drive could be anonymous automatically, so i don't check the options carefully. After adding `driver_options.add_argument("--disable-blink-features=AutomationControlled")`, it works.

Thank a lot!

**Comment by QIN2DIM** [comment]
> 极验和 `Google reCAPTCHA` 以及 `hCaptcha` 都差远了，两者都不是一个段位的，只有后面说的这两种以及 `FunCaptcha` 需要使用 `undetected_chromedriver` 隐藏浏览器特征。
> 
> 极验前端不存在检测用户行为代码，它相当于是直接插入在前端网页中的模块，在配置 `ChromeOptions()` 时需要留意，否则挑战需要用到的图片以及渲染脚本会被禁止运行。
> 
> 至于 `undetected_chromedriver headless` 无法弹出拼图窗口的情况我还没测试过，也可能是你的打开方式不太对。
> 
> 极验存在 v2 和 v3 两个版本，v2 的话直接把缺口完全对齐就能通过。v3需要拟人化的轨迹和加速度。这些检测都是在 `iframe` 中独立计算的，不会涉及到判断浏览器特征的东西，所以用普通的 `selenium` 就能处理。

敲，特地來回復一下。上文説到GeeTest的種種不足，只能說我太膚淺了。我上次運行關於 GeeTest 的代碼還是在兩年前事情，沒想到現在这么花里胡哨了！！

![image](https://user-images.githubusercontent.com/62018067/165529217-7fc946e7-0d99-429e-9cff-4b64b4d0a076.png)

![image](https://user-images.githubusercontent.com/62018067/165528599-d0bd335d-dfcf-4f00-9979-18a6537ffc6c.png)

**Comment by QIN2DIM** [comment]
> 毕竟是商业化的，要恰饭的嘛：）

但从我的经验来看，能够对抗机器人的只有特征检测，浮于表面看起来花里胡哨的验证逻辑只会把人类挡在外面。

**Comment by donggoing** [comment]
> > 毕竟是商业化的，要恰饭的嘛：）
> 
> 但从我的经验来看，能够对抗机器人的只有特征检测，浮于表面看起来花里胡哨的验证逻辑只会把人类挡在外面。

同意~
