### ISSUE TITLE
Detected by Distill Network

### ISSUE THREAD

**Issue by FocuSPower** [ultrafunkamsterdam/undetected-chromedriver#6]
I was trying to scrap g2.com. First time i went to the website it works fine, but the second time i return it detects suspicious activity. The message it pops is: 

Pardon Our Interruption...
As you were browsing something about your browser made us think you were a bot. There are a few reasons this might happen:

You're a power user moving through this website with super-human speed.
You've disabled JavaScript and/or cookies in your web browser.
A third-party browser plugin, such as Ghostery or NoScript, is preventing JavaScript from running. Additional information is available in this support article.
After completing the CAPTCHA below, you will immediately regain access to the site again

Brief:
The fact is that i did not moved fast at all, just tried to acces a page. First time it worked, second time i got caught.

**Comment by ultrafunkamsterdam** [comment]
Please provide OS, chrome version, and your code.

**Comment by FocuSPower** [comment]
OS: Windows10
ChromeVersion: 81.0.4044.138
Sorry, im new in web-scraping, what kinda code ?

**Comment by FocuSPower** [comment]
> OS: Windows10
> ChromeVersion: 81.0.4044.138
> Sorry, im new in web-scraping, what kinda code ?

**Comment by chemeng** [comment]
I think they can identify you from your browsing behavior. Maybe they can track the mouse speed or something similar and identify you AFTER the first page has been loaded and as you move towards a second page.

**Comment by ultrafunkamsterdam** [comment]
> Sorry, im new in web-scraping, what kinda code ?

Given this reply (on the biggest coding-related platform) , makes me think you might have just used your mouse and keyboard to navigate to g2.com .  Doing so will not make you **detectable even with a patched driver** (i just reproduced). Once detected, subsequent requests in a short time from the same ip will trigger the captcha again.  So just solve the captcha, stay away for a while (or/and use your regular browser and navigate through the site). 

What also might help is to create a dedicated Chrome profile using your regular chrome session,  make a note of the path to the folder, log into your google acccount, then quit chrome, specify that profile path explicitly in ChromeOptions object which you can pass to Chrome(options=options_obj).

Anyway, tested:

```python
import undetected_chromedriver as uc
driver = uc.Chrome()
driver.get('https://g2.com')
driver.find_element_by_id('query').send_keys('Coding')   # ;)
driver.find_element_by_css_selector('button[type=submit] div').click()
driver.close()
```
Not detected (even when **not** trying to act human-like).  However after i opened a new tab using my mouse and navigated to the site, i was detected as described above.

**Comment by FocuSPower** [comment]
Now i realised you we're talking about the script xD. Sorry, my bad

`if 'g2' in nnn.get_attribute('value'):
                driver.get('https://www.g2.com/products/'+site[:-4]+'/reviews')
                number1_g2 = driver.find_element_by_class_name('link js-log-click')
                number2_g2 = number1_g2[1].text
                number_g2 = number2_g2[:-8]
                rate1_g2 = driver.find_element_by_class_name('fw-semibold')
                rate_g2=rate1_g2[2].text`
