### ISSUE TITLE
bet365

### ISSUE THREAD

**Issue by Hoozits728** [ultrafunkamsterdam/undetected-chromedriver#60]
Up until a few days ago this worked on bet365 but now I am just getting a white browser window and a spinning icon showing that the page is not loading.

![image](https://user-images.githubusercontent.com/1102584/100544447-4353c000-321b-11eb-8b86-eb88e4b83da4.png)

**Comment by ultrafunkamsterdam** [comment]
When i access the site in a regular "clean" browser.. the website isn't really cooperating either....

![image](https://user-images.githubusercontent.com/21027969/100573889-16fe7900-32d9-11eb-9f41-7eb39a63fb09.png)

... still waiting ...

**Comment by boganfoo** [comment]
Hi, after some research I found that bet365 might be doing something nasty. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1673636
Any ideas on what we can do here?

**Comment by boganfoo** [comment]
Hello, I worked out this problem. I don't really know what I'm talking about, someone else fixed this for me. 
It was the cdc variable in chromedriver. 
Once I received a patched chromedriver, along with using undetected-chromedriver, bet365 loaded. 
Thanks so much for your good work.

**Comment by asliazas** [comment]
I have the same issue, where I could find this patched chromedriver? I tried replacing cdc variables myself by it didn't work.

**Comment by Hoozits728** [comment]
Changing the cdc variable int he chromedriver was the answer for me. I opened the exe file up in Notepad++ and did a find and replace to convert all cdc_ to xyz_. Thanks for this answer and this awesome work.

> Hello, I worked out this problem. I don't really know what I'm talking about, someone else fixed this for me.
> It was the cdc variable in chromedriver.
> Once I received a patched chromedriver, along with using undetected-chromedriver, bet365 loaded.
> Thanks so much for your good work.
