### ISSUE TITLE
UC and rotating proxy service

### ISSUE THREAD

**Issue by bezkos** [ultrafunkamsterdam/undetected-chromedriver#600]
I use a http rotating proxy service that rotates IPs on every request.

I check UC (3.1.1) and see that keeps same IP on every request like such
self.driver = uc.Chrome(**driver_kwargs)
self.driver.get(request.url1)
self.driver.get(request.url2)
self.driver.get(request.url3)

I tested rotating proxy service with Scrappy for 4-5 URLS and works fine rotating IPs.

I would like @ultrafunkamsterdam or someone else who use such service and test IPs to confirm this so to understand if it is bug of UC.

**Comment by SeriyVol4ishe** [comment]
you can look at [selenium-wire](https://github.com/wkeeling/selenium-wire) which uses undetected-chromedriver.

**Comment by sebdelsol** [comment]
To be sure we understand your issue : 
* you expect each `driver.get()` to use a different IP ?
* have you tried your proxy on a regular chrome browser and checked that you IP change with each url ?
* have you tried something with undetected-chrome-driver ?

If you wonder how to use proxies, please check [this answer](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/587#issuecomment-1096591305)

**Comment by bezkos** [comment]
you expect each driver.get() to use a different IP ? **Yes**
what triggers IP rotation with your proxy service ? **Each Request**
have you tried your proxy on a regular chrome browser and checked that you IP change with each url? **No with Chrome but I did several requests with Scrappy and each one get different IP**

It isn't proxy setup problem with UC. Anyway its rotate proxy service with whitelist IP so need only 1 line like
options.add_argument('--proxy-server=IP:PORT')
UC get proxy IP for 1st driver.get() but didn't change it on every request. Thats why i need to confirm from someone who use similar service if its a limitation from UC/Selenium.
Thanx in advance

**Comment by SeriyVol4ishe** [comment]
@bezkos as i wrote above try to use selenium-wire cause it can rotate proxy for each get.

**Comment by sebdelsol** [comment]
Last thing I would try is using `keep_alive=True` kwarg for your driver and `driver.reconnect()`  between each `driver.get()`
If that doesn't work then you'll to try to find what makes your IP rotate _in a regular Chrome browser_, then it'll be easy to reproduce with Selenium.
Btw does you proxy service has an API and/or a description how they trigger IP rotation ?

**Comment by sebdelsol** [comment]
You can close the window in incognito mode without ditching the driver, you should have a new clean session then:
```python3
    options = uc.ChromeOptions()
    options.add_argument("--incognito")
    driver = uc.Chrome(options=options, **driver_kwargs)
    
    driver.tab_new(url1)
    driver.close()
    driver.tab_new(url2)
    driver.close()
    driver.tab_new(url3)
```

**Comment by bezkos** [comment]
@sebdelsol @SeriyVol4ishe, 
I found solution to this problem.
I need to add to request.header({'Connection': 'close'})
Cause Selenium dont support add to headers, i used seleniumwire for it.
Now every request get different IP.

**Comment by quentinjs** [comment]
Given that SeleniumWire is SOOOO SLOW, I found another approach.  Works with UC 

class CloseConnectionAdapter(requests.adapters.HTTPAdapter):
    def __init__(self, *args, **kwargs):
        pool_connections = kwargs.pop('pool_connections', 1)
        pool_maxsize = kwargs.pop('pool_maxsize', 1)
        super().__init__(*args, **kwargs)
        self.poolmanager.connection_pool_kw['maxsize'] = pool_maxsize
        self.poolmanager.connection_pool_kw['block'] = True
        self.poolmanager.connection_pool_kw['headers'] = {'Connection': 'close'}

    #def init_poolmanager(self, *args, **kwargs):
    #    kwargs['keep_alive'] = False
    #    self.poolmanager = PoolManager(*args, **kwargs)


session = requests.Session()
session.mount('http://', CloseConnectionAdapter())
session.mount('https://', CloseConnectionAdapter())
driver = webdriver.Chrome()
driver.get('https://www.example.com')
response = session.get(driver.current_url)

The code commented out will work if your version of UR Lib has keep alive as an alternative

**Comment by ngohanquangvu** [comment]
> request.header({'Connection': 'close'})

can u give me full code, i dont know how to add it
