### ISSUE TITLE
Unable to add multiple extensions

### ISSUE THREAD

**Issue by ariyasas** [ultrafunkamsterdam/undetected-chromedriver#602]
First of all, thanks @ultrafunkamsterdam for this magic little module. Everything works great except I've been running into an issue when trying to run uc.Chrome with more than a single extension. My code is below:

    import undetected_chromedriver.v2 as uc

    options = uc.ChromeOptions()
    options.add_argument('--load-extension=/Users/User1/Desktop/live_stream')
    options.add_argument('--load-extension=/Users/User1/Desktop/ublock')

    driver = uc.Chrome(use_subprocess=True, options=options)

    driver.get('https://real-gomovies.com/watch-movie/spider-man-no-way-home/8nviiIe2/KOiUVHIs-online.html')```

Both extensions work individually, however when both are present, uc.Chromedriver only runs with the last extension loaded. So for this case, it would only load up with the 'uBlock.' Is there a mistake on my end, or is this an intentional feature meant to preserve the module's primary purpose of undetectability? Thanks for any and all help.

**Comment by sebdelsol** [comment]
According to this extensive list of Chrome command line switches [here](https://peter.sh/experiments/chromium-command-line-switches/#load-extension) you should use a **Comma-separated list of paths to extensions to load at startup**

**Comment by ariyasas** [comment]
> 

This worked. Thank you @sebdelsol.
