### ISSUE TITLE
Can't  bypass https://gleam.io/

### ISSUE THREAD

**Issue by JenoKey** [ultrafunkamsterdam/undetected-chromedriver#606]
I've tried with this site but can't seem to pass its checker

**Comment by sebdelsol** [comment]
It works fine I have the exact same page as in a regular Chrome... You'll want to show some code and explain what doesn't work as expected.

**Comment by JenoKey** [comment]
`from time import sleep
import undetected_chromedriver as uc
options = uc.ChromeOptions()
options.user_data_dir = "PATH_profile"
driver = uc.Chrome(options=options, use_subprocess=True)  
driver.get('https://gleam.io/Yp3um/fusotao-second-batch-testnet-rewards-activity?gsr=Yp3um-w7OhFF03Pw')
`
This is my code. I try it with my other profiles. But it is not accessible
*Note: I use ip 4g from mobile.

**Comment by sebdelsol** [comment]
Again I land on the exact same page by using undetected-chromedriver or a regular Chrome browser.
Btw you shouldn't use `use_subprocess=True` as stated in the uc.Chrome() class docsctring. 
Please format correctly your code.

**Comment by QIN2DIM** [comment]
I suddenly found it very difficult to communicate with the community on this project. Many of the basic questions were repeated, almost several times a week. Second, many people do not know how to ask questions. Finally, most of the questions are related to the programming ability of the individual questioner and not to the project itself.

But no matter how uninteresting the question is, you'll be able to recover in enthusiasm. Salute. @sebdelsol
