### ISSUE TITLE
i dont know exactly why but when i run the setup this error apears

### ISSUE THREAD

**Issue by georgepelal** [ultrafunkamsterdam/undetected-chromedriver#607]
![setup py - ok - Visual Studio Code 4_23_2022 4_26_05 PM](https://user-images.githubusercontent.com/103337766/164896568-d2d66a04-b298-4b8e-99ac-990c24a7fae1.png)

and when i try to add it on a program this error appears
![ok3 py - ok - Visual Studio Code 4_23_2022 4_45_50 PM](https://user-images.githubusercontent.com/103337766/164903620-02d020aa-5da0-4562-925f-db9e195f7a6d.png)

please help

**Comment by georgepelal** [comment]
and when i try to add it on my program this error appears 
![setup py - ok - Visual Studio Code 4_23_2022 4_26_05 PM](https://user-images.githubusercontent.com/103337766/164896949-3caf1dd9-b425-4c3c-a08b-40927137c2ef.png)

**Comment by sebdelsol** [comment]
* [Installing Python Modules (Legacy version)](https://docs.python.org/3/install/index.html) but you should use pip instead
* Check [this](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/561#issuecomment-1075363395)

**Comment by georgepelal** [comment]
for the first one do you mean that i should do this? : pip install undetected-chromedriver
Because I already did

**Comment by georgepelal** [comment]
now the program runs but the chrome window doesnt show up for some reason 
![ok2 py - ok - Visual Studio Code 4_23_2022 5_42_20 PM](https://user-images.githubusercontent.com/103337766/164910836-2debabe7-6457-4e7f-95ca-cf64a31e8a63.png)

**Comment by georgepelal** [comment]
oh nevermind i figured it out i shoud put the rest of the code behind if 
Thanks tho

**Comment by sebdelsol** [comment]
> for the first one do you mean that i should do this? : pip install undetected-chromedriver
> Because I already did

Then you don’t need to use setup.
Please close the issue.

**Comment by georgepelal** [comment]
now i get it thanks again
