### ISSUE TITLE
Message: session not created: This version of ChromeDriver only supports Chrome version 87

### ISSUE THREAD

**Issue by youpsla** [ultrafunkamsterdam/undetected-chromedriver#61]
Hello. I have seen issue [#8 ](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/8) but proposed solution doesn't sole my issue.

I'm running a debian with ChromeDriver 83.0.4103.39  and google-chrome 83 and undetected-chromedriver 1.5.1. Had no issue running this configuration with selenium. Recently, I need to bypass CloudFare 5 sec redirection page.

I have tried the 3 methods in the readme of undetected-chromedriver. Got same error each time.
```
Nov 30 18:21:54 carnac python[855]: selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 87
Nov 30 18:21:54 carnac python[855]: Current browser version is 83.0.4103.106 with binary path /usr/bin/google-chrome

```

I have tried:
```python
import undetected_chromedriver as uc
uc.TARGET_VERSION = 85
opts = uc.ChromeOptions()
opts.add_argument("--headless")
driver = uc.Chrome(options=opts, enable_console_log=True)
driver.get(my_target_url)
```
and

```python
import undetected_chromedriver as uc
uc.TARGET_VERSION = 85
uc.install()

from selenium.webdriver import Chrome
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--headless")
driver = webdriver.Chrome(options=chrome_options) 
driver.get(my_target_url)
```

Any idea ?

**Comment by ultrafunkamsterdam** [comment]
Error is quite clear.

Remove your chrome driver executable. Otherwise it will never download other version
```rm -f /your/workdir/chromedriver```

And ```uc.TARGET_VERSION = 85``` won't work if your version is 83 . Change that as well or it will download incorrect version again.

**Comment by youpsla** [comment]
Thanks for your answer.

It works now.
