### ISSUE TITLE
Updating proxy without quit the driver

### ISSUE THREAD

**Issue by 4mekki4** [ultrafunkamsterdam/undetected-chromedriver#612]
Hello,
As selenium-wise suggests, we can switch the proxy using:
------------
driver.get(...)  # Using some initial proxy

# Change the proxy
driver.proxy = {
    'https': 'https://user:pass@192.168.10.100:8888',
}

driver.get(...)  # These requests will use the new proxy
------------

How can we do the same with UC?

**Comment by sebdelsol** [comment]
You can use undetected-chromedriver with seleniumwire as documented [here](https://github.com/wkeeling/selenium-wire#bot-detection)

**Comment by 4mekki4** [comment]
> You can use undetected-chromedriver with seleniumwire as documented [here](https://github.com/wkeeling/selenium-wire#bot-detection)

I agree, but as mentioned before, seleniumwire weaken the bot detection?

Is there any manner to do it from UC without the use of seleniumwire?

**Comment by sebdelsol** [comment]
please check [this answer](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/587#issuecomment-1096591305) for different ways to implement proxies with their caveats. 
If you want to be able to change proxies without quitting the driver you'll have to create an extension that do that. 
I don't think it's in the scope of this project though.

**Comment by 4mekki4** [comment]
Got it!
