### ISSUE TITLE
SSL Handshake Error With Docker and Selenium trying to access website

### ISSUE THREAD

**Issue by thlorenzen** [ultrafunkamsterdam/undetected-chromedriver#615]
I have a python script which is running Chrome with chromedriver and selenium. When I run the script without Docker it works normally and I access the website, if in Docker the Exception gets shown in the Browser with a 502 Gateway Error. My theory is that I need to configure the SSl Settings in the Docker Container, but I dont know exactly how Error shown in Chrome in Docker(Selenium):

`TlsProtocolException('Cannot establish TLS with accounts.ea.com:443 (sni: accounts.ea.com): 
TlsException("SSL handshake error: Error([(\'SSL routines\', \'\', \'unsafe legacy renegotiation disabled\')])")')````

**Comment by QIN2DIM** [comment]
What is your version of `urllib3`?

**Comment by thlorenzen** [comment]
Thank you very much for your answer!

`urllib3` version = `1.26.9`

I updated the one in Dockercontainer to the same version now, still not working. I updated all packages like on host, still not working...

My theory now is that the website detects that im running it from a Docker-Container

**Comment by thlorenzen** [comment]
> What is your version of `urllib3`?
