### ISSUE TITLE
Browser Not Launched

### ISSUE THREAD

**Issue by yuta0904** [ultrafunkamsterdam/undetected-chromedriver#618]
def SendVerificationEmailMeta2(email,meta):
    if __name__ == '__main__':
        print("Starting...")
        proxy_details = Proxy.get_proxy(proxy_list)
        print(proxy_details)
        print("Proxy Settings...")
   
        print("Chrome Settings...")
        driver = uc.Chrome(driver_executable_path = './chromedriver.exe')
        print("Chrome Done Settings...")
     
        #Go to link and wait until there are no more than 2 connections for at least 500 ms
        print("Page Open Starting...")
        driver.get(url)
        randomwait(3,4)

I am able to see print("Chrome Settings...") output.
I believe there will be an issue in driver = uc.Chrome(driver_executable_path = './chromedriver.exe')

**Comment by sebdelsol** [comment]
Please format correctly your code.
You don't wan't to use `driver_executable_path ` sot that your driver will be downloaded and randomly patched and lower the probability to be detected.

**Comment by yuta0904** [comment]
> Please format correctly your code. You don't wan't to use `driver_executable_path ` sot that your driver will be downloaded and randomly patched and lower the probability to be detected.

Can you please review my source code if possible?

**Comment by sebdelsol** [comment]
Sure, please gives a fully working example and use code blocks with syntax highlighting : [Check here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) and use `python3` for Python code.

**Comment by yuta0904** [comment]
```python
def SendVerificationEmailMeta2(email,meta):
    if __name__ == '__main__':
        print("Starting...")
        proxy_details = Proxy.get_proxy(proxy_list)
        print(proxy_details)
        print("Proxy Settings...")

        PROXY = proxy_details[0].split(":")[0] + ':' + proxy_details[0].split(":")[1]
        options.add_argument(f"--load-extension=C:\MAT\Proxy\Proxy Auto Auth.crx")
        options.add_argument("--proxy-server=http://{}".format(PROXY))	

        print("Chrome Settings...")
        driver = uc.Chrome()
        print("Chrome Done Settings...")

        driver.get("chrome-extension://ggmdpepbjljkkkdaklfihhngmmgmpggp/options.html")
        driver.findElement(By.id("login")).send_keys(proxy_details[0].split(":")[2])
        driver.findElement(By.id("password")).send_keys(proxy_details[0].split(":")[3])
        randomwait(2,4)
        driver.findElement(By.id("save")).click()
        print(proxy_details)
        #Go to link and wait until there are no more than 2 connections for at least 500 ms
        print("Page Open Starting...")
        driver.get(url)
```

**Comment by yuta0904** [comment]
Thank you for reply.

Proxy Settings...
Traceback (most recent call last):
  File "MAT_Refactor_v1.py", line 318, in <module>
    SendVerificationEmailMeta2(email,meta)
  File "MAT_Refactor_v1.py", line 197, in SendVerificationEmailMeta2
    options = ChromeOptions()
NameError: name 'ChromeOptions' is not defined
'''python3
def SendVerificationEmailMeta2(email,meta):
    print("Starting...")
    proxy_details = Proxy.get_proxy(proxy_list)
    print(proxy_details)
    print("Proxy Settings...")
    options = ChromeOptions()
    PROXY = proxy_details[0].split(":")[0] + ':' + proxy_details[0].split(":")[1]
    options.add_argument(f'--load-extension="C:\MAT\Chrome\ProxyAutoAuth.crx"')
    chrome_options.add_argument("--proxy-server=http://{}".format(PROXY))
    print("Chrome Settings...")
    options.add_argument("start-maximized")
    driver = uc.Chrome(options=options)
    print("Chrome Done Settings...")
    driver.get("chrome-extension://ggmdpepbjljkkkdaklfihhngmmgmpggp/options.html")
    driver.findElement(By.id("login")).send_keys(proxy_details[0].split(":")[2])
    driver.findElement(By.id("password")).send_keys(proxy_details[0].split(":")[3])
    randomwait(2,4)
    driver.findElement(By.id("save")).click()
    print(proxy_details)
    print("Page Open Starting...")
    driver.get(url)
    randomwait(3,4)
'''

**Comment by yuta0904** [comment]
> There are a lot stuff missing...
> 
> * There are no imports, so I'm not completely sure what you're doing.
> * `if __name__ == '__main__':` has to be in the global scope of your script (not in a function).
>   please check it's [idiomatic usage here](https://docs.python.org/3/library/__main__.html#id1) and [this](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/561#issuecomment-1075363395) to understand why it's needed.
> * You need to instantiate `options = uc.ChromeOptions()` and pass it to `uc.Chrome(options=options)`.
> * You need to quote arguments that have spaces in it :
>   try `options.add_argument(f'--load-extension="C:\MAT\Proxy\Proxy Auto Auth.crx"')` or it will be seen as several command line switches by Chrome.
> * You'd rather use [Selenium explicit wait](https://selenium-python.readthedocs.io/waits.html#explicit-waits) to save you a lot of hassle instead of relying on unreliable `time.sleep()`.
> * BTW there are other (and probably more reliable) ways to implement proxies with authentication, please [check this answer](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/587#issuecomment-1096591305).
> 
> EDIT : it's `uc.ChromeOptions()` since it's part of undetected-chromedriver and I guess you import it `as uc`

RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Exception ignored in: <function Chrome.__del__ at 0x000001DF851ECDC0>
Traceback (most recent call last):
  File "C:\Users\yuuta\AppData\Local\Programs\Python\Python38\lib\site-packages\undetected_chromedriver\__init__.py", line 583, in __del__
  File "C:\Users\yuuta\AppData\Local\Programs\Python\Python38\lib\site-packages\undetected_chromedriver\__init__.py", line 539, in quit
  File "C:\Users\yuuta\AppData\Local\Programs\Python\Python38\lib\site-packages\undetected_chromedriver\__init__.py", line 367, in __getattribute__
AttributeError: 'Chrome' object has no attribute 'service'

**Comment by yuta0904** [comment]
How can I solve above error?
selenium                  4.1.3
undetected-chromedriver   3.1.0
PS C:\MAT> python -V
Python 3.8.10

**Comment by sebdelsol** [comment]
```python3
if __name__ == '__main__':
    SendVerificationEmailMeta2(email,meta)
```
please check  [this](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/561#issuecomment-1075363395) to understand why it's needed.

**Comment by yuta0904** [comment]
> ```python
> if __name__ == '__main__':
> ```
```python3
        init()
        load_emails()
        load_metamask()
        for (email,meta) in zip(emails_list,metamask_list):
            if __name__ == '__main__':
                endVerificationEmailMeta2(email,meta)
        sys.exit()
```

**Comment by yuta0904** [comment]
Like this?

**Comment by yuta0904** [comment]
PS C:\MAT> python MAT_Refactor_v1.py
Enter Option : 2


Starting...
Proxy Settings...
Chrome Settings...
Enter Option : 2

**Comment by yuta0904** [comment]
It is stuck....

**Comment by yuta0904** [comment]
PS C:\MAT> python MAT_Refactor_v1.py
Enter Option : 2


Starting...
Proxy Settings...
Chrome Settings...
Enter Option : 2


Invalid input. Try again!
Enter Option : 2


Invalid input. Try again!
Enter Option :

**Comment by sebdelsol** [comment]
Sure it's stuck : you have a `while True` and it obviously hangs when the Chrome process is launched...

Please be aware that undetected-chromedriver launch a (detached) process to open a Chrome browser,  that one of its trick to avoid detection.

When launching another processes on Windows you have to protect your entry point with the infamous `if __name__ == '__main__'`. _Please learn how to use it_ : I've given you all the documentation you'll need to do that : again it needs to be _in the global scope_ of your script

**Comment by yuta0904** [comment]
> It does as expected : you have a `while True` _infinite loop_ and it hangs when the Chrome process is launched.
> 
> Please be aware that undetected-chromedriver create a (detached) process that launches a Chrome browser, that's one of its tricks to avoid detection.
> 
> When launching another processes on Windows _you have to protect your script entry point_ with the infamous `if __name__ == '__main__'`. _Please learn how to use it_ : I've given all the documentation you'll need : again you've to use it _in the global scope_ of your script.

But it is working on V3.0.3 as I refered to another issue.
BTW there are other (and probably more reliable) ways to implement proxies with authentication, please https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/587#issuecomment-1096591305.

**Comment by yuta0904** [comment]
Can you please help me imprement proxies with auth?

**Comment by sebdelsol** [comment]
> But it is working on V3.0.3 as I reffered to another issue. 

Because the former versions where not working the same way and were more detectable.

**Comment by yuta0904** [comment]
> > But it is working on V3.0.3 as I reffered to another issue.
> 
> Because the former versions were not working the same way and were more detectable.
> 
> > Can you please help me imprement proxies with auth?
> 
> I already gave you the answer above : check [here](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/587#issuecomment-1096591305)

https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/587#issuecomment-1102946225
Do I just copy and paste?

For example
manifest_json = **"""**
{
    "version": "1.0.0",
    "manifest_version": 2,
    "name": "Chrome Proxy",
    "permissions": [
        "proxy",
        "tabs",
        "unlimitedStorage",
        "storage",
        "<all_urls>",
        "webRequest",
        "webRequestBlocking"
    ],
    "background": {
        "scripts": ["background.js"]
    },
    "minimum_chrome_version":"22.0.0"
}

**Comment by yuta0904** [comment]
Fixed and working now!
Thank you for your help!
