### ISSUE TITLE
 undetected-chromedriver + auth proxy = ip doesn't change

### ISSUE THREAD

**Issue by realdronos** [ultrafunkamsterdam/undetected-chromedriver#619]
My ip just didn't change, any ideas?

selenium-wire - 4.6.3
selenium - 4.1.3
undetected-chromedriver - 3.1.5.post4

    import time
    from seleniumwire import webdriver
   
     if __name__ == '__main__':

    seleniumwire_options = {'proxy': {'https': 'https://LOGIN:PASSWORD@IP:PORT', }}

    driver = uc.Chrome(seleniumwire_options=seleniumwire_options)

    driver.get('https://api.myip.com/')

    time.sleep(10)

Proxy up and works

**Comment by sebdelsol** [comment]
You should have check the [documentation here](https://github.com/wkeeling/selenium-wire#bot-detection) how to use undetected-chromedriver with seleniumwire on the relevant [repo](https://github.com/wkeeling/selenium-wire)

```python3
import time
import seleniumwire.undetected_chromedriver as uc

if __name__ == "__main__":
    chrome_options = uc.ChromeOptions()
    # here your chrome options

    seleniumwire_options = {
        "proxy": {
            "https": "https://LOGIN:PASSWORD@IP:PORT"
        }
    }

    driver = uc.Chrome(
        options=chrome_options, seleniumwire_options=seleniumwire_options
    )
    driver.get("https://api.myip.com/")
    time.sleep(10)
```
You can even switch your proxy dynamically, please check [here](https://github.com/wkeeling/selenium-wire#switching-dynamically).
Anyway this is the wrong repo for your issue.

**Comment by realdronos** [comment]
Thank you!

**Comment by mittal-amit** [comment]
I'm using the same code and getting this error, any help would be appreciated. Thanks!

urllib.error.URLError: <urlopen error Tunnel connection failed: 407 Proxy Authentication Required>

**Comment by sebdelsol** [comment]
This issue is closed and doesn't belong in this repo... 
It probably means your proxy is not properly set, like getting an http page with an https proxy or the other way around.
