### ISSUE TITLE
[Question] Driver is detected by hCaptcha running inisde Docker container

### ISSUE THREAD

**Issue by QIN2DIM** [ultrafunkamsterdam/undetected-chromedriver#625]
## Question
I would like to know if undetected-chromedriver will behave differently on the image and host respectively in some special cases?

I have written a project that involves a process for handling [hCaptcha](https://www.hcaptcha.com/) challenges using undetected-chromedriver. I was able to **pass** the challenge by running the program directly **on the server**, but after packaging the project into an **image**, the challenge **did not pass** (the driver was detected).

**I first ruled out the server ip issue.** I did the same test on six servers from all over the world and on my local computer as well as on a linux virtual machine and all had the same problem.

So I'm guessing whether undetected-chromedriver will have occasional exceptions in some special application scenarios.

## ChromeOptions

Everything about this project you can see in [this repository](https://github.com/QIN2DIM/epic-awesome-gamer).

```python 
# Google Chrome 101.0.4951.54
# Python3.10
import os
import sys
from typing import Optional

from selenium.common.exceptions import WebDriverException
import undetected_chromedriver as uc
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.utils import get_browser_version_from_os, ChromeType


def get_challenge_ctx(
    silence: Optional[bool] = None,
    language: str = None,
    user_data_dir: Optional[str] = None,
):
    options = uc.ChromeOptions()
    options.add_argument("--log-level=3")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("--no-sandbox")

    os.environ["LANGUAGE"] = "zh" if language is None else language
    options.add_argument(f"--lang={os.getenv('LANGUAGE', '')}")

    silence = True if silence is None or "linux" in sys.platform else silence
    driver_executable_path = ChromeDriverManager(log_level=0).install()
    version_main = get_browser_version_from_os(ChromeType.GOOGLE).split(".")[0]

    try:
        return uc.Chrome(
            headless=silence,
            options=options,
            driver_executable_path=driver_executable_path,
            user_data_dir=user_data_dir,
        )
    except OSError:
        return uc.Chrome(headless=silence, options=options, user_data_dir=user_data_dir)
    except WebDriverException:
        if version_main.isdigit():
            return uc.Chrome(
                headless=silence,
                options=options,
                version_main=int(version_main),
                user_data_dir=user_data_dir,
            )

```
## Dockerfile

```dockerfile
FROM python:3.10-slim as builder

WORKDIR /home/epic

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

RUN apt update -y \
    && apt install -y wget

COPY src ./
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt install -y ./google-chrome-stable_current_amd64.deb \
    && rm ./google-chrome-stable_current_amd64.deb
```

**Comment by QIN2DIM** [comment]
## Fingerprint
Below is a screenshot of the fingerprint .mhtml, which can be opened with your browser.

[selenium(linux_headless).zip](https://github.com/ultrafunkamsterdam/undetected-chromedriver/files/8646891/selenium.linux_headless.zip)

**Comment by QIN2DIM** [comment]
## Additional

It is worth noting that until 2022-04-23 GMT+8, both methods described above will work fine. I guess it might have something to do with the version of google-chrome?

**Comment by ultrafunkamsterdam** [comment]
2 things

1 - don't pass all those options to uc. it's all been taken care of (including locale code). supplying those might cause chromedriver to be started with invalid command line arguments.
2 - headless is not supported

**Comment by ultrafunkamsterdam** [comment]
I forgot 3
- browsing using datacenter IPs != human. red flag

**Comment by QIN2DIM** [comment]
Thank you for your patient reply.

Regarding ip and headless mode, I actually did more testing and I determined that adding these parameters did not affect the experimental results.

Now I don't know why running python code directly on the same machine has different results than running the container. This is very confusing to me, I'm having a hard time debugging in the container, and I don't know what the problem is. 😂

**Comment by QIN2DIM** [comment]
## Additional
> I did the same test on six servers from all over the world and on my local computer as well as on a linux virtual machine and all had the same problem.

I think I need to correct some of the statements above.

I ran the same test on many machines, but one machine showed unexpected results, and it was the only one that could run both the code directly and the container.

**Comment by QIN2DIM** [comment]
Is there a better solution for error checking? I can reproduce it to the best of my ability.

If the problem is not solved within a week, I will close this issue.

**Comment by marrakechi** [comment]
Hello! 
I'm having the same issue as you! the exact time 23/04/2022! 
I've looked and found that there was an update of Google chrome, 

I've tried older verions, no result! 

Do you mind sharing the website you're testing? 
by the way, I'm also using your hcaptcha script, good work!

**Comment by denismur** [comment]
@QIN2DIM @marrakechi try to use another User Agent, i had the same issue with playwright+stealth. Now I have another problem - script in docker container works on local machine, but doesn't work on server

**Comment by marrakechi** [comment]
@denismur , thank you for your answer, 

I've already tried multiple user_agents, I've also tried randoms user_agents

**Comment by QIN2DIM** [comment]
>  script

By script you mean hcaptcha-challenger? 

> try to use another User Agent ... but doesn't work on server

How exactly do you practice.

@denismur Thank you for the reminder.

**Comment by denismur** [comment]
@QIN2DIM try to set User Agent and Viewport
User agents I took from this list: https://github.com/aw1875/puppeteer-hcaptcha/blob/master/src/useragents.json
```
    user_agent = choice(USER_AGENTS)
    browser_args = [
            '--window-size=1300,570',
            '--window-position=000,000',
            '--disable-dev-shm-usage',
            '--no-sandbox',
            '--disable-web-security',
            '--disable-features=site-per-process',
            '--disable-setuid-sandbox',
            '--disable-accelerated-2d-canvas',
            '--no-first-run',
            '--no-zygote',
            '--single-process',
            '--disable-gpu'
    ]         
    chromium = playwright.chromium
    browser = await chromium.launch(
        headless=True,
        args=browser_args,
    )
    context = await browser.new_context(
        ignore_https_errors=True,
        locale='en-US',
        user_agent=user_agent,
        viewport={
            'width': 1024 + math.floor(random() * 100),
            'height': 768 + math.floor(random() * 100)
        }
    )
```

**Comment by QIN2DIM** [comment]
Which version of browser are you using? @denismur I tried using the request header from that file, and as I expected, it didn't fix the problem. 

I think what we need to address is the "fundamental problem". Since the same code produced different results in different environments, I wanted to know what exactly made these things change.🀄

**Comment by QIN2DIM** [comment]
> try to use another User Agent ... but doesn't work on server

From my experience, you may need a switch to control the browser launch parameters in different situations. For example, when running code directly without user-agent.

**Comment by denismur** [comment]
@QIN2DIM I use latest Playwright 1.21 , so the webrdrivers are:
- chromium v1000
- ffmpeg v1007 (also works in docker)
Did you set the viewport as well?

**Comment by QIN2DIM** [comment]
I have set @denismur

**Comment by sebdelsol** [comment]
@QIN2DIM have you tried with different Python docker image ?

**Comment by QIN2DIM** [comment]
@sebdelsol Always use `python:3.10-slim`.Will this be an attack surface 0.0?

**Comment by QIN2DIM** [comment]
## Solution
Just change this. Everything is back.🛵 Thank you all!

`FROM python:3.10-slim as builder` **-->** `FROM python:3.10 as builder`

## Result

I GOT IT. @sebdelsol Thanks for the reminder, I had an epiphany.😂 

I never thought it could cause anomalies!

**Comment by Winand** [comment]
@denismur interestingly, in my case `locale='en-US'` was required to avoid hCaptcha. Thanks for your example.
