### ISSUE TITLE
Using with scrapy: the best way

### ISSUE THREAD

**Issue by ohld** [ultrafunkamsterdam/undetected-chromedriver#63]
Hey! 👋

### intro
First of all, thank you for your work. It is purely amazing and helped me to train my scraping skills for educational purposes.

I have a question, it might be not relevant at all. If so, please just close the issue - I will understand.

I'm learning Scrapy right now and I really like that it already has a lot of modules and integrations. But I can't find the easiest and good looking way to integrate your undetected chromedriver with scrapy. 

I've searched in issues and couldn't find the solution. Maybe you can guide me with links or snippets. That would be awesome ✨

### question

What is the best way to use your patched driver with scrapy? I use [this package](https://github.com/clemfromspace/scrapy-selenium#configuration) for regular Selenium driver integration. Using it, I can specify a path to executable or a URL to a remote Selenium driver. 

But your library provides a Python driver class object and I can't just simply put it into the existing scrapy-selenium integration. 

What can you suggest? How do you integrate this driver with scrapy? 👀

**Comment by ohld** [comment]
Ok, what I already did:

1. I run `uc.install()`, downloaded & patched chromedriver. 
2. Then I specify the path to this executable as SELENIUM_DRIVER_EXECUTABLE_PATH in [scrapy-selenium](https://github.com/clemfromspace/scrapy-selenium#configuration)
3. Then I opened the webpage https://bot.sannysoft.com/ and took a screenshot:

![angellist-](https://user-images.githubusercontent.com/5613295/100731731-d556f680-33dc-11eb-9c41-2e68d37fd698.png)


Seems like I failed.

**Comment by undernewmanagement** [comment]
I just stumbled over this stuff as well with scrapy. There is a fork of the scrapy-selenium repo where someone has used this browser. Look here: [https://github.com/cyclehacker/scrapy-selenium-undetectable](https://github.com/cyclehacker/scrapy-selenium-undetectable)

That might give you some help.

**Comment by ohld** [comment]
yep, thanks.

As I see, I need just to patched the existing chromedriver once and the whole undetectable magic will happen

**Comment by ultrafunkamsterdam** [comment]
Could you eleborate what difference the scrapy + using this driver makes, undetectable-wise...  Since patching is just one of the measures, which is not enough being undetected usually. So Scapy must heave some stuff in place that also migitates detection attempts, which i'm curious about and might be worth implementing in coming v2. Thanks in advance.

**Comment by undernewmanagement** [comment]
As far as I know you have control over the following via settings or in code:

- Set/delete/modify Cookies
- Set/delete/modify Headers
- Set and Rotating user-agent strings
- Rotating proxies
- Setting crawl-delay (or take it from robots.txt)
- Setting min/max number of crawlers per domain and/or IP
- Obey/ignore robots.txt

**Comment by ultrafunkamsterdam** [comment]
Allright, thanks. 

However this is possible with chromedriver as well, with some extra code of course. Nice one to add as i'm building a more modular version to release for version 2.0
