### ISSUE TITLE
Runtime Error w/ Suggested Usage

### ISSUE THREAD

**Issue by makeukus** [ultrafunkamsterdam/undetected-chromedriver#645]
Environment：

python=3.8/3.9/3.10
chrome=101.0.4951.64
chrome_driver=101.0.4951.41
undetected-chromedriver=3.1.5.post2

![1](https://user-images.githubusercontent.com/57167180/169948686-559d0935-2eb6-47db-b83d-5346d80a6f26.png)
![2](https://user-images.githubusercontent.com/57167180/169948695-c130226b-bf93-47c7-96a6-66f29c211ef9.png)
![3](https://user-images.githubusercontent.com/57167180/169948704-dc442cb2-7c34-474e-ac5d-3c567c6e4ef5.png)
![4](https://user-images.githubusercontent.com/57167180/169948727-9ff509dc-d5d3-4d9d-aa43-b1f149602d7f.png)
![5](https://user-images.githubusercontent.com/57167180/169948745-d7bab370-346e-407d-b23b-d9689e8ca413.png)
![err](https://user-images.githubusercontent.com/57167180/170007818-6e922488-6991-4a31-8740-9361e5e8e0cf.png)

**Comment by sebdelsol** [comment]
duplicate of #644

**Comment by sebdelsol** [comment]
having the same main version should be enough to have both connecting.
Since you're on Windows you can easily check your Chrome version and force to download the correct driver:
```python3
from win32api import HIWORD, LOWORD, GetFileVersionInfo

import undetected_chromedriver as uc


def get_chrome_main_version():
    filename = uc.find_chrome_executable()
    info = GetFileVersionInfo(filename, "\\")
    version = (
        HIWORD(info["FileVersionMS"]),
        LOWORD(info["FileVersionMS"]),
        HIWORD(info["FileVersionLS"]),
        LOWORD(info["FileVersionLS"]),
    )
    print(f"Chrome version={'.'.join(map(str, version))}")
    return version[0]


if __name__ == "__main__":
    version_main = get_chrome_main_version()
    driver = uc.Chrome(version_main=version_main)
    print(f"driver version={driver.patcher.version_full}")
```

**Comment by makeukus** [comment]
> 拥有相同的主版本应该足以同时连接。 由于您使用的是 Windows，因此您可以轻松检查 Chrome 版本并强制下载正确的驱动程序：
> 
> ```python
> from win32api import HIWORD, LOWORD, GetFileVersionInfo
> 
> import undetected_chromedriver as uc
> 
> 
> def get_chrome_main_version():
>     filename = uc.find_chrome_executable()
>     info = GetFileVersionInfo(filename, "\\")
>     version = (
>         HIWORD(info["FileVersionMS"]),
>         LOWORD(info["FileVersionMS"]),
>         HIWORD(info["FileVersionLS"]),
>         LOWORD(info["FileVersionLS"]),
>     )
>     print(f"Chrome version={'.'.join(map(str, version))}")
>     return version[0]
> 
> 
> if __name__ == "__main__":
>     version_main = get_chrome_main_version()
>     driver = uc.Chrome(version_main=version_main)
>     print(f"driver version={driver.patcher.version_full}")
> ```
Thank you very much for your reply, but Chrome still cannot be connected.so bad ,I'll test it again on New-VMware

<img width="962" alt="Err-1" src="https://user-images.githubusercontent.com/57167180/170096490-d2c394cf-72c0-40fc-89ab-f94e5d41bb17.png">

**Comment by makeukus** [comment]
> 拥有相同的主版本应该足以同时连接。 由于您使用的是 Windows，因此您可以轻松检查 Chrome 版本并强制下载正确的驱动程序：
> 
> ```python
> from win32api import HIWORD, LOWORD, GetFileVersionInfo
> 
> import undetected_chromedriver as uc
> 
> 
> def get_chrome_main_version():
>     filename = uc.find_chrome_executable()
>     info = GetFileVersionInfo(filename, "\\")
>     version = (
>         HIWORD(info["FileVersionMS"]),
>         LOWORD(info["FileVersionMS"]),
>         HIWORD(info["FileVersionLS"]),
>         LOWORD(info["FileVersionLS"]),
>     )
>     print(f"Chrome version={'.'.join(map(str, version))}")
>     return version[0]
> 
> 
> if __name__ == "__main__":
>     version_main = get_chrome_main_version()
>     driver = uc.Chrome(version_main=version_main)
>     print(f"driver version={driver.patcher.version_full}")
> ```

I don't know why Chrome crashed, but the script worked fine on a brand new Windows system. That's enough for me. Thank you again for your help.

**Comment by sebdelsol** [comment]
不客气
