### ISSUE TITLE
TLS detection by akamai

### ISSUE THREAD

**Issue by adinator97** [ultrafunkamsterdam/undetected-chromedriver#646]
I'm trying to fetch some requests on https://www.zalando.de inside the browser, but getting 403s.
latest undected-chromedriver (3.15) with python 3.10

Similar issue described here:
https://httptoolkit.tech/blog/tls-fingerprinting-node-js/

My response is looking the same:
statuscode 403, response: "edge_error": "halt"

**Comment by sebdelsol** [comment]
I've tried 'https://en.zalando.de/api/navigation' and both undetected-chromedriver and my regular chrome land on the same page  and don't get any _403 forbidden response_... So you probably do something wrong and/or had your IP flagged.

**Comment by ad1c1337** [comment]
> I've tried 'https://en.zalando.de/api/navigation' and both undetected-chromedriver and my regular chrome land on the exact same page and I don't get any _403 forbidden response_... So you probably do something wrong and/or had your IP flagged.
> 
> You've to be aware that :
> 
> * headless mode is detectable even if there are some known evasions but it's a cat & mouse game.
> * undetected-chromedriver won't prevent rate limitation and bot behavior detection.

I just tested it again, you were right. Seems like my local IP and my proxies were flagged. 
It worked now.

**Comment by sebdelsol** [comment]
Please Close this bug
