### ISSUE TITLE
Monkey patch not working

### ISSUE THREAD

**Issue by huynhit-biztex-92** [ultrafunkamsterdam/undetected-chromedriver#647]
I can not monkey patch with version 3.1.0, is there any way to do this now?

https://github.com/ultrafunkamsterdam/undetected-chromedriver#monkeypatch-mode--v1-old-stuff
```
import undetected_chromedriver as uc
uc.install()

from selenium.webdriver import Chrome
driver = Chrome()
driver.get('https://distilnetworks.com')
```

**Comment by sebdelsol** [comment]
Please read the documentation : **"v1" moved to _compat for now**.
```python3
 import undetected_chromedriver._compat as uc
```

**Comment by huynhit-biztex-92** [comment]
V1 are no longer working but i found the way to monkey patch!!!
