### ISSUE TITLE
AttributeError: module 'undetected_chromedriver' has no attribute 'Chrome'

### ISSUE THREAD

**Issue by Goldorak4321** [ultrafunkamsterdam/undetected-chromedriver#65]
I'm certain that I'm doing something wrong.

As a test, I have a simple Python script of 3 lines:
import undetected_chromedriver as uc
driver = uc.Chrome()
driver.get('some_web_site')

I get an error:
Traceback (most recent call last):
  File "C:\Python\undetected_chromedriver.py", line 1, in <module>
    import undetected_chromedriver as uc
  File "C:\Python\undetected_chromedriver.py", line 2, in <module>
    driver = uc.Chrome()
AttributeError: module 'undetected_chromedriver' has no attribute 'Chrome'

What am I missing?

I'm using Python 3.7.

**Comment by Goldorak4321** [comment]
Fixed. Issues was with path setting in Windows. Unfortunately, this release of undetected_chromedriver is not successful at bypassing Cloudflare roadblocks. :-(

**Comment by ultrafunkamsterdam** [comment]
Example url ?

**Comment by ultrafunkamsterdam** [comment]
Also you can't  name your script undetected_chromedriver.py, of all names .

**Comment by Goldorak4321** [comment]
https://exposecheatersonline.com/

**Comment by Goldorak4321** [comment]
> Also you can't name your script undetected_chromedriver.py, of all names .

I'll rename it, but I doubt that Cloudflare is able to detect the name of my test python script.

**Comment by ultrafunkamsterdam** [comment]
if you get this message ```AttributeError: module 'undetected_chromedriver' has no attribute 'Chrome'```  then it's caused by your script name having the same name as the undetected_chromedriver package.
when using imports python tries the current working dir first, and in your case finds undetected_chromedriver.py  without a Chrome class, which you are trying to use.
