### ISSUE TITLE
How to get  self.browser_pid of browser launched by undetected chromedriver

### ISSUE THREAD

**Issue by sunny9495-dev** [ultrafunkamsterdam/undetected-chromedriver#651]
Hi,

How to get  self.browser_pid of browser launched by undetected chromedriver

@sebdelsol i think you know better how to get the browser ID of undetected chromedriver launched browser, i see the self.browser_pid in undected chromedriver library __init__ function

```
        if not use_subprocess:
            self.browser_pid = start_detached(
                options.binary_location, *options.arguments
            )
        else:
            browser = subprocess.Popen(
                [options.binary_location, *options.arguments],
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                close_fds=IS_POSIX,
            )
            self.browser_pid = browser.pid
```
but is there any chance we get that id and add to a list
Waiting for your update

**Comment by sebdelsol** [comment]
yes that's actually `browser_pid`.

**Comment by sunny9495-dev** [comment]
I want to get that ID and want to add it to a list mate, can you help me to get that ID @sebdelsol plzzz....

**Comment by sunny9495-dev** [comment]
Thanks alot @sebdelsol Jesus bless you
