### ISSUE TITLE
Launch chrome browser with specific version

### ISSUE THREAD

**Issue by PePinodemrs** [ultrafunkamsterdam/undetected-chromedriver#652]
Hey, how can i start my browser with a choosen version ? 

If i put version_main = 72 for exemple it say me an error. He wants start with my version of my chrome

**Comment by sebdelsol** [comment]
`version_main` force the driver version, but your browser might be another one... and it won't work.
A reliable way to have both synced on Windows would be:
```python3
from win32api import HIWORD, GetFileVersionInfo

import undetected_chromedriver as uc


def get_chrome_main_version():
    filename = uc.find_chrome_executable()
    info = GetFileVersionInfo(filename, "\\")
    return HIWORD(info["FileVersionMS"])


if __name__ == "__main__":
    version_main = get_chrome_main_version()
    driver = uc.Chrome(version_main=version_main)
```

**Comment by PePinodemrs** [comment]
Yes, but if i want chrome version 98 i have to install it on my pc ? it's the only solution ? I have chrome 102 on my pc

**Comment by sebdelsol** [comment]
yes you have to install this Chrome browser version too in another folder.
Then use the `browser_executable_path` argument to point to this specific chrome browser executable.

```python3
# Windows only... pywin32 needed : pip install pywin32
from win32api import HIWORD, GetFileVersionInfo

import undetected_chromedriver as uc

# path to your specific chrome browser you want to use
CHROME_PATH = "some path/chrome.exe" 

def get_chrome_main_version():
    filename = CHROME_PATH
    info = GetFileVersionInfo(filename, "\\")
    return HIWORD(info["FileVersionMS"])


if __name__ == "__main__":
    # damn Google auto update, we'll get the Chrome current version anyway :
    version_main = get_chrome_main_version()

    # force the driver to download this same version :
    driver = uc.Chrome(version_main=version_main, browser_executable_path=CHROME_PATH )
```

**Comment by PePinodemrs** [comment]
Thanks man, and in my other post i asked about requests an api without selenium but just a simple module undetectable

**Comment by sebdelsol** [comment]
As far as I know it doesn't exist. You need a browser running to mimic a normal client behavior.

**Comment by PePinodemrs** [comment]
ty

**Comment by PePinodemrs** [comment]
> yes you have to install this Chrome browser version too in another folder. Then use the `browser_executable_path` argument to point to this specific chrome browser executable.
> 
> ```python
> # Windows only... pywin32 needed : pip install pywin32
> from win32api import HIWORD, GetFileVersionInfo
> 
> import undetected_chromedriver as uc
> 
> # path to your specific chrome browser you want to use
> CHROME_PATH = "some path/chrome.exe" 
> 
> def get_chrome_main_version():
>     filename = CHROME_PATH
>     info = GetFileVersionInfo(filename, "\\")
>     return HIWORD(info["FileVersionMS"])
> 
> 
> if __name__ == "__main__":
>     # damn Google auto update, we'll get the Chrome current version anyway :
>     version_main = get_chrome_main_version()
> 
>     # force the driver to download this same version :
>     driver = uc.Chrome(version_main=version_main, browser_executable_path=CHROME_PATH )
> ```

do you know where i can install all version of chrome ?
