### ISSUE TITLE
How to turn off the message like "DevTools listening on"?

### ISSUE THREAD

**Issue by rjuven2401** [ultrafunkamsterdam/undetected-chromedriver#654]
Hello, first, I am really thankful to you for the undetected-chromedriver. It is really great.

My python script is like as follows.

```
def make_chrome_options(chrome_options):
    chrome_options.add_argument('--headless')
    chrome_options.add_argument('--lang=ko_KR')
    chrome_options.add_argument('--disable-gpu')
    chrome_options.add_argument('--window-size=1920x1080')
    return chrome_options

def undetected_chromedriver_init():
    chrome_options = uc.ChromeOptions()
    chrome_options = make_chrome_options(chrome_options)
    driver = uc.Chrome(options=chrome_options)
    return driver

if __name__ == '__main__':
    for url in [there are about 100 urls in this list]:
        driver = undetected_chromedriver_init()
        driver.get(url)
        (scrapping html and do something)
```

When the following line executes,
```
    driver = uc.Chrome(options=chrome_options)
```
in my terminal, the following message appears. The hex values at the end are different every time.
```
DevTools listening on ws://127.0.0.1:50494/devtools/browser/23e558c4-454a-4d6b-ad94-629a56b0381b
```
I am visiting about 100 pages (1 page per 2 seconds), so too many such messages appear.
I want to ignore the message. Is there any way to mute the messages?

Thank you for your answer.

**Comment by sebdelsol** [comment]
I don't see this message when I use undetected-chromedriver.
It seems that you use the regular `selenium.webdriver.Chrome()` instead.

**Comment by rjuven2401** [comment]
Oh yeah, thank you. I don't know why but I was using 2.x.x version. I upgraded now and no such messages appear anymore. I hope I haven’t been a bother.

**Comment by sebdelsol** [comment]
You're welcome, please close this bug if it's fine with you.

**Comment by dmquang** [comment]
;') someone who use seleniumwire help me
