### ISSUE TITLE
Instagram aware.

### ISSUE THREAD

**Issue by Andromeda606** [ultrafunkamsterdam/undetected-chromedriver#659]
When you open a live broadcast, you cannot watch it with the undetected chromedriver. This is because bots cannot watch the broadcast.

```python
import undetected_chromedriver.v2 as uc
options = uc.ChromeOptions()
options.user_data_dir = "c:\\temp\\profile"
options.add_argument('--user-data-dir=c:\\temp\\profile2')
options.add_argument('--no-first-run --no-service-autorun --password-store=basic')
driver = uc.Chrome(options=options, version_main=94)

driver.get('https://instagram.com/blabla/live')
```

**Comment by sebdelsol** [comment]
Extraordinary claims require extraordinary evidence...

**Comment by Andromeda606** [comment]
> Extraordinary claims require extraordinary evidence...

It's pretty easy to test. Open a live stream and try to watch using the module.

**Comment by sebdelsol** [comment]
If you want some answers you should provide the minimum code to show how to reproduce your issue.

**Comment by Andromeda606** [comment]
> If you want some answers you should provide the minimum code to show how to reproduce your issue.

updated

**Comment by ultrafunkamsterdam** [comment]
options.user_data_dir = "c:\\temp\\profile"
options.add_argument('--user-data-dir=c:\\temp\\profile2')

why setting this twice... and then not even the same folder.   i should be locking up the config possibilities as 9/10 raised issues are terrible custom configs
