### ISSUE TITLE
Error result on linux64

### ISSUE THREAD

**Issue by powliger** [ultrafunkamsterdam/undetected-chromedriver#66]
Hello

This code is wonderful, but I have some promblem.

When I run this code to window, it's ok, but when I run in Linux64(Ubuntu 20) result is error.

please tell me what am I missing.

I use this code 

import undetected_chromedriver as uc
driver = uc.Chrome()
driver.get('https://distilnetworks.com')

error occurs like this 
OSError                                   Traceback (most recent call last)
<ipython-input-2-238625bd1e7f> in <module>
      1 import undetected_chromedriver as uc
----> 2 driver = uc.Chrome()
      3 driver.get('https://distilnetworks.com')

~/.local/lib/python3.8/site-packages/undetected_chromedriver/__init__.py in __new__(cls, enable_console_log, *args, **kwargs)
     49             kwargs["options"] = ChromeOptions()
     50         instance = object.__new__(_Chrome)
---> 51         instance.__init__(*args, **kwargs)
     52 
     53         instance._orig_get = instance.get

~/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py in __init__(self, executable_path, port, options, service_args, desired_capabilities, service_log_path, chrome_options, keep_alive)
     71             service_args=service_args,
     72             log_path=service_log_path)
---> 73         self.service.start()
     74 
     75         try:

~/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py in start(self)
     70             cmd = [self.path]
     71             cmd.extend(self.command_line_args())
---> 72             self.process = subprocess.Popen(cmd, env=self.env,
     73                                             close_fds=platform.system() != 'Windows',
     74                                             stdout=self.log_file,

/usr/lib/python3.8/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    852                             encoding=encoding, errors=errors)
    853 
--> 854             self._execute_child(args, executable, preexec_fn, close_fds,
    855                                 pass_fds, cwd, env,
    856                                 startupinfo, creationflags, shell,

/usr/lib/python3.8/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1700                     if errno_num != 0:
   1701                         err_msg = os.strerror(errno_num)
-> 1702                     raise child_exception_type(errno_num, err_msg, err_filename)
   1703                 raise child_exception_type(err_msg)
   1704 

OSError: [Errno 8] Exec format error: './chromedriver'

Thank you.

**Comment by ultrafunkamsterdam** [comment]
my best guess is you need to install Chrome itself.
