### ISSUE TITLE
undetected-chromedriver downloads wrong version of ChromeDriver 

### ISSUE THREAD

**Issue by azazar** [ultrafunkamsterdam/undetected-chromedriver#664]
unknown error: cannot connect to chrome at 127.0.0.1:60961
    from session not created: This version of ChromeDriver only supports Chrome version 102
    Current browser version is 101.0.4951.64

Is there any option to specify proper version?

**Comment by azazar** [comment]
Read the readme. Found it

**Comment by RestOp** [comment]
> Read the readme. Found it

Hi what readme do you mean?How have you solved it?
