### ISSUE TITLE
avoid bot detection

### ISSUE THREAD

**Issue by Arnold1** [ultrafunkamsterdam/undetected-chromedriver#67]
Hi,

how to avoid being detected as bot on a different website you mentioned in the readme? I already use tor proxy...

Im seeing this message + redCAPTCHA
```
We’re trying to get you in
We’re experiencing very high traffic. You will be let into our store shortly.
```

Thanks,
Arnold

**Comment by ultrafunkamsterdam** [comment]
Exactly that. Tor proxy is 99% instant detected because the ip's are flagged since another thousand scrapers are on each ip.
