### ISSUE TITLE
delay

### ISSUE THREAD

**Issue by Stainpy** [ultrafunkamsterdam/undetected-chromedriver#673]
i think this issue might be similar to this one #632, let me first show you a small video of what's happening [here](https://www.veed.io/view/79e37fd0-793c-4022-b8be-af16ceda9a91?sharingWidget=true),
as you saw that what's happening is when it finish 4 tasks it delays like 1:30/2mins but i didn't recorded that because of the video time, also i noticed something which is when i set `subprocess` to `True` it delays after 6 tasks instead of 4, anyway and im 100% sure that it's not my code issue because i don't have any timeouts and the max time sleep in the code is 3secs.
i use undetected-chromedriver v2 and python 3.9.7.

btw sorry for not showing the whole code because it's private but i can share it with the owner of repo if needed

**Comment by sebdelsol** [comment]
#623 is due to weird recursive drivers creation... so the probability your're doing something wrong is very high. I use extensively undetected-chrome-driver in multi-thread env and never had those kind of delays. Anyway without a minimum reproductible example your issue is moot.

**Comment by Stainpy** [comment]
> #623 is due to weird recursive drivers creation... so the probability your're doing something wrong is very high. I use extensively undetected-chrome-driver in multi-thread env and never had those kind of delays, it looks like race conditions to me. Anyway without some minimum code to reproduce your issue, this is moot.

i don't really know what's going on with my code, but i need to fix this soon because i looked up everywhere and i couldn't  find why and how this issue is happening, can i show you the code in somewhere privet so you can take a look?
thanks.

**Comment by Stainpy** [comment]
fixed by replacing `quit()` with `close()` lol
thanks anyway
