### ISSUE TITLE
Being detected if change useragent

### ISSUE THREAD

**Issue by ninacoder-info** [ultrafunkamsterdam/undetected-chromedriver#677]
So basically work great if I use a random UserAgent which marked with Opera System. For example I'm using mac os and use useragent like this

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36

Everything work fine, but if I change to Windows platform for example: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.7113.93 Safari/537.36

Then I will be detected by the site even enable '--disable-features=UserAgentClientHint', when starting browser.

Anyone have idea how to make it look like Windows browser?

Also tried to use UserAgent

    chrome_options = uc.ChromeOptions()
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33")
    chrome_options.add_argument("--disable-features=UserAgentClientHint")
    chrome_options.add_argument("--profile-directory=Profile 3")
    driver = uc.Chrome(options=chrome_options)

Thanks

**Comment by sebdelsol** [comment]
Spoofing your user agent is quite a bad ideas because sites use several ways to detect discrepancies between the user agent and other hints given by the browser.

There are 2 other known ways to detect the user's OS :  `navigator.platform`  and `navigator.appVersion`. 
So you might try to spoof those too:
```python3
        driver.execute_cdp_cmd(
            "Page.addScriptToEvaluateOnNewDocument",
            {
                "source": """
                    Object.defineProperty(navigator, 'platform', {get: () => "Win32"});
                    Object.defineProperty(navigator, 'appVersion', {get: () => navigator.userAgent.split('/').slice(1,-1).join('')});
                    """
            },
        )
```

I'm not sure it 'd be enough though.

**Comment by ninacoder-info** [comment]
Thank you @sebdelsol and @ultrafunkamsterdam, basically I'm running undetected-chromedriver in a LINUX container and want to make it look like Windows as possible, I have tried many but always get detected, can you guys give me some tips around that?

**Comment by sebdelsol** [comment]
Have you tried the code above ?

**Comment by ninacoder-info** [comment]
> Have you tried the code [**above** ](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/677#issuecomment-1154252884)?

Yes, sadly not working, still get detected.

**Comment by ninacoder-info** [comment]
> **Spoofing your user agent is quite a bad idea** because sites usually detect discrepancies between the user agent and other hints given by the browser.
> 
> There are 2 other well known ways to detect the user's OS : `navigator.platform` and `navigator.appVersion`. So you'd want to spoof those too :
> 
> ```python
> driver.execute_cdp_cmd(
>     "Page.addScriptToEvaluateOnNewDocument",
>     {
>         "source": """
>             Object.defineProperty(navigator, 'platform', {get: () => "Win32"});
>             Object.defineProperty(navigator, 'appVersion', {get: () => navigator.userAgent.split('/').slice(1).join('/')});
>             """
>     },
> )
> ```
> 
> I'm really not sure it 'd be enough though.

after use those code, I type window.navigator.platform in console, it still show "MacIntel" which is my real OS
