### ISSUE TITLE
How can I change information browser like canvas, webgl,...

### ISSUE THREAD

**Issue by guidetuanhp** [ultrafunkamsterdam/undetected-chromedriver#685]
I want to change the value WebGL, Canvas, Audio, Client Rects, WebRTC or something to antidetect. Does anyone know the method?

**Comment by sebdelsol** [comment]
Why would you don't need those ?

**Comment by ultrafunkamsterdam** [comment]
prolly he wants to spoof  live input camera. i alrready wrote a plugin for that :)

**Comment by ahmedabdelhamedz** [comment]
@ultrafunkamsterdam please where the plugin that change canva and webgl ?

**Comment by StanislavGluharev** [comment]
@ultrafunkamsterdam I think this is a very cool plugin =) How would I use it?
