### ISSUE TITLE
Sites keep detecting bot, and complaining that Javascript and cookies are not enabled.

### ISSUE THREAD

**Issue by henrybm** [ultrafunkamsterdam/undetected-chromedriver#69]
They all seem to complain about javascript and cookies.

**CRUNCHBASE ERROR:**
Access to this page has been denied because we believe you are using automation tools to browse the website.
Please make sure that Javascript and cookies are enabled on your browser and that you are not blocking them from loading.
https://www.crunchbase.com/organization/secret-escapes

**BLOOMBERG ERROR**
To continue, please click the box below to let us know you're not a robot. Please make sure your browser supports JavaScript and cookies and that you are not blocking them from loading.
https://www.bloomberg.com/profile/company/FB:US

**TRACXN ERROR**
JavaScript is disabled in your browser. enable it to enjoy the full features of Tracxn. Your browser was unable to load all of Tracxn resources. They may have been blocked by your firewall, proxy or browser configuration.
https://tracxn.com/d/companies/designwithfriends.com

Thanks!

**Comment by ultrafunkamsterdam** [comment]
They say so. But that's false. In fact they're in one way or another using CloudFlare (just like other thousands of sites do).
One detection (and not solving captcha), flags your ip for all their other customers as well.  So either solve some captcha's to get off the flaglist or use a clean ip.

To show you that it works:

```python 
In [1]: import undetected_chromedriver as uc

In [2]: driver = uc.Chrome()

DevTools listening on ws://127.0.0.1:59070/devtools/browser/6a5e6dc1-7604-4f88-ab06-63340cfbc765

In [3]:

In [4]: driver.get('https://www.crunchbase.com/organization/secret-escapes')

In [5]: driver.get_screenshot_as_png('crunchbase.png')   # OUCH 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
      ...     
In [6]: driver.save_screenshot('crunchbase.png')
Out[25]: True 
```
![crunchbase](https://user-images.githubusercontent.com/21027969/102499206-30464a00-407b-11eb-8b5c-2060a98fac68.png)
