### ISSUE TITLE
Detected by imperva on https://driverpracticaltest.dvsa.gov.uk/login

### ISSUE THREAD

**Issue by Jabbers99** [ultrafunkamsterdam/undetected-chromedriver#690]
Using the basic example on the main page, https://driverpracticaltest.dvsa.gov.uk/login is detected.
I get the following error: 

![image](https://user-images.githubusercontent.com/39739543/174798101-13c69325-88c3-4443-b09f-eb49a9ad85f8.png)

**Comment by Jabbers99** [comment]
Can confirm it works on incognito

**Comment by sebdelsol** [comment]
Sure but you can save those after solving the ReCaptcha and reuse them ina later session... 
They have an expiry date though.

```python3
import pickle
from contextlib import contextmanager

import undetected_chromedriver as uc


@contextmanager
def get_driver():
    options = uc.ChromeOptions()
    options.add_argument("--incognito")
    _driver = uc.Chrome(options=options)
    try:
        yield _driver
    finally:
        _driver.quit()


if __name__ == "__main__":
    url = "https://driverpracticaltest.dvsa.gov.uk/login"

    # resolve the captcha by hand and save the cookies
    with get_driver() as driver:
        driver.get(url)
        input("resolve the captcha then hit enter")
        cookies = driver.get_cookies()

    with open("cookies", mode="wb") as f:
        pickle.dump(cookies, f)

    # now you can reuse the cookies
    with get_driver() as driver:
        driver.get(url)
        with open("cookies", mode="rb") as f:
            for cookie in pickle.load(f):
                driver.add_cookie(cookie)
        driver.refresh()
        input("it works, hit enter to quit")
```

**Comment by Jabbers99** [comment]
Just got the same error message after pressing a button right after logging in.
This didn't happen in incognito - do I need to manually persist the cookies after every navigation redirect?

**Comment by Jabbers99** [comment]
Changed absolutely nothing and now getting this on incognito but can access the site fine on my browser.

**Comment by sebdelsol** [comment]
Yeah there's a cooldown, that's why you should save a working profile instead of cookies that have to be apply after a deny, hence reducing your "I'm not a bot" score...

**Comment by sebdelsol** [comment]
They fingerprint your environment + IP. I've tried to change resolution but that's deeper than that. Still looking where they store those information....

**Comment by sebdelsol** [comment]
No it means you need a clear profile where you show all the right credential. So you should save a _Chrome profile_ when you've passed the ReCaptcha (it's easy since your can login in non-incognito mode) and reuse it till it's expired.

**Comment by Jabbers99** [comment]
> No it means you need a clear profile where you show all the right credential. So you should save a _Chrome profile_ when you've passed the ReCaptcha (it's easy since your can login in non-incognito mode) and reuse it till it's expired.

I mean to stop the ban on the original chrome profile without the cookie

**Comment by sebdelsol** [comment]
I've tried with a chrome browser _without any options_ except a blank temp profile and that's enough to trigger the detection. _So there's something discriminant in a blank profile that triggers it_...

**Comment by Jabbers99** [comment]
> I've tried with a chrome browser _without any options_ except a blank temp profile and that's enough to trigger the detection. _So there's something discriminant in a blank profile that triggers it_... And now my IP has been flagged...

Your entire IP? So you get blocked when accessing from a regular chrome browser?

**Comment by sebdelsol** [comment]
yes

**Comment by Jabbers99** [comment]
> yes

Strange, that hasn't happened to me yet

**Comment by sebdelsol** [comment]
My IP is not flagged anymore... Here's a better version :
* Check we have _valid cookies_, if not ask a human to solve the ReCaptcha in incognito and save the session's cookie.
* **_preload_** the valid cookies so that we can freely enter the site without triggering a denial.
That was the issue with `driver.add_cookie` that needs the page to be loaded before...
* It seems some of those cookies have a quite short expiry like ~10 minutes.

```python3
import os
import pickle
import time
from contextlib import contextmanager

import undetected_chromedriver as uc

URL = "https://driverpracticaltest.dvsa.gov.uk/login"
COOKIE_FILE = "cookies.pickle"


@contextmanager
def get_driver(incognito=True):
    options = uc.ChromeOptions()
    options.add_argument("--start-maximized")
    if incognito:
        options.add_argument("--incognito")
    driver_ = uc.Chrome(options=options)
    try:
        yield driver_
    finally:
        driver_.quit()


def are_cookies_valid(cookie_file):
    if os.path.exists(cookie_file):
        now = time.time() + 30 # 30s in the future
        with open(cookie_file, mode="rb") as f:
            # check all are still valid
            return all(
                expiry >= now
                for cookie in pickle.load(f)
                if (expiry := cookie.get("expiry"))
            )
    return False


if __name__ == "__main__":
    if not are_cookies_valid(COOKIE_FILE):
        # resolve the captcha by hand and save the cookies
        with get_driver(incognito=True) as driver:
            driver.get(URL)
            input("resolve the captcha then hit enter")
            with open(COOKIE_FILE, mode="wb") as f:
                pickle.dump(driver.get_cookies(), f)

    with get_driver(incognito=False) as driver:
        driver.execute_cdp_cmd("Network.enable", {})
        with open(COOKIE_FILE, mode="rb") as f:
            for cookie in pickle.load(f):
                driver.execute_cdp_cmd("Network.setCookie", cookie)
        driver.execute_cdp_cmd("Network.disable", {})
        driver.get(URL)
        input("it works, hit enter")
````

**Comment by Jabbers99** [comment]
> My IP is no longer flagged... here's a better version :
> 
> * Check we have _valid cookies_, if not ask a human to solve the ReCaptcha in incognito and save the session's cookie.
> * **_preload_** the valid cookies so that we can freely enter the site without triggering a denial.
>   So don't use `driver.add_cookie` that needs the page to be already loaded and denied once and that's suspicious.
> * It seems some of those cookies have a quite short-lived ~10 minutes.
> 
> ```python
> import os
> import pickle
> import time
> from contextlib import contextmanager
> 
> import undetected_chromedriver as uc
> 
> URL = "https://driverpracticaltest.dvsa.gov.uk/login"
> COOKIE_FILE = "cookies.pickle"
> 
> 
> @contextmanager
> def get_driver(incognito=True):
>     options = uc.ChromeOptions()
>     options.add_argument("--start-maximized")
>     if incognito:
>         options.add_argument("--incognito")
>     _driver = uc.Chrome(options=options)
>     try:
>         yield _driver
>     finally:
>         _driver.quit()
> 
> 
> def are_cookies_valid(cookie_file):
>     if os.path.exists(cookie_file):
>         now = time.time() + 30 # 30s in the future
>         with open(cookie_file, mode="rb") as f:
>             # check all are still valid
>             return all(
>                 expiry >= now
>                 for cookie in pickle.load(f)
>                 if (expiry := cookie.get("expiry"))
>             )
>     return False
> 
> 
> if __name__ == "__main__":
>     if not are_cookies_valid(COOKIE_FILE):
>         # solve the captcha by hand and save the cookies
>         with get_driver(incognito=True) as driver:
>             driver.get(URL)
>             input("resolve the captcha then hit enter")
>             with open(COOKIE_FILE, mode="wb") as f:
>                 pickle.dump(driver.get_cookies(), f)
>     else:
>         # we have valid cookies, preload those
>         with get_driver(incognito=False) as driver:
>             driver.execute_cdp_cmd("Network.enable", {})
>             with open(COOKIE_FILE, mode="rb") as f:
>                 for cookie in pickle.load(f):
>                     driver.execute_cdp_cmd("Network.setCookie", cookie)
>             driver.execute_cdp_cmd("Network.disable", {})
>             driver.get(URL)
>             input("it works, hit enter")
> ```

Preloading the cookies was a good idea, I was thinking about the fact that they were getting loaded after the main chrome page had already been denied.

I'm still experiencing the same issue, however, where the initial request to solve the captcha in incognito is blocked. It's not my IP thats flagged, as I can access the page fine on my other browser, so not really sure where to go from here.

**Comment by Jabbers99** [comment]
> I guess you've been flagged with an incognito fingerprint, so wait for some hours : they have very aggressive cool-downs.

I have been blocked from that page for 15 hours

**Comment by Jabbers99** [comment]
> I started working on a bot for this yesterday as well. It works for me without any incognito. I can even bypass the reCAPTCHA 50% of the time by using ActionChains.
> 
> I am opening the ChromeDriver using:
> 
> ```
> @contextmanager
> def start_chromedriver():
>     options = ChromeOptions()
>     options.add_argument("--start-maximized")
> 
>     _driver = uc.Chrome(options)
>     _driver.delete_all_cookies()
>     _driver.implicitly_wait(5)
>     try:
>         yield _driver
>     finally:
>         _driver.quit()
> ```
> 
> The profile is mostly empty, except I have an app automatically adding its extension to the newly created profile.
> 
> I am nowhere near finished, but sometimes it does randomly present an reCAPTCHA again while searching. I am considering making making the keyboard and mouse inputs more human like although I am not sure yet if they are actually capturing mouse movement and input delays.

That's interesting, you haven't been temporarily banned yet for not saving the cookies then?

**Comment by lukect** [comment]
> > I started working on a bot for this yesterday as well. It works for me without any incognito. I can even bypass the reCAPTCHA 50% of the time by using ActionChains.
> > I am opening the ChromeDriver using:
> > ```
> > @contextmanager
> > def start_chromedriver():
> >     options = ChromeOptions()
> >     options.add_argument("--start-maximized")
> > 
> >     _driver = uc.Chrome(options)
> >     _driver.delete_all_cookies()
> >     _driver.implicitly_wait(5)
> >     try:
> >         yield _driver
> >     finally:
> >         _driver.quit()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The profile is mostly empty, except I have an app automatically adding its extension to the newly created profile.
> > I am nowhere near finished, but sometimes it does randomly present an reCAPTCHA again while searching. I am considering making making the keyboard and mouse inputs more human like although I am not sure yet if they are actually capturing mouse movement and input delays.
> 
> That's interesting, you haven't been temporarily banned yet for not saving the cookies then?

Nope. There is no dynamic blacklist at all; only a fixed blacklist of non-residential IPs. Otherwise I would have definitely been banned by now.

It is far more likely that they are blocking your browser fingerprint. Try add some extensions or switch which GPU you are using.

**Comment by Jabbers99** [comment]
> Yeah of course they are blocking my browser fingerprint, that's what I meant. I was asking if that had happened to you yet?

**Comment by tstoco** [comment]
I am having the same issues. 

After the change that COVID cancellations will not be free anymore. It seems that the their WAF got tweaked.  

WAF is kicking in incognito or normal mode crazily in my project. 

The options currently in use. 

```
@dataclass
class ChromeOpts:
    """Define custom chrome options."""

    incognito: bool  = True
    maximized: str   = "--start-maximized"
    headless: bool   = False
    #user_agent: str  = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36"
    user_profile:str = '/home/tiago/.config/google-chrome'
```
I will try the cookies trick suggested by @sebdelsol and will update this thread. By the way thanks for the code.

**Comment by tstoco** [comment]
Hey folks, 

I have managed to curate my code and create a public version to omit anything private there. 

Just take my code with a grain of salt. I am not a professional coder and just an enthusiast actually. 

I will appreciate suggestions and I can even open the project for collaboration if you guys are interested.

https://git.infoitech.co.uk/tstoco/dvsa-cancellation-slot-checker-public

**Comment by tstoco** [comment]
@sebdelsol I am facing a new issue that I am struggling to get my head around.
Chrome is launched but nothing happens it takes a few good seconds until it fails with the below.
You can check my project code in the link shared above. Many thanks


**Python package versions**
undetected-chromedriver 3.1.5.post4
selenium                4.3.0
selenium-page-factory   2.5

**Chrome Version**
╰─>$ google-chrome --version
Google Chrome 102.0.5005.61

**logs.log**
`[28/06/2022 09:42:29 AM] DEBUG (patcher@147) getting release number from /LATEST_RELEASE_102
[28/06/2022 09:42:29 AM] DEBUG (patcher@164) downloading from https://chromedriver.storage.googleapis.com/102.0.5005.61/chromedriver_linux64.zip
[28/06/2022 09:42:29 AM] DEBUG (patcher@174) unzipping /tmp/tmphi72drbp
[28/06/2022 09:42:29 AM] INFO (patcher@231) patching driver executable /home/tiago/.local/share/undetected_chromedriver/cb832db3dc283db3_chromedriver
[28/06/2022 09:42:30 AM] DEBUG (remote_connection@358) POST http://localhost:56969/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "binary": "/bin/google-chrome-stable", "args": ["--incognito", "--start-maximized", "--user-data-dir=/home/tiago/.config/google-chrome", "--remote-debugging-host=127.0.0.1", "--remote-debugging-port=58193", "--lang=en-GB", "--no-default-browser-check", "--no-first-run", "--log-level=0"], "debuggerAddress": "127.0.0.1:58193"}}}}
[28/06/2022 09:42:30 AM] DEBUG (connectionpool@228) Starting new HTTP connection (1): localhost:56969
[28/06/2022 09:43:30 AM] DEBUG (connectionpool@456) http://localhost:56969 "POST /session HTTP/1.1" 500 769
[28/06/2022 09:43:30 AM] DEBUG (remote_connection@380) Remote response: status=500 | data={"value":{"error":"unknown error","message":"unknown error: cannot connect to chrome at 127.0.0.1:58193\nfrom chrome not reachable","stacktrace":"#0 0x55db5036ff33 \u003Cunknown>\n#1 0x55db500b9faf \u003Cunknown>\n#2 0x55db500a8209 \u003Cunknown>\n#3 0x55db500e0a79 \u003Cunknown>\n#4 0x55db500d8a06 \u003Cunknown>\n#5 0x55db50113d3a \u003Cunknown>\n#6 0x55db5010de63 \u003Cunknown>\n#7 0x55db500e382a \u003Cunknown>\n#8 0x55db500e4985 \u003Cunknown>\n#9 0x55db503b44cd \u003Cunknown>\n#10 0x55db503b85ec \u003Cunknown>\n#11 0x55db5039e71e \u003Cunknown>\n#12 0x55db503b9238 \u003Cunknown>\n#13 0x55db50393870 \u003Cunknown>\n#14 0x55db503d5608 \u003Cunknown>\n#15 0x55db503d5788 \u003Cunknown>\n#16 0x55db503eff1d \u003Cunknown>\n#17 0x7fc21b6ab947 \u003Cunknown>\n"}} | headers=HTTPHeaderDict({'Content-Length': '769', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
[28/06/2022 09:43:30 AM] DEBUG (remote_connection@409) Finished Request
[28/06/2022 09:43:30 AM] DEBUG (dprocess@69) cleaning up pid 40884 
[28/06/2022 09:43:30 AM] DEBUG (patcher@270) successfully unlinked /home/tiago/.local/share/undetected_chromedriver/cb832db3dc283db3_chromedriver`

**Exception trown**
`selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:58193
from chrome not reachable`

**Comment by sebdelsol** [comment]
I see you force your chromedriver to 102. Maybe your chrome browser has auto-updated to 103 ?

**Comment by tstoco** [comment]
> 

I don't think that's happening.

```
╰─>$ sudo apt list --installed | grep chrome

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

google-chrome-stable/now 102.0.5005.61-1 amd64 [installed,upgradable to: 103.0.5060.53-1]
```

I am using 102 because of this comment from yourself [694](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/694#issuecomment-1165539116)

BTW -> :eye: into #680

**Comment by tstoco** [comment]
@sebdelsol I have implemented your suggestion.

--------------------------------

However, with a slight change :

```
return os.popen(f'{chrome_path} --version').read().strip('Google Chrome').split('.')[0]
```
instead of :point_down: 
```
return os.popen(f"{chrome_path} --version").read().strip("Google Chrome").strip()
```
Your original code was returning the full version (102.0.5005.61) and the `version_main` option was complaining.

`urllib.error.HTTPError: HTTP Error 404: Not Found`

--------------------------------

The change did not fix it. To be honest, it was like passing it manually but your solution automates it and makes sure `uc` has the matching driver (neat).

The thing that bothers me is the version that apt reports `google-chrome-stable/now 102.0.5005.61-1` the `-1` does not appear in the driver. When I open chrome and check the version it reports 102.0.5005.61 though. That `-1` seems to be a sort of flag used by Ubuntu and does not interfere with the chrome version.

Help is appreciated. Many Thanks.

**Comment by ultrafunkamsterdam** [comment]
instead of finding silly constructs using sleeps and stuff: use UC's own silly structure:
```
with driver:
    driver.get(url)
```
this will (after connection has been made, disconnect the chromedriver session for N seconds, and reconnects after that. it should be impossible for any site to detect it since there is simply no chromedriver at that very moment. 
I actually forgot to remove that feature (context manager), but i think i leave it in anyways.

**Comment by jiwaCh** [comment]
@Jabbers99 did you manage to resolve the issue?  I have looked at your code in your github -  it just seem to wait and refresh. It's  a good temporary solution but will lead to ban in the future.

Also, the cookies example is not valid
