### ISSUE TITLE
Update Docker Container to newest Chromedriver

### ISSUE THREAD

**Issue by Wamy-Dev** [ultrafunkamsterdam/undetected-chromedriver#692]
When running the [Docker container](https://hub.docker.com/r/ultrafunk/undetected-chromedriver) I get: 

> WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:41855
from session not created: This version of ChromeDriver only supports Chrome version 103
Current browser version is 102.0.5005.61

Just needs a simple update. I would make a pull request myself, but the docker container itself is not listed anywhere so I have no way to alter the code.

EDIT: @ultrafunkamsterdam, I just looked at the image layers. It literally just requires you to rebuild and push the image to docker again. The best solution would be to open source the image, so the users can update whenever they need, or make some way that the image stays updated automatically.

**Comment by chris-aeviator** [comment]
@Wamy-Dev check https://hub.docker.com/layers/ultrafunk/undetected-chromedriver/latest/images/sha256-1b1a1a292f5b0605926831f3fc8497675d3ff210ba3fd1d7e871270d9e11bc66?context=explore for the dockerfile used to build the image

**Comment by chris-aeviator** [comment]
it seems you can also set `target_version` to match the prev. installed chrome version when initializing.

```
❯ rg target_version
undetected_chromedriver/_compat.py
125:    target_version = None
129:    def __init__(self, executable_path=None, target_version=None, *args, **kwargs):
```

```
undetected_chromedriver/patcher.py
139:        Gets the latest major version available, or the latest major version of self.target_version if set explicitly.
```

**Comment by chris-aeviator** [comment]
I was running into the same issue (though outside docker in my python pipeline) and I'm able to get around this by initiallizing UC with the target version

```
driver = uc.Chrome(version_main=102)
```

**Comment by Wamy-Dev** [comment]
Wow that worked! Thank you @chris-aeviator.
