### ISSUE TITLE
DataDome not bypassed

### ISSUE THREAD

**Issue by JackDev-cc** [ultrafunkamsterdam/undetected-chromedriver#693]
Datadome security varies between site, e.g tidal.com and it is being detected.

![datadome_undetected_webddriver](https://user-images.githubusercontent.com/51898206/175302450-12e5724f-adc4-4dff-936f-28a35f01e5a6.png)
t

**Comment by sebdelsol** [comment]
I'm not sure it's actually detected because I landed on the same ReCaptcha page on my regular Chrome browser the first time I tried this site... So it's more like my IP was already flagged as somewhat suspicious.
Anyway you can use [**this workaround**](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/690#issuecomment-1163501242).

**Comment by qhjink** [comment]
![36343c772977df941818984656292be](https://user-images.githubusercontent.com/53812117/177291053-cb525109-d556-451d-bc56-e8bda120bd9b.png)
url:https://www.cma-cgm.com
I also have the same problem. When I open the website, it shows that it has been detected. If I open it manually, it doesn't

**Comment by sebdelsol** [comment]
> I also have the same problem. When I open the website, it shows that it has been detected. If I open it manually, it doesn't

I'm not : your IP or whatever fingerprint has been flagged.

**Comment by JackDev-cc** [comment]
> > I also have the same problem. When I open the website, it shows that it has been detected. If I open it manually, it doesn't
> 
> I'm not : your IP or whatever fingerprint has been flagged.

I can assure you it's detected.

Brand new residential IP, clean browser Tidal loads fine can browse site, spam requests to a degree nothing.
Same IP, launch undetected for Tidal instant recaptcha, once IP has been detected then my normal browser also gets it, until I change IP+ clean browser than cycle repeats.

**Comment by sebdelsol** [comment]
I'm not talking about tidal (I gave you a workaround btw) but I was replying to @qhjink

**Comment by JackDev-cc** [comment]
> I'm not talking about tidal (I gave you a workaround btw) but I was replying to @qhjink

I know, but your workaround has the same issue it isn't a solution, and I mentioned it as the reason he is having his issue is because this repo is 100% detected by others I can repeatedly prove it it's just a matter of time until more detect it they are noticing something.

**Comment by sebdelsol** [comment]
Here's a working solution.
* On a clean new session UC is detected with js timings of math or strings operations as explained [**here**](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/684#issuecomment-1158717836).
* Fortunately there is a workaround as found [**here**](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/684#issuecomment-1159470013).
* Then you can use the cookies from that first session to re access from a new clean session.
* There's a caveat thought, you might be detected by rate limitation or behavioral detection. 
_In that case you'll always be served a Captcha_ when you try to connect from the same IP,  even on a regular Chrome.

```python3
import os
import pickle
from contextlib import contextmanager
from urllib.parse import urlparse

import undetected_chromedriver as uc


class ChromeForTimingsTest(uc.Chrome):
    def get(self, url):
        self.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {"source": "alert();"})
        super().get(url)
        self.switch_to.alert.accept()
        self.reconnect(5)


# pylint: disable=redefined-outer-name
@contextmanager
def get_driver(timings_test=False):
    options = uc.ChromeOptions()
    options.add_argument("--start-maximized")
    chrome_cls = ChromeForTimingsTest if timings_test else uc.Chrome
    driver = chrome_cls(options=options)
    try:
        yield driver
    finally:
        driver.quit()


class Cookies:
    def __init__(self, url):
        self.filename = f"{urlparse(url).netloc}.cookies.pickle"

    def are_valid(self):
        return os.path.exists(self.filename)

    def load(self, driver):
        driver.execute_cdp_cmd("Network.enable", {})
        with open(self.filename, mode="rb") as f:
            for cookie in pickle.load(f):
                driver.execute_cdp_cmd("Network.setCookie", cookie)
        driver.execute_cdp_cmd("Network.disable", {})

    def save(self, driver):
        with open(self.filename, mode="wb") as f:
            pickle.dump(driver.get_cookies(), f)


if __name__ == "__main__":
    URL = "https://tidal.com/"
    cookies = Cookies(URL)

    if cookies.are_valid():
        # we have valid cookies, preload those
        with get_driver() as driver:
            cookies.load(driver)
            driver.get(URL)
            input("hit enter")
    else:
        # use ChromeForTimingsTest and save the cookies
        with get_driver(timings_test=True) as driver:
            driver.get(URL)
            # you're not supposed to see a captcha, but it might happen
            # if you've been rate limited or detected by behavioral detection.
            input("If you see a captcha, solve it and hit enter")
            cookies.save(driver)
```

**Comment by qhjink** [comment]
> 
I tried to change the IP, but I still couldn't. But I noticed that when I opened the browser with UC, the breakpoint manually visited the website, and the website was normal, using driver.get is abnormal when opening the website.


`import undetected_chromedriver as uc

    options = uc.ChromeOptions()
    options.add_argument("--start-maximized")
    driver = Chrome(options=options,driver_executable_path= "ChromeDriver.exe",browser_executable_path="Chrome/chrome.exe")

    driver.get('https://www.cma-cgm.com')
    print("!11")`

**Comment by sebdelsol** [comment]
Saving and reusing the cookies definitely works for me and the relevant one for datadome have quite long expiry.
I'm not sure about the js timings detection because this site doesn't allow several sessions from the same IP, the subsequent one are always served a captcha, so it's hard to know if reconnecting actually works.

**Comment by qhjink** [comment]
I try to use the no_timings_detection_get method, which works normally at first, but after running for a while, the target website still prompts to block.

**Comment by sebdelsol** [comment]
Yes if you keep coming with a blank profile from the same IP you'll be quickly blocked. That's why you need to save your first session cookies and reuse them.

**Comment by qhjink** [comment]
Well, when I use new IP and new cookies, they are not detected at first, but other operations after I log in normally are detected.

**Comment by sebdelsol** [comment]
Well, I can't help you without minimal reproducible example.

**Comment by ultrafunkamsterdam** [comment]
no problem here
![image](https://user-images.githubusercontent.com/21027969/178919063-89183936-cd9b-46fc-b476-7a362e434570.png)

**Comment by mianahmad8949** [comment]
> Datadome security varies between site, e.g tidal.com and it is being detected.
> 
> ![datadome_undetected_webddriver](https://user-images.githubusercontent.com/51898206/175302450-12e5724f-adc4-4dff-936f-28a35f01e5a6.png) t

Are you found the solutionn?

**Comment by mianahmad8949** [comment]
> ![36343c772977df941818984656292be](https://user-images.githubusercontent.com/53812117/177291053-cb525109-d556-451d-bc56-e8bda120bd9b.png) url:https://www.cma-cgm.com I also have the same problem. When I open the website, it shows that it has been detected. If I open it manually, it doesn't

You found the solution?
