### ISSUE TITLE
Could you provide an example, on how to run it with Edge?

### ISSUE THREAD

**Issue by Avnsx** [ultrafunkamsterdam/undetected-chromedriver#70]
Kinda couldn't get it to work. 🙄

Thanks in advance!

**Comment by henrybm** [comment]
What do you mean by Edge? As in the Microsoft browser?

This is a package for loading websites in a headless **chrome** browser (headless meaning no graphical interface, or extra stuff that'd slow down a script). It's specifically made to be camouflaged as a normal Chrome browser, and to be undetected as a headless browser.

Could you clarify what do you mean by Edge?

**Comment by Avnsx** [comment]
> What do you mean by Edge? As in the Microsoft browser?
> 
> This is a package for loading websites in a headless **chrome** browser (headless meaning no graphical interface, or extra stuff that'd slow down a script). It's specifically made to be camouflaged as a normal Chrome browser, and to be undetected as a headless browser.
> 
> Could you clarify what do you mean by Edge?

out of the uc read me file `patching also works on MS Edge (chromium-based) webdriver binary`

**Comment by ultrafunkamsterdam** [comment]
Exactly that: The patching works for the edge driver (msedgedriver) as well. Nothing more nothing less. How to use msedgedriver in/or with this package is beyond scope. You can assume same behaviour as Chrome since the engines are are the same.

**Comment by mostafakamelrslan** [comment]
bad support in this point

**Comment by YacineBenzo** [comment]
Anyone to show us how to run it?

**Comment by AdityaSher** [comment]
@YacineBenzo , I tried running edge using it but it doesn't recognize it as a chrome browser so it just shuts down

**Comment by ultrafunkamsterdam** [comment]
You'll off course need to specify the browser_executable since the program searches specifically for Chrome and that overrides that behaviour
