### ISSUE TITLE
Debug mode error

### ISSUE THREAD

**Issue by guidetuanhp** [ultrafunkamsterdam/undetected-chromedriver#704]
![Capture](https://user-images.githubusercontent.com/25765812/176336425-a50d3a86-0321-47b4-b84f-cb6221a92be9.PNG)
```
import time
import undetected_chromedriver as uc
from selenium.webdriver.chrome.options import Options
if __name__ == '__main__':
    options = Options()
    options.debugger_address = "127.0.0.1:9222"
    driver = uc.Chrome(driver_executable_path='C:\\Users\\guide\\Downloads\\chromedriver.exe', options=options)
    driver.get("https://abrahamjuliot.github.io/creepjs/")
    time.sleep(1000)
```

When I run with debug mode, it will run 2 chromes the same as the picture. 
Anyone can show me a method to fix it? Thank you

**Comment by sebdelsol** [comment]
Yes it's actually a bug in UC. Why do you need to provide a debugger address ? 
UC will find one for you on a free port.

**Comment by sebdelsol** [comment]
* You should use `uc.ChromeOptions()` instead of the Selenium one.
* **Why do you need to specify a debug address ?** _UC already looks for a free port for you..._
* There's a bug indeed with `options.debugger_address` 
* To fix it you'll to modify the code [in `__init__.py`, line 250](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/b2e804e977c9cf3dd9c845474752cac142a72508/undetected_chromedriver/__init__.py#L250) :
```python 3
        # debug_port = selenium.webdriver.common.service.utils.free_port()
        # debug_host = "127.0.0.1"

        # if not options.debugger_address:
        #     options.debugger_address = "%s:%d" % (debug_host, debug_port)

        # FIX : REPLACED BY

        if not options.debugger_address:
            debug_port = port if port != 0 else selenium.webdriver.common.service.utils.free_port()
            debug_host = "127.0.0.1"
            options.debugger_address = "%s:%d" % (debug_host, debug_port)
        else:
            debug_host, debug_port = options.debugger_address.split(":")
            debug_port = int(debug_port)

        # END of FIX
```

**Comment by sebdelsol** [comment]
Sure you launch twice your chrome, once with cmd and a second time with `uc.Chrome()` in your script. 
You should read the doc to check how to use UC. 
by the way the correct option would be `--remote-debugging-port`

**Comment by guidetuanhp** [comment]
> _**Sure you launch twice your chrome**, once with `cmd` and a second time with `uc.Chrome()` in your script_ !! And by the way the correct command line switch is `--remote-debugging-port`...
> 
> Anyway you don't have to launch a chrome by hand or specify an address or a port :
> 
> ```python
> import undetected_chromedriver as uc
> 
> if __name__ == '__main__':
>     driver = uc.Chrome()
>     driver.get("https://abrahamjuliot.github.io/creepjs/")
>     input("hit a key to quit")
>     driver.quit()
> ```
> 
> Thanks for closing this non issue.

But when I run this code
```
from selenium import webdriver
option = webdriver.ChromeOptions()
option.debugger_address = "127.0.0.1:9222"
driver = webdriver.Chrome(executable_path= 'C:\\Users\\guide\\Downloads\\chromedriver.exe', options=option)
driver.get("https://abrahamjuliot.github.io/creepjs/")
time.sleep(1000)
```
it only opened 1 chrome. My aim is to control chrome in cmd and not open more chrome browser.

**Comment by sebdelsol** [comment]
Why would you want to do that ?!

**Comment by guidetuanhp** [comment]
> Why would you want to do that ?!

I want to remote gologin profile by undetect_chromedriver.

**Comment by guidetuanhp** [comment]
> why don't you use the Chrome browser launched and controlled by UC for that ? Sorry it doesn't make sense.

gologin can fake all fingerprint browsers and I want to remote it.

**Comment by sebdelsol** [comment]
I guess it's possible but it would mean a lot of change in UC :
UC does launch a Chrome browser in a detached process and handles it's termination. 
So you'll have to get red of all this code to make it works. 
Good luck.

**Comment by lqdm** [comment]
@guidetuanhp Have you solved the problem yet
I also need to control the open browser and have the same problem as you

**Comment by hoanm1206** [comment]
@guidetuanhp @fomsun use subprocess = True and add argument to options chrome:

**Comment by hoanm1206** [comment]
@guidetuanhp @fomsun 
I fixed it, pm me

**Comment by BeMoreHappY** [comment]
@hoanm1206 How you fix it? 
Can you pm me? Discord: WhySoSerious#2434

**Comment by jay-sync** [comment]
@guidetuanhp @fomsun @hoanm1206 did u guys found how to do it? I'm really struggling to find a fix
