### ISSUE TITLE
Can I get html code of site by driver, like requests library?

### ISSUE THREAD

**Issue by kronargames** [ultrafunkamsterdam/undetected-chromedriver#707]
Can I get html code of site by driver, like requests library? Standar html code of page.
Like this.

<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="utf-8">

<title>Топ 100 игр скачать через торрент бесплатно на ПК</title>

<meta name="description" content="Скачать Топ 100 игр 🎮 через торрент бесплатно Вы можете с нашего сайта.  	Заходите и скачивайте Топ 100 игр на высокой скорости через торрент.">

<meta name="keywords" content="Топ 100 игр скачать через торрент бесплатно на ПК">

<link rel="search" type="application/opensearchdescription+xml" href="https://i.torrentis.net/index.php?do=opensearch" title="Скачать игры через торрент бесплатно на компьютер">

<link rel="canonical" href="https://i.torrentis.net/top-100/">
<link href="/engine/editor/css/default.css?v=26" rel="stylesheet" type="text/css">
<script src="/engine/classes/js/jquery.js?v=26"></script>
<script src="/engine/classes/js/jqueryui.js?v=26" defer></script><!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="utf-8">

<title>Топ 100 игр скачать через торрент бесплатно на ПК</title>

<meta name="description" content="Скачать Топ 100 игр 🎮 через торрент бесплатно Вы можете с нашего сайта.  	Заходите и скачивайте Топ 100 игр на высокой скорости через торрент.">

<meta name="keywords" content="Топ 100 игр скачать через торрент бесплатно на ПК">

<link rel="search" type="application/opensearchdescription+xml" href="https://i.torrentis.net/index.php?do=opensearch" title="Скачать игры через торрент бесплатно на компьютер">

<link rel="canonical" href="https://i.torrentis.net/top-100/">
<link href="/engine/editor/css/default.css?v=26" rel="stylesheet" type="text/css"><!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="utf-8">

<title>Топ 100 игр скачать через торрент бесплатно на ПК</title>

<meta name="description" content="Скачать Топ 100 игр 🎮 через торрент бесплатно Вы можете с нашего сайта.  	Заходите и скачивайте Топ 100 игр на высокой скорости через торрент.">

<meta name="keywords" content="Топ 100 игр скачать через торрент бесплатно на ПК">

<link rel="search" type="application/opensearchdescription+xml" href="https://i.torrentis.net/index.php?do=opensearch" title="Скачать игры через торрент бесплатно на компьютер">

<link rel="canonical" href="https://i.torrentis.net/top-100/">
<link href="/engine/editor/css/default.css?v=26" rel="stylesheet" type="text/css">
<script src="/engine/classes/js/jquery.js?v=26"></script>
<script src="/engine/classes/js/jqueryui.js?v=26" defer></script>
<script src="/engine/classes/js/dle_js.js?v=26" defer></script>
    <meta name="verify-admitad" content="226ea1ccf2" />
    <meta name="yandex-verification" content="8bdbbe25a66a2e56" />
    <meta name="verify-admitad" content="f3714d0ba3" />
	<meta name="yandex-verification" content="62ed312594ca20d2" />
	<meta name="HandheldFriendly" content="true">
    <meta name="verify-admitad" content="18ee11e3ee" />
	<meta name="format-detection" content="telephone=no">
	<meta name="viewport" content="user-scalable=0, initial-scale=1.0, maximum-scale=1.0, width=device-width">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="default">
  	<meta name="google-site-verification" content="eFYQD-WIyu6Xoee3aZMREYexcFhVMd8S-hBVfwlCm8Q" />
	<meta name="google-site-verification" content="TpGOU32aea0IOW5vZ_SKVfoJGbAXxEA21iWce9vRyEU" />
	<meta name="yandex-verification" content="3a136934ff604c58" />
	<meta name="yandex-verification" content="62ed312594ca20d2" />
	<link rel="shortcut icon" href="/templates/AniMan/images/favicon.ico">
	<link rel="apple-touch-icon" href="/templates/AniMan/images/touch-icon-iphone.png">
	<link rel="apple-touch-icon" sizes="76x76" href="/templates/AniMan/images/touch-icon-ipad.png">
	<link rel="apple-touch-icon" sizes="120x120" href="/templates/AniMan/images/touch-icon-iphone-retina.png">
	<link rel="apple-touch-icon" sizes="152x152" href="/templates/AniMan/images/touch-icon-ipad-retina.png">
	<meta name="yandex-verification" content="1d0adb1d61db3890" />
	<link rel="stylesheet" type="text/css" href="/engine/classes/min/index.php?f=/templates/AniMan/css/engine.css,/templates/AniMan/css/styles.css,/templates/AniMan/css/dark-styles.css,/templates/AniMan/css/fa-svg-with-js.css,/templates/AniMan/css/filter-xf.css" />
	
	
	
	

</head>
<body>
	<div class="wrap">
		<form class="droptopbar" id="q_search" method="post">
			<div class="wrp">
				<div class="q_search">
					<input id="mstory" name="story" placeholder="Поиск по сайту..." type="search">
					<button class="btn" type="submit" title="Найти">Искать</button>
				</div>
			</div>
			<input type="hidden" name="do" value="search">
			<input type="hidden" name="subaction" value="search">
		</form>
		<header class="header clearfix">
			<div class="head_in center  fx-row fx-middle ">
				<div class="h_left">
					<a id="toggle-btn" href="#" class="menu-btn active">
            <span></span>
            <span></span>
            <span></span>
          </a>
          <a id="menu-btn" href="#" class="menu-btn active">
            <span></span>
            <span></span>
            <span></span>
          </a>
					<a href="/" class="logotype" title="На главную">TORRENT <span>is.NET</span></a>
				</div>
				<div id="s-btn" class="s-btn"><span class="far fa-search fa-2x"></span></div>
				<div class="search-box">
						<form id="quicksearch" method="post">
							<input type="hidden" name="do" value="search">
							<input type="hidden" name="subaction" value="search">
							<div class="search-field">
								<input id="story" name="story" placeholder="Поиск игр..." type="text" autocomplete="off">
								<button type="submit" title="Найти"><span class="far fa-search"></span></button>
							</div>
						</form>
				</div>
				
				<div class="login-btns">
				    <div class="lb-in">
						
						

	<a href="/?do=register">Регистрация</a>

	<div class="l-show">Вход</div>

	<div class="l-box" id="l-box" title="Авторизация">

**Comment by sebdelsol** [comment]
```python3
driver.get(url)

# here wait for something that makes sure the page is loaded

html = driver.page_source
```

**Comment by ultrafunkamsterdam** [comment]
i forgot about that one, woops.!  much better than using `execute_script("""return document.documentElement.outerHTML""") ` ;)

**Comment by alexey-salmin-navee** [comment]
> html = driver.page_source

But doesn't it ignore all of the dynamic content?

An ability to get a complete DOM tree (i.e. after the JS execution) directly from the driver would be really helpful. Right now only the execute_script solution works and I suspect it can lead to detection. So very relevant to the undetected-chromedriver project.
