### ISSUE TITLE
Module not working properly on Ubuntu 18.04.5 LTS (Server)

### ISSUE THREAD

**Issue by sirgoogleadmin** [ultrafunkamsterdam/undetected-chromedriver#71]
When i try running a script with using this module, an error is incurring.

Traceback (most recent call last):
  File "cfsolver.py", line 1, in <module>
    import undetected_chromedriver as uc
  File "/usr/local/lib/python2.7/dist-packages/undetected_chromedriver/__init__.py", line 38
    def __new__(cls, *args, enable_console_log=False, **kwargs):
                                             ^
SyntaxError: invalid syntax

When i run the script on my PC (Windows 10) it's working with no problem.

import undetected_chromedriver as uc
options = uc.ChromeOptions()
options.headless=True
options.add_argument('--headless')
chrome = uc.Chrome(options=options)
chrome.get('https://www.cloudflare.com/')
chrome.save_screenshot('cfscreenshot.png')

Thats the script i try to run.

Any Idea how to fix this?
Already reinstalled it as well

**Comment by ultrafunkamsterdam** [comment]
python2.7 is not supported.
