### ISSUE TITLE
Cloudflare detection

### ISSUE THREAD

**Issue by samvsodev** [ultrafunkamsterdam/undetected-chromedriver#73]
As of 12-16-20, CloudFlare is detecting chromedriver again. I noitced the last commit to fix this was                    

newline = re.sub(b"cdc_.{22}", b"xxz_undetectedchromeDRiver", line)

I tried randomly changing 'xxz_undetectedchromeDRiver' but no success.

**Comment by ultrafunkamsterdam** [comment]
Thanks for notifying! Randomized on it's way

**Comment by montovaneli** [comment]
In case it helps, here is a possible workaround I've accomplished just a few minutes ago:

- Start driver;
- driver.get('http://google.com/?q={THE_WEBSITE_YOU_WANT}')
- I realized if I open the website using CTRL + Click (Open Link in New Tab) at the first google result, Cloudfare doesn't detect it.
- So I imported:

```
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

```
- And after starting the driver:

```
driver.get('http://google.com/search?q=bsportfan')
element = driver.find_element_by_xpath('.//h3[@class = "LC20lb DKV0Md"]') # h3 class for the first google result.

# Ctrl+Click

ActionChains(driver) \
    .key_down(Keys.CONTROL) \
    .click(element) \
    .key_up(Keys.CONTROL) \
    .perform()

driver.switch_to.window(driver.window_handles[1])
```

And the Cloudfare has not detected it.

**Comment by samvsodev** [comment]
@montovaneli Worth a try! lol! But in my case, it didn't work :/

**Comment by ultrafunkamsterdam** [comment]
I did not even test it to be honest, but i just like it since i know what he has been going through before ending up with  a solution like this. I do it all the time.
V2 is almost to be published, has a "almost" complete rewrite and other inner workings and has a nifty workaround for cloudflare too. On top of that it is blazing fast, even much faster than the official selenium package.  I'm however looking for some volunteers for a small pilot at  the end of coming week (i expect fixing the major bugs , and have some docu ready by then)

**Comment by aleixrodri98** [comment]
Hello @ultrafunkamsterdam, thanks for your work, has been a big inspiration for me, keep it up.

I would love to volunteer for you, I have a cluster of selenium browsers running 24/7 and I could use a small part to test your software and help on everything I can.

Thanks for everything again,
Aleix

**Comment by chemeng** [comment]
@ultrafunkamsterdam if you need more testing bandwidth I got a dozen machines running 24/7 on a variety of sites. Let me know.

**Comment by ultrafunkamsterdam** [comment]
@chemeng 

Thanks for the offer, however i got enough 😄

I tackled hCaptcha (which cloudflare uses behind the scenes couple of days ago), and working hard to bring a new version ( implement it in a cross platform, head/headless non breaking way)

**Comment by ultrafunkamsterdam** [comment]
'pip install -u undetected-chromedriver'

```python
import undetected_chromedriver.v2 as uc
driver = uc.Chrome()
with driver:
    driver.get('https://coinfaucet.eu')
```
