### ISSUE TITLE
Getting IP detected

### ISSUE THREAD

**Issue by KexoTV** [ultrafunkamsterdam/undetected-chromedriver#737]
So i have bot that is on heroku which scrapes sites once a day

code:

```
import undetected_chromedriver.v2 as uc
from selenium import webdriver

options = webdriver.ChromeOptions()
options.add_argument("start-maximized")
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument("--deny-permission-prompts")
driver = uc.Chrome(executable_path=os.environ.get("CHROMEDRIVER_PATH"), options=options)

```
Site is normally scraped when on my PC, but on heroku the edited response is this:

```
Access Denied
The location (IP Address) you are using is from a data center.  To prevent fraud, Gleam blocks entry from these locations.  This is usually the result of using a VPN to access our site.

Please turn off your VPN and try again.

Reload

Access denied

You do not have access to gleam.io. The site owner may have set restrictions that prevent you from accessing the site. Contact the site owner for access or try loading the page again
```

**Comment by ALCarter2** [comment]
You're using a lot of custom arguments that aren't recommended by the creator. Have you tried the default settings?

**Comment by KexoTV** [comment]
So i removed everything except --headless option and results are same

**Comment by ALCarter2** [comment]
The documentation states that undetected chromedriver isn't meant to be run in headless mode and can lead to detection. I'm not sure where I exactly I read this-- maybe in the code comments when I was going through the package. Anyway, I would probably have removed the headless option as well, just to establish a baseline.

**Comment by KexoTV** [comment]
Ok so i removed all options and today my bot pinged site and still same source code where it says same thing again.

No, i am not using VPN, weird is, this is the only site which does that, i am not sure if heroku is on their blacklist or something else.

**Comment by KexoTV** [comment]
Now it says:

One more step

Please complete this security check to access gleam.io

**Comment by KexoTV** [comment]
I asked on stackoverflow and answer is to add these options:

```
chrome_options.add_argument("--headless") 
chrome_options.add_argument("--disable-dev-shm-usage") 
chrome_options.add_argument("--no-sandbox")
```
