### ISSUE TITLE
How to avoid downloading the chromedriver every time start?

### ISSUE THREAD

**Issue by WhZzi** [ultrafunkamsterdam/undetected-chromedriver#744]
Situation: I can make sure that my Google browser is always in the same version( I stop the automatic update actually ), and I have downloaded the corresponding version of chromedriver. Now it seems that every time the browser is initialized, a new chromedriver will be downloaded again. 

I need to run my code in multi threads, download everytime I init the uc is hard for me.

Possible solve method:
provide browser_executable_path param when uc is init. In this method, I want to know use same chromedriver will effect anti-detection work in well?

**Comment by AkramiPro** [comment]
i have the same issue . please send some information about it

**Comment by WhZzi** [comment]
> i have the same issue . please send some information about it

import undetected_chromedriver as uc
driver = uc.Chrome(browser_executable_path="YOUR_WEBDRIVER_PATH")

Maybe you can try in this way.

**Comment by AkramiPro** [comment]
i think the right option is `driver_executable_path` not `browser_executable_path`
