### ISSUE TITLE
Partially detected by seekingalpha.com

### ISSUE THREAD

**Issue by Agney-gt** [ultrafunkamsterdam/undetected-chromedriver#748]
undetected chromedriver is really good. If we try using regular selenium here, it will outright prevent you from logging in as the "browser is unsecure". Using uc, we can log in, scrape a list and then visit one link and scrape the data. However, once it goes to the second item on the list, we are forced to fill a captcha which keeps on repeating no matter how many times you fill it.

Code:

```
def Login():
    driver.get("https://seekingalpha.com/")
    time.sleep(30)
    driver.find_element_by_xpath('//button[contains(@data-test-id, "sign-in")]').click()
    time.sleep(5)
    driver.find_element_by_xpath('//span[contains(text( ), "Sign in with Google")]').click()
    time.sleep(5)
    pyautogui.write("123@gmail.com")
    time.sleep(2)
    pyautogui.press("enter")
    time.sleep(5)
    pyautogui.write("12345")
    time.sleep(2)
    pyautogui.press("enter")
    time.sleep(30)


def ScrollToLast():
    fromDate="2022-06-15"
    toDate="2022-07-07"
    transcriptsListURL="https://seekingalpha.com/earnings/earnings-call-transcripts?from="+fromDate+"T18%3A30%3A00.000Z&to="+toDate+"T18%3A29%3A59.999Z"
    driver.get(transcriptsListURL)
    time.sleep(15)
    
    reached_page_end = False
    last_height = driver.execute_script("return document.body.scrollHeight")
    while not reached_page_end:
        driver.find_element_by_xpath('//body').send_keys(Keys.END)
        try:
            driver.find_element_by_xpath('//a[contains(text( ), "Show more")]').click()
        except Exception as e:
            pass
        time.sleep(5)
        new_height = driver.execute_script("return document.body.scrollHeight")
        if last_height == new_height:
            reached_page_end = True
        else:
            last_height = new_height

def TranscriptList():
    URLList=set()
    postList=driver.find_elements_by_xpath('//a[contains(@data-test-id, "post-list-item-title")]')    
    for post in postList:
        postURL=post.get_attribute('href')
        URLList.add(postURL)
    return URLList

Login()
ScrollToLast()
urls=TranscriptList()
urlz=list(urls)

for url in urlz:
    driver.get(url)
    time.sleep(5)
    driver.find_element_by_xpath('//span[contains(text( ), "Play")]').click()
    time.sleep(2)
    driver.find_element_by_xpath('//button[contains(@data-test-id, "options-button")]').click()
    time.sleep(2)
    driver.find_element_by_xpath('//button[contains(text( ), "Download")]').click()
    time.sleep(2)

    time.sleep(120)
    #WebDriverWait(driver, 600).until(EC.element_to_be_clickable((By.XPATH, '//span[contains(text( ), "Pause")]')))
    print("Element Clickable")#time.sleep(2)
    title=driver.find_element_by_xpath('//h1[contains(@data-test-id, "post-title")]').text
    company=driver.find_element_by_xpath('//span[contains(@data-test-id, "post-primary-tickers")]').text
    timez=driver.find_element_by_xpath('//span[contains(@data-test-id, "post-date")]').text
     
    driver.find_element_by_xpath('//span[contains(@data-test-id, "post-primary-tickers")]').text
    body=driver.find_element_by_xpath('//div[contains(@data-test-id, "content-container")]').get_attribute("outerHTML")
    b=BeautifulSoup(body,'lxml')
    print(title)
    print(company)
    print(timez)
    print(b.text)
    with open(company.split(" ")[0]+".txt", "x") as f:
        f.write(title+"\n\n"+timez+"\n\n"+body)
        print("Write to file")
        time.sleep(5)
```

I am using a clean IP - Tried multiple different IP using VPN and the same problem is seen in all cases.
I am able to go to the website. Login to a free account. Go to the transcript listing page, scroll till the end and scrape the urls.
Then i can go to the first URL and download the audio as well as scrape the text and write to file successfully.

You can see the working of the script in the video below.

https://user-images.githubusercontent.com/84612798/181423877-dd48b8c5-0a4a-4c7b-ab05-2d0067f23bc0.mp4

However, as soon as i go to the second url, i am faced with captcha saying "enable javascript, enable cookies and disable adblock". No matter how many times i solve the captcha, it still does not remove the flag.

If anyone has faced this before and knows how to solve this, would really appreciate the help,

Thanks

**Comment by theansweryang** [comment]
I have similar issues when I was working on Realtor.com. Please let me know if there are any possible solutions on this one.

**Comment by Agney-gt** [comment]
Found this, https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/675

Also found https://github.com/droefs/HLISA

Perhaps this can solve this issue. Will work on It and update.

**Comment by theansweryang** [comment]
> 

I have tried this for Realtor.com. It works for an hour, then it still got detected.

**Comment by Agney-gt** [comment]
@ultrafunkamsterdam @sebdelsol 

I would like to thank you guys from the bottom of my heart for literally holding our hands and guiding a large number of us clowns 🤡 with your hard work on the module + docker and activity/comments on GitHub.

Thank you for your patience, consideration and contributions
