### ISSUE TITLE
 This version of ChromeDriver only supports Chrome version 104 Current browser version is 103.0.5060.134

### ISSUE THREAD

**Issue by 1bowmanjac** [ultrafunkamsterdam/undetected-chromedriver#757]
I'm getting this error every time I start my script. It worked with no issues last night so I don't know what changed.

I've tried downloading the newest version of the chrome driver and targeting it. As well as setting the target version but it's still happening

**Comment by Alexei17** [comment]
Same, forgot to turn off auto updates. What is happening?

**Comment by 1bowmanjac** [comment]
That fixed it for me as well. Thank's a ton

**Comment by HoangMoli** [comment]
Manually update your Chrome version then relaunch, that should work, but how should I prevent this from happening in the future tho?
