### ISSUE TITLE
Is cache being saved within one session? 

### ISSUE THREAD

**Issue by repeating** [ultrafunkamsterdam/undetected-chromedriver#762]
I'm calling the same webpage several times in one driver session, but every time I do .get(<PAGE_URL>) it takes 15-30 seconds to load it. Nevertheless, when I open the same webpage from my normal browser it loads immediately due to the fact that it's cashed. 

Any idea why this is happening and how can I cache the webpage to load faster? 

**Minimum reproducible code:**
```
from src.driver import Driver

def main():
    d = Driver()
    d.get('https://sonarhome.pl/zaloguj')
    d.get('https://sonarhome.pl/zaloguj') # takes long to load
    d.get('https://sonarhome.pl/zaloguj') # takes long to load
    
if __name__ == '__main__':
    main()
```

**Comment by sebdelsol** [comment]
Your code **_isn't reproductible_** since you don't provide the code for instantiating your driver and _what Chrome options you use._ 
I can't reproduce your long loading time... Anyway Chrome is your regular one and yes it should caches your page.

**Comment by repeating** [comment]
Sorry, I was appearently doing something with the options that's deleting the caches.
Thank you so muc for highliting that **it should caches**!
