### ISSUE TITLE
add_experimental_option doesn't work

### ISSUE THREAD

**Issue by fabifont** [ultrafunkamsterdam/undetected-chromedriver#769]
```python
options.add_experimental_option("useAutomationExtension", False)
options.add_experimental_option("excludeSwitches", ["enable-automation"])
```

UC crashes with:
```
[ERROR] Message: invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: unrecognized chrome option: excludeSwitches
Stacktrace:
#0 0x55a1e24aff33 <unknown>
#1 0x55a1e21fa118 <unknown>
#2 0x55a1e22136f2 <unknown>
#3 0x55a1e2217c85 <unknown>
#4 0x55a1e2210282 <unknown>
#5 0x55a1e225291b <unknown>
#6 0x55a1e2252356 <unknown>
#7 0x55a1e2253acd <unknown>
#8 0x55a1e224de63 <unknown>
#9 0x55a1e222382a <unknown>
#10 0x55a1e2224985 <unknown>
#11 0x55a1e24f44cd <unknown>
#12 0x55a1e24f85ec <unknown>
#13 0x55a1e24de71e <unknown>
#14 0x55a1e24f9238 <unknown>
#15 0x55a1e24d3870 <unknown>
#16 0x55a1e2515608 <unknown>
#17 0x55a1e2515788 <unknown>
#18 0x55a1e252ff1d <unknown>
#19 0x7f34e2fa254d <unknown>
```

Is there any way to fix this?

**Comment by sebdelsol** [comment]
No and those options are useless.

**Comment by fabifont** [comment]
> No and those options are useless.

Why are they useless?

**Comment by sebdelsol** [comment]
They are not needed to prevent detection when using UC.
Thanks for closing this non issue.

**Comment by fabifont** [comment]
> They are not needed to prevent detection when using UC. Thanks for closing this non issue.

If this is not an issue it should be reported somewhere.

**Comment by Auties00** [comment]
> 

How is this a non issue? This only happens in conjunction with this library so it's clearly the result of a bug.

**Comment by Auties00** [comment]
> They are not needed to prevent detection when using UC. Thanks for closing this non issue.

How is this a non issue? This only happens in conjunction with this library so it's clearly the result of a bug.

**Comment by sebdelsol** [comment]
No it's not due to the way the Chrome browser is launched before the driver, experimental options are not supported except for prefs thanks to a workaround using the profile preferences file. Anyway you absolutely don't need those options with UC.

**Comment by markthepixel** [comment]
The `options.add_experimental_option("detach", True)` is very helpful for testing
