### ISSUE TITLE
Detected by DataDome

### ISSUE THREAD

**Issue by jhnguyen521** [ultrafunkamsterdam/undetected-chromedriver#771]
Unfortunately it looks like this is now instantly detected by datadome. Been trying to figure out how to no avail.
https://antoinevastel.com/bots/datadome

**Comment by ezako2** [comment]
I too still have big problem with datadome
s h o p 2 g a m e . c o m 
on free fire when using login by ID
for example this one: 741517200
when clicking on login, the DataDome detected that chrome is a bot, and they blocked the IP for 24 hours
however: if I test on normal chrome (before using undetected-chromedriver) , it works very fast and without any problem

I have tested the waiting time between any action 5 sec
also using actionchain to send player id and click on the login button

selenium version 4
undetected-chromedriver last version 3.5.1post4


how can bypass this, its very difficult.. any advice here ?

**Comment by RestOp** [comment]
Hi,

please post the whole code also how you make click on Login

Thanks

**Comment by QIN2DIM** [comment]
boring. It just checks if you press F12 to see the source code.

**Comment by chrisbag** [comment]
I also get detected by datadome. On antoinevastel "see your fingerprint" page, the webdriver test is Inconsistent.
Is there any way to by pass ? Do you change window size and User agent ?

**Comment by ultrafunkamsterdam** [comment]
You just use bad ip. Period.
