### ISSUE TITLE
Some problems encountered when cleaning up the chrome cache are -- JavaScript error: cannot read properties of null (reading 'shadowroot')

### ISSUE THREAD

**Issue by Lousm** [ultrafunkamsterdam/undetected-chromedriver#777]
When I do not add "options. Add_argument (" -- headless ")", I can use the following code to clean up the chrome cache normally. It is
`driver.get('chrome://settings/clearBrowserData')
        time.sleep(2)
        driver.execute_script(
            'document.querySelector("body > settings-ui").shadowRoot.querySelector("#main").shadowRoot.querySelector("settings-basic-page").shadowRoot.querySelector("#basicPage > settings-section:nth-child(9) > settings-privacy-page").shadowRoot.querySelector("settings-clear-browsing-data-dialog").shadowRoot.querySelector("#clearBrowsingDataConfirm").click()')
`
However, when I add "options. Add_argument (" -- headless ")" again, an error will be reported. It is
`selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read properties of null (reading 'shadowRoot')`

How can I clean up the chrome cache correctly in the interface less mode? Thank you.

**Comment by Lousm** [comment]
> When I do not add "options. Add_argument (" -- headless ")", I can use the following code to clean up the chrome cache normally. It is
 `driver.get('chrome://settings/clearBrowserData') 
time.sleep(2) 
driver.execute_script( 'document.querySelector("body > settings-ui").shadowRoot.querySelector("#main").shadowRoot.querySelector("settings-basic-page").shadowRoot.querySelector("#basicPage > settings-section:nth-child(9) > settings-privacy-page").shadowRoot.querySelector("settings-clear-browsing-data-dialog").shadowRoot.querySelector("#clearBrowsingDataConfirm").click()') ` However, when I add "options. Add_argument (" -- headless ")" again, an error will be reported. It is `selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read properties of null (reading 'shadowRoot')`
> 
> How can I clean up the chrome cache correctly in the interface less mode? Thank you.

**Comment by sebdelsol** [comment]
It seems `chrome://settings/` are not supported in headless mode : [**Please check this**.](https://bugs.chromium.org/p/chromium/issues/detail?id=773874#c6)

**Comment by sebdelsol** [comment]
@Lousm does that solve your issue ?

**Comment by Lousm** [comment]
> ```python
> driver.execute_cdp_cmd("Network.clearBrowserCache", {})
> driver.execute_cdp_cmd("Network.clearBrowserCookies", {})
> ```

Sorry, it didn't work. The cookies of the website still exist in the cache. What I want to achieve is to completely clear the cookie, and then regenerate the new cookie the next time I visit this link

**Comment by Dec1lent** [comment]
You could generate a new chrome profile on every and then delete them after. But I don't know if you are using some profile settings that can't be changed in headless.

**Comment by Lousm** [comment]
> You could generate a new chrome profile on every and then delete them after. But I don't know if you are using some profile settings that can't be changed in headless @Lousm

Thank you for your help. Based on your method, I tried again, but I couldn't implement it very well. However, in the end, I used the BitBrowser and used the API provided by the software to drive the chromedriver, which can effectively meet my requirements. Thank you again.

**Comment by Lousm** [comment]
@Dec1lent  @sebdelsol  Thank you all
