### ISSUE TITLE
Page wont open - https://288365.com

### ISSUE THREAD

**Issue by takamaka-1337** [ultrafunkamsterdam/undetected-chromedriver#79]
Is it possible that page https://288365.com detects driver?

It worked fine now for quite some time, but not anymore.

Using chrome + chromedriver 87 and latest undetected-chromedriver (1.5.2)

Can you please check?

**Comment by Avnsx** [comment]
I can't even open it in my normal chrome browser lol

**Comment by takamaka-1337** [comment]
I think its an issue with python > 3.6 or so. It is working with 3.6, but not with 3.9. Anyone can confirm?

**Comment by ultrafunkamsterdam** [comment]
No, bet365 has geo-restrictions. this is primariliy IP-bound. closing.

**Comment by takamaka-1337** [comment]
@ultrafunkamsterdam it is not bet365 geo-restriction, as i can use it from browser. When using python3.6+last undetected chromedriver+last chrome it is working ok. When i switch to >=3.8 python it wont work.

Any suggestion what could be the case for this?
