### ISSUE TITLE
 Message: session not created: This version of ChromeDriver only supports Chrome version 81

### ISSUE THREAD

**Issue by banyous** [ultrafunkamsterdam/undetected-chromedriver#8]
when I run this code : 
```
from undetected_chromedriver import Chrome, ChromeOptions 
browser = Chrome()
browser.get('https://www.quora.com/')
```

I am getting this error : 
`  raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81`

Note : I have Chrome version 83

**Comment by chemeng** [comment]
just change the version in the code. 

Line 32
https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/master/undetected_chromedriver/__init__.py

**Comment by banyous** [comment]
Thanks for the prompt response, How do I install the package with the 83 version?

**Comment by chemeng** [comment]
i would just download it. it's one file. @ultrafunkamsterdam was kind enough to put this on github

**Comment by ultrafunkamsterdam** [comment]
import undetected_chromedriver
undetected_chromedriver.TARGET_VERSION = 83

i will update the default soon

**Comment by ultrafunkamsterdam** [comment]
or run ```pip -U git+https://github.com/ultrafunkamsterdam/undetected-chromedriver```
