### ISSUE TITLE
Can't do "driver = Chrome(options=opts)" in monkeypatch mode

### ISSUE THREAD

**Issue by Jka3003** [ultrafunkamsterdam/undetected-chromedriver#80]
If I do "driver = Chrome(options=opts)" then when the script launches it says "Chrome is being controlled by an automated test web browser" at the top. When I changed it to "driver = Chrome()" there is no banner at the top

**Comment by Jka3003** [comment]
This is what my code looks like
`# Undetected Chrome Driver
import undetected_chromedriver as uc
uc.install()

# Selenium Libraries
from selenium.webdriver import Chrome
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains


# Product Url
url = input('Product ID:')
print('Getting Session')

##################
# Selenium settings 
opts = Options()
#opts.add_argument("--headless")
opts.add_argument("start-maximized")
opts.add_argument("user-agent=Mozilla/5.0 (BB10; Kbd) AppleWebKit/537.35+ (KHTML, like Gecko) Version/10.3.3.2205 Mobile Safari/537.35+")
opts.add_argument('--disable-blink-features=AutomationControlled')
opts.add_argument("disable-infobars")
#opts.add_argument("window-size=1600,900")
#opts.add_argument('proxy-server='+Proxy+'')


driver = Chrome(options=opts)

# Open Link
driver.get(url)

`

**Comment by ultrafunkamsterdam** [comment]
You do not have to specify all these options as most of them are hardcoded in the patched classes. No need to set blink or user agent whatsoever.  Please just start with the quickstart (recommended) and see what does (or does not 😅) and paste relevant code and full error.

**Comment by Jka3003** [comment]
Oh okay, thank you for explaining that. I just got one more question, with the code (down below). when I run the script this is what it shows [imgur link](https://imgur.com/a/OfC2dGW). Is it normal for the message "Chrome is being controlled by automated test software" to be there. Also when I do the recommended mode how would I import something like "import expected_conditions as EC"
`
import undetected_chromedriver as uc
uc.install()

from selenium.webdriver import Chrome
from selenium.webdriver.chrome.options import Options

opts = Options()
opts.add_argument("window-size=1280,720")

driver = Chrome(options=opts)
driver.get('https://www.google.ca/')
`

**Comment by ultrafunkamsterdam** [comment]
Just use omit the uc.install route. It is in the examples, i know and it works usually, but havent really tested specifially how you ar using it.  Just `import Chrome, ChromeOptions from undetected_chromedriver`   then import the EC , other stuff from selenium as you wish... and  instanstiate `driver = Chrome()` .. and continue like jou would normally.
