### ISSUE TITLE
Which version of selenium?

### ISSUE THREAD

**Issue by MacMarde** [ultrafunkamsterdam/undetected-chromedriver#804]
Is there a specific version required to run UC?
I want to use selenium version 4.1.3 instead of the latest version.

**Comment by sebdelsol** [comment]
Please check the `install_requires` list in the `setup.py` [**here**]( https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/b2e804e977c9cf3dd9c845474752cac142a72508/setup.py#L43).

**Comment by MacMarde** [comment]
Perfect. Thanks!
