### ISSUE TITLE
Undetected Chromedriver issue when headless is on

### ISSUE THREAD

**Issue by AmericanY** [ultrafunkamsterdam/undetected-chromedriver#810]
```python
import undetected_chromedriver.v2 as uc
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


def main(url):
    options = uc.ChromeOptions()
    options.headless = True
    driver = uc.Chrome(options=options)
    driver.get(url)
    try:
        WebDriverWait(driver, 10).until(
            EC.title_contains(('Example'))
        )
        print(driver.title)
    except Exception as e:
        print(type(e).__name__)
    finally:
        driver.quit()


if __name__ == "__main__":
    main('https://www.example.com/')
```

I'm open to any solution where i can use `headless` = `True`, even i tried to use @sebdelsol  docker https://hub.docker.com/r/ultrafunk/undetected-chromedriver but no luck!

**Comment by modbender** [comment]
I'm not sure if this helps but I probably used to have this same trouble long time back... and I added these and it started working

argument_list = [
            '--no-first-run',
            '--no-service-autorun',
            '--password-store=basic',
            '--disable-web-security',
            '--log-level=3'
        ]
options.arguments.extend(argument_list)

**Comment by AmericanY** [comment]
@modbender Thank you but that's not works.

**Comment by rrfaria** [comment]
I have same issue, And I realised that this issue is related to selenium instead of this lib. 
I did same try in selenium enabling/disabling headless and had same issue.
If I found sothing in selenium I'll send here to help.

**Comment by QIN2DIM** [comment]
@rrfaria 

```python
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--disable-setuid-sandbox")
options.add_argument("--disable-software-rasterizer")
```
