### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by Nullum-CC** [ultrafunkamsterdam/undetected-chromedriver#82]
I am having issues with the following line;

options.add_argument(f'--proxy-server=https://X:X')

I need to add my authentication in the proxy. Proxy is IP:PORT:USER:PASS. Any explanation how to fill that in?

Thanks!

**Comment by steathy** [comment]
to use proxy with auth in selenium chromedrive needs some work
either use selenium-wire or load an extension with chrome driver

**Comment by chemeng** [comment]
There are a couple of ways you can do it. One is to use a plugin (see code below). The other one is to do IP based authentication (if you can) in which case you don't need the user/pass.

`
def set_authenticated_proxy_through_plugin(proxy):
    '''
    Creates plugin for proxy auth
    '''
    pluginfile = 'proxy_auth_plugin_{}.zip'.format(proxy_to_url(proxy))
    pluginfile = os.path.join(PLUGIN_DIR, pluginfile)
    if glob.glob(pluginfile):
        return pluginfile
    manifest_json = """
                        {
                            "version": "1.0.0",
                            "manifest_version": 2,
                            "name": "Chrome Proxy",
                            "permissions": [
                                "proxy",
                                "tabs",
                                "unlimitedStorage",
                                "storage",
                                "<all_urls>",
                                "webRequest",
                                "webRequestBlocking"
                            ],
                            "background": {
                                "scripts": ["background.js"]
                            },
                            "minimum_chrome_version":"22.0.0"
                        }
                        """
    background_js = """
                        var config = {
                                mode: "fixed_servers",
                                rules: {
                                singleProxy: {
                                    scheme: "http",
                                    host: "%s",
                                    port: parseInt(%s)
                                },
                                bypassList: ["localhost"]
                                }
                            };

                        chrome.proxy.settings.set({value: config, scope: "regular"}, function() {});

                        function callbackFn(details) {
                            return {
                                authCredentials: {
                                    username: "%s",
                                    password: "%s"
                                }
                            };
                        }

                        chrome.webRequest.onAuthRequired.addListener(
                                    callbackFn,
                                    {urls: ["<all_urls>"]},
                                    ['blocking']
                        );
                        """ % (proxy['proxy_address'], str(proxy['ports']['http']), proxy['username'], proxy['password'])
    with zipfile.ZipFile(pluginfile, 'w') as zp:
        zp.writestr("manifest.json", manifest_json)
        zp.writestr("background.js", background_js)
    return pluginfile

`

**Comment by JAManfredi** [comment]
This only works for headful right?

**Comment by chemeng** [comment]
Right, I combined this with Pyvirtualdisplay so make it "headless"

**Comment by ultrafunkamsterdam** [comment]
the correct url format would be
 `options.add_argument(f'--proxy-server=https://{user}:{pass}@{host}:{port}')` 
 
 however, sending plaintext password is never a good idea.

**Comment by KhushC-03** [comment]
> There are a couple of ways you can do it. One is to use a plugin (see code below). The other one is to do IP based authentication (if you can) in which case you don't need the user/pass.

How did you load this extension in selenium using ucdriver?

**Comment by Avnsx** [comment]
@KhushC-03 I do strongly recommend you just going with the easiest option, which is slenium-wire. Here's an example of how easy it is https://github.com/wkeeling/selenium-wire/issues/256#issue-849660821 (don't mind the issue, that got fixed by now so the code snippet works)

**Comment by CodeGodz** [comment]
This is closed now but niether passing it as options or using the plugin workds on V2 for me

**Comment by taytanqbpass** [comment]
anybody got a workaround for this? both plugin and seleniumwire didnt work for me.

**Comment by Avnsx** [comment]
> anybody got a workaround for this? both plugin and seleniumwire didnt work for me.

are you sure this doesn't work?

```python
import seleniumwire.undetected_chromedriver as uc
from seleniumwire import webdriver

chrome_options = webdriver.ChromeOptions()
chrome_options.headless = False
seleniumwire_options = {'proxy': {'https': 'type://host:port',}} 
driver = uc.Chrome(options=chrome_options, seleniumwire_options=seleniumwire_options)

driver.get('https://api.myip.com/')
```

**Comment by taytanqbpass** [comment]
@Avnsx sorry, i mean authenticated proxies.

**Comment by Avnsx** [comment]
> @Avnsx sorry, i mean authenticated proxies.

Did you try ``'type://username:password@host:port'`` for the var seleniumwire_options above?

for type https, socks4 or socks5

Also have you tried to do a loop on multiple proxies, to see if any of them worked? If I remember correctly some proxies seleniumwire did not allow me to connect to, while I could connect with requests.

**Comment by taytanqbpass** [comment]
i had to use undetected_chromedriver.v2 here (for google login) so the seleniumwire_options option is not really possible. are there other ways for this?

**Comment by Avnsx** [comment]
> i had to use undetected_chromedriver.v2 here (for google login) so the seleniumwire_options option is not really possible. are there other ways for this?

Not sure, I didn't ever try using proxies with v2.
But for me that code snippet I sent works for v1.

**Comment by taytanqbpass** [comment]
still no luck with v2 here, anybody got any ideas? tried the zip plugin, it didn't work on my side.

**Comment by NameEgor** [comment]
> 

<img width="396" alt="image" src="https://user-images.githubusercontent.com/75030577/143325626-08408915-40dd-48e9-a861-193e15329282.png">

f.e:
```
proxy = dict(
        proxy_address="127.0.0.1",
        port=5000,
        username="admin",
        password="admin"
    )
    proxy_plugin_name = set_authenticated_proxy_through_plugin(proxy)
    options = uc.ChromeOptions()
    options.add_extension(proxy_plugin_name)
    chrome = uc.Chrome(chrome_options=options)
```

**Comment by NameEgor** [comment]
Installed undetected-chromedriver           2.2.1

Try it yourself

**Comment by muhy06** [comment]
> Installed undetected-chromedriver 2.2.1
> 
> Try it yourself

No, not working, it wont add plugin.  for some reason, have same undetected-chromedriver version.

**Comment by NameEgor** [comment]
> > Installed undetected-chromedriver 2.2.1
> > Try it yourself
> 
> No, not working, it wont add plugin. for some reason, have same undetected-chromedriver version.

give me a minimally reproducible example of what you are doing

**Comment by muhy06** [comment]
> > > Installed undetected-chromedriver 2.2.1
> > > Try it yourself
> > 
> > 
> > No, not working, it wont add plugin. for some reason, have same undetected-chromedriver version.
> 
> give me a minimally reproducible example of what you are doing

It would great help, find the code attached. 

`def set_authenticated_proxy_through_plugin(proxy):
    '''
    Creates plugin for proxy auth
    '''
    pluginfile = 'proxy_auth_plugin_{}.zip'.format(str(0))
    pluginfile = PLUGIN_DIR + '\\' + pluginfile
    if glob.glob(pluginfile):
        return pluginfile

    manifest_json = """
            {
                "version": "1.0.0",
                "manifest_version": 2,
                "name": "Chrome Proxy",
                "permissions": [
                    "proxy",
                    "tabs",
                    "unlimitedStorage",
                    "storage",
                    "<all_urls>",
                    "webRequest",
                    "webRequestBlocking"
                ],
                "background": {
                    "scripts": ["background.js"]
                },
                "minimum_chrome_version":"22.0.0"
            }
            """
    background_js = """
            var config = {
                    mode: "fixed_servers",
                    rules: {
                    singleProxy: {
                        scheme: "http",
                        host: "%s",
                        port: parseInt(%s)
                    },
                    bypassList: ["localhost"]
                    }
                };

            chrome.proxy.settings.set({value: config, scope: "regular"}, function() {});

            function callbackFn(details) {
                return {
                    authCredentials: {
                        username: "%s",
                        password: "%s"
                    }
                };
            }

            chrome.webRequest.onAuthRequired.addListener(
                        callbackFn,
                        {urls: ["<all_urls>"]},
                        ['blocking']
            );
            """ % (proxy['proxy_address'], str(proxy['ports']), proxy['username'], proxy['password'])

    with zipfile.ZipFile(pluginfile, 'w') as zp:
        zp.writestr("manifest.json", manifest_json)
        zp.writestr("background.js", background_js)

    return pluginfile


host = provided_proxy[0]
port = provided_proxy[1]
username = provided_proxy[2]
password = provided_proxy[3]
proxy = dict(
    proxy_address = host,
    ports = port,
    username = username,
    password = password
)
proxy_plugin_name = set_authenticated_proxy_through_plugin(proxy)
opt.add_extension(proxy_plugin_name)

driver = uc.Chrome(options=opt, version_main=96)
`

**Comment by muhy06** [comment]
> > > Installed undetected-chromedriver 2.2.1
> > > Try it yourself
> > 
> > 
> > No, not working, it wont add plugin. for some reason, have same undetected-chromedriver version.
> 
> give me a minimally reproducible example of what you are doing

that would be great help, been trying it for last couple of days now.

https://drive.google.com/file/d/1NKTg0uXqJ7eEVo7F8ke2suNby_FrMrwL/view?usp=sharing

**Comment by muhy06** [comment]
> > > Installed undetected-chromedriver 2.2.1
> > > Try it yourself
> > 
> > 
> > No, not working, it wont add plugin. for some reason, have same undetected-chromedriver version.
> 
> give me a minimally reproducible example of what you are doing

Using the same method on selenium and it works, but not on undetected-chromedriver. Plugins does not load up.

**Comment by NameEgor** [comment]
> > > > Installed undetected-chromedriver 2.2.1
> > > > Try it yourself
> > > 
> > > 
> > > No, not working, it wont add plugin. for some reason, have same undetected-chromedriver version.
> > 
> > 
> > give me a minimally reproducible example of what you are doing
> 
> that would be great help, been trying it for last couple of days now.
> 
> https://drive.google.com/file/d/1NKTg0uXqJ7eEVo7F8ke2suNby_FrMrwL/view?usp=sharing

you use options, not chrome_options 

Read carefully what I wrote earlier, please.

**Comment by muhy06** [comment]
it worked, but it opened up two browsers simultaneously. Second one has plugin but i guess it is not very much like undetected-chromedriver. 

![WhatsApp Image 2021-11-26 at 20 34 35](https://user-images.githubusercontent.com/16038348/143603918-73c08328-e141-4b62-a6f2-3868fb7dcd54.jpeg)

**Comment by NameEgor** [comment]
> it worked, but it opened up two browsers simultaneously. Second one has plugin but i guess it is not very much like undetected-chromedriver.
> 
> ![WhatsApp Image 2021-11-26 at 20 34 35](https://user-images.githubusercontent.com/16038348/143603918-73c08328-e141-4b62-a6f2-3868fb7dcd54.jpeg)

solved?

**Comment by NameEgor** [comment]
here's the solution.

```
selenium-wire           4.5.6
selenium                4.1.0
undetected-chromedriver 2.2.1

```

```
from seleniumwire.undetected_chromedriver.v2 import Chrome, ChromeOptions

options = {
    'proxy': {
        'http': 'http://user:pass@ip:port',
        'https': 'https://user:pass@ip:port',
        'no_proxy': 'localhost,127.0.0.1'
    }
}

driver = Chrome(seleniumwire_options=options)
```

**Comment by woodcowper** [comment]
Yo! is that possible to handle proxy auth with latest version of undetected-chromedriver 3.1.3 ?

**Comment by Ahmad-Ishaq** [comment]
is there a way we can add a chrome profile because using this snippet of code doesn't allows us to work with oprions to add profile !!!

> here's the solution.
> 
> ```
> selenium-wire           4.5.6
> selenium                4.1.0
> undetected-chromedriver 2.2.1
> ```
> 
> ```
> from seleniumwire.undetected_chromedriver.v2 import Chrome
> 
> options = {
>     'proxy': {
>         'http': 'http://user:pass@ip:port',
>         'https': 'https://user:pass@ip:port',
>         'no_proxy': 'localhost,127.0.0.1'
>     }
> }
> 
> driver = Chrome(seleniumwire_options=options)
> ```

**Comment by rezonasyu** [comment]
> ```python
> options=chrome_options, seleniumwire_options=seleniumwire_options
> ```

This works definately... But cant use it with google login. https certificate error. 

What could be the work around to work with V2?

**Comment by realdronos** [comment]
My ip just didn't change, any ideas?

selenium-wire - 4.6.3
selenium - 4.1.3
undetected-chromedriver - 3.1.5.post4

import time
from seleniumwire import webdriver


if __name__ == '__main__':

    seleniumwire_options = {'proxy': {'https': 'https://LOGIN:PASSWORD@IP:PORT', }}

    driver = uc.Chrome(seleniumwire_options=seleniumwire_options)

    driver.get('https://api.myip.com/')

    time.sleep(10)

**Comment by moein99** [comment]
@rezonasyu 
forget about selenium wire (because it still has a problem with HTTPS certificate) and use undetected chrome with [this](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/557#issuecomment-1073114056)
Then you will be able to use proxy with credentials + Gmail login.

**Comment by SolimanAhmed25** [comment]
@muhy06 @Avnsx

Guys I tried this code, but it did not work. can some one help me. I am using proxies form "Smart Proxy" this is there link "https://smartproxy.com/"



The code:



import zipfile
import undetected_chromedriver.v2 as uc


def set_authenticated_proxy_through_plugin(endpoint, port, username, password):
    '''
    Creates plugin for proxy auth
    '''

    manifest_json = """
                        {
                            "version": "1.0.0",
                            "manifest_version": 2,
                            "name": "Chrome Proxy",
                            "permissions": [
                                "proxy",
                                "tabs",
                                "unlimitedStorage",
                                "storage",
                                "<all_urls>",
                                "webRequest",
                                "webRequestBlocking"
                            ],
                            "background": {
                                "scripts": ["background.js"]
                            },
                            "minimum_chrome_version":"22.0.0"
                        }
                        """
    background_js = """
                        var config = {
                                mode: "fixed_servers",
                                rules: {
                                singleProxy: {
                                    scheme: "http",
                                    host: "%s",
                                    port: parseInt(%s)
                                },
                                bypassList: ["localhost"]
                                }
                            };

                        chrome.proxy.settings.set({value: config, scope: "regular"}, function() {});

                        function callbackFn(details) {
                            return {
                                authCredentials: {
                                    username: "%s",
                                    password: "%s"
                                }
                            };
                        }

                        chrome.webRequest.onAuthRequired.addListener(
                                    callbackFn,
                                    {urls: ["<all_urls>"]},
                                    ['blocking']
                        );
                        """ % (endpoint, port, username, password)
    
    pluginfile = 'proxies_extension.zip'

    with zipfile.ZipFile(pluginfile, 'w') as zp:
        zp.writestr("manifest.json", manifest_json)
        zp.writestr("background.js", background_js)
    return pluginfile

username = 'user'
password = 'pass'
endpoint = 'gate.dc.smartproxy.com'
port = '20000'

options = uc.ChromeOptions()
proxies_extension = set_authenticated_proxy_through_plugin(username, password, endpoint, port)
Browser = uc.Chrome(chrome_options=options)
Browser.get('https://www.myexternalip.com/raw')

**Comment by basvdl97** [comment]
> @muhy06 @Avnsx
> 
> Guys I tried this code, but it did not work. can some one help me. I am using proxies form "Smart Proxy" this is there link "https://smartproxy.com/"
> 
> The code:
> 
> import zipfile import undetected_chromedriver.v2 as uc
> 
> def set_authenticated_proxy_through_plugin(endpoint, port, username, password): ''' Creates plugin for proxy auth '''
> 
> ```
> manifest_json = """
>                     {
>                         "version": "1.0.0",
>                         "manifest_version": 2,
>                         "name": "Chrome Proxy",
>                         "permissions": [
>                             "proxy",
>                             "tabs",
>                             "unlimitedStorage",
>                             "storage",
>                             "<all_urls>",
>                             "webRequest",
>                             "webRequestBlocking"
>                         ],
>                         "background": {
>                             "scripts": ["background.js"]
>                         },
>                         "minimum_chrome_version":"22.0.0"
>                     }
>                     """
> background_js = """
>                     var config = {
>                             mode: "fixed_servers",
>                             rules: {
>                             singleProxy: {
>                                 scheme: "http",
>                                 host: "%s",
>                                 port: parseInt(%s)
>                             },
>                             bypassList: ["localhost"]
>                             }
>                         };
> 
>                     chrome.proxy.settings.set({value: config, scope: "regular"}, function() {});
> 
>                     function callbackFn(details) {
>                         return {
>                             authCredentials: {
>                                 username: "%s",
>                                 password: "%s"
>                             }
>                         };
>                     }
> 
>                     chrome.webRequest.onAuthRequired.addListener(
>                                 callbackFn,
>                                 {urls: ["<all_urls>"]},
>                                 ['blocking']
>                     );
>                     """ % (endpoint, port, username, password)
> 
> pluginfile = 'proxies_extension.zip'
> 
> with zipfile.ZipFile(pluginfile, 'w') as zp:
>     zp.writestr("manifest.json", manifest_json)
>     zp.writestr("background.js", background_js)
> return pluginfile
> ```
> 
> username = 'user' password = 'pass' endpoint = 'gate.dc.smartproxy.com' port = '20000'
> 
> options = uc.ChromeOptions() proxies_extension = set_authenticated_proxy_through_plugin(username, password, endpoint, port) Browser = uc.Chrome(chrome_options=options) Browser.get('https://www.myexternalip.com/raw')

You need to downgrade ther undetected chrome version: pip install undetected-chromedriver==2.2.1
And I also ended up using webdriver.ChromeOptions(), then u should be fine.

**Comment by muhy06** [comment]
> > @muhy06 @Avnsx
> > Guys I tried this code, but it did not work. can some one help me. I am using proxies form "Smart Proxy" this is there link "https://smartproxy.com/"
> > The code:
> > import zipfile import undetected_chromedriver.v2 as uc
> > def set_authenticated_proxy_through_plugin(endpoint, port, username, password): ''' Creates plugin for proxy auth '''
> > ```
> > manifest_json = """
> >                     {
> >                         "version": "1.0.0",
> >                         "manifest_version": 2,
> >                         "name": "Chrome Proxy",
> >                         "permissions": [
> >                             "proxy",
> >                             "tabs",
> >                             "unlimitedStorage",
> >                             "storage",
> >                             "<all_urls>",
> >                             "webRequest",
> >                             "webRequestBlocking"
> >                         ],
> >                         "background": {
> >                             "scripts": ["background.js"]
> >                         },
> >                         "minimum_chrome_version":"22.0.0"
> >                     }
> >                     """
> > background_js = """
> >                     var config = {
> >                             mode: "fixed_servers",
> >                             rules: {
> >                             singleProxy: {
> >                                 scheme: "http",
> >                                 host: "%s",
> >                                 port: parseInt(%s)
> >                             },
> >                             bypassList: ["localhost"]
> >                             }
> >                         };
> > 
> >                     chrome.proxy.settings.set({value: config, scope: "regular"}, function() {});
> > 
> >                     function callbackFn(details) {
> >                         return {
> >                             authCredentials: {
> >                                 username: "%s",
> >                                 password: "%s"
> >                             }
> >                         };
> >                     }
> > 
> >                     chrome.webRequest.onAuthRequired.addListener(
> >                                 callbackFn,
> >                                 {urls: ["<all_urls>"]},
> >                                 ['blocking']
> >                     );
> >                     """ % (endpoint, port, username, password)
> > 
> > pluginfile = 'proxies_extension.zip'
> > 
> > with zipfile.ZipFile(pluginfile, 'w') as zp:
> >     zp.writestr("manifest.json", manifest_json)
> >     zp.writestr("background.js", background_js)
> > return pluginfile
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > username = 'user' password = 'pass' endpoint = 'gate.dc.smartproxy.com' port = '20000'
> > options = uc.ChromeOptions() proxies_extension = set_authenticated_proxy_through_plugin(username, password, endpoint, port) Browser = uc.Chrome(chrome_options=options) Browser.get('https://www.myexternalip.com/raw')
> 
> You need to downgrade ther undetected chrome version: pip install undetected-chromedriver==2.2.1 And I also ended up using webdriver.ChromeOptions(), then u should be fine.

Hi, I finally found the solution. Im using windows 10. Not sure if other OS have the same issue. Basically, zip file for pluginfile is not working instead create a folder and place two files: manifest.json and background.js. then use following code snippet.:

`import undetected_chromedriver as uc

        opts = uc.ChromeOptions()
        pluginfile = set_authenticated_proxy_through_plugin(proxies)
        opts.add_argument(f'--proxy-server=http://{proxies["proxy"]}:{proxies["port"]}')
        opts.add_argument('--load-extension={}'.format(pluginfile))
        driver = uc.Chrome(options=opts,use_subprocess=True)`

**Comment by SafeerAbbas624** [comment]
> > > @muhy06 @Avnsx
> > > Guys I tried this code, but it did not work. can some one help me. I am using proxies form "Smart Proxy" this is there link "https://smartproxy.com/"
> > > The code:
> > > import zipfile import undetected_chromedriver.v2 as uc
> > > def set_authenticated_proxy_through_plugin(endpoint, port, username, password): ''' Creates plugin for proxy auth '''
> > > ```
> > > manifest_json = """
> > >                     {
> > >                         "version": "1.0.0",
> > >                         "manifest_version": 2,
> > >                         "name": "Chrome Proxy",
> > >                         "permissions": [
> > >                             "proxy",
> > >                             "tabs",
> > >                             "unlimitedStorage",
> > >                             "storage",
> > >                             "<all_urls>",
> > >                             "webRequest",
> > >                             "webRequestBlocking"
> > >                         ],
> > >                         "background": {
> > >                             "scripts": ["background.js"]
> > >                         },
> > >                         "minimum_chrome_version":"22.0.0"
> > >                     }
> > >                     """
> > > background_js = """
> > >                     var config = {
> > >                             mode: "fixed_servers",
> > >                             rules: {
> > >                             singleProxy: {
> > >                                 scheme: "http",
> > >                                 host: "%s",
> > >                                 port: parseInt(%s)
> > >                             },
> > >                             bypassList: ["localhost"]
> > >                             }
> > >                         };
> > > 
> > >                     chrome.proxy.settings.set({value: config, scope: "regular"}, function() {});
> > > 
> > >                     function callbackFn(details) {
> > >                         return {
> > >                             authCredentials: {
> > >                                 username: "%s",
> > >                                 password: "%s"
> > >                             }
> > >                         };
> > >                     }
> > > 
> > >                     chrome.webRequest.onAuthRequired.addListener(
> > >                                 callbackFn,
> > >                                 {urls: ["<all_urls>"]},
> > >                                 ['blocking']
> > >                     );
> > >                     """ % (endpoint, port, username, password)
> > > 
> > > pluginfile = 'proxies_extension.zip'
> > > 
> > > with zipfile.ZipFile(pluginfile, 'w') as zp:
> > >     zp.writestr("manifest.json", manifest_json)
> > >     zp.writestr("background.js", background_js)
> > > return pluginfile
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > username = 'user' password = 'pass' endpoint = 'gate.dc.smartproxy.com' port = '20000'
> > > options = uc.ChromeOptions() proxies_extension = set_authenticated_proxy_through_plugin(username, password, endpoint, port) Browser = uc.Chrome(chrome_options=options) Browser.get('https://www.myexternalip.com/raw')
> > 
> > 
> > You need to downgrade ther undetected chrome version: pip install undetected-chromedriver==2.2.1 And I also ended up using webdriver.ChromeOptions(), then u should be fine.
> 
> Hi, I finally found the solution. Im using windows 10. Not sure if other OS have the same issue. Basically, zip file for pluginfile is not working instead create a folder "pluginfile" and place two files: manifest.json and background.js. then use following code snippet.:
> 
> `
> 
> ```
>     import undetected_chromedriver as uc
> 
>     opts = uc.ChromeOptions()
>     pluginfile = set_authenticated_proxy_through_plugin(proxies)
>     opts.add_argument(f'--proxy-server=http://{proxies["proxy"]}:{proxies["port"]}')
>     opts.add_argument('--load-extension={}'.format(pluginfile))
>     driver = uc.Chrome(options=opts,use_subprocess=True)
> ```
> 
> `
> 
> pluginfile is the folder path where you have saved manifest.json and background.js.
> 
> Note if you use selenium-wire for undetected, it is no longer fully undetected. I have tested it.

Yeesssss its working. Do not make zip plugin or extension. make folder and it will work. even I didn't downgraded any library. all are the latest. thanks mate
