### ISSUE TITLE
Failed to bypass cloudflare

### ISSUE THREAD

**Issue by M-Zubair10** [ultrafunkamsterdam/undetected-chromedriver#824]
Recently, it looks like cloudflare have updated bot-detection algorithm as I cannot open website from 2 days, it just stuck on hcaptcha loop and even if i solve hcapcha by hand it refreshes and then hcaptcha come again

Really appreciate if you can solve it in headless too

Now it is not working in both headless, headfull

Or any external library, framework, language to automate cloudflare website (in headless if possible) would be appreciated

**Comment by Ansh-Fakesum** [comment]
```
import undetected_chromedriver as uc

if __name__ == "__main__":
	driver = uc.Chrome()

	driver.get("https://nowsecure.nl")

	input("Done?")
```
works, maybe you are using some options that are causing this or cloudflare might have flaged your ip.

**Comment by M-Zubair10** [comment]
Will it work in headless?
I used selenium stealth with it, and disabled navigator flags

**Comment by Fakesum** [comment]
Headless does make chromedriver more detectable try usng pyvirtualdisplay if you are on linux. otherwise on windows, there is a high chance that chromedriver will be detected in headless mode.

**Comment by M-Zubair10** [comment]
Pyvirtualdisplay still can't bypass it, it stuck on hcaptcha loop
Sadly

**Comment by Fakesum** [comment]
Try just using undetected chromedriver without selenium stealth and without any other flag.

**Comment by Fakesum** [comment]
I just tested it and, it gets stuck when using selenium-stealth but it works perfectly when only using undetected chromedriver without any options

**Comment by M-Zubair10** [comment]
Again, with no luck using the same script you have provided it works on nowsecure.nl but not on other sites
Example of such site: freeshib.biz/login

**Comment by M-Zubair10** [comment]
What's your version
If ip banned, then why it works on default chrome

Sometimes it works, but most of the time it stuck on hcaptcha loop

Thanks for your help!

**Comment by M-Zubair10** [comment]
Thanks, I'll check it out.

Please check if it can pass in xvfb or headless, that will be awesome!

**Comment by M-Zubair10** [comment]
Is it possible to open browser context using pyautogui, real browser and
after bypassing cloudflare using real browser, attach the selenium to it

Or any alternative even paid solution?
I needed to scrape large tables from different sitesa

**Comment by M-Zubair10** [comment]
Yeah stealth is causing the issue, thanks
