### ISSUE TITLE
can't change default download directory

### ISSUE THREAD

**Issue by almottier** [ultrafunkamsterdam/undetected-chromedriver#837]
Hello,
I am not able to change the default download directory on Mac/Linux using:

```python
import undetected_chromedriver as uc
options = uc.ChromeOptions()
prefs = {"download.default_directory": "/Users/user/Desktop",  "download.directory_upgrade": True, "download.prompt_for_download": False}
options.add_experimental_option('prefs', prefs)
driver = uc.Chrome(options=options)
```

but it is working using selenium:

```python
from selenium import webdriver
options = webdriver.ChromeOptions()
prefs = {"download.default_directory": "/Users/user/Desktop",  "download.directory_upgrade": True, "download.prompt_for_download": False}
options.add_experimental_option('prefs', prefs)
driver = webdriver.Chrome(options=options)
```

Am I doing it wrong ?

**Comment by Fakesum** [comment]
#477 the experimental prefs are not working. This [Work around](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/260#issuecomment-901276808) might help

**Comment by almottier** [comment]
> #477 the experimental prefs are not working. This [Work around](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/260#issuecomment-901276808) might help

The work around is perfect for my need. Thanks

**Comment by maneendra-zen3** [comment]
> #477 the experimental prefs are not working. This [Work around](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/260#issuecomment-901276808) might help

https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/260#issuecomment-1475150952
