### ISSUE TITLE
Any way to bypass cloudflare in headless chrome

### ISSUE THREAD

**Issue by M-Zubair10** [ultrafunkamsterdam/undetected-chromedriver#847]
Hi,
I wanted to scrape websites in headless now, it works flawlessly in normal chrome but cloudflare is causing issue in headless
Please give me any solution, even paid solution will be accepted, or new framework

**Comment by mdmintz** [comment]
You can use https://github.com/seleniumbase/SeleniumBase to do it.
(It has a special **undetected-chromedriver** mode that works with **headless** mode.)

``pip install -U seleniumbase``

And then run the following with ``python``:

```python
from seleniumbase import Driver
from seleniumbase import page_actions

driver = Driver(headless=True, uc=True)
driver.get("https://nowsecure.nl")
page_actions.wait_for_text(driver, "OH YEAH, you passed!", "h1")
print(driver.find_element("css selector", "body").text)
screenshot_name = "now_secure_image.png"
driver.save_screenshot(screenshot_name)
print("\nScreenshot saved to: %s" % screenshot_name)
driver.quit()
```

**Comment by M-Zubair10** [comment]
Thanks man you are a life saver!

**Comment by anovob** [comment]
Chromedriver console open with Pyinstaller

**Comment by anovob** [comment]
> ```python
> from seleniumbase import Driver
> from seleniumbase import page_actions
> 
> driver = Driver(uc=True)
> driver.get("https://nowsecure.nl")
> page_actions.wait_for_text(driver, "OH YEAH, you passed!", "h1")
> print(driver.find_element("css selector", "body").text)
> screenshot_name = "now_secure_image.png"
> driver.save_screenshot(screenshot_name)
> print("\nScreenshot saved to: %s" % screenshot_name)
> driver.quit()
> ```

Chromedriver console open with Pyinstaller
