### ISSUE TITLE
tutorial?

### ISSUE THREAD

**Issue by Haluna11** [ultrafunkamsterdam/undetected-chromedriver#857]
Import undetecte_chromedriver could not be resolved

I get this error when I try to import the driver

**Comment by Peterich36** [comment]
@Haluna11 

you have to write undetected correctly

**Comment by Haluna11** [comment]
I did and it still doesnt work

**Comment by Haluna11** [comment]
import undetected_chromedriver as uc

**Comment by Fakesum** [comment]
You can simply replace `webdriver` with `uc` in any selenium script, as long as you add
```
import undetected_chromedriver as uc
```
instead of
```
from selenium import webdriver
```

**Comment by Fakesum** [comment]
Place the code like this l:
```
def main():
    # your code here
If __name__ == "__main__":
    main()
```
replace Def main with your code, see issue #829

**Comment by Haluna11** [comment]
using 
> driver = uc.Chrome(use_subprocess=True)
from that issue fixed this error for me, thanks.
