### ISSUE TITLE
Can’t figure out how to install:/

### ISSUE THREAD

**Issue by Doctuh** [ultrafunkamsterdam/undetected-chromedriver#86]
If anyone would be so kind to help me out, either here, or on discord: doc#5244

would really appreciate, and can also donate for the required help :)

regards

**Comment by esezen** [comment]
Can you be more specific about what is not working and how you tried to install it? I'll try helping.

**Comment by Doctuh** [comment]
Yea I installed it with pip. Is  it only available in the python language? I am writing in C#.
Im thinking that might be the case.

**Comment by Avnsx** [comment]
> Yea I installed it with pip. Is it only available in the python language? I am writing in C#.
> Im thinking that might be the case.

Of course that's why it won't work, this entire project is purely python.

**Comment by Doctuh** [comment]
> > Yea I installed it with pip. Is it only available in the python language? I am writing in C#.
> > Im thinking that might be the case.
> 
> Of course that's why it won't work, this entire project is purely python.

sad, I was hoping I would be able to compile it into undetectedChromeDriver.exe and use it that way.
thanks anyways!

**Comment by ultrafunkamsterdam** [comment]
you could patch the chromedriver.exe though.... and copy the file to your c# project. But keep in mind that only patching the binary is only 1 step.

```
from undetected_chromedriver.v2 import Patcher
Patcher().auto()
input()
# copy the patched chromedriver.exe from the current workdir to some other folder

```
