### ISSUE TITLE
undetected-chromedriver docker image command error

### ISSUE THREAD

**Issue by VoidDevelopmentTeam** [ultrafunkamsterdam/undetected-chromedriver#864]
Hello,

Recently I've installed the official docker image for UC but when I attempt to execute the command:
`docker run --rm -it -v ${PWD}/data:/data ultrafunk/undetected-chromedriver ipython yourscript.py`

it just gives me the following error:
> ~# docker run --rm -it -v ${PWD}/data:/data ultrafunk/undetected-chromedriver ipython yourscript.py
> running: ipython yourscript.py
> running keepUpScreen()
> [TerminalIPythonApp] WARNING | File 'yourscript.py' doesn't exist

I've made sure to include the full path for the file.
I've even tried to use the %%writefile to save a file and use it every time I try to run my script but it seems my changes just get reset.

**Comment by ultrafunkamsterdam** [comment]
Lol 😆. Do you have a file called yourscript.py ?

**Comment by VoidDevelopmentTeam** [comment]
> Lol 😆. Do you have a file called yourscript.py ?

Yes, I

**Comment by VoidDevelopmentTeam** [comment]
Woops closed it accidentally

**Comment by VoidDevelopmentTeam** [comment]
Resorted to a different method, got better results.
UC is amazing

**Comment by varna9000** [comment]
@VoidDevelopmentTeam can you please tell me what method you used to run your script?

**Comment by ultrafunkamsterdam** [comment]
> @VoidDevelopmentTeam can you please tell me what method you used to run your script?

Educated guess: make sure yourscript.py lives IN your container so it can actually find it
