### ISSUE TITLE
clicking on a recaptcha in an iframe does not work when window on different desktop

### ISSUE THREAD

**Issue by awfe3** [ultrafunkamsterdam/undetected-chromedriver#893]
clicking on a recaptcha in an iframe does not work when the browser window is minimized or is on another desktop, but the rest of the clicks, entering characters in the fields work.

my program enters text in the field on the site, clicks the necessary buttons, and clicks on the recaptha checkbox, but when the browser window is minimized or is on another desktop, everything happens fine except for clicking on the captcha checkbox in the iframe, it is not clicked, and when I switch to the second one desktop click on the captcha checkbox, then everything works.

How to make the script normally click on the captcha checkmark when the window is on another desktop or minimized?

this was not in the usual chromedriver, this only happens with UC, but I need it to work on UC

perhaps this is due to the fact that the window becomes inactive and it is impossible to click the captcha checkbox, although all other actions on the site are normal
please help

```
import undetected_chromedriver as webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options

profileg = "profile path"
options = Options()
options.add_argument(f"user-data-dir={profileg}")
options.add_argument("allow-running-insecure-content")
driver = webdriver.Chrome(options=options, use_subprocess=True)
driver.get(url1)
#some code
driver.switch_to.frame(driver.find_element(By.XPATH,"/html/body/div[4]/div/div/div/div/div/iframe")) #captcha iframe xpath
driver.find_element(By.XPATH, '/html/body/div[2]/div[3]/div[1]/div/div/span/div[1]').click() #captcha button xpath
```

**Comment by ultrafunkamsterdam** [comment]
Switch_to.window ?

**Comment by ultrafunkamsterdam** [comment]
But a captcha probably shows something else is wrong in your config since you shouldn't get them, unless it's one that everyone gets, at some login page for example

**Comment by awfe3** [comment]
I need to click on the checkbox of the captcha, but it is not clicked when the window is on another desktop, I call the click through .click (), through the usual chromedriver, everything is clicked on the checkbox without problems, but the click just does not work

**Comment by sebdelsol** [comment]
Chrome throttles javascript and doesn't render content in occluded/minimized windows [**to reduce memory usage**](https://blog.chromium.org/2021/12/chrome-windows-performance-improvements-native-window-occlusion.html) and that might prevent a Selenium mouse click. There are known command line switches to make it works but those come and go...
```python3
options.add_argument("--disable-renderer-backgrounding")
options.add_argument("--disable-backgrounding-occluded-windows")
```
I haven't tested those since Chrome 103 tho.

**Comment by awfe3** [comment]
Thank you

**Comment by boludoz** [comment]
@ultrafunkamsterdam I want to select an OTP within an iframe with nodriver but it won't let me do it.

**Comment by Mazentmaalouf** [comment]
How do I click the reCAPTCHA checkbox with nodriver?
