### ISSUE TITLE
Behavior of undetected chrome driver differs on PC vs VPS - it is still detected on VPS

### ISSUE THREAD

**Issue by vk643** [ultrafunkamsterdam/undetected-chromedriver#894]
What am I doing wrong? Running the same code on my PC and via VPS results in different behavior. Under VPS the page I am opening still shows hCaptcha request. While on the PC the security test is always passed successfully.

**Comment by MattWaller** [comment]
Probably datacenter ip, vs residential ip

**Comment by ultrafunkamsterdam** [comment]
What @MattWaller says. Try a smaller hoster. I've got no problem using vps, but it's a "small" Dutch company

**Comment by vk643** [comment]
Dear @MattWaller and @ultrafunkamsterdam. Thanks a lot for your prompt responses. Will try that and revert with the results.

**Comment by vk643** [comment]
Yes. indeed. The issue was with IP of the VPS provider. Resolver through the change to another company as advised above. Thanks again.
