### ISSUE TITLE
Can I use it in ruby on rails?

### ISSUE THREAD

**Issue by goldenking0412** [ultrafunkamsterdam/undetected-chromedriver#90]
I am running a scraper bot and want to use it ruby on rails framework.
Is it possible?
Thank you

**Comment by HMaker** [comment]
Just port the code to ruby since selenium has bindings for it https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings

**Comment by goldenking0412** [comment]
I don't understand how to use it. I know how to use selenium in ruby on rails framework. But not sure how to use your library in rails framework.
Can you please give me more details?

**Comment by HMaker** [comment]
@goldenking0412 to port a code means to implement the same logic in other language. So you would write a equivalent lib in ruby, for that you need to know how this lib works and a little of Python. This library is pretty simple, just a single Python file.

**Comment by goldenking0412** [comment]
I want to know is which option did you add to selenium and what kind of javascript you ran on newDocument to avoid selenium detection. Anyway I will check the python code as I know it

**Comment by goldenking0412** [comment]
This library patch chromedriver and output an undetectable chromedriver?
If yes, then can you send me undetectable chromedriver linux version?

**Comment by HMaker** [comment]
These are the key points you need to implement in ruby
https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/master/undetected_chromedriver/__init__.py#L57
https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/master/undetected_chromedriver/__init__.py#L107
https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/master/undetected_chromedriver/__init__.py#L154
https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/master/undetected_chromedriver/__init__.py#L232

**Comment by goldenking0412** [comment]
```
    def patch_binary(self):
        """
        Patches the ChromeDriver binary
        :return: False on failure, binary name on success
        """
        linect = 0
        replacement = self.random_cdc()
        with io.open(self.executable_path, "r+b") as fh:
            for line in iter(lambda: fh.readline(), b""):
                if b"cdc_" in line:
                    fh.seek(-len(line), 1)
                    newline = re.sub(b"cdc_.{22}", replacement, line)
                    fh.write(newline)
                    linect += 1
            return linect
```

This code is for navigator.webdriver, right?

**Comment by goldenking0412** [comment]
Also this
https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/master/undetected_chromedriver/__init__.py#L57

is for navigator.webdriver, right?

**Comment by goldenking0412** [comment]
Regarding this,
https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/master/undetected_chromedriver/__init__.py#L232

Have you ever tried this with recent chromedriver?
I've manually patched chromedriver and it didn't work.
Not sure how your script works

**Comment by yellowgolfball** [comment]
Anyone get the RoR patch working?

**Comment by goldenking0412** [comment]
@yellowgolfball Yes I did

**Comment by yellowgolfball** [comment]
> @yellowgolfball Yes I did

can you share your code?

**Comment by khalilgharbaoui** [comment]
@goldenking0412 care to share a gist?

**Comment by tluthra** [comment]
@goldenking0412 following up here, would you be able to share a repo or gist of your ruby port?

**Comment by buiquangthang** [comment]
@goldenking0412 could you share your patch, please?

**Comment by kevinguiot** [comment]
up

**Comment by yann120** [comment]
I added this argument options, suggested by chatGPT and it works in headless
```
      # Add user-agent
      options.add_argument(
        'user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
      )

      # Disable WebDriver flag
      options.add_argument('--disable-blink-features=AutomationControlled')
```

**Comment by khalilgharbaoui** [comment]
> I added this argument options, suggested by chatGPT and it works in headless
> 
> ```
>       # Add user-agent
>       options.add_argument(
>         'user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
>       )
> 
>       # Disable WebDriver flag
>       options.add_argument('--disable-blink-features=AutomationControlled')
> ```

care to share full code example?

**Comment by Dmytrenko-I** [comment]
@yann120 any chances you could share an example?
