### ISSUE TITLE
ssl certificate in proxy selenium wire

### ISSUE THREAD

**Issue by ahmedabdelhamedz** [ultrafunkamsterdam/undetected-chromedriver#902]
`import os
import shutil
import tempfile
import DLLs
import undetected_chromedriver.v2 as uc
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from seleniumwire import webdriver

from selenium import webdriver
from selenium.webdriver.common.proxy import *

import time
import seleniumwire.undetected_chromedriver as uc

if __name__ == "__main__":
    chrome_options = uc.ChromeOptions()
    # here your chrome options

    seleniumwire_options = {
        "proxy": {
            "https": "http://user:pass@ip:port"
        },
        'verify_ssl': True,
        
    }

    driver = uc.Chrome(
        options=chrome_options, seleniumwire_options=seleniumwire_options
    )
    driver.get("https://api.myip.com/")
    time.sleep(10)

'''`
ssl certification not loaded appear connection is not secuered how can i solve this problem

**Comment by kaliiiiiiiiii** [comment]
#### As far I know:
ssl certificates don't work with selenium-wire, because you need to pass the data decryptet through the wire-proxy for being able to modify it.
* Although there are other options to modify headers:
	* you can use [ModHeader](https://github.com/modheader/modheader_selenium) to *modify//add headers*.
	* you can use [Selenium-Profiles](https://github.com/kaliiiiiiiiii/Selenium-Profiles) for emulating specific devices (Android, Linux, Windows, Tablet, ...)
#### Depends on what you need
