### ISSUE TITLE
I can't get driver.get_screenshot_as_png() from two open drivers.

### ISSUE THREAD

**Issue by Eduli** [ultrafunkamsterdam/undetected-chromedriver#903]
When i open two drivers and both of them try get_screenshot_as_png(), the first one raise an error: 'Message: timeout: Timed out receiving message from renderer: 10.000'. I think is something with which one got the focus, because if you change the order of the creation of drivers, it changes the one that raises the error.
I'm on Windows 10 Enterprise with Python 3.10.2 64-bit.

This is my code:

import undetected_chromedriver
if __name__ == '__main__':
    driver1 = undetected_chromedriver.Chrome()
    driver2 = undetected_chromedriver.Chrome()
    driver1.get("https://www.google.es/")
    driver2.get("https://www.google.es/")
    image1=driver1.get_screenshot_as_png()
    image2=driver2.get_screenshot_as_png()
    driver1.close()
    driver1.stop()
    driver2.close()
    driver2.stop()

This is my solution but when you maximizes any window it stops and raise the error:

import undetected_chromedriver
if __name__ == '__main__':
    driver1 = undetected_chromedriver.Chrome()
    driver2 = undetected_chromedriver.Chrome()
    driver1.get("https://www.google.es/")
    driver2.get("https://www.google.es/")
    image1=driver1.get_screenshot_as_png()
    image2=driver2.get_screenshot_as_png()
    
    for x in range(100):
        pos_dirver1=driver1.get_window_position()
        driver1.set_window_position(pos_dirver1["x"]+2, pos_dirver1["y"]+2, windowHandle='current')
        image1=driver1.get_screenshot_as_png()

        pos_dirver2=driver2.get_window_position()
        driver2.set_window_position(pos_dirver2["x"]+1, pos_dirver2["y"]+1, windowHandle='current')
        image2=driver2.get_screenshot_as_png()
               
        print(x)
    
    driver1.close()
    driver1.stop()
    driver2.close()
    driver2.stop()

Thank you for all of your time, effort, patience, and guidance. ;)

**Comment by sebdelsol** [comment]
Now that you've found the solution what's the issue ?

**Comment by Eduli** [comment]
My solution don’t work if you have a maximized window.
I can’t understand why driver need to be on focus to get their png image.
Thanks.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: ***@***.***>
Enviado: miércoles, 16 de noviembre de 2022 13:46
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [ultrafunkamsterdam/undetected-chromedriver] I can't get driver.get_screenshot_as_png() from two open drivers. (Issue #903)


Now that you've found the solution what's the issue ?

**Comment by sebdelsol** [comment]
I still doesn't understand your issue, it works even when you maximize your windows.

Anyway it's a weird piece of code. Why would you need to invoke several drivers when you use them sequentially ?

```python3
import undetected_chromedriver as uc

if __name__ == '__main__':
    drivers = [uc.Chrome() for _ in range(2)]

    for driver in drivers:
        driver.get("https://www.google.es/")
        driver.maximize_window()
        image=driver.get_screenshot_as_png()
        print(len(image))
    
    for driver in drivers:
        driver.quit()
```

**Comment by sebdelsol** [comment]
Ok I guess you try to do that on several threads ?

In that case you indeed need the focus to take a screenshot or it would timeout. 
That's probably a Chromium limitation on Windows.

So use a Lock :
```python3
import threading
import undetected_chromedriver as uc 

from concurrent.futures import ThreadPoolExecutor

def job(lock):
        driver = uc.Chrome()
        driver.get("https://www.google.es/")
        with lock:
            # here's a trick to force the focus on this browser window
            # it won't work if you've already started maximized tho
            driver.maximize_window() 
            image = driver.get_screenshot_as_png()
        print(f"image size {len(image)}")
        driver.quit()


if __name__ == "__main__":
    N_THREADS = 2
    
    screenshot_lock = threading.Lock()
    with ThreadPoolExecutor() as executor:
        for _ in range(N_THREADS):
            executor.submit(job, screenshot_lock)
    print("done")
```

**Comment by Eduli** [comment]
Ok, i’ll try that, Thanks a lot.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: ***@***.***>
Enviado: miércoles, 16 de noviembre de 2022 16:45
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [ultrafunkamsterdam/undetected-chromedriver] I can't get driver.get_screenshot_as_png() from two open drivers. (Issue #903)


Ok I guess you try to do that on several threads ?

In that case you indeed need the focus to take a screenshot or it would timeout.
That's probably a Chromium limitation on Windows.

So use a Lock :

import threading

import undetected_chromedriver as uc



from concurrent.futures import ThreadPoolExecutor



def job(lock):

        driver = uc.Chrome()

        driver.get("https://www.google.es/")

        with lock:

            # here's a trick to force the focus on this browser window

            # it won't work if you've already started maximized tho

            driver.maximize_window()

            image = driver.get_screenshot_as_png()

        print(f"image size {len(image)}")

        driver.quit()





if __name__ == "__main__":

    N_THREADS = 2



    screenshot_lock = threading.Lock()

    with ThreadPoolExecutor() as executor:

        for _ in range(N_THREADS):

            executor.submit(job, screenshot_lock)

    print("done")

**Comment by sebdelsol** [comment]
ok you don't really need having the focus to make it work...

This is the same issue as #893 : Chrome throttles doesn't render content in occluded/minimized windows [**to reduce memory usage**](https://blog.chromium.org/2021/12/chrome-windows-performance-improvements-native-window-occlusion.html). And because of that your screenshots might timeout !

The solution is to use `--disable-renderer-backgrounding` and `--disable-backgrounding-occluded-windows` command lines :

```python3
import undetected_chromedriver as uc 

from concurrent.futures import ThreadPoolExecutor

def job():
        options = uc.ChromeOptions()
        options.add_argument("--disable-renderer-backgrounding")
        options.add_argument("--disable-backgrounding-occluded-windows")        
        driver = uc.Chrome(options=options)
        driver.get("https://www.google.es/")
        image = driver.get_screenshot_as_png()
        print(f"image size {len(image)}")
        driver.quit()


if __name__ == "__main__":
    N_ITERATION = 100
    
    with ThreadPoolExecutor() as executor:
        for _ in range(N_ITERATION):
            executor.submit(job)
    print("done")
```

**Comment by Eduli** [comment]
This one really did the job. Thanks a lot.
