### ISSUE TITLE
Weird bug with patched chromedriver binary

### ISSUE THREAD

**Issue by robert-engel** [ultrafunkamsterdam/undetected-chromedriver#92]
This happens to me on chrome version 88, but I did not use it before version 88 so I don't know if its related to the version.

After the chromedriver is running for a while it suddenly seems like chrome cannot connect to the internet anymore. My normal browser works fine but in the chrome window that is connected to the chromedriver the websites just load infinitely. 

Trying to locate the issue I removed the patch logic and just manually modified the chromedriver. It seems like it has something to do with the page cache as shown in the method below. I left the other cdc variables modified but reverted the `key` to the original value and the issue did not appear anymore. But obviously with unmodified key I get detected. Anyone with more knowledge of the chromedriver know how I can fix this?
```
function getPageCache(opt_doc, opt_w3c) {
  var doc = opt_doc || document;
  var w3c = opt_w3c || false;
  // |key| is a long random string, unlikely to conflict with anything else.
  var key = '$cdc_asdjflasutopfhvcZLmcfl_';
  if (w3c) {
    if (!(key in doc))
      doc[key] = new CacheWithUUID();
    return doc[key];
  } else {
    if (!(key in doc))
      doc[key] = new Cache();
    return doc[key];
  }
}
```

**Comment by HMaker** [comment]
it hangs loading which website? are you sure they don't have antibot mechanisms?

**Comment by robert-engel** [comment]
Its not related to the website. After it starts hanging I tried opening many other websites and none load until I restart chrome. Even manually opening them in a new window/tab did not work. But my other chrome instance that uses the default user-data-dir and is not connected to a chrome driver works fine.

**Comment by HMaker** [comment]
are you talking about that function in this brach https://source.chromium.org/chromium/chromium/src/+/master:chrome/test/chromedriver/js/call_function.js;l=240 ?

**Comment by robert-engel** [comment]
Yeah thats the one.

**Comment by ultrafunkamsterdam** [comment]
for this issue, i would start removing chromedriver executable from the current work folder, and run your program again. It will re-download and patch the driver for you.  This makes sure the chromedriver version and chrome browser version match.  If you start using this prior to a update to chrome, or happen to have used this before some time and chromedriver(.exe) is still in your folder, it will not automatically replace it. you would have to remove chromedriver.exe by hand.  This is different in v2, where (if you like it or not), the driver is replaced for every session (when file is not locked)

**Comment by robert-engel** [comment]
Very weird but it worked again after deleting the user data dir.
