### ISSUE TITLE
How to prevent UC from auto-closing after script end

### ISSUE THREAD

**Issue by frankhuurman** [ultrafunkamsterdam/undetected-chromedriver#924]
I dove into all the open issues and read the entire README but am unable to find an answer to this.

The default behavior from UC seems to be to implicitly driver.close() at the end of a script.
Is there some way to control this manually like the regular Selenium webdriver behavior so I can driver.close() whenever I need it to close?

_edit: I know I can use time.sleep() of course to extend a session, but what if I want it to not have a finite amount of time before auto-closing?_

Thanks in advance, and thanks for an amazing necessary library :smile:

**Comment by frankhuurman** [comment]
Additionally, I ran into weird behavior when cancelling time.sleep with ctrl + c. I'll try to see if I can recreate it.

In one of my tests, ctrl + c apparently didn't fully close everything which made it impossible to run the script again cause the moment I ran it again the script just seemed to be hanging forever and didn't launch chromium to do the tests.
A reboot fixed it but apparently there's a chance to make the chromium webdriver unusable if you ctrl + c to end your script that's using time.sleep.

**Comment by ultrafunkamsterdam** [comment]
Hi Frank. The "issue" here is that uc also manages the browser process, where original driver takes care of that within the driver. To answer your question: you can use driver.quit() to shut it down, while driver.close() only closes the underlying session, which can then be reconnected by using .start_session() (top of my head), or better: driver.reconnect() (which handles all the magic for you, useful in case of exceptions where normally you would lose your session.

**Comment by ultrafunkamsterdam** [comment]
as for:
> I know I can use time.sleep() of course to extend a session, but what if I want it to not have a finite amount of time before auto-closing?

my favourite is:

`sys.stdin.read()`  somewhere near the end, so your script keeps running and outputting.

**Comment by frankhuurman** [comment]
Ah thanks for your detailed replies!
I'll try some of your suggestions and see if I can make it work 😄 

> You can't Ctrl c when time.sleep (it's a python/Windows thing)
I'm on Linux but I guess it still doesn't handle time.sleep + ctrl + c very gracefully on there as well.

> my favourite is:

> sys.stdin.read() somewhere near the end, so your script keeps running and outputting.

Will try that, thank you!

**Comment by frankhuurman** [comment]
> 
> my favourite is:
> 
> `sys.stdin.read()` somewhere near the end, so your script keeps running and outputting.

Can confirm this does exactly what I want so I can send a sigint to kill the script :) Thanks a lot!

Closing ticket.
