### ISSUE TITLE
code example isn't working OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by Fovex** [ultrafunkamsterdam/undetected-chromedriver#954]
python version: 3.11.0
undetected-chromedriver: latest
chrome version: 108
code: 
import undetected_chromedriver.v2 as uc
driver = uc.Chrome()
driver.get('https://google.com)

error: 
OSError: [WinError 6] The handle is invalid

**Comment by timbeh** [comment]
Hey, had you solved this issue? And if yes, how?
