### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by DefacedFace** [ultrafunkamsterdam/undetected-chromedriver#959]
code:
import undetected_chromedriver as uc
driver = uc.Chrome()
driver.get('https://google.com')

Error: 
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)>

any ideas? i only get this issue when trying to use chrome-undetected. im running latest version of chrome (not beta). im on mac

**Comment by ultrafunkamsterdam** [comment]
Your problem
