### ISSUE TITLE
Cloudflare Detected?

### ISSUE THREAD

**Issue by dumbshow** [ultrafunkamsterdam/undetected-chromedriver#963]
Hi, I'm getting detected when using undetected chromedriver at this URL.  Are others able to load it?  Thanks for checking.

https://www.whitepages.com/auth/login?redirect=/

**Comment by denene12** [comment]
it legendary detects it if it detects everytime try closin your router and starting it back

**Comment by ManiMozaffar** [comment]
#1031 Works here
