### ISSUE TITLE
Import error when use the library in python 3.7

### ISSUE THREAD

**Issue by tyIceStream** [ultrafunkamsterdam/undetected-chromedriver#964]
Hi, I have a project run the code with your library using github action.
But it meets bug after updating to 3.2.0.
Please help debug this.
https://github.com/tyIceStream/GLaDOS_Checkin/actions/runs/3795359703/jobs/6454400367

I have find the root cause that it does not support python in low version.
After updating the python version from 3.7 to 3.9, this bug is fixed.

Maybe your project needs do something. Thanks

**Comment by IvanReznikov** [comment]
break confirm.

from typing import List ?

**Comment by ultrafunkamsterdam** [comment]
Hero!
