### ISSUE TITLE
suddenly detected

### ISSUE THREAD

**Issue by avinerv** [ultrafunkamsterdam/undetected-chromedriver#97]
- In bet365.es it has stopped working since they detect chromedriver and block it, any clue to solve it?

**Comment by migue1986** [comment]
In effect, since yesterday it has been detected again. The solution indicated in the following post https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/60 worked until yesterday. Has anyone been able to fix it? Thank you so much for everything

**Comment by nesttle** [comment]
Did you found a workaround for this? Having similar issue in an online store since yesterday @avinerv

**Comment by avinerv** [comment]
No, I did not. I closed this issue by mistake.

**Comment by migue1986** [comment]
Any solution ? Thanks !

**Comment by ultrafunkamsterdam** [comment]
Closet until proper code/examples/errors are provided.
