### ISSUE TITLE
UC driver gets detected as bot

### ISSUE THREAD

**Issue by aspeed98** [ultrafunkamsterdam/undetected-chromedriver#977]
UC driver gets detected as bot type "undetectedChromedriver" on [https://fingerprint.com/products/bot-detection/](url)
`driver = uc.Chrome()`
`driver.get("chrome://new-tab-page")`
`driver.maximize_window()`
`time.sleep(1)`
`driver.get("https://fingerprint.com/products/bot-detection/")`
`time.sleep(999999)`
![bot 1](https://user-images.githubusercontent.com/122220640/211215671-5698acb5-88fc-484a-836c-f2955c8e9f0a.jpg)
![bot 2](https://user-images.githubusercontent.com/122220640/211215677-70653aa7-95c0-4299-9d95-18e0117b7a54.jpg)

**Comment by ultrafunkamsterdam** [comment]
Good to see uc has its own category.

However, this is not intended usage..
