### ISSUE TITLE
The driver is detected

### ISSUE THREAD

**Issue by migue1986** [ultrafunkamsterdam/undetected-chromedriver#98]
Since yesterday it not working in bet365.es . The solution indicated in the following post #60 worked until yesterday. Has anyone been able to fix it? Thank you so much for everything

**Comment by nesttle** [comment]
Did you found a workaround for this? Having similar issue in an online store since yesterday

**Comment by HMaker** [comment]
Are you sure your IP is not blocked? Use the same IP and try to access bet365 in browser

**Comment by ultrafunkamsterdam** [comment]
That is not an entirely fair test. As another browser is ... well another browser. In general, i see just too many "bet365" "issues", but all not using official URL for it... smells a bit fishy. Any of these calls will not be supported anymore as 9/10 times the URL either does not even work, and smells too fishy.  Rather spend valuable time researching New detection methods.On Jan 30, 2021 21:15, Heraldo Lucena <notifications@github.com> wrote:
Are you sure your IP is not blocked? Use the same IP and try to access bet365 in browser

**Comment by HMaker** [comment]
When the IP is blocked bet365 will redirect the requests to the session endpoint, `/default/sports-configuration`, to localhost. That's why I asked them to make sure the IP was not blocked.

**Comment by boganfoo** [comment]
Hello, I can confirm this issue occurs when not blocked by IP. 
Multiple IPs that previously worked are no longer working 
I am accessing using bet365.com.au (official site) 
headless mode on/off doesn't work 
Is there any way we can gather data to help with the research on this?

**Comment by migue1986** [comment]
Hello ! The browser goes blank. stays charging indefinitely. I have tried with the normal Chrome and if it loads the data, so it is not IP problem.

**Comment by boganfoo** [comment]
Fixed it. Temporarily probably. Nice try bet365 :) 
Hats off to them. 
I added this before driver.get

driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
        "source": """
        Object.defineProperty(navigator, 'maxTouchPoints', {
          get: () => 1
        })
      """
    })

**Comment by migue1986** [comment]
Wow !!!! Incredible !!!I have applied that code and it works correctly. Thank you very much :)

**Comment by liqing1990** [comment]
w

> Fixed it. Temporarily probably. Nice try bet365 :)
> Hats off to them.
> I added this before driver.get
> 
> driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
> "source": """
> Object.defineProperty(navigator, 'maxTouchPoints', {
> get: () => 1
> })
> """
> })


You are so amazing, thank you very much for your answer！！！！！！！！

**Comment by karim090** [comment]
adding in _get_wrapped definition:
`            if instance.execute_script("return navigator.maxTouchPoints") is 0:
                instance.execute_cdp_cmd(
                    "Page.addScriptToEvaluateOnNewDocument",
                    {
                        "source": """
                                Object.defineProperty(navigator, 'maxTouchPoints', {
                                get: () => 1
                                })
                        """
                    }
                )
`
                
 will modify the property
 
 @ultrafunkamsterdam  let me contriubute

**Comment by ultrafunkamsterdam** [comment]
> adding in _get_wrapped definition:
> ` if instance.execute_script("return navigator.maxTouchPoints") is 0: instance.execute_cdp_cmd( "Page.addScriptToEvaluateOnNewDocument", { "source": """ Object.defineProperty(navigator, 'maxTouchPoints', { get: () => 1 }) """ } )`
> 
> will modify the property
> 
> @ultrafunkamsterdam let me contriubute

@karim090 , does this also work on cloudflare perhaps?

**Comment by HMaker** [comment]
@ultrafunkamsterdam this is specific of https://www.bet365.com/ it's a big bookmaker which is scraped by many bots, they have their own automated environment detection algorithm.

**Comment by ultrafunkamsterdam** [comment]
I know bet365. 
Touchpoints check is quite common so i wonder why  bet365 is the only one using it successfully

**Comment by ultrafunkamsterdam** [comment]
> > adding in _get_wrapped definition:
> > ` if instance.execute_script("return navigator.maxTouchPoints") is 0: instance.execute_cdp_cmd( "Page.addScriptToEvaluateOnNewDocument", { "source": """ Object.defineProperty(navigator, 'maxTouchPoints', { get: () => 1 }) """ } )`
> > will modify the property
> > @ultrafunkamsterdam let me contriubute
> 
> @karim090 , does this also work on cloudflare perhaps?

I will implement it, but as an option , using a constructor param since it seems bound to 1 specific page, and might break other use cases.

**Comment by ultrafunkamsterdam** [comment]
> When the IP is blocked bet365 will redirect requests to the session endpoint, `/default/sports-configuration`, to localhost. That's why I asked them to make sure the IP was not blocked.

That's frustrating to test. In the Netherlands bet365 is not allowed by geo restriction, and using VPN also seems blocked as it's trying to get something of localhost..

@boganfoo 's  excellent find however is implemented in a patch (branch:  update-patch), together with some other minor changes. However i cannot test it... so i'll wait for confirmation from any of you guys.

**Comment by Avnsx** [comment]
@ultrafunkamsterdam if we keep going like this, you can soon re-name it to `undetected-bet365driver` 🤪

**Comment by ultrafunkamsterdam** [comment]
> @ultrafunkamsterdam if we keep going like this, you can soon re-name it to `undetected-bet365driver` 🤪

I agree. but there were too many issues, and even though the use case is very arguable, it detected the package... which does not represent "undetectable"
