### ISSUE TITLE
Detected by Imperva

### ISSUE THREAD

**Issue by blockfan7** [ultrafunkamsterdam/undetected-chromedriver#981]
It worked well till 3 days ago.
Now it is detected by Imperva.

**Comment by lendog269** [comment]
This does need to be fixed!!

**Comment by lukect** [comment]
I posted a quick two line fix here: https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/986

**Comment by blockfan7** [comment]
Thank you.
It works

**Comment by fabifont** [comment]
> Thank you. It works

Can you please tell me a website that uses Imperva and provide a link to the page where you can be detected?
