### ISSUE TITLE
Headless detected by cloudflare when using chrome version 109?

### ISSUE THREAD

**Issue by IsaacHog** [ultrafunkamsterdam/undetected-chromedriver#989]
Works fine on 108/107, does anyone else encounter this problem?

**Comment by lukect** [comment]
Try my solution: https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/986
Please note I have not tested it on headless yet. Let me know how it goes!

**Comment by mdmintz** [comment]
See https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/847#issuecomment-1287546593

**Comment by Rwing** [comment]
@mdmintz 
Amazing! Can your library passed Datadome?

**Comment by IsaacHog** [comment]
> Try my solution: #986 Please note I have not tested it on headless yet. Let me know how it goes!

Thanks, tried this yesterday before posting but didn't work now either :/
