### ISSUE TITLE
Detected?

### ISSUE THREAD

**Issue by MarMaris-p** [ultrafunkamsterdam/undetected-chromedriver#99]
I am unable to load bet365.com using python's regular selenium webdriver, but I am also unable to load it using this library. All other websites load just fine.

Do you think this is a detection issue or something else?

**Comment by lmtcba** [comment]
> I am unable to load bet365.com using python's regular selenium webdriver, but I am also unable to load it using this library. All other websites load just fine.
> 
> Do you think this is a detection issue or something else?

I have been working for the last days in this problem.  Do you think is possible find a solution?

**Comment by lmtcba** [comment]
> I am unable to load bet365.com using python's regular selenium webdriver, but I am also unable to load it using this library. All other websites load just fine.
> 
> Do you think this is a detection issue or something else?

SOLUTION: https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/98

**Comment by ultrafunkamsterdam** [comment]
update package to latest version and try `Chrome(emulate_touch=True)`
